import { notFound } from "next/navigation";
import Link from "next/link";
import Image from "next/image";
import { getContexteColors } from "@/lib/contexte";
import { resoudreRoleColors } from "@/lib/acces-colors";
import { peutEffectuerColors } from "@/lib/permissions-colors";
import { listerEmplacementsColors, obtenirSeauColors } from "@/lib/metier-colors";
import { ajusterQuantiteAction, archiverSeauAction, changerEtatAction, deplacerSeauAction, modifierSeauAction } from "@/app/actions-metier";
import { PhotoUploader } from "@/components/PhotoUploader";
import { FlashMessage } from "@/components/FlashMessage";
import { formaterQuantite } from "@/lib/quantites";

export default async function FicheSeauPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{ok?:string;erreur?:string}>}){
 const [{id},f,contexte]=await Promise.all([params,searchParams,getContexteColors()]);if(!contexte.entrepriseId)return null;const [fiche,emplacements,role]=await Promise.all([obtenirSeauColors(contexte.entrepriseId,id),listerEmplacementsColors(contexte.entrepriseId),resoudreRoleColors(contexte)]);if(!fiche)notFound();const {seau,mouvements,photoUrl}=fiche;
 return <><header className="page-heading"><div><span className="eyebrow">Fiche individualisée</span><h1>{seau.marque} — {seau.produit}</h1><p>{seau.teinte_nom??"Teinte non renseignée"} · {seau.colors_emplacements?.nom??"Non rangé"}</p></div><Link className="outline-button" href="/inventaire">Retour à l’inventaire</Link></header><FlashMessage ok={f.ok} erreur={f.erreur}/><section className="detail-grid"><article className="panel photo-panel">{photoUrl?<Image unoptimized width={900} height={900} src={photoUrl} alt={`Seau ${seau.marque} ${seau.produit}`}/>:<div className="photo-placeholder">Aucune photo</div>}{peutEffectuerColors(role,"ocr")&&<PhotoUploader seauId={id}/>}<p className="color-note">Les couleurs numériques et correspondances RAL sont indicatives. Validez toujours avec un nuancier physique.</p></article><article className="panel"><h2>Niveau et état</h2><div className="big-level"><strong>{seau.pourcentage_restant}%</strong><div><i style={{width:`${seau.pourcentage_restant}%`}}/></div><span>{formaterQuantite({mode:seau.mode_quantite,unite:seau.unite,nominale:seau.quantite_nominale,restante:seau.quantite_restante,pourcentage:seau.pourcentage_saisi})}</span></div>{peutEffectuerColors(role,"ajuster_quantite")&&<form action={ajusterQuantiteAction.bind(null,id)} className="inline-form"><label>Nouvelle quantité<input name="valeur" type="number" min="0" step="0.01" required/></label><input type="hidden" name="type" value="ajustement"/><label>Motif<input name="motif" required/></label><button className="primary-action">Mettre à jour</button></form>}{peutEffectuerColors(role,"deplacer")&&<form action={deplacerSeauAction.bind(null,id)} className="inline-form"><label>Déplacer vers<select name="emplacement_id" required defaultValue=""><option value="" disabled>Choisir…</option>{emplacements.map(e=><option key={e.id} value={e.id}>{e.nom}</option>)}</select></label><button className="outline-button">Déplacer</button></form>}{peutEffectuerColors(role,"marquer_vide")&&seau.etat!=="archive"&&seau.etat!=="vide"&&<form action={changerEtatAction.bind(null,id)} className="button-row">{seau.etat==="ferme"&&<button name="etat" value="ouvert" className="outline-button">Marquer ouvert</button>}{seau.etat==="ouvert"&&<button name="etat" value="ferme" className="outline-button">Marquer fermé</button>}<button name="etat" value="vide" className="danger-button">Marquer vide</button></form>}</article></section>
 {peutEffectuerColors(role,"modifier_seau")&&<details className="panel create-panel"><summary>Modifier les informations</summary><form action={modifierSeauAction.bind(null,id)} className="form-grid"><label>Marque<input name="marque" defaultValue={seau.marque} required/></label><label>Produit<input name="produit" defaultValue={seau.produit} required/></label><label>Référence<input name="reference_produit" defaultValue={seau.reference_produit??""}/></label><label>Teinte<input name="teinte_nom" defaultValue={seau.teinte_nom??""}/></label><label>Référence teinte<input name="teinte_reference" defaultValue={seau.teinte_reference??""}/></label><label>HEX<input name="couleur_hex" defaultValue={seau.couleur_hex??""} pattern="#[0-9A-Fa-f]{6}"/></label><label className="wide">Notes<textarea name="notes" defaultValue={seau.notes??""}/></label><button className="primary-action wide">Enregistrer</button></form></details>}
 <article className="panel history"><div className="panel-head"><div><h2>Historique immuable</h2><p>{mouvements.length} mouvements récents</p></div>{peutEffectuerColors(role,seau.etat==="archive"?"restaurer":"archiver")&&<form action={archiverSeauAction.bind(null,id,seau.etat!=="archive")}><button className="danger-button">{seau.etat==="archive"?"Restaurer":"Archiver"}</button></form>}</div>{mouvements.map(m=><div className="history-row" key={m.id}><span className="badge">{m.type.replaceAll("_"," ")}</span><span>{m.motif??"Mise à jour Colors"}</span><small>{new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(m.created_at))}</small></div>)}</article></>;
}
