begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
create function pg_temp.id(k text) returns uuid language sql as $$select current_setting('test.d.'||k)::uuid$$;
create function pg_temp.draft(asset uuid,patch jsonb default '{}') returns jsonb language sql security definer set search_path='' as $$
select jsonb_build_object('generator_version','v1','aspect_ratio','9:16','target_duration_ms',null,'total_duration_ms',3000,'excluded_assets',0,'clips',jsonb_build_array(
jsonb_build_object('asset_id',asset,'sort_order',0,'clip_type','image','source_start_ms',0,'source_end_ms',null,'timeline_start_ms',0,'timeline_end_ms',3000,'duration_ms',3000,
'crop_mode','cover','scale',1,'position_x',0.5,'position_y',0.5,'rotation',0,'playback_rate',1,'volume',0,'animation_type','zoom_in','transition_in','fade','transition_out','cut','transition_duration_ms',500,'metadata_json',public.studio_photo_motion('zoom_in'))||patch));
$$;
create function pg_temp.save(p uuid,t uuid,d jsonb,r integer default null) returns uuid language sql as $$
select public.studio_save_timeline(p,t,r,(select revision from public.studio_projects where id=p),d)$$;
insert into auth.users(id,email) values
('54000000-0000-0000-0000-000000000001','montage-a@example.test'),
('54000000-0000-0000-0000-000000000002','montage-b@example.test'),
('54000000-0000-0000-0000-000000000003','montage-admin@example.test'),
('54000000-0000-0000-0000-000000000004','montage-editor@example.test'),
('54000000-0000-0000-0000-000000000005','montage-viewer@example.test');
set local role authenticated;
select set_config('request.jwt.claim.sub','54000000-0000-0000-0000-000000000001',true);
select set_config('test.d.wa',public.studio_create_workspace('Montage A','personal')::text,true);
select set_config('test.d.pa',public.studio_create_project(pg_temp.id('wa'),'Chantier Strasbourg','construction')::text,true);
select set_config('test.d.aa',public.studio_reserve_media(pg_temp.id('pa'),gen_random_uuid(),'a.jpg','image/jpeg',123)::text,true);
select set_config('test.d.va',public.studio_reserve_media(pg_temp.id('pa'),gen_random_uuid(),'v.mp4','video/mp4',123)::text,true);
select public.studio_set_member(pg_temp.id('wa'),'54000000-0000-0000-0000-000000000003','admin');
select public.studio_set_member(pg_temp.id('wa'),'54000000-0000-0000-0000-000000000004','editor');
select public.studio_set_member(pg_temp.id('wa'),'54000000-0000-0000-0000-000000000005','viewer');
select throws_ok('select pg_temp.save(pg_temp.id(''pa''),null,pg_temp.draft(pg_temp.id(''aa'')))','42501',null,'pending refused');
reset role;
update public.studio_media_assets set upload_status='ready',duration_ms=case when media_type='video' then 10000 end where workspace_id=pg_temp.id('wa');
set local role authenticated;
select set_config('test.d.ta',pg_temp.save(pg_temp.id('pa'),null,pg_temp.draft(pg_temp.id('aa')))::text,true);
reset role;
insert into storage.objects(bucket_id,name,metadata) select storage_bucket,storage_key,'{"size":123}'::jsonb from public.studio_media_assets where workspace_id=pg_temp.id('wa');
set local role authenticated;
select set_config('test.d.req',gen_random_uuid()::text,true);
select set_config('test.d.job',public.studio_request_render(pg_temp.id('pa'),pg_temp.id('req'),'preview')::text,true);
select is(public.studio_request_render(pg_temp.id('pa'),pg_temp.id('req'),'preview'),pg_temp.id('job'),'idempotent request');
select is((select count(*) from public.studio_render_jobs),1::bigint,'one job');
select throws_ok('select public.studio_request_render(pg_temp.id(''pa''),pg_temp.id(''req''),''standard'')','22023',null,'idempotency mismatch refused');
select is((select width from public.studio_render_jobs),540,'preview width');
select is((select height from public.studio_render_jobs),960,'preview height');
select throws_ok('update public.studio_render_jobs set status=''completed''','42501',null,'client cannot complete');
select throws_ok('select public.studio_claim_render(pg_temp.id(''job''),gen_random_uuid())','42501',null,'client cannot claim');
select lives_ok('select pg_temp.save(pg_temp.id(''pa''),pg_temp.id(''ta''),pg_temp.draft(pg_temp.id(''aa'')),1)','timeline remains editable');
select is((select (snapshot->'timeline'->>'revision')::int from public.studio_render_jobs),1,'snapshot remains immutable');
select set_config('request.jwt.claim.sub','54000000-0000-0000-0000-000000000002',true);
select is((select count(*) from public.studio_render_jobs),0::bigint,'B cannot read A jobs');
select throws_ok('select public.studio_request_render(pg_temp.id(''pa''),gen_random_uuid())','42501',null,'B cannot render A');
select throws_ok('select public.studio_cancel_render(pg_temp.id(''job''))','42501',null,'B cannot cancel A');
select set_config('request.jwt.claim.sub','54000000-0000-0000-0000-000000000005',true);
select is((select count(*) from public.studio_render_jobs),1::bigint,'viewer reads jobs');
select throws_ok('select public.studio_request_render(pg_temp.id(''pa''),gen_random_uuid())','42501',null,'viewer cannot render');
select throws_ok('select public.studio_cancel_render(pg_temp.id(''job''))','42501',null,'viewer cannot cancel');
select set_config('request.jwt.claim.sub','54000000-0000-0000-0000-000000000004',true);
select lives_ok('select public.studio_request_render(pg_temp.id(''pa''),gen_random_uuid())','editor creates');
select set_config('request.jwt.claim.sub','54000000-0000-0000-0000-000000000003',true);
select lives_ok('select public.studio_request_render(pg_temp.id(''pa''),gen_random_uuid())','admin creates');
reset role;set local role service_role;
select set_config('test.d.lease',gen_random_uuid()::text,true);
select ok(public.studio_claim_render(pg_temp.id('job'),pg_temp.id('lease')) is not null,'worker claims');
select ok(public.studio_claim_render(pg_temp.id('job'),gen_random_uuid()) is null,'duplicate worker refused');
select is(public.studio_render_progress(pg_temp.id('job'),gen_random_uuid(),'rendering',20),false,'stale lease refused');
select is(public.studio_render_progress(pg_temp.id('job'),pg_temp.id('lease'),'rendering',20),true,'progress rendering');
select is(public.studio_render_progress(pg_temp.id('job'),pg_temp.id('lease'),'rendering',10),true,'lower progress accepted without regression');
select is((select progress_percent from public.studio_render_jobs where id=pg_temp.id('job')),20,'monotone progress');
select throws_ok('select public.studio_render_progress(pg_temp.id(''job''),pg_temp.id(''lease''),''preparing'',30)','22023',null,'stage regression denied');
select throws_ok('select public.studio_complete_render(pg_temp.id(''job''),pg_temp.id(''lease''),123,3000)','22023',null,'no completed without object');
reset role;
insert into storage.objects(bucket_id,name,metadata) values('studio-renders','studio/'||pg_temp.id('wa')||'/'||pg_temp.id('pa')||'/renders/'||pg_temp.id('job')||'/'||pg_temp.id('lease')||'/output.mp4','{"size":123}');
set local role service_role;
select set_config('test.d.output',public.studio_complete_render(pg_temp.id('job'),pg_temp.id('lease'),123,3000)::text,true);
select is((select status from public.studio_render_jobs where id=pg_temp.id('job')),'completed','completed with storage proof');
select ok(public.studio_complete_render(pg_temp.id('job'),pg_temp.id('lease'),123,3000) is null,'duplicate publication refused');
select is((select count(*) from public.studio_render_outputs where render_job_id=pg_temp.id('job')),1::bigint,'one output');
reset role;set local role authenticated;
select set_config('request.jwt.claim.sub','54000000-0000-0000-0000-000000000002',true);
select is((select count(*) from public.studio_render_outputs),0::bigint,'B cannot read A output');
select set_config('request.jwt.claim.sub','54000000-0000-0000-0000-000000000005',true);
select is((select count(*) from public.studio_render_outputs),1::bigint,'viewer reads output');
select is((select count(*) from storage.objects where bucket_id='studio-renders'),0::bigint,'private bucket protected from direct read');
select set_config('request.jwt.claim.sub','54000000-0000-0000-0000-000000000001',true);
select set_config('test.d.cancel',public.studio_request_render(pg_temp.id('pa'),gen_random_uuid())::text,true);
select public.studio_cancel_render(pg_temp.id('cancel'));
select is((select status from public.studio_render_jobs where id=pg_temp.id('cancel')),'cancelled','queued cancellation');
reset role;set local role service_role;
select ok(public.studio_claim_render(pg_temp.id('cancel'),gen_random_uuid()) is null,'cancelled cannot claim');
reset role;set local role authenticated;
select set_config('test.d.lost',public.studio_request_render(pg_temp.id('pa'),gen_random_uuid())::text,true);
reset role;set local role service_role;
select ok(exists(select 1 from public.studio_render_dispatch() id where id=pg_temp.id('lost')),'outbox dispatches queued job');
select ok(exists(select 1 from public.studio_render_dispatch() id where id=pg_temp.id('lost')),'Redis rebuild can redispatch without losing DB job');
select ok(public.studio_claim_render(pg_temp.id('lost'),pg_temp.id('lease')) is not null,'claim recovery fixture');
reset role;
update public.studio_render_jobs set heartbeat_at=now()-interval '61 seconds' where id=pg_temp.id('lost');
set local role service_role;
select public.studio_render_dispatch();
select is((select error_code from public.studio_render_jobs where id=pg_temp.id('lost')),'WORKER_LOST','expired worker fails explicitly');
select is(public.studio_render_progress(pg_temp.id('lost'),pg_temp.id('lease'),'rendering',30),false,'expired lease cannot resume');
select ok(public.studio_complete_render(pg_temp.id('lost'),pg_temp.id('lease'),123,3000) is null,'expired lease cannot publish');
reset role;set local role authenticated;
select set_config('request.jwt.claim.sub','54000000-0000-0000-0000-000000000003',true);
select set_config('test.d.revoked',public.studio_request_render(pg_temp.id('pa'),gen_random_uuid())::text,true);
reset role;set local role service_role;
select public.studio_claim_render(pg_temp.id('revoked'),pg_temp.id('lease'));
reset role;set local role authenticated;
select set_config('request.jwt.claim.sub','54000000-0000-0000-0000-000000000001',true);
select public.studio_set_member(pg_temp.id('wa'),'54000000-0000-0000-0000-000000000003','viewer');
reset role;set local role service_role;
select is(public.studio_render_progress(pg_temp.id('revoked'),pg_temp.id('lease'),'rendering',30),false,'revoked writer loses active render lease');
select is((select status from public.studio_render_jobs where id=pg_temp.id('revoked')),'cancelled','revoked render is cancelled');
reset role;
select ok((select relrowsecurity from pg_class where oid='public.studio_render_jobs'::regclass),'jobs RLS');
select ok((select relrowsecurity from pg_class where oid='public.studio_render_outputs'::regclass),'outputs RLS');
select is((select public from storage.buckets where id='studio-renders'),false,'private renders bucket');
select * from finish();rollback;
