begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
create function pg_temp.id(k text) returns uuid language sql as $$select current_setting('test.h.'||k)::uuid$$;
create function pg_temp.result() returns jsonb language sql as $$select jsonb_build_object('sha256',repeat('a',64),'quality_score',80,'face_count',0,'samples',jsonb_build_array(jsonb_build_object('dhash','0000000000000000')))$$;
insert into auth.users(id,email) values
('55000000-0000-0000-0000-000000000001','analysis-a@example.test'),
('55000000-0000-0000-0000-000000000002','analysis-b@example.test'),
('55000000-0000-0000-0000-000000000003','analysis-admin@example.test'),
('55000000-0000-0000-0000-000000000004','analysis-editor@example.test'),
('55000000-0000-0000-0000-000000000005','analysis-viewer@example.test');
set local role authenticated;
select set_config('request.jwt.claim.sub','55000000-0000-0000-0000-000000000001',true);
select set_config('test.h.wa',public.studio_create_workspace('Analyse A','personal')::text,true);
select set_config('test.h.pa',public.studio_create_project(pg_temp.id('wa'),'Chantier Strasbourg','construction')::text,true);
select set_config('test.h.aa',public.studio_reserve_media(pg_temp.id('pa'),gen_random_uuid(),'a.jpg','image/jpeg',123)::text,true);
select public.studio_set_member(pg_temp.id('wa'),'55000000-0000-0000-0000-000000000003','admin');
select public.studio_set_member(pg_temp.id('wa'),'55000000-0000-0000-0000-000000000004','editor');
select public.studio_set_member(pg_temp.id('wa'),'55000000-0000-0000-0000-000000000005','viewer');
select is(public.studio_request_analysis(pg_temp.id('pa')),0,'pending upload not analyzed');
reset role;
update studio_media_assets set upload_status='ready',width=1920,height=1080 where id=pg_temp.id('aa');
set local role authenticated;
select is(public.studio_request_analysis(pg_temp.id('pa')),1,'owner requests analysis');
select is(public.studio_request_analysis(pg_temp.id('pa')),0,'idempotent admission');
select set_config('test.h.ja',(select id::text from studio_media_analysis where asset_id=pg_temp.id('aa')),true);
select is((select analysis_version from studio_media_analysis where id=pg_temp.id('ja')),'media-v1','version stored');
select is(jsonb_array_length(studio_list_analysis(pg_temp.id('pa'))),1,'A reads analysis A');
select ok(not ((studio_list_analysis(pg_temp.id('pa'))->0) ? 'lease_token'),'lease excluded from API projection');
select throws_ok('update studio_media_analysis set status=''completed''','42501',null,'direct mutation denied');
select set_config('request.jwt.claim.sub','55000000-0000-0000-0000-000000000005',true);
select is(jsonb_array_length(studio_list_analysis(pg_temp.id('pa'))),1,'viewer reads results');
select throws_ok('select studio_request_analysis(pg_temp.id(''pa''))','42501',null,'viewer cannot launch');
select throws_ok('select studio_cancel_analysis(pg_temp.id(''pa''))','42501',null,'viewer cannot cancel');
select set_config('request.jwt.claim.sub','55000000-0000-0000-0000-000000000004',true);
select lives_ok('select studio_request_analysis(pg_temp.id(''pa''))','editor can request cached/pending');
select set_config('request.jwt.claim.sub','55000000-0000-0000-0000-000000000003',true);
select lives_ok('select studio_request_analysis(pg_temp.id(''pa''))','admin can request');
select set_config('request.jwt.claim.sub','55000000-0000-0000-0000-000000000002',true);
select is((select count(*) from studio_media_analysis),0::bigint,'B cannot read A by direct RLS');
select is(jsonb_array_length(studio_list_analysis(pg_temp.id('pa'))),0,'B cannot read A through list RPC');
select throws_ok('select studio_request_analysis(pg_temp.id(''pa''))','42501',null,'B cannot request A');
select throws_ok('select studio_cancel_analysis(pg_temp.id(''pa''))','42501',null,'B cannot cancel A');
select set_config('test.h.wb',public.studio_create_workspace('Analyse B','personal')::text,true);
select set_config('test.h.pb',public.studio_create_project(pg_temp.id('wb'),'Voyage','travel')::text,true);
select set_config('test.h.ab',public.studio_reserve_media(pg_temp.id('pb'),gen_random_uuid(),'b.jpg','image/jpeg',123)::text,true);
reset role;
update studio_media_assets set upload_status='ready' where id=pg_temp.id('ab');
select throws_ok('insert into studio_media_analysis(workspace_id,asset_id,project_id,analysis_version,requested_by) values(pg_temp.id(''wb''),pg_temp.id(''aa''),pg_temp.id(''pb''),''media-v2'',''55000000-0000-0000-0000-000000000002'')','23503',null,'composite FK prevents foreign asset');
set local role authenticated;
select is(studio_request_analysis(pg_temp.id('pb')),1,'B requests B');
select is((select count(*) from studio_media_analysis),1::bigint,'B reads only B');
select set_config('request.jwt.claim.sub','55000000-0000-0000-0000-000000000001',true);
select is(jsonb_array_length(studio_list_analysis(pg_temp.id('pb'))),0,'A cannot read B');
select throws_ok('select studio_claim_analysis(pg_temp.id(''ja''),gen_random_uuid())','42501',null,'client cannot claim worker lease');
reset role;
set local role service_role;
select set_config('test.h.lease',gen_random_uuid()::text,true);
select ok(studio_claim_analysis(pg_temp.id('ja'),pg_temp.id('lease')) is not null,'private worker claims');
select ok(studio_claim_analysis(pg_temp.id('ja'),gen_random_uuid()) is null,'double claim rejected');
select ok(not studio_finish_analysis(pg_temp.id('ja'),gen_random_uuid(),pg_temp.result(),10),'stale lease cannot publish');
select throws_ok('select studio_finish_analysis(pg_temp.id(''ja''),pg_temp.id(''lease''),pg_temp.result()||''{"quality_score":101}'',10)','22023',null,'invalid score rejected');
select ok(studio_finish_analysis(pg_temp.id('ja'),pg_temp.id('lease'),pg_temp.result(),10,true),'local fallback result published');
reset role;
set local role authenticated;
select is(studio_request_analysis(pg_temp.id('pa')),0,'completed version cache reused');
select is(studio_request_analysis(pg_temp.id('pa'),true),0,'immediate forced reanalysis cooldown');
select is((select fallback from studio_media_analysis where id=pg_temp.id('ja')),true,'fallback provenance retained');
reset role;
update studio_media_analysis set requested_at=now()-interval '1 minute' where id=pg_temp.id('ja');
set local role authenticated;
select is(studio_request_analysis(pg_temp.id('pa'),true),1,'explicit reanalysis after cooldown');
reset role;
set local role service_role;
select ok(studio_claim_analysis(pg_temp.id('ja'),pg_temp.id('lease')) is not null,'reanalysis claimed');
reset role;
set local role authenticated;
select lives_ok('select studio_cancel_analysis(pg_temp.id(''pa''))','owner cancels inflight analysis');
select is((select status from studio_media_analysis where id=pg_temp.id('ja')),'skipped','cancelled analysis is skipped');
reset role;
set local role service_role;
select ok(not studio_analysis_touch(pg_temp.id('ja'),pg_temp.id('lease')),'cancel invalidates heartbeat');
select ok(not studio_finish_analysis(pg_temp.id('ja'),pg_temp.id('lease'),pg_temp.result(),10),'cancelled worker cannot publish');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','55000000-0000-0000-0000-000000000004',true);
select is(studio_request_analysis(pg_temp.id('pa')),1,'editor retries skipped job');
select set_config('request.jwt.claim.sub','55000000-0000-0000-0000-000000000001',true);
select studio_set_member(pg_temp.id('wa'),'55000000-0000-0000-0000-000000000004','viewer');
reset role;
set local role service_role;
select ok(studio_claim_analysis(pg_temp.id('ja'),pg_temp.id('lease')) is null,'revoked editor cannot start queued job');
reset role;
select is((select error_code from studio_media_analysis where id=pg_temp.id('ja')),'ACCESS_REVOKED','revocation persisted as generic error');
select throws_ok('insert into studio_media_analysis(workspace_id,asset_id,project_id,analysis_version,requested_by) select workspace_id,asset_id,project_id,analysis_version,requested_by from studio_media_analysis where id=pg_temp.id(''ja'')','23505',null,'one result per asset/version');
insert into studio_media_analysis(workspace_id,asset_id,project_id,analysis_version,requested_by,status)
 select workspace_id,asset_id,project_id,'media-v2',requested_by,'pending' from studio_media_analysis where id=pg_temp.id('ja');
select is((select count(*) from studio_media_analysis where asset_id=pg_temp.id('aa')),2::bigint,'future version separate');
set local role authenticated;
select lives_ok('select studio_remove_project_media(pg_temp.id(''pa''),pg_temp.id(''aa''))','last reference removal');
reset role;
select is((select count(*) from studio_media_analysis where asset_id=pg_temp.id('aa')),0::bigint,'analysis purged with last-reference tombstone');
select ok((select deleted_at is not null from studio_media_assets where id=pg_temp.id('aa')),'asset follows existing deletion contract');
select ok(not has_function_privilege('anon','studio_list_analysis(uuid)','EXECUTE'),'anon denied');
select ok(not has_function_privilege('authenticated','studio_finish_analysis(uuid,uuid,jsonb,integer,boolean,text)','EXECUTE'),'client cannot invent results');
select * from finish();rollback;
