begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
create function pg_temp.id(k text) returns uuid language sql as $$select current_setting('test.c.'||k)::uuid$$;
create function pg_temp.input(extra jsonb default '{}') returns jsonb language sql as $$select '{"name":"Projet","project_type":"travel","description":"Description","location_label":"Croatie","started_at":"2026-08-01","ended_at":"2026-08-10","target_aspect_ratio":"9:16","target_duration_seconds":90,"status":"draft","metadata_json":{}}'::jsonb||extra$$;
insert into auth.users(id,email) values
 ('53000000-0000-0000-0000-000000000001','projects-a@example.test'),
 ('53000000-0000-0000-0000-000000000002','projects-b@example.test'),
 ('53000000-0000-0000-0000-000000000003','projects-admin@example.test'),
 ('53000000-0000-0000-0000-000000000004','projects-editor@example.test'),
 ('53000000-0000-0000-0000-000000000005','projects-viewer@example.test');
set local role authenticated;
select set_config('request.jwt.claim.sub','53000000-0000-0000-0000-000000000001',true);
select set_config('test.c.wa',public.studio_create_workspace('Projects A','personal')::text,true);
select set_config('test.c.pa',public.studio_save_project(pg_temp.id('wa'),null,pg_temp.input(),null)::text,true);
select set_config('test.c.aa',public.studio_reserve_media(pg_temp.id('pa'),gen_random_uuid(),'a.jpg','image/jpeg',123)::text,true);
select set_config('test.c.a2',public.studio_reserve_media(pg_temp.id('pa'),gen_random_uuid(),'a2.jpg','image/jpeg',124)::text,true);
select public.studio_set_member(pg_temp.id('wa'),'53000000-0000-0000-0000-000000000003','admin');
select public.studio_set_member(pg_temp.id('wa'),'53000000-0000-0000-0000-000000000004','editor');
select public.studio_set_member(pg_temp.id('wa'),'53000000-0000-0000-0000-000000000005','viewer');
select throws_ok('select public.studio_duplicate_project(pg_temp.id(''pa''))','22023',null,'duplication refuse les pending');
reset role;
update public.studio_media_assets set upload_status='ready',width=100,height=100 where workspace_id=pg_temp.id('wa');
update public.studio_media_assets set captured_at='2020-01-01' where id=pg_temp.id('a2');
set local role authenticated;
select set_config('request.jwt.claim.sub','53000000-0000-0000-0000-000000000002',true);
select set_config('test.c.wb',public.studio_create_workspace('Projects B','personal')::text,true);
select set_config('test.c.pb',public.studio_save_project(pg_temp.id('wb'),null,pg_temp.input(),null)::text,true);
select set_config('test.c.ab',public.studio_reserve_media(pg_temp.id('pb'),gen_random_uuid(),'b.jpg','image/jpeg',123)::text,true);
reset role;update public.studio_media_assets set upload_status='ready' where id=pg_temp.id('ab');set local role authenticated;
select set_config('request.jwt.claim.sub','53000000-0000-0000-0000-000000000001',true);
select is((select count(*) from public.studio_projects where id=pg_temp.id('pb')),0::bigint,'tenant 1 ne lit pas le projet étranger');
select is((select count(*) from public.studio_project_assets where project_id=pg_temp.id('pb')),0::bigint,'tenant 1 ne lit pas les références étrangères');
select throws_ok('select public.studio_save_project(pg_temp.id(''wa''),pg_temp.id(''pb''),pg_temp.input(),1)', '42501', null, 'tenant 1 mutation étrangère interdite');
select throws_ok('select public.studio_duplicate_project(pg_temp.id(''pb''))', '42501', null, 'tenant 1 mutation étrangère interdite');
select throws_ok('select public.studio_set_project_cover(pg_temp.id(''pb''),pg_temp.id(''ab''))', '42501', null, 'tenant 1 mutation étrangère interdite');
select throws_ok('select public.studio_order_project_media(pg_temp.id(''pb''),array[pg_temp.id(''ab'')],false,1)', '42501', null, 'tenant 1 mutation étrangère interdite');
select throws_ok('select public.studio_project_lifecycle(pg_temp.id(''pb''),''archive'')', '42501', null, 'tenant 1 mutation étrangère interdite');
select throws_ok('select public.studio_project_lifecycle(pg_temp.id(''pb''),''restore'')', '42501', null, 'tenant 1 mutation étrangère interdite');
select throws_ok('select public.studio_project_lifecycle(pg_temp.id(''pb''),''delete'')', '42501', null, 'tenant 1 mutation étrangère interdite');
select throws_ok('select public.studio_remove_project_media(pg_temp.id(''pb''),pg_temp.id(''ab''))', '42501', null, 'tenant 1 mutation étrangère interdite');
select set_config('request.jwt.claim.sub','53000000-0000-0000-0000-000000000002',true);
select is((select count(*) from public.studio_projects where id=pg_temp.id('pa')),0::bigint,'tenant 2 ne lit pas le projet étranger');
select is((select count(*) from public.studio_project_assets where project_id=pg_temp.id('pa')),0::bigint,'tenant 2 ne lit pas les références étrangères');
select throws_ok('select public.studio_save_project(pg_temp.id(''wb''),pg_temp.id(''pa''),pg_temp.input(),1)', '42501', null, 'tenant 2 mutation étrangère interdite');
select throws_ok('select public.studio_duplicate_project(pg_temp.id(''pa''))', '42501', null, 'tenant 2 mutation étrangère interdite');
select throws_ok('select public.studio_set_project_cover(pg_temp.id(''pa''),pg_temp.id(''aa''))', '42501', null, 'tenant 2 mutation étrangère interdite');
select throws_ok('select public.studio_order_project_media(pg_temp.id(''pa''),array[pg_temp.id(''aa'')],false,1)', '42501', null, 'tenant 2 mutation étrangère interdite');
select throws_ok('select public.studio_project_lifecycle(pg_temp.id(''pa''),''archive'')', '42501', null, 'tenant 2 mutation étrangère interdite');
select throws_ok('select public.studio_project_lifecycle(pg_temp.id(''pa''),''restore'')', '42501', null, 'tenant 2 mutation étrangère interdite');
select throws_ok('select public.studio_project_lifecycle(pg_temp.id(''pa''),''delete'')', '42501', null, 'tenant 2 mutation étrangère interdite');
select throws_ok('select public.studio_remove_project_media(pg_temp.id(''pa''),pg_temp.id(''aa''))', '42501', null, 'tenant 2 mutation étrangère interdite');
select set_config('request.jwt.claim.sub','53000000-0000-0000-0000-000000000001',true);
select lives_ok('select public.studio_save_project(pg_temp.id(''wa''),null,pg_temp.input(''{"project_type":"construction"}''),null)', 'création type construction');
select lives_ok('select public.studio_save_project(pg_temp.id(''wa''),null,pg_temp.input(''{"project_type":"travel"}''),null)', 'création type travel');
select lives_ok('select public.studio_save_project(pg_temp.id(''wa''),null,pg_temp.input(''{"project_type":"wedding"}''),null)', 'création type wedding');
select lives_ok('select public.studio_save_project(pg_temp.id(''wa''),null,pg_temp.input(''{"project_type":"birthday"}''),null)', 'création type birthday');
select lives_ok('select public.studio_save_project(pg_temp.id(''wa''),null,pg_temp.input(''{"project_type":"event"}''),null)', 'création type event');
select lives_ok('select public.studio_save_project(pg_temp.id(''wa''),null,pg_temp.input(''{"project_type":"memory"}''),null)', 'création type memory');
select lives_ok('select public.studio_save_project(pg_temp.id(''wa''),null,pg_temp.input(''{"project_type":"free"}''),null)', 'création type free');
select lives_ok('select public.studio_save_project(pg_temp.id(''wa''),null,pg_temp.input(''{"target_aspect_ratio":"9:16"}''),null)', 'format 9:16');
select lives_ok('select public.studio_save_project(pg_temp.id(''wa''),null,pg_temp.input(''{"target_aspect_ratio":"16:9"}''),null)', 'format 16:9');
select lives_ok('select public.studio_save_project(pg_temp.id(''wa''),null,pg_temp.input(''{"target_aspect_ratio":"1:1"}''),null)', 'format 1:1');
select lives_ok('select public.studio_save_project(pg_temp.id(''wa''),null,pg_temp.input(''{"target_aspect_ratio":"4:5"}''),null)', 'format 4:5');
select throws_ok('select public.studio_save_project(pg_temp.id(''wa''),null,pg_temp.input(''{"name":""}''),null)', '23514', null, 'contrainte nom vide');
select throws_ok('select public.studio_save_project(pg_temp.id(''wa''),null,pg_temp.input(''{"project_type":"unknown"}''),null)', '23514', null, 'contrainte type');
select throws_ok('select public.studio_save_project(pg_temp.id(''wa''),null,pg_temp.input(''{"target_aspect_ratio":"4:3"}''),null)', '23514', null, 'contrainte format');
select throws_ok('select public.studio_save_project(pg_temp.id(''wa''),null,pg_temp.input(''{"target_duration_seconds":0}''),null)', '23514', null, 'contrainte durée zéro');
select throws_ok('select public.studio_save_project(pg_temp.id(''wa''),null,pg_temp.input(''{"target_duration_seconds":601}''),null)', '23514', null, 'contrainte durée haute');
select throws_ok('select public.studio_save_project(pg_temp.id(''wa''),null,pg_temp.input(''{"ended_at":"2026-01-01"}''),null)', '23514', null, 'contrainte dates inversées');
select throws_ok('select public.studio_save_project(pg_temp.id(''wa''),null,pg_temp.input(''{"metadata_json":{"company":"GP"}}''),null)', '23514', null, 'contrainte metadata hors chantier');
select throws_ok('select public.studio_set_project_cover(pg_temp.id(''pa''),pg_temp.id(''ab''))', '42501', null, 'cover étrangère refusée');
select is((select count(*) from public.studio_media_assets where id=pg_temp.id('aa')),1::bigint,'lecture asset A');
select lives_ok('select public.studio_set_project_cover(pg_temp.id(''pa''),pg_temp.id(''aa''))','cover image locale');
select lives_ok('select public.studio_order_project_media(pg_temp.id(''pa''),array[pg_temp.id(''a2''),pg_temp.id(''aa'')],false,(select revision from public.studio_projects where id=pg_temp.id(''pa'')))','ordre manuel');
select is((select asset_id from public.studio_project_assets where project_id=pg_temp.id('pa') order by sort_order limit 1),pg_temp.id('a2'),'ordre manuel persisté');
select throws_ok('select public.studio_order_project_media(pg_temp.id(''pa''),array[pg_temp.id(''aa''),pg_temp.id(''ab'')],false,(select revision from public.studio_projects where id=pg_temp.id(''pa'')))','42501',null,'ordre cross workspace refusé');
select throws_ok('select public.studio_order_project_media(pg_temp.id(''pa''),array[pg_temp.id(''aa''),pg_temp.id(''aa'')],false,(select revision from public.studio_projects where id=pg_temp.id(''pa'')))','42501',null,'ordre doublons refusé');
select throws_ok('select public.studio_order_project_media(pg_temp.id(''pa''),array[pg_temp.id(''aa'')],false,(select revision from public.studio_projects where id=pg_temp.id(''pa'')))','42501',null,'ordre incomplet refusé');
select lives_ok('select public.studio_order_project_media(pg_temp.id(''pa''),array[]::uuid[],true,(select revision from public.studio_projects where id=pg_temp.id(''pa'')))','tri chronologique');
select is((select asset_id from public.studio_project_assets where project_id=pg_temp.id('pa') order by sort_order limit 1),pg_temp.id('a2'),'date capturée prioritaire');
select throws_ok('select public.studio_save_project(pg_temp.id(''wa''),pg_temp.id(''pa''),pg_temp.input(),1)','40001',null,'conflit édition protégé');
select set_config('test.c.copy',public.studio_duplicate_project(pg_temp.id('pa'))::text,true);
select is((select count(*) from public.studio_project_assets where project_id=pg_temp.id('copy')),2::bigint,'copie avec deux références');
select is((select count(*) from public.studio_media_assets where workspace_id=pg_temp.id('wa')),2::bigint,'aucun asset physique dupliqué');
select is((select cover_asset_id from public.studio_projects where id=pg_temp.id('copy')),pg_temp.id('aa'),'couverture copiée');
select is((select asset_id from public.studio_project_assets where project_id=pg_temp.id('copy') order by sort_order limit 1),pg_temp.id('a2'),'ordre copié');
select lives_ok('select public.studio_project_lifecycle(pg_temp.id(''pa''),''archive'')','archive owner');
select is((public.studio_project_summaries(pg_temp.id('wa'),'','travel','archived')->>'total')::int,1,'filtre archives');
select is((public.studio_project_summaries(pg_temp.id('wa'),'aucun titre compatible','','all')->>'total')::int,0,'recherche nom description');
select is((public.studio_project_summaries(pg_temp.id('wa'),'','','all','2099-01-01')->>'total')::int,0,'filtre date modification');
select is((public.studio_project_summaries(pg_temp.id('wb'))->>'total')::int,0,'liste RPC workspace étranger vide');

select is((select status from public.studio_projects where id=pg_temp.id('pa')),'archived','statut archive');
select is((select count(*) from public.studio_project_assets where project_id=pg_temp.id('pa')),2::bigint,'archive conserve médias');
select throws_ok('select public.studio_reserve_media(pg_temp.id(''pa''),gen_random_uuid(),''x.jpg'',''image/jpeg'',100)','22023',null,'upload projet archivé refusé');
select lives_ok('select public.studio_project_lifecycle(pg_temp.id(''pa''),''restore'')','restauration');
select is((select status from public.studio_projects where id=pg_temp.id('pa')),'draft','restauré en brouillon');
select set_config('request.jwt.claim.sub','53000000-0000-0000-0000-000000000003',true);
select lives_ok('select public.studio_save_project(pg_temp.id(''wa''),pg_temp.id(''pa''),pg_temp.input(),(select revision from public.studio_projects where id=pg_temp.id(''pa'')))', 'admin édite');
select lives_ok('select public.studio_project_lifecycle(pg_temp.id(''pa''),''archive'')','admin archive');
select lives_ok('select public.studio_project_lifecycle(pg_temp.id(''pa''),''restore'')','admin restaure');
select lives_ok('select public.studio_duplicate_project(pg_temp.id(''pa''))', 'admin mutation autorisée');
select lives_ok('select public.studio_set_project_cover(pg_temp.id(''pa''),pg_temp.id(''aa''))', 'admin mutation autorisée');
select lives_ok('select public.studio_order_project_media(pg_temp.id(''pa''),array[pg_temp.id(''aa''),pg_temp.id(''a2'')],false,(select revision from public.studio_projects where id=pg_temp.id(''pa'')))', 'admin mutation autorisée');
select throws_ok('update public.studio_projects set name=''intrusion'' where id=pg_temp.id(''pa'')', '42501', null, 'admin DML direct interdit');
select throws_ok('insert into public.studio_project_assets values(pg_temp.id(''wa''),pg_temp.id(''pa''),pg_temp.id(''ab''),9,now())', '42501', null, 'admin références directes interdites');
select set_config('request.jwt.claim.sub','53000000-0000-0000-0000-000000000004',true);
select lives_ok('select public.studio_save_project(pg_temp.id(''wa''),pg_temp.id(''pa''),pg_temp.input(),(select revision from public.studio_projects where id=pg_temp.id(''pa'')))', 'editor édite');
select lives_ok('select public.studio_duplicate_project(pg_temp.id(''pa''))', 'editor mutation autorisée');
select lives_ok('select public.studio_set_project_cover(pg_temp.id(''pa''),pg_temp.id(''aa''))', 'editor mutation autorisée');
select lives_ok('select public.studio_order_project_media(pg_temp.id(''pa''),array[pg_temp.id(''aa''),pg_temp.id(''a2'')],false,(select revision from public.studio_projects where id=pg_temp.id(''pa'')))', 'editor mutation autorisée');
select throws_ok('select public.studio_project_lifecycle(pg_temp.id(''pa''),''archive'')', '42501', null, 'editor lifecycle refusé');
select throws_ok('select public.studio_project_lifecycle(pg_temp.id(''pa''),''restore'')', '42501', null, 'editor lifecycle refusé');
select throws_ok('select public.studio_project_lifecycle(pg_temp.id(''pa''),''delete'')', '42501', null, 'editor lifecycle refusé');
select throws_ok('update public.studio_projects set name=''intrusion'' where id=pg_temp.id(''pa'')', '42501', null, 'editor DML direct interdit');
select throws_ok('insert into public.studio_project_assets values(pg_temp.id(''wa''),pg_temp.id(''pa''),pg_temp.id(''ab''),9,now())', '42501', null, 'editor références directes interdites');
select set_config('request.jwt.claim.sub','53000000-0000-0000-0000-000000000005',true);
select throws_ok('select public.studio_save_project(pg_temp.id(''wa''),pg_temp.id(''pa''),pg_temp.input(),(select revision from public.studio_projects where id=pg_temp.id(''pa'')))', '42501', null, 'viewer édition refusée');
select throws_ok('select public.studio_duplicate_project(pg_temp.id(''pa''))', '42501', null, 'viewer mutation refusée');
select throws_ok('select public.studio_set_project_cover(pg_temp.id(''pa''),pg_temp.id(''aa''))', '42501', null, 'viewer mutation refusée');
select throws_ok('select public.studio_order_project_media(pg_temp.id(''pa''),array[pg_temp.id(''aa''),pg_temp.id(''a2'')],false,(select revision from public.studio_projects where id=pg_temp.id(''pa'')))', '42501', null, 'viewer mutation refusée');
select throws_ok('select public.studio_project_lifecycle(pg_temp.id(''pa''),''archive'')', '42501', null, 'viewer lifecycle refusé');
select throws_ok('select public.studio_project_lifecycle(pg_temp.id(''pa''),''restore'')', '42501', null, 'viewer lifecycle refusé');
select throws_ok('select public.studio_project_lifecycle(pg_temp.id(''pa''),''delete'')', '42501', null, 'viewer lifecycle refusé');
select throws_ok('update public.studio_projects set name=''intrusion'' where id=pg_temp.id(''pa'')', '42501', null, 'viewer DML direct interdit');
select throws_ok('insert into public.studio_project_assets values(pg_temp.id(''wa''),pg_temp.id(''pa''),pg_temp.id(''ab''),9,now())', '42501', null, 'viewer références directes interdites');
select set_config('request.jwt.claim.sub','53000000-0000-0000-0000-000000000001',true);
reset role;
select throws_ok('insert into public.studio_project_assets values(pg_temp.id(''wa''),pg_temp.id(''pa''),pg_temp.id(''ab''),9,now())','23503',null,'FK tenant asset même en SQL privilégié');
select throws_ok('insert into public.studio_project_assets values(pg_temp.id(''wb''),pg_temp.id(''pa''),pg_temp.id(''ab''),9,now())','23503',null,'FK tenant projet même en SQL privilégié');
select throws_ok('update public.studio_media_assets set deleted_at=now() where id=pg_temp.id(''aa'')','23514',null,'tombstone asset partagé impossible');
set local role authenticated;
select lives_ok('select public.studio_project_lifecycle(pg_temp.id(''pa''),''delete'')','suppression source');
select is((select count(*) from public.studio_projects where id=pg_temp.id('pa')),0::bigint,'projet soft deleted invisible');
select is((select count(*) from public.studio_media_assets where id=pg_temp.id('aa')),1::bigint,'asset copie lisible après suppression source');
select is(jsonb_array_length(public.studio_list_project_media(pg_temp.id('copy'))),2,'copie garde sa bibliothèque');
select lives_ok('select public.studio_remove_project_media(pg_temp.id(''copy''),pg_temp.id(''aa''))','retirer une référence');
select is((select cover_asset_id from public.studio_projects where id=pg_temp.id('copy')),null::uuid,'cover nettoyée');
-- Remove all remaining copies before checking the final reference tombstone.
reset role;
update public.studio_projects set cover_asset_id=null where workspace_id=pg_temp.id('wa');
delete from public.studio_project_assets where workspace_id=pg_temp.id('wa') and project_id<>pg_temp.id('copy');
set local role authenticated;
select lives_ok('select public.studio_project_lifecycle(pg_temp.id(''copy''),''delete'')','suppression dernière copie');
reset role;
select ok((select deleted_at is not null from public.studio_media_assets where id=pg_temp.id('a2')),'dernier média devient tombstone');
select is((select count(*) from public.studio_workspace_members where workspace_id=pg_temp.id('wa') and role='owner'),1::bigint,'dernier owner préservé');
select ok((select relrowsecurity from pg_class where oid='public.studio_project_assets'::regclass),'RLS références active');
select ok((select relrowsecurity from pg_class where oid='public.studio_projects'::regclass),'RLS projets active');
select ok(has_table_privilege('service_role','public.studio_project_assets','select'),'réconciliation autorisée à vérifier les références');
select * from finish();
rollback;
