begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email) values ('51000000-0000-0000-0000-000000000001','studio-a@invalid.local');
insert into auth.users(id,email) values ('51000000-0000-0000-0000-000000000002','studio-b@invalid.local');
insert into auth.users(id,email) values ('51000000-0000-0000-0000-000000000003','studio-admin@invalid.local');
insert into auth.users(id,email) values ('51000000-0000-0000-0000-000000000004','studio-editor@invalid.local');
insert into auth.users(id,email) values ('51000000-0000-0000-0000-000000000005','studio-viewer@invalid.local');
insert into auth.users(id,email) values ('51000000-0000-0000-0000-000000000006','studio-outside@invalid.local');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','51000000-0000-0000-0000-000000000001',true);
select set_config('studio.test.a',public.studio_create_workspace('Studio A','personal')::text,true);
select is(public.studio_create_workspace('Autre nom','personal'), current_setting('studio.test.a')::uuid, 'onboarding idempotent');
select is((select count(*) from public.studio_workspaces), 1::bigint, 'A voit son workspace');
select is(public.studio_my_role(current_setting('studio.test.a')::uuid), 'owner'::text, 'A est owner');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','51000000-0000-0000-0000-000000000002',true);
select set_config('studio.test.b',public.studio_create_workspace('Studio B','personal')::text,true);
select is((select count(*) from public.studio_workspaces where id=current_setting('studio.test.a')::uuid), 0::bigint, 'B ne lit pas A');
select is((select count(*) from public.studio_workspace_members where workspace_id=current_setting('studio.test.a')::uuid), 0::bigint, 'B ne lit pas les membres A');
select throws_ok(format('select public.studio_rename_workspace(%L, %L)',current_setting('studio.test.a')::uuid,'pirate'), '42501', 'Accès refusé', 'B ne modifie pas A');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','51000000-0000-0000-0000-000000000001',true);
select is((select count(*) from public.studio_workspaces where id=current_setting('studio.test.b')::uuid), 0::bigint, 'A ne lit pas B');
select is((select count(*) from public.studio_workspace_members where workspace_id=current_setting('studio.test.b')::uuid), 0::bigint, 'A ne lit pas membres B');
select throws_ok(format('select public.studio_rename_workspace(%L, %L)',current_setting('studio.test.b')::uuid,'pirate'), '42501', 'Accès refusé', 'A refuse studio_rename_workspace B');
select throws_ok(format('select public.studio_archive_workspace(%L)',current_setting('studio.test.b')::uuid), '42501', 'Accès refusé', 'A refuse studio_archive_workspace B');
select throws_ok(format('select public.studio_set_member(%L,%L,%L)',current_setting('studio.test.b')::uuid,'51000000-0000-0000-0000-000000000001','admin'), '42501', 'Accès refusé', 'A ne peut ajouter membre B');
select throws_ok(format('select public.studio_set_member(%L,%L,NULL)',current_setting('studio.test.b')::uuid,'51000000-0000-0000-0000-000000000002'), '42501', 'Accès refusé', 'A ne peut retirer membre B');
select public.studio_set_member(current_setting('studio.test.a')::uuid,'51000000-0000-0000-0000-000000000003','admin');
select public.studio_set_member(current_setting('studio.test.a')::uuid,'51000000-0000-0000-0000-000000000004','editor');
select public.studio_set_member(current_setting('studio.test.a')::uuid,'51000000-0000-0000-0000-000000000005','viewer');
select is((select count(*) from public.studio_workspace_members where workspace_id=current_setting('studio.test.a')::uuid), 4::bigint, 'Owner ajoute les trois roles');
select public.studio_rename_workspace(current_setting('studio.test.a')::uuid,'Nom modifié');
select is((select name from public.studio_workspaces where id=current_setting('studio.test.a')::uuid), 'Nom modifié'::text, 'Owner renomme');
select throws_ok(format('select public.studio_set_member(%L,%L,''admin'')',current_setting('studio.test.a')::uuid,'51000000-0000-0000-0000-000000000001'), '42501', 'Propriétaire protégé : transfert indisponible', 'Owner ne peut perdre son role');
select throws_ok(format('select public.studio_set_member(%L,%L,NULL)',current_setting('studio.test.a')::uuid,'51000000-0000-0000-0000-000000000001'), '42501', 'Propriétaire protégé : transfert indisponible', 'Owner ne peut perdre son role');
select throws_ok(format('select public.studio_set_member(%L,%L,%L)',current_setting('studio.test.a')::uuid,'51000000-0000-0000-0000-000000000002','owner'), '42501', 'Propriétaire protégé : transfert indisponible', 'Second owner et transfert refusés');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','51000000-0000-0000-0000-000000000003',true);
select is(public.studio_my_role(current_setting('studio.test.a')::uuid), 'admin'::text, 'Role admin représenté');
select public.studio_rename_workspace(current_setting('studio.test.a')::uuid,'Admin renomme');
select is((select name from public.studio_workspaces where id=current_setting('studio.test.a')::uuid), 'Admin renomme'::text, 'Admin renomme workspace');
select public.studio_set_member(current_setting('studio.test.a')::uuid,'51000000-0000-0000-0000-000000000004','viewer');
select is((select role from public.studio_workspace_members where user_id='51000000-0000-0000-0000-000000000004' and workspace_id=current_setting('studio.test.a')::uuid), 'viewer'::text, 'Admin gère un membre simple');
select public.studio_set_member(current_setting('studio.test.a')::uuid,'51000000-0000-0000-0000-000000000004','editor');
select throws_ok(format('select public.studio_set_member(%L,%L,%L)',current_setting('studio.test.a')::uuid,'51000000-0000-0000-0000-000000000003','owner'), '42501', 'Propriétaire protégé : transfert indisponible', 'Admin ne se promeut pas owner');
select throws_ok(format('select public.studio_set_member(%L,%L,%L)',current_setting('studio.test.a')::uuid,'51000000-0000-0000-0000-000000000004','admin'), '42501', 'Seul le propriétaire gère les administrateurs', 'Admin ne crée pas admin');
select throws_ok(format('select public.studio_archive_workspace(%L)',current_setting('studio.test.a')::uuid), '42501', 'Accès refusé', 'Admin ne supprime pas workspace');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','51000000-0000-0000-0000-000000000004',true);
select is(public.studio_my_role(current_setting('studio.test.a')::uuid), 'editor'::text, 'Role editor représenté');
select is((select count(*) from public.studio_workspace_members where workspace_id=current_setting('studio.test.a')::uuid), 4::bigint, 'editor lit ses membres');
select throws_ok(format('select public.studio_rename_workspace(%L,%L)',current_setting('studio.test.a')::uuid,'pirate'), '42501', 'Accès refusé', 'editor ne renomme pas');
select throws_ok(format('select public.studio_set_member(%L,%L,%L)',current_setting('studio.test.a')::uuid,'51000000-0000-0000-0000-000000000004','admin'), '42501', 'Accès refusé', 'editor ne se promeut pas');
select throws_ok(format('select public.studio_set_member(%L,%L,NULL)',current_setting('studio.test.a')::uuid,'51000000-0000-0000-0000-000000000001'), '42501', 'Accès refusé', 'editor ne retire pas owner');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','51000000-0000-0000-0000-000000000005',true);
select is(public.studio_my_role(current_setting('studio.test.a')::uuid), 'viewer'::text, 'Role viewer représenté');
select is((select count(*) from public.studio_workspace_members where workspace_id=current_setting('studio.test.a')::uuid), 4::bigint, 'viewer lit ses membres');
select throws_ok(format('select public.studio_rename_workspace(%L,%L)',current_setting('studio.test.a')::uuid,'pirate'), '42501', 'Accès refusé', 'viewer ne renomme pas');
select throws_ok(format('select public.studio_set_member(%L,%L,%L)',current_setting('studio.test.a')::uuid,'51000000-0000-0000-0000-000000000005','admin'), '42501', 'Accès refusé', 'viewer ne se promeut pas');
select throws_ok(format('select public.studio_set_member(%L,%L,NULL)',current_setting('studio.test.a')::uuid,'51000000-0000-0000-0000-000000000001'), '42501', 'Accès refusé', 'viewer ne retire pas owner');
select ok(not has_table_privilege('authenticated','public.studio_workspaces','INSERT'), 'DML direct INSERT studio_workspaces refusé');
select ok(not has_table_privilege('authenticated','public.studio_workspaces','UPDATE'), 'DML direct UPDATE studio_workspaces refusé');
select ok(not has_table_privilege('authenticated','public.studio_workspaces','DELETE'), 'DML direct DELETE studio_workspaces refusé');
select ok(not has_table_privilege('authenticated','public.studio_workspaces','TRUNCATE'), 'DML direct TRUNCATE studio_workspaces refusé');
select ok(not has_table_privilege('authenticated','public.studio_workspace_members','INSERT'), 'DML direct INSERT studio_workspace_members refusé');
select ok(not has_table_privilege('authenticated','public.studio_workspace_members','UPDATE'), 'DML direct UPDATE studio_workspace_members refusé');
select ok(not has_table_privilege('authenticated','public.studio_workspace_members','DELETE'), 'DML direct DELETE studio_workspace_members refusé');
select ok(not has_table_privilege('authenticated','public.studio_workspace_members','TRUNCATE'), 'DML direct TRUNCATE studio_workspace_members refusé');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','51000000-0000-0000-0000-000000000001',true);
select public.studio_set_member(current_setting('studio.test.a')::uuid,'51000000-0000-0000-0000-000000000002','viewer');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','51000000-0000-0000-0000-000000000002',true);
select is((select count(*) from public.studio_workspaces), 2::bigint, 'B appartient à plusieurs workspaces');
select is(public.studio_my_role(current_setting('studio.test.b')::uuid), 'owner'::text, 'B owner de son workspace uniquement');
select is(public.studio_my_role(current_setting('studio.test.a')::uuid), 'viewer'::text, 'B viewer de A');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','51000000-0000-0000-0000-000000000001',true);
select public.studio_set_member(current_setting('studio.test.a')::uuid,'51000000-0000-0000-0000-000000000002',NULL);
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','51000000-0000-0000-0000-000000000002',true);
select is((select count(*) from public.studio_workspaces where id=current_setting('studio.test.a')::uuid), 0::bigint, 'Révocation immédiate dans la même session');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','51000000-0000-0000-0000-000000000006',true);
select is((select count(*) from public.studio_workspaces), 0::bigint, 'Compte sans membership ne lit aucun workspace');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','51000000-0000-0000-0000-000000000001',true);
select set_config('studio.test.pro',public.studio_create_workspace('Professionnel','professional')::text,true);
select is((select count(*) from public.studio_workspaces), 2::bigint, 'Création professionnelle sans entreprise');
select public.studio_archive_workspace(current_setting('studio.test.pro')::uuid);
select is((select count(*) from public.studio_workspaces), 1::bigint, 'Workspace archivé invisible');
select is((select count(*) from public.studio_workspace_members where workspace_id=current_setting('studio.test.pro')::uuid), 0::bigint, 'Membres archivés invisibles');
reset role;
set constraints studio_owner_membership_fk immediate;
select throws_ok(format('delete from public.studio_workspace_members where workspace_id=%L and role=%L',current_setting('studio.test.a')::uuid,'owner'), '23503', 'update or delete on table "studio_workspace_members" violates foreign key constraint "studio_owner_membership_fk" on table "studio_workspaces"', 'Contrainte DB protège owner même en écriture privilégiée');
select ok((select bool_and(relrowsecurity) from pg_class where oid in ('public.studio_workspaces'::regclass,'public.studio_workspace_members'::regclass)), 'RLS activée sur les deux tables');
select is((select count(*) from public.utilisateurs_entreprises where utilisateur_id::text like '51000000-%'), 0::bigint, 'Aucune entreprise créée pour les utilisateurs Studio');
select ok(not has_function_privilege('anon','public.studio_create_workspace(text,text)','EXECUTE'), 'Anon ne peut exécuter studio_create_workspace(text,text)');
select ok(not has_function_privilege('anon','public.studio_rename_workspace(uuid,text)','EXECUTE'), 'Anon ne peut exécuter studio_rename_workspace(uuid,text)');
select ok(not has_function_privilege('anon','public.studio_archive_workspace(uuid)','EXECUTE'), 'Anon ne peut exécuter studio_archive_workspace(uuid)');
select ok(not has_function_privilege('anon','public.studio_set_member(uuid,uuid,text)','EXECUTE'), 'Anon ne peut exécuter studio_set_member(uuid,uuid,text)');
select ok(not has_function_privilege('anon','public.studio_my_role(uuid)','EXECUTE'), 'Anon ne peut exécuter studio_my_role(uuid)');
set local role authenticated;
select set_config('request.jwt.claim.sub','',true);
select throws_ok($$select public.studio_create_workspace('Anon','personal')$$, '42501', 'Authentification requise', 'Pas de création sans auth.uid');
reset role;
select * from finish();
rollback;
