import Link from "next/link";
import { notFound } from "next/navigation";
import { getContexteEntreprise } from "@/lib/entreprise";
import { createClient } from "@/lib/supabase/server";
import { permissionsUtilisateur } from "@/lib/permissions";
import { ajouterCategorieNoteFraisAction, changerCategorieNoteFraisAction, modifierPolitiqueNotesFraisAction } from "@/app/actions/notes-frais-admin";

const champ="w-full rounded-md border px-3 py-2 text-sm dark:bg-neutral-900";

export default async function ParametresNotesFraisPage({searchParams}:{searchParams:Promise<{error?:string;succes?:string}>}) {
  const message=await searchParams; const ctx=await getContexteEntreprise(); const supabase=await createClient(); const permissions=await permissionsUtilisateur(ctx);
  if(!permissions?.includes("administrer_archivage_notes_frais")) notFound();
  const [{data:politique},{data:categories}]=await Promise.all([
    supabase.from("politiques_conservation_notes_frais").select("*").eq("entreprise_id",ctx.entrepriseId).single(),
    supabase.from("categories_notes_frais").select("id,code,libelle,actif,ordre").eq("entreprise_id",ctx.entrepriseId).order("ordre"),
  ]);
  return <main className="p-8"><div className="mx-auto max-w-4xl space-y-6"><div><Link href="/notes-frais" className="text-sm text-neutral-500">← Notes de frais</Link><h1 className="mt-2 text-xl font-semibold">Archivage des justificatifs</h1><p className="text-sm text-neutral-500">Réglages administrateur de {ctx.entrepriseNom}.</p></div>
    {message.error&&<p className="rounded bg-red-50 p-3 text-sm text-red-700">{message.error}</p>}{message.succes&&<p className="rounded bg-green-50 p-3 text-sm text-green-700">{message.succes}</p>}
    <form action={modifierPolitiqueNotesFraisAction} className="space-y-4 rounded-lg border p-4"><h2 className="font-semibold">Politique de conservation</h2><label className="block text-sm">Niveau d’archivage<select name="mode_archivage" defaultValue={politique?.mode_archivage??"simple_document_storage"} className={`${champ} mt-1`}><option value="simple_document_storage">Justificatif numérique simple</option><option value="reinforced_archive">Archivage numérique renforcé — non qualifié</option></select></label><p className="rounded bg-amber-50 p-3 text-xs text-amber-900">Le mode renforcé ajoute copie figée, empreintes et traçabilité. Il ne doit pas être présenté comme conforme fiscalement ou à valeur probante sans validation juridique, comptable et technique.</p><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Conservation (années)<input name="duree_conservation_annees" type="number" min="1" max="50" defaultValue={politique?.duree_conservation_annees??10} className={`${champ} mt-1`}/></label><label className="text-sm">Taille maximale par fichier (Mo)<input name="taille_max_mo" type="number" min="1" max="50" defaultValue={Math.round((politique?.taille_max_octets??15728640)/1024/1024)} className={`${champ} mt-1`}/></label></div><label className="flex gap-2 text-sm"><input name="analyse_antivirus_obligatoire" type="checkbox" defaultChecked={politique?.analyse_antivirus_obligatoire}/><span>Exiger une analyse antivirus externe avant import</span></label>{politique?.analyse_antivirus_obligatoire&&<p className="text-xs text-red-700">Aucun prestataire antivirus n’est configuré : les imports resteront volontairement bloqués jusqu’à sa connexion.</p>}<p className="text-xs text-neutral-500">La suppression automatique reste désactivée. Les échéances sont présentées à un administrateur et toute suppression exige une validation explicite.</p><button className="rounded-md bg-[#0d1b2a] px-4 py-2 text-sm font-semibold text-white">Enregistrer la politique</button></form>
    <section className="space-y-3 rounded-lg border p-4"><h2 className="font-semibold">Catégories de dépenses</h2><form action={ajouterCategorieNoteFraisAction} className="grid gap-2 sm:grid-cols-[1fr_1fr_100px_auto]"><input name="libelle" required placeholder="Nouvelle catégorie" className={champ}/><input name="code" placeholder="Code automatique" className={champ}/><input name="ordre" type="number" defaultValue="500" className={champ}/><button className="rounded-md border px-3 py-2 text-sm">Ajouter</button></form><div className="divide-y rounded border">{(categories??[]).map(c=><div key={c.id} className="flex items-center justify-between gap-3 p-3 text-sm"><div><strong>{c.libelle}</strong><p className="font-mono text-xs text-neutral-400">{c.code}</p></div><form action={changerCategorieNoteFraisAction.bind(null,c.id,!c.actif)}><button className={`rounded px-3 py-1 text-xs ${c.actif?"bg-green-100 text-green-800":"bg-neutral-100 text-neutral-600"}`}>{c.actif?"Active · désactiver":"Inactive · réactiver"}</button></form></div>)}</div></section>
  </div></main>;
}
