"""Modes opératoires transversaux du manuel.

Les chapitres de ``modules.py`` expliquent chaque écran. Ce fichier explique
les enchaînements réels entre plusieurs écrans : qui commence, quels contrôles
effectuer, quelles données sont synchronisées et comment terminer proprement.
"""

PROCEDURES = [
    {
        "titre": "Configurer une entreprise avant la première utilisation",
        "objectif": "Mettre l’entreprise en état de produire des documents fiables, d’inviter les équipes et de calculer correctement les coûts.",
        "roles": "Gérant ou administrateur entreprise.",
        "prerequis": [
            "Disposer des informations légales : raison sociale, SIRET, TVA, adresse, assurances et coordonnées de contact.",
            "Disposer du logo dans une image nette et des coordonnées bancaires destinées aux documents clients.",
            "Avoir défini les postes réels de l’entreprise et le responsable de chaque validation.",
        ],
        "etapes": [
            ("Compléter l’identité de l’entreprise", "Dans Paramètres, renseignez le nom légal, le nom commercial, le SIRET, la TVA, l’adresse, le téléphone et l’e-mail. Relisez ces informations : elles sont reprises sur les documents."),
            ("Importer le logo", "Utilisez une image nette, cadrée et lisible sur fond clair. Contrôlez immédiatement le résultat dans l’aperçu d’un devis."),
            ("Choisir la numérotation", "Définissez les préfixes et la logique interne avant d’émettre les premiers documents. Une facture émise ne doit pas être renumérotée."),
            ("Régler les documents", "Choisissez le modèle, la police, la couleur, la position du logo et les mentions. Générez un PDF d’essai avant toute utilisation réelle."),
            ("Configurer le temps de travail", "Indiquez les heures normales de chaque jour. Elles servent à comparer planning, pointages et heures supplémentaires."),
            ("Créer les postes", "Partez des rôles prédéfinis, puis retirez ou ajoutez les droits nécessaires. Séparez toujours consulter, créer, modifier, valider et payer."),
            ("Créer les fiches employés", "Créez d’abord la fiche RH, puis le compte de connexion seulement si la personne doit utiliser l’application."),
            ("Configurer les validations", "Désignez les responsables du pointage, des congés, des notes de frais, des achats, de la paie et des paiements."),
            ("Tester avec un compte limité", "Connectez-vous avec un profil ouvrier ou chef d’équipe et vérifiez que les prix, marges et modules interdits sont réellement absents."),
            ("Sauvegarder le contrôle initial", "Conservez un devis PDF d’essai, une facture brouillon et la matrice des droits comme preuve de la configuration de départ."),
        ],
        "controles": [
            ["Documents", "Logo, SIRET, TVA, adresse, assurances, IBAN et mentions sont exacts."],
            ["Droits", "Un utilisateur limité ne voit ni prix, ni marges, ni données d’un autre salarié."],
            ["Horaires", "Le total hebdomadaire correspond au contrat collectif de l’entreprise."],
            ["Notifications", "Chaque validation a au moins un responsable identifié."],
        ],
        "synchronisations": [
            ["Paramètres", "Alimente les devis, factures, commandes et impressions."],
            ["Postes", "Pilotent le menu, les actions serveur et le périmètre visible par l’IA."],
            ["Horaires", "Servent au contrôle du planning, du pointage et de la préparation de paie."],
        ],
        "exceptions": [
            ["Le logo paraît minuscule", "Recadrez l’image autour du logo puis réimportez-la."],
            ["Un salarié voit trop d’informations", "Retirez immédiatement le droit concerné et contrôlez le poste, pas seulement le menu."],
            ["Un document réel a déjà été émis", "Ne changez pas rétroactivement son numéro ; appliquez les nouveaux réglages aux documents suivants."],
        ],
    },
    {
        "titre": "Créer un employé, lui donner accès puis gérer son départ",
        "objectif": "Distinguer correctement la fiche employé, le compte de connexion, le poste, les droits et les appareils autorisés.",
        "roles": "Administrateur, RH ou gérant selon les droits accordés.",
        "prerequis": [
            "Connaître l’identité, le poste, la date d’entrée, les coordonnées et l’horaire contractuel.",
            "Avoir préparé le poste et ses droits dans Paramètres > Accès et rôles.",
        ],
        "etapes": [
            ("Créer la fiche employé", "Renseignez identité, fonction, date d’entrée, coût horaire chargé si autorisé, photo et informations utiles. Le numéro interne est généré selon le préfixe choisi."),
            ("Ajouter les documents professionnels", "Importez Carte BTP, attestation provisoire, CACES, SST, habilitations et dates de validité. La copie numérique de Carte BTP ne remplace jamais l’original officiel."),
            ("Choisir le poste", "Affectez le rôle qui correspond au travail réel. Ne donnez pas un rôle de direction uniquement pour contourner un écran bloqué."),
            ("Créer ou inviter le compte", "Utilisez l’e-mail professionnel de la personne. L’invitation lie le futur compte à la fiche déjà préparée."),
            ("Contrôler l’état d’activation", "Depuis la liste des employés, vérifiez invitation envoyée, compte créé, dernière connexion, appareils connus et statut actif ou en pause."),
            ("Faire tester le premier accès", "Le salarié vérifie son nom, son planning, son pointage, ses propres documents et les modules autorisés."),
            ("Ajuster individuellement si nécessaire", "Le poste fournit la base ; les autorisations particulières doivent rester exceptionnelles, explicables et révisables."),
            ("Révoquer un appareil", "Depuis la fiche, retirez un téléphone ou ordinateur ancien. Deux appareils actifs sont inclus ; les dépassements peuvent être facturés."),
            ("Suspendre temporairement", "Mettez le compte en pause sans supprimer la fiche lorsque l’accès doit être interrompu mais que l’historique doit rester."),
            ("Clôturer un départ", "Renseignez la date de sortie uniquement au départ réel, terminez les affectations, récupérez matériel et véhicule, puis désactivez le compte."),
        ],
        "controles": [
            ["Identité", "Le compte est lié à la bonne fiche et ne peut agir qu’en son nom pour les actions personnelles."],
            ["Périmètre", "Le salarié ne voit que ses pointages et les chantiers autorisés ou assignés."],
            ["Confidentialité", "Coût horaire, RIB, paie et documents RH restent limités aux droits appropriés."],
            ["Départ", "Compte désactivé, appareils révoqués, matériel restitué et historique conservé."],
        ],
        "synchronisations": [
            ["Planning", "La fiche active devient planifiable."],
            ["Pointage", "Le compte pointe uniquement pour la fiche liée."],
            ["Flotte / Outillage", "Les affectations apparaissent sur la fiche employé."],
            ["Abonnement", "Les comptes actifs ou en pause sont comptabilisés selon l’offre."],
        ],
        "exceptions": [
            ["Invitation non reçue", "Vérifiez l’adresse, l’état de l’invitation et renvoyez-la sans créer une seconde fiche."],
            ["Mauvais employé après connexion", "Désactivez le compte et corrigez la liaison avant toute nouvelle action."],
            ["Ancien salarié encore visible", "La fiche reste dans l’historique ; seul le compte et le statut actif doivent être coupés."],
        ],
    },
    {
        "titre": "Du premier contact client au chantier prêt à démarrer",
        "objectif": "Créer une seule fois le client, le chantier et le devis, puis conserver leurs liens pendant toute l’affaire.",
        "roles": "Administration, commercial, conducteur de travaux ou gérant.",
        "prerequis": [
            "Disposer au minimum du nom du client et d’un moyen de contact.",
            "Connaître l’adresse du chantier ou pouvoir la compléter ultérieurement.",
        ],
        "etapes": [
            ("Rechercher avant de créer", "Tapez le nom, l’e-mail, le téléphone ou la référence afin d’éviter un doublon."),
            ("Créer le client", "Renseignez type de client, identité ou raison sociale, contact, adresse de facturation et conditions de paiement."),
            ("Créer le chantier", "Depuis la fiche client ou depuis le nouveau devis, saisissez le nom, l’adresse, le responsable, les dates prévisionnelles et le budget éventuel."),
            ("Créer le devis lié", "Choisissez le client puis le chantier. Si l’un manque, créez-le sans quitter le parcours."),
            ("Ajouter les prestations", "Utilisez la bibliothèque, les ouvrages ou le métré. Vérifiez quantité, unité, prix HT, remise et taux de TVA ligne par ligne."),
            ("Contrôler le document", "Vérifiez identité, adresse, validité, total HT, ventilation TVA, TTC, assurance et conditions avant envoi."),
            ("Envoyer et tracer", "Téléchargez le PDF ou utilisez le canal configuré. Notez l’envoi et la prochaine relance dans le CRM si nécessaire."),
            ("Enregistrer la réponse", "Passez le devis à Accepté, Refusé ou Annulé uniquement lorsque l’événement réel a eu lieu."),
            ("Préparer le chantier", "Après acceptation, contrôlez les tâches créées depuis les lignes du devis, ajoutez les plans et affectez l’équipe."),
            ("Vérifier la confidentialité terrain", "Ouvrez Mes travaux avec un compte terrain : les tâches doivent être visibles sans prix de vente."),
        ],
        "controles": [
            ["Doublons", "Un seul client et un seul chantier par affaire réelle."],
            ["Liaison", "Le devis indique bien le chantier et la fiche chantier renvoie au devis."],
            ["TVA", "Le taux est justifié pour chaque prestation et la ventilation du PDF est correcte."],
            ["Terrain", "Les tâches sont créées à l’acceptation et aucun prix n’est exposé aux profils non autorisés."],
        ],
        "synchronisations": [
            ["Devis accepté", "Crée les tâches terrain et rend possible la facturation."],
            ["Chantier", "Centralise plans, équipe, temps, dépenses, devis et factures."],
            ["CRM", "Conserve appels, e-mails et relances liés au client."],
        ],
        "exceptions": [
            ["Client déjà existant sous un autre nom", "Fusionnez ou utilisez la fiche correcte ; ne poursuivez pas avec deux historiques."],
            ["Devis accepté sans tâches", "Vérifiez la liaison au chantier et les lignes du devis, puis utilisez l’action de synchronisation prévue."],
            ["Chantier confidentiel", "Limitez sa visibilité aux personnes assignées ou explicitement autorisées."],
        ],
    },
    {
        "titre": "Facturer un chantier : acompte, situation, solde et avoir",
        "objectif": "Choisir le bon document, préserver le cumul déjà facturé et maintenir une comptabilité cohérente.",
        "roles": "Administration, comptable ou gérant avec gestion de la facturation.",
        "prerequis": [
            "Le devis doit être accepté ; une situation exige également un chantier lié.",
            "Les coordonnées client, mentions légales et règles de TVA doivent être contrôlées.",
        ],
        "etapes": [
            ("Choisir le besoin réel", "Utilisez l’acompte avant démarrage, la situation pour l’avancement, le solde à la fin et l’avoir pour corriger une facture émise."),
            ("Sélectionner le devis accepté", "La liste ne montre que les devis compatibles. Si elle est vide, contrôlez statut et liaison chantier."),
            ("Calculer l’acompte", "Saisissez le pourcentage ou le montant convenu. Vérifiez qu’il correspond aux conditions du devis."),
            ("Calculer une situation", "Saisissez l’avancement cumulé total depuis le début. Le logiciel déduit les situations antérieures afin d’isoler la période."),
            ("Appliquer la retenue", "Utilisez une retenue de garantie uniquement si le marché la prévoit et contrôlez son taux."),
            ("Prévisualiser", "Comparez marché, déjà facturé, nouvelle période, retenues, TVA et net à payer."),
            ("Créer le brouillon", "Relisez toutes les lignes et les références. Tant que le document est brouillon, corrigez avant émission."),
            ("Émettre et envoyer", "L’émission attribue le numéro définitif. Envoyez ensuite le PDF et conservez la trace."),
            ("Enregistrer les règlements", "Saisissez uniquement les encaissements réellement constatés, avec date, moyen et référence."),
            ("Émettre un avoir si nécessaire", "Ne supprimez pas une facture émise. Créez l’avoir lié puis, si besoin, une nouvelle facture correcte."),
            ("Clôturer par le solde ou DGD", "Vérifiez que l’ensemble des acomptes, situations, avoirs et paiements reconstitue exactement le marché."),
        ],
        "controles": [
            ["Cumul", "Le montant cumulé n’excède pas le marché accepté, sauf avenant explicite."],
            ["Numérotation", "Aucun numéro de facture émise n’est supprimé ni réutilisé."],
            ["Règlements", "Le statut payé correspond à un encaissement bancaire réel."],
            ["DGD", "Toutes les situations, retenues, révisions et avoirs sont inclus avant clôture."],
        ],
        "synchronisations": [
            ["Chantier", "Le facturé et l’encaissé alimentent son avancement financier."],
            ["Trésorerie", "Les échéances deviennent des entrées prévues ; les règlements deviennent des entrées réalisées."],
            ["Export comptable", "Factures, avoirs et règlements sont repris sur la période."],
        ],
        "exceptions": [
            ["Liste vide", "Aucun devis accepté compatible ou chantier manquant pour la situation."],
            ["Erreur après émission", "Créez un avoir ; ne modifiez pas silencieusement l’original."],
            ["Paiement partiel", "Enregistrez le montant réel : le reste dû et le statut se recalculent."],
        ],
    },
    {
        "titre": "Cycle fournisseur complet : besoin, commande, réception, facture et règlement",
        "objectif": "Suivre chaque achat depuis la demande jusqu’au paiement sans perdre le lien avec le chantier, le stock et la comptabilité.",
        "roles": "Achats, conducteur de travaux, administration, comptable ou gérant selon les étapes.",
        "prerequis": [
            "Le fournisseur doit exister dans le carnet avec ses coordonnées et son délai de paiement.",
            "Les articles commandés doivent être liés au catalogue si la réception doit alimenter le stock.",
            "Le chantier doit être sélectionné si l’achat lui est imputable.",
        ],
        "etapes": [
            ("Créer ou vérifier le fournisseur", "Recherchez par nom ou SIRET. Complétez contact, numéro client, délai de paiement, portail et RIB si des virements seront préparés."),
            ("Créer la commande", "Choisissez fournisseur, chantier éventuel, date souhaitée et lignes. Une ligne précise référence, désignation, quantité, unité, prix HT et TVA."),
            ("Faire valider selon la procédure interne", "Avant envoi, contrôlez budget chantier, disponibilité stock et autorisation d’achat."),
            ("Envoyer au fournisseur", "Transmettez le bon de commande par le canal autorisé et passez le statut à Envoyée ou Confirmée selon le retour réel."),
            ("Préparer la réception", "Ouvrez la commande attendue ou démarrez une série de scans. Le logiciel peut proposer les commandes compatibles avec les articles scannés."),
            ("Scanner tous les articles reçus", "Scannez successivement les références. Regroupez les quantités identiques puis corrigez manuellement emballages, reliquats ou substitutions."),
            ("Valider les quantités", "Pour chaque ligne, comparez commandé, déjà reçu, reçu aujourd’hui et restant. Une livraison partielle conserve le reliquat."),
            ("Alimenter le stock", "Après validation, vérifiez les mouvements d’entrée et l’emplacement de dépôt. Un article non lié doit être rapproché avant clôture."),
            ("Saisir la facture fournisseur", "Renseignez numéro, date, échéance, HT, taux de TVA, TVA et TTC. Liez la commande et le même fournisseur."),
            ("Joindre l’original", "Importez le PDF ou la photo complète. Conservez l’original électronique reçu par e-mail."),
            ("Rapprocher les trois sources", "Comparez commande, réception et facture. Traitez les écarts de quantité, de prix ou de TVA avant validation."),
            ("Classer la dépense", "Rattachez-la au chantier concerné ou laissez-la en frais généraux. Ce choix modifie directement la marge."),
            ("Préparer le paiement", "Après validation, utilisez le RIB vérifié et créez un lot bancaire, ou enregistrez le règlement effectué hors application."),
            ("Confirmer le paiement", "Ne marquez payé qu’après confirmation de la banque. Le reste à payer et la trésorerie se mettent à jour."),
        ],
        "controles": [
            ["Fournisseur", "Commande et facture concernent exactement le même fournisseur."],
            ["Quantités", "Reçu du jour + reliquat = cohérence avec la commande."],
            ["Montants", "HT + TVA = TTC ; prix facturé comparé au prix commandé ou négocié."],
            ["Imputation", "Le bon chantier, véhicule, outil ou frais général est choisi."],
            ["Paiement", "RIB vérifié, facture validée, séparation préparation/validation et confirmation bancaire."],
        ],
        "synchronisations": [
            ["Réception", "Crée les mouvements d’entrée de stock."],
            ["Facture fournisseur", "Alimente dépenses, rentabilité, trésorerie et export comptable."],
            ["Chantier", "Reçoit les coûts des achats qui lui sont imputés."],
            ["Banque", "La facture validée devient une source possible de virement."],
        ],
        "exceptions": [
            ["Plusieurs commandes dans une livraison", "Laissez le système proposer toutes les commandes compatibles puis validez la ventilation ligne par ligne."],
            ["Article sans code connu", "Recherchez la référence ou créez le lien catalogue avant de valider définitivement la réception."],
            ["Écart de prix", "Conservez la facture telle que reçue, signalez l’écart et demandez l’avoir ou la correction au fournisseur."],
            ["Livraison refusée", "N’alimentez pas le stock ; consignez le motif et conservez la trace du litige."],
        ],
    },
    {
        "titre": "Importer et maintenir les tarifs négociés fournisseurs",
        "objectif": "Mettre à jour les prix d’achat sans stocker de mot de passe fournisseur ni prétendre à une synchronisation inexistante.",
        "roles": "Administrateur, achats ou gestionnaire de stock.",
        "prerequis": [
            "Obtenir le fichier officiel CSV, Excel ou FAB-DIS, ou un accès API/EDI/PunchOut fourni par le partenaire.",
            "Identifier le fournisseur et le numéro de compte client professionnel.",
        ],
        "etapes": [
            ("Créer le connecteur", "Choisissez le fournisseur, indiquez le numéro client non secret et sélectionnez le mode réellement disponible."),
            ("Télécharger le catalogue officiel", "Utilisez le portail fournisseur. Ne transformez pas un PDF en catalogue si un fichier structuré existe."),
            ("Préparer les colonnes", "Conservez au minimum référence, désignation, unité et prix d’achat. Ajoutez code-barres, marque, famille, TVA et conditionnement si disponibles."),
            ("Importer en aperçu", "Choisissez le fichier puis associez chaque colonne source au champ Liria correspondant."),
            ("Contrôler les exemples", "Vérifiez accents, décimales, devise, unité, taux de TVA et quelques références connues."),
            ("Choisir création ou mise à jour", "Une référence identique met à jour l’article prévu ; une nouvelle référence crée un nouvel article selon les options."),
            ("Valider l’import", "Lisez le compte rendu : créés, mis à jour, ignorés et erreurs. Ne relancez pas sans comprendre les erreurs."),
            ("Définir les prix de revente", "Appliquez votre coefficient ou votre prix de vente. Le prix fournisseur n’est pas automatiquement un prix client."),
            ("Conserver la source", "Archivez le fichier, sa date et son fournisseur pour justifier l’origine du tarif."),
            ("Planifier la prochaine mise à jour", "La fréquence dépend du fournisseur. Une API officielle peut automatiser, un import manuel doit être daté."),
        ],
        "controles": [
            ["Encodage", "Les accents sont corrects ; CSV en UTF-8 ou fichier Excel natif."],
            ["Décimales", "Virgule et point ne multiplient pas les prix par 100."],
            ["Unité", "Le prix correspond à l’unité ou au conditionnement réellement vendu."],
            ["Revente", "La marge et la TVA client sont contrôlées avant utilisation dans un devis."],
        ],
        "synchronisations": [
            ["Stock", "Met à jour références, descriptions, codes-barres et prix d’achat."],
            ["Prestations / Devis", "Les fournitures peuvent reprendre les prix à jour selon les règles de vente."],
            ["Commandes", "Les lignes utilisent les références et prix négociés disponibles."],
        ],
        "exceptions": [
            ["PDF uniquement", "Importez le document comme pièce de référence ou utilisez une extraction contrôlée ; validez chaque donnée avant usage."],
            ["Pas d’API officielle", "Restez en portail ou import. Ne fournissez jamais votre mot de passe à Liria."],
            ["Référence remplacée", "Créez la correspondance avec la nouvelle référence sans effacer l’historique des anciennes commandes."],
        ],
    },
    {
        "titre": "Réceptionner, sortir et inventorier le stock",
        "objectif": "Garantir que le stock informatique correspond au dépôt et expliquer toute variation en quantité et en valeur.",
        "roles": "Compte dépôt, magasinier, gestionnaire de stock ou administrateur.",
        "prerequis": [
            "Les articles actifs possèdent une référence ou un code-barres lisible.",
            "Le compte dépôt est verrouillé sur la borne ; chaque salarié s’identifie pour ses propres mouvements.",
        ],
        "etapes": [
            ("Identifier l’opérateur", "Sur la borne, utilisez l’identifiant et le mot de passe stock personnel ou le QR salarié. Le mouvement doit rester attribué à la bonne personne."),
            ("Choisir entrée ou sortie", "Réception fournisseur, retour chantier, ajustement, sortie chantier, véhicule ou outillage."),
            ("Scanner en série", "Scannez les articles les uns après les autres. Le système classe le code selon son préfixe et regroupe les références identiques."),
            ("Corriger les quantités", "Après la série de scans, modifiez les quantités si un carton contient plusieurs unités ou si une lecture a été faite deux fois."),
            ("Choisir la destination", "Pour une sortie, scannez ou sélectionnez le chantier, le véhicule ou l’outil. Vérifiez le libellé affiché avant validation."),
            ("Rapprocher une réception", "Si des commandes ouvertes correspondent, contrôlez les propositions et répartissez la réception sur une ou plusieurs commandes."),
            ("Valider le lot", "Relisez article, quantité, sens, destination, opérateur et commentaire. Une validation crée les mouvements."),
            ("Contrôler le stock après mouvement", "Vérifiez quantité disponible, emplacement et alerte de réapprovisionnement."),
            ("Créer un inventaire", "Sélectionnez le dépôt ou les emplacements et les familles à compter. Figez les quantités théoriques du moment."),
            ("Compter physiquement", "Saisissez ou scannez ce qui est réellement présent sans vous laisser influencer par la théorie."),
            ("Analyser les écarts", "Le rapport indique quantité théorique, comptée, différence, prix d’achat et valeur de l’écart."),
            ("Justifier et clôturer", "Expliquez casse, perte, erreur de saisie, retour non enregistré ou article déplacé, puis faites valider les corrections."),
            ("Exporter pour la clôture", "Transmettez la valeur finale et les écarts à l’expert-comptable pour l’inventaire annuel."),
        ],
        "controles": [
            ["Identité", "Aucun salarié n’effectue un mouvement au nom d’un autre."],
            ["Destination", "Une sortie chantier, véhicule ou outillage est imputée au bon objet."],
            ["Stock négatif", "Toute quantité insuffisante est bloquée ou explicitement régularisée par un gestionnaire."],
            ["Valeur", "Le calcul d’inventaire utilise le prix d’achat enregistré et la méthode validée avec le comptable."],
        ],
        "synchronisations": [
            ["Commandes", "La réception met à jour les quantités reçues et le reliquat."],
            ["Chantiers", "Les sorties chantier alimentent les consommations et la rentabilité."],
            ["Flotte / Outillage", "Les sorties ciblées restent rattachées à l’équipement."],
            ["Comptabilité", "L’inventaire clôturé fournit quantités, valeurs et écarts."],
        ],
        "exceptions": [
            ["Code inconnu", "Recherchez la référence puis créez ou corrigez le code avant validation."],
            ["Mauvais objet détecté", "Annulez la lecture et rescanner ; ne forcez pas un QR employé dans le champ article."],
            ["Inventaire déjà clôturé", "Ne modifiez pas l’original. Créez un inventaire de correction et documentez l’écart."],
        ],
    },
    {
        "titre": "Planifier, pointer et valider les heures d’un chantier",
        "objectif": "Relier le planning prévisionnel au pointage GPS réel, puis à la rentabilité et à la paie.",
        "roles": "Conducteur ou chef pour planifier et valider ; chaque salarié pour son propre pointage.",
        "prerequis": [
            "Le chantier est actif et l’employé possède une fiche active.",
            "Les horaires normaux de l’entreprise sont configurés.",
            "Le téléphone autorise la localisation au moment du pointage.",
        ],
        "etapes": [
            ("Affecter l’équipe au chantier", "Depuis le chantier, ajoutez ouvriers, chefs et conducteur autorisés à voir le dossier."),
            ("Créer le planning", "Dans la semaine concernée, affectez chaque personne à une date, un lieu et un nombre d’heures prévues."),
            ("Utiliser les lieux internes", "Pour bureau, dépôt, formation ou visite médicale, choisissez l’activité correspondante sans créer de faux chantier."),
            ("Consulter le planning terrain", "Le salarié voit son programme du jour et retrouve le chantier prévu en priorité au pointage."),
            ("Pointer l’arrivée", "Le salarié sélectionne le lieu proposé, autorise le GPS et valide. L’heure et la date sont celles du serveur."),
            ("Pointer le départ", "À la fin, il valide le départ avec position. Il ne saisit jamais un pointage au nom d’un collègue."),
            ("Traiter un oubli", "Le salarié signale l’oubli ; le responsable corrige ou complète avec justification sans masquer l’anomalie."),
            ("Contrôler les alertes", "Examinez absence de départ, durée inhabituelle, position manquante, journée supérieure aux seuils ou écart avec le planning."),
            ("Valider ou rejeter", "La personne autorisée contrôle chantier, date, durée, position et commentaire. Un refus ou une correction doit être expliqué."),
            ("Comparer à l’horaire normal", "Analysez les heures en plus ou en moins par jour et sur la semaine avant transmission à la paie."),
            ("Contrôler le chantier", "La fiche doit afficher personnes ayant travaillé, total validé, détail par jour et heures encore en attente."),
        ],
        "controles": [
            ["Nom propre", "Le compte connecté et l’employé pointé sont identiques."],
            ["GPS", "Position présente pour arrivée et départ lorsque le pointage GPS est exigé."],
            ["Durée", "Les journées longues sont signalées et justifiées avant validation."],
            ["Périmètre", "Un salarié ne voit que ses heures ; seuls les gestionnaires autorisés voient l’équipe."],
        ],
        "synchronisations": [
            ["Planning", "Propose le lieu prioritaire et les heures prévues."],
            ["Chantier", "Reçoit les heures validées par salarié et par jour."],
            ["Rentabilité", "Valorise les heures validées avec le coût horaire autorisé."],
            ["Paie", "Reprend uniquement les heures contrôlées de la période."],
        ],
        "exceptions": [
            ["GPS refusé", "Autorisez la localisation dans les réglages du navigateur puis recommencez sur place."],
            ["Travail non prévu", "Choisissez un chantier actif autorisé ou une activité interne, puis ajoutez un commentaire."],
            ["Durée supérieure à 12 ou 15 heures", "Ne validez pas automatiquement : vérifiez oubli de départ, travail réel et règles sociales."],
        ],
    },
    {
        "titre": "Gérer une note de frais de la photo au remboursement",
        "objectif": "Conserver le justificatif original, contrôler la dépense et la rembourser sans exposer les notes des autres salariés.",
        "roles": "Salarié déclarant, responsable valideur, comptable et administrateur.",
        "prerequis": [
            "Le salarié utilise son propre compte.",
            "La catégorie, le moyen de paiement et le chantier éventuel sont connus.",
        ],
        "etapes": [
            ("Photographier ou importer", "Cadrez le document entier, net et en couleur. Pour une facture électronique, importez le fichier original plutôt qu’une capture."),
            ("Choisir le type de justificatif", "Facture, ticket, reçu de paiement ou autre. Un simple reçu de carte ne décrit pas suffisamment la dépense."),
            ("Renseigner les montants", "Saisissez deux valeurs parmi HT, TVA, TTC et taux ; contrôlez le calcul automatique de la troisième."),
            ("Choisir l’imputation", "Sélectionnez un chantier, Dépôt, Bureau ou Sans chantier selon la réalité. Sans chantier, la charge reste générale."),
            ("Ajouter le commentaire", "Expliquez le motif, les personnes concernées pour un repas, ou toute information nécessaire au contrôle."),
            ("Soumettre", "La demande part au responsable. Le salarié ne peut pas se valider lui-même ni changer le statut de contrôle."),
            ("Contrôler par salarié", "Le responsable consulte le regroupement, ouvre le justificatif, vérifie date, fournisseur, montants, TVA, doublon et imputation."),
            ("Demander une correction", "Expliquez précisément le champ ou la pièce à corriger. Le salarié reçoit une notification et peut resoumettre."),
            ("Valider ou refuser", "Une validation rend la dépense disponible au comptable ; un refus exige un motif."),
            ("Exporter ou préparer le remboursement", "Le comptable ajoute sa référence, inclut la pièce dans l’export ou prépare un lot bancaire vers le RIB vérifié."),
            ("Confirmer le remboursement", "Marquez remboursée seulement après confirmation bancaire. L’historique reste accessible depuis la fiche employé."),
            ("Conserver selon la politique", "En stockage simple, conservez le papier jusqu’à confirmation de l’entreprise. Ne promettez pas une valeur probante non validée."),
        ],
        "controles": [
            ["Original", "Fichier original privé, lisible, complet et non remplacé par une version améliorée."],
            ["Calcul", "HT + TVA = TTC et taux cohérent avec la nature de la dépense."],
            ["Doublon", "Empreinte identique ou même fournisseur/date/montant signalé avant validation."],
            ["Confidentialité", "Le salarié ne consulte que ses dépenses ; les gestionnaires voient leur périmètre."],
        ],
        "synchronisations": [
            ["Chantier", "La note imputée contribue au coût et à la rentabilité."],
            ["Employé", "L’historique personnel conserve demandes et remboursements."],
            ["Exports", "Le justificatif original, le manifeste et les empreintes peuvent être transmis au comptable."],
            ["Banque", "Une note validée peut devenir une source de remboursement."],
        ],
        "exceptions": [
            ["Document illisible", "Demandez une nouvelle photo avant validation et conservez la trace de la correction."],
            ["Reçu CB seul", "Ajoutez la facture ou le ticket qui décrit la dépense."],
            ["Dépense personnelle", "Refusez avec motif ; ne la classez ni sur un chantier ni en frais généraux."],
        ],
    },
    {
        "titre": "Préparer et clôturer une période de paie",
        "objectif": "Produire un dossier mensuel contrôlé pour l’expert-comptable, distribuer les bulletins et préparer les salaires sans se substituer au logiciel légal de paie.",
        "roles": "RH, gestionnaire de paie, comptable ou gérant selon les droits confidentiels.",
        "prerequis": [
            "Profils salariés à jour : contrat, horaire, date d’entrée ou de sortie, coût autorisé et RIB vérifié.",
            "Pointages, congés, absences, grands déplacements et remboursements de la période saisis.",
            "Responsables de contrôle et d’export identifiés.",
        ],
        "etapes": [
            ("Ouvrir la période", "Créez le mois avec ses dates exactes. Vérifiez qu’il ne chevauche pas une période déjà verrouillée."),
            ("Contrôler les salariés inclus", "Vérifiez actifs, entrants, sortants et personnes suspendues. Une date de sortie ne doit être renseignée qu’en cas de départ réel."),
            ("Importer les heures validées", "Comparez temps normal, heures supplémentaires, absences et écarts. Les pointages non validés restent hors du calcul."),
            ("Importer les congés et absences", "Contrôlez type, dates, validation et éventuel justificatif."),
            ("Ajouter les variables", "Primes, indemnités, paniers, trajets, grands déplacements, acomptes ou retenues doivent avoir une source et une justification."),
            ("Contrôler les notes de frais", "Séparez remboursement de frais et élément de salaire. Une note validée ne devient pas automatiquement une prime."),
            ("Examiner les anomalies", "Traitez salarié sans profil, heure manquante, journée longue, doublon, contrat incohérent ou variable sans justificatif."),
            ("Faire un second contrôle", "Une autre personne relit les écarts, totaux et changements sensibles. Chaque correction conserve son auteur et son motif."),
            ("Verrouiller la préparation", "Après validation interne, empêchez les modifications silencieuses. Toute correction ultérieure doit être tracée."),
            ("Exporter au cabinet", "Téléchargez le fichier et les pièces attendues. Notez la date, la version et le destinataire."),
            ("Recevoir le retour", "Importez les bulletins officiels reçus du cabinet et rapprochez chacun du bon salarié et de la bonne période."),
            ("Contrôler les bulletins", "Comparez identité, période, heures, absences, variables, net à payer et RIB sans recalculer vous-même les cotisations légales."),
            ("Distribuer individuellement", "Le bulletin privé est visible uniquement au salarié concerné et aux personnes ayant le droit confidentiel."),
            ("Préparer le lot de salaires", "À partir des bulletins contrôlés, créez les ordres de virement vers les RIB vérifiés."),
            ("Valider et transmettre", "Appliquez la séparation des rôles puis l’authentification bancaire forte du prestataire."),
            ("Confirmer et clôturer", "Après retour bancaire, rapprochez les salaires confirmés et archivez la période, l’export et les contrôles."),
        ],
        "controles": [
            ["Population", "Tous les salariés attendus et uniquement eux sont présents."],
            ["Temps", "Heures validées, congés et absences concordent avec le planning et les justificatifs."],
            ["Variables", "Chaque prime, indemnité ou retenue a une origine et un valideur."],
            ["Confidentialité", "Aucun salarié ne peut voir le bulletin ou le RIB d’un autre."],
            ["Paiement", "Le net payé vient du bulletin officiel retourné, pas d’une estimation préparatoire."],
        ],
        "synchronisations": [
            ["Pointage / Congés", "Alimentent les variables après validation."],
            ["Grands déplacements", "Ajoutent les éléments contrôlés selon la politique de l’entreprise."],
            ["Cabinet de paie", "Reçoit l’export et renvoie les bulletins officiels."],
            ["Banque", "Transforme les bulletins contrôlés en sources de virements."],
        ],
        "exceptions": [
            ["Correction après verrouillage", "Créez une nouvelle version ou déverrouillez exceptionnellement avec motif et journal d’audit."],
            ["Bulletin pour le mauvais salarié", "Bloquez immédiatement la distribution, corrigez le rattachement et journalisez l’incident."],
            ["Virement rejeté", "Ne marquez pas le salaire payé ; corrigez le RIB ou la cause puis créez une nouvelle transmission."],
        ],
    },
    {
        "titre": "Enregistrer et utiliser les RIB en sécurité",
        "objectif": "Centraliser les coordonnées bancaires sans exposer les IBAN et empêcher un paiement vers un bénéficiaire non vérifié.",
        "roles": "Personne disposant de gerer_coordonnees_bancaires ; validation et exécution selon droits séparés.",
        "prerequis": [
            "La fiche employé, fournisseur, client ou sous-traitant existe.",
            "Le document bancaire provient d’une source contrôlée.",
        ],
        "etapes": [
            ("Ouvrir la fiche du bénéficiaire", "Utilisez la section Coordonnées bancaires de la fiche correspondante, ou le coffre Banque & paie."),
            ("Saisir l’IBAN et le BIC", "Recopiez depuis le RIB original. Le nom du titulaire doit correspondre à la personne ou société."),
            ("Enregistrer de façon chiffrée", "Après enregistrement, l’interface ne doit afficher que les derniers caractères nécessaires à l’identification."),
            ("Faire vérifier", "Une seconde personne compare le RIB enregistré à l’original et marque la coordonnée vérifiée."),
            ("Protéger les changements", "Tout nouvel IBAN annule la vérification précédente et exige un nouveau contrôle."),
            ("Choisir le RIB au paiement", "Seuls les bénéficiaires et RIB vérifiés doivent être proposés dans un lot."),
            ("Contrôler avant envoi", "Vérifiez titulaire, derniers caractères, montant, motif et source du paiement."),
            ("Conserver la confirmation", "Le retour du prestataire ou la référence bancaire clôt le paiement."),
        ],
        "controles": [
            ["Titulaire", "Nom du RIB cohérent avec la fiche et le justificatif."],
            ["Modification", "Toute modification déclenche une nouvelle vérification."],
            ["Affichage", "Aucun IBAN complet dans les listes, exports courants ou journaux techniques."],
            ["Droits", "La consultation d’un RIB complet reste exceptionnelle et journalisée."],
        ],
        "synchronisations": [
            ["Employés", "RIB utilisé pour salaires et remboursements."],
            ["Fournisseurs / Sous-traitants", "RIB utilisé pour les factures validées."],
            ["Clients", "RIB éventuel conservé uniquement pour les besoins autorisés, jamais pour débiter sans mandat."],
        ],
        "exceptions": [
            ["Changement communiqué par e-mail", "Confirmez par un canal indépendant avant de modifier le RIB : risque de fraude au faux fournisseur."],
            ["RIB non vérifié", "Le paiement reste préparatoire et ne doit pas être transmis."],
            ["Erreur après transmission", "Contactez immédiatement la banque ; Liria ne peut pas annuler seule un virement exécuté."],
        ],
    },
    {
        "titre": "Préparer, valider et suivre un lot de paiements",
        "objectif": "Séparer les paiements clients entrants des règlements fournisseurs, salaires et remboursements sortants.",
        "roles": "Préparateur, valideur et exécuteur distincts selon l’organisation.",
        "prerequis": [
            "Les sources sont validées : facture fournisseur, bulletin de salaire ou note de frais.",
            "Les bénéficiaires possèdent un RIB vérifié.",
            "Le prestataire bancaire réglementé et le consentement sont configurés pour un envoi réel.",
        ],
        "etapes": [
            ("Choisir le type de lot", "Fournisseurs, sous-traitants, salaires ou remboursements. Ne mélangez pas encaissements clients et sorties."),
            ("Sélectionner les sources", "Filtrez par échéance, bénéficiaire et statut. Chaque source doit afficher montant restant et référence."),
            ("Créer le lot", "Définissez date souhaitée, compte débité et libellés. Le lot préparé ne déclenche encore aucun débit."),
            ("Contrôler les doublons", "Vérifiez que la source n’est pas déjà incluse dans un autre lot actif ou confirmée payée."),
            ("Faire valider", "Le valideur contrôle total, détail, bénéficiaires, RIB masqués et pièces sources."),
            ("Transmettre", "L’exécuteur ouvre le prestataire bancaire et réalise l’authentification forte."),
            ("Suivre le statut", "Préparé, validé, transmis, en traitement, confirmé, partiellement rejeté ou rejeté."),
            ("Traiter les rejets", "Identifiez les ordres rejetés, corrigez la cause et préparez un nouveau lot uniquement pour eux."),
            ("Rapprocher", "Une confirmation met à jour la source : réglée, remboursée ou salaire payé. Un simple envoi ne suffit pas."),
            ("Exporter la preuve", "Conservez référence, date, montant, statut et détail pour la comptabilité."),
        ],
        "controles": [
            ["Sens", "Entrée client et sortie fournisseur ne sont jamais confondues."],
            ["Séparation", "Préparation, validation et exécution suivent les droits configurés."],
            ["Doublon", "Aucune source déjà confirmée ne repart dans un lot."],
            ["Confirmation", "Le statut métier change seulement après le retour bancaire définitif."],
        ],
        "synchronisations": [
            ["Factures fournisseurs", "Le reste à payer diminue après confirmation."],
            ["Paie", "Le bulletin contrôlé devient payé après confirmation du salaire."],
            ["Notes de frais", "La note validée devient remboursée après confirmation."],
            ["Trésorerie", "Les sorties prévues puis réalisées sont distinguées."],
        ],
        "exceptions": [
            ["Prestataire absent", "Utilisez le lot comme préparation, effectuez le paiement dans la banque puis enregistrez la référence réelle."],
            ["Lot partiellement rejeté", "Ne relancez pas les ordres confirmés ; recréez uniquement les rejets."],
            ["Source corrigée après validation", "Annulez le lot avant envoi et recommencez la validation."],
        ],
    },
    {
        "titre": "Gérer un sous-traitant et imputer son coût au chantier",
        "objectif": "Contrôler les documents du sous-traitant, suivre son intervention et régler ses factures comme des achats.",
        "roles": "Direction, administration, conducteur de travaux et comptable selon droits.",
        "prerequis": [
            "Disposer de l’identité légale, assurances, attestations et contacts.",
            "Connaître le chantier, le périmètre confié et le prix prévu.",
        ],
        "etapes": [
            ("Créer la fiche", "Renseignez raison sociale, SIRET, contacts, spécialité et adresse."),
            ("Ajouter les documents", "Importez assurances et attestations avec leurs dates de validité. Refusez une intervention si un document obligatoire manque."),
            ("Enregistrer et vérifier le RIB", "Appliquez le même double contrôle que pour un fournisseur."),
            ("Rattacher le chantier", "Décrivez le lot, les dates, le responsable et le montant prévu."),
            ("Planifier l’intervention", "Ajoutez les dates utiles au planning ou au suivi chantier sans créer une fausse fiche salarié."),
            ("Contrôler les travaux", "Conservez comptes rendus, photos, réserves et validation du responsable."),
            ("Saisir la facture", "Traitez-la comme une facture fournisseur, catégorie sous-traitance, et liez-la au bon chantier."),
            ("Comparer prévu et facturé", "Analysez avenants, retenues ou écarts avant validation."),
            ("Préparer le règlement", "Utilisez la facture validée et le RIB vérifié dans un lot fournisseur."),
            ("Clôturer", "Vérifiez factures, paiements, documents et coût final dans la rentabilité du chantier."),
        ],
        "controles": [
            ["Conformité", "Documents obligatoires présents et valides à la date d’intervention."],
            ["Coût", "Facture classée sur le chantier et catégorie sous-traitance."],
            ["RIB", "Coordonnée vérifiée avant lot bancaire."],
            ["Historique", "Travaux, réserves, factures et paiements restent consultables."],
        ],
        "synchronisations": [
            ["Chantier", "Reçoit le périmètre et les coûts de sous-traitance."],
            ["Rentabilité", "Compare coût prévu, facturé et payé."],
            ["Banque", "Règle la facture comme une sortie fournisseur."],
        ],
        "exceptions": [
            ["Avenant", "Ajoutez le montant et la justification avant de valider une facture supérieure au prévu."],
            ["Document expiré", "Bloquez la nouvelle affectation ou demandez la pièce mise à jour."],
            ["Sous-traitant également fournisseur", "Conservez une identité cohérente et évitez les doubles paiements entre deux fiches."],
        ],
    },
    {
        "titre": "Suivre un chantier jusqu’à sa clôture et au DOE",
        "objectif": "Réunir équipe, tâches, documents, heures, achats, facturation, réserves et dossier final.",
        "roles": "Conducteur, chef de chantier, administration et direction selon périmètre.",
        "prerequis": [
            "Client, chantier et devis accepté correctement liés.",
            "Équipe affectée et documents de démarrage disponibles.",
        ],
        "etapes": [
            ("Préparer le dossier", "Contrôlez adresse, contacts, dates, responsable, budget et devis accepté."),
            ("Ajouter les documents", "Classez plans, notices, PPSPS, autorisations et consignes. Définissez qui peut consulter chaque pièce."),
            ("Vérifier les tâches", "Les lignes du devis accepté alimentent la liste terrain sans prix. Ajoutez les tâches internes nécessaires."),
            ("Affecter les personnes", "Ajoutez ouvriers, chefs et conducteur. La visibilité chantier suit l’affectation et les droits décidés par l’administrateur."),
            ("Planifier", "Répartissez dates et heures prévues ; intégrez dépôt, bureau ou autres activités séparément."),
            ("Suivre le terrain", "Photos, comptes rendus, tâches terminées et incidents mettent à jour l’avancement."),
            ("Valider les heures", "Contrôlez les pointages avant qu’ils ne pèsent sur la rentabilité et la paie."),
            ("Classer les achats", "Rattachez commandes, factures fournisseurs, notes de frais, sorties de stock et sous-traitance au chantier."),
            ("Facturer l’avancement", "Utilisez acompte, situations et solde en cohérence avec le devis et le réalisé."),
            ("Analyser la rentabilité", "Comparez vendu, facturé, heures valorisées, achats, sous-traitance et frais."),
            ("Traiter les réserves", "Documentez réserve, responsable, action, photo avant/après et date de levée."),
            ("Constituer le DOE", "Rassemblez plans à jour, fiches techniques des produits utilisés, notices, procès-verbaux, photos et documents contractuels."),
            ("Clôturer", "Vérifiez tâches, pointages, dépenses, factures, paiements et DOE avant de passer le chantier à Terminé puis Archivé."),
        ],
        "controles": [
            ["Périmètre", "Seules les personnes affectées ou autorisées consultent le chantier."],
            ["Financier", "Devis accepté, facturé, encaissé et coûts réels sont cohérents."],
            ["Temps", "Aucune heure en attente ou anomalie non traitée."],
            ["DOE", "Documents finaux lisibles, à jour et classés avant livraison."],
        ],
        "synchronisations": [
            ["Devis / Factures", "Portent le marché et son avancement financier."],
            ["Planning / Pointage", "Portent temps prévu et temps réel."],
            ["Achats / Stock", "Portent les coûts et consommations."],
            ["Documents produits", "Les fiches techniques peuvent alimenter le DOE."],
        ],
        "exceptions": [
            ["Dépense absente", "Vérifiez si elle est restée en frais généraux ou liée à un autre chantier."],
            ["Tâche absente", "Contrôlez l’acceptation et la liaison du devis puis ajoutez ou synchronisez les tâches."],
            ["DOE incomplet", "N’archivez pas avant d’avoir identifié chaque pièce manquante et son responsable."],
        ],
    },
    {
        "titre": "Importer les données d’un autre logiciel",
        "objectif": "Reprendre clients, chantiers, articles, fournisseurs, documents et historiques sans polluer la base par des doublons.",
        "roles": "Administrateur avec accompagnement du support ou du prestataire de migration.",
        "prerequis": [
            "Exporter les données de Batappli, Batigest ou de l’ancien outil dans les formats les plus structurés disponibles.",
            "Conserver une copie intégrale et inchangée des exports d’origine.",
            "Créer une entreprise de test distincte pour la répétition.",
        ],
        "etapes": [
            ("Inventorier les sources", "Listez modules, périodes, volumes, formats, pièces jointes, codes-barres et relations entre fichiers."),
            ("Définir le périmètre", "Décidez ce qui doit être repris, archivé séparément ou laissé dans l’ancien outil."),
            ("Nettoyer sans détruire", "Corrigez encodage, colonnes et doublons dans une copie ; conservez l’original."),
            ("Mapper les colonnes", "Associez chaque champ source au champ Liria, y compris identifiants externes pour garder la traçabilité."),
            ("Importer les référentiels", "Commencez par clients, fournisseurs, employés et articles avant les documents qui les référencent."),
            ("Importer les affaires", "Chargez chantiers, devis, factures, règlements et pièces dans l’ordre chronologique nécessaire."),
            ("Rapprocher les documents", "Vérifiez que devis, chantier, facture, fournisseur et règlement pointent vers les bonnes fiches."),
            ("Contrôler un échantillon", "Comparez au moins plusieurs dossiers complets et des totaux par période avec l’ancien logiciel."),
            ("Tester les codes", "Scannez des codes-barres historiques et vérifiez l’article ou l’équipement retrouvé."),
            ("Rejouer en test", "Corrigez le mapping puis recommencez jusqu’à obtenir un rapport sans erreur critique."),
            ("Planifier la bascule", "Fixez une date de gel, export final, import final, contrôle et ouverture aux utilisateurs."),
            ("Conserver la preuve", "Archivez sources, mappings, rapports d’import et validation de la reprise."),
        ],
        "controles": [
            ["Comptabilité", "Totaux facturés, TVA, encaissés et restes dus concordent par période."],
            ["Relations", "Aucun document orphelin et aucun chantier rattaché au mauvais client."],
            ["Encodage", "Accents, symboles monétaires et références sont lisibles."],
            ["Sécurité", "La reprise est limitée à la bonne entreprise et les fichiers restent privés."],
        ],
        "synchronisations": [
            ["Référentiels", "Servent de base aux imports de documents."],
            ["Stock", "Reprend références, codes-barres, quantités et prix d’achat selon validation."],
            ["Exports comptables", "Permettent la comparaison après bascule."],
        ],
        "exceptions": [
            ["Format propriétaire", "Demandez un export officiel ou une prestation de conversion ; n’inventez pas les colonnes manquantes."],
            ["Historique incomplet", "Conservez les PDF ou archives de l’ancien logiciel avec une mention claire de leur origine."],
            ["Écart comptable", "Arrêtez la bascule et faites valider la correction par le comptable avant production."],
        ],
    },
    {
        "titre": "Clôture mensuelle et clôture annuelle",
        "objectif": "Produire des données cohérentes pour la direction et l’expert-comptable, sans confondre estimation de gestion et comptabilité officielle.",
        "roles": "Gérant, comptable, administration et responsables de module.",
        "prerequis": [
            "Toutes les pièces du mois sont saisies ou identifiées comme manquantes.",
            "Les validations opérationnelles sont terminées.",
        ],
        "etapes": [
            ("Clôturer le chiffre d’affaires", "Vérifiez devis acceptés, factures émises, avoirs, situations, règlements et impayés."),
            ("Clôturer les achats", "Rapprochez commandes, réceptions, factures fournisseurs, échéances et paiements."),
            ("Valider les notes de frais", "Traitez les corrections et exportez les justificatifs originaux avec leur manifeste."),
            ("Valider le temps", "Aucune journée inhabituelle ou pointage en attente ne doit rester sans décision."),
            ("Préparer la paie", "Exportez les variables contrôlées, importez les bulletins et rapprochez les salaires confirmés."),
            ("Contrôler les chantiers", "Imputez achats, notes, sous-traitance et stock sur les bons chantiers avant de lire les marges."),
            ("Contrôler la trésorerie", "Comparez échéances, encaissements, décaissements prévus et confirmations bancaires."),
            ("Produire les exports", "Choisissez la période, le format attendu et incluez les pièces demandées."),
            ("Faire valider par le comptable", "Les règles de TVA, comptes, méthodes de valorisation et corrections restent sous son contrôle."),
            ("Pour l’année, réaliser l’inventaire", "Comptez le dépôt, valorisez au prix d’achat selon la méthode validée et expliquez les écarts."),
            ("Archiver", "Conservez exports, manifestes, journaux d’audit, inventaires et validations selon la politique de conservation."),
        ],
        "controles": [
            ["Ventes", "Factures - avoirs = chiffre d’affaires attendu ; encaissements rapprochés."],
            ["Achats", "Factures, TVA déductible, paiements et imputation chantier contrôlés."],
            ["Stock", "Quantité finale et valeur validées par inventaire."],
            ["Paie", "Retour du cabinet et paiements bancaires rapprochés."],
        ],
        "synchronisations": [
            ["Rentabilité", "Dépend des heures et dépenses correctement classées."],
            ["Trésorerie", "Dépend des échéances et paiements confirmés."],
            ["Expert-comptable", "Reçoit les exports et reste responsable de la comptabilité officielle."],
        ],
        "exceptions": [
            ["Pièce manquante", "Inscrivez-la dans une liste d’attente ; ne créez pas un faux justificatif pour fermer le mois."],
            ["Période déjà exportée", "Créez un export correctif versionné plutôt que remplacer silencieusement le précédent."],
            ["Litige ou contrôle", "Activez la conservation renforcée ou legal hold et suspendez toute suppression."],
        ],
    },
    {
        "titre": "Administrer l’abonnement, les appareils et les services externes",
        "objectif": "Comprendre ce qui est facturé, configurer les services nécessaires et éviter qu’une option externe soit prise pour une fonction déjà active.",
        "roles": "Gérant ou administrateur entreprise ; administrateur plateforme pour les opérations SaaS.",
        "prerequis": [
            "Disposer d’un moyen de paiement et des coordonnées de l’entité facturée.",
            "Connaître l’offre, les comptes utilisateurs et les options choisies.",
        ],
        "etapes": [
            ("Consulter le détail du coût", "Ouvrez Abonnement pour voir offre, comptes facturables, options, stockage, IA et dépassements."),
            ("Contrôler les comptes", "Les comptes actifs et en pause peuvent rester facturables. Fermez uniquement selon les règles contractuelles."),
            ("Contrôler les appareils", "Deux appareils actifs sont inclus par compte selon la règle affichée. Révoquez ceux qui ne sont plus utilisés."),
            ("Choisir l’option IA", "Sélectionnez le palier, la politique au quota et le plafond. L’IA reste limitée aux droits du compte."),
            ("Surveiller le stockage", "Identifiez photos, plans et justificatifs les plus volumineux. N’effacez pas une pièce soumise à conservation."),
            ("Ouvrir le portail Stripe", "Changez la carte, consultez factures d’abonnement ou résiliation depuis le portail sécurisé."),
            ("Configurer l’e-mail", "Un domaine d’envoi et un prestataire sont nécessaires pour l’envoi automatique avec pièce jointe ; sinon le logiciel ouvre la messagerie."),
            ("Configurer la banque", "Un contrat et des clés avec un prestataire réglementé sont nécessaires pour initier de vrais virements."),
            ("Configurer les fournisseurs", "API, EDI, PunchOut ou OAuth exigent un accord du fournisseur. Sans cela, utilisez portail ou import."),
            ("Tester avant activation", "Réalisez un essai avec données de test, vérifiez webhooks, erreurs, retours et journalisation."),
        ],
        "controles": [
            ["Facturation", "Montant, période, offre, comptes et options correspondent au contrat."],
            ["Appareils", "Chaque appareil appartient à un utilisateur réel et les anciens sont révoqués."],
            ["Services", "Un écran indique clairement configuré, test ou indisponible."],
            ["Secrets", "Aucune clé, mot de passe ou jeton n’est copié dans une conversation ou un champ non sécurisé."],
        ],
        "synchronisations": [
            ["Stripe Billing", "Gère l’abonnement Liria, distinct de Stripe Connect pour les paiements des clients de l’entreprise."],
            ["Stockage", "Les documents privés alimentent le quota de l’entreprise."],
            ["IA", "La consommation est suivie par palier et compte autorisé."],
        ],
        "exceptions": [
            ["Service non configuré", "Le module doit expliquer la limite et proposer l’action manuelle sûre, sans simuler une connexion."],
            ["Paiement d’abonnement échoué", "L’administrateur reçoit l’avertissement et le délai avant suspension selon la politique."],
            ["Plus de deux appareils", "L’avertissement et le coût apparaissent dans Abonnement, jamais dans le tableau de bord métier."],
        ],
    },
]
