import type { AccessTier, Capability } from "./access";
import type { CategoryId } from "./categories";

export const TOOL_IDS = ["diagonale-rectangle", "angle-droit-345", "pythagore", "pente", "surface-rectangle", "cercle", "arc-corde-fleche", "repartition", "entraxes", "repartition-vitrages", "poids-vitrage", "calcul-plaques", "quantite-peinture", "isolation", "fixations", "arche"] as const;
export type ToolId = (typeof TOOL_IDS)[number];
export type ToolStatus = "active" | "preview" | "hidden";
export type ToolEngineId = "rectangle-diagonal" | "right-triangle" | "slope" | "rectangle-area" | "circle" | "distribution" | "segmental-arch" | "maximum-spacing" | "glass-weight" | "area-quantitative" | "paint" | "insulation";
export type ToolDefinition = {
  id: ToolId; slug: string; name: string; shortName: string; categoryId: CategoryId;
  description: string; keywords: readonly string[]; icon: string; access: AccessTier;
  capabilities: readonly Capability[]; status: ToolStatus; order: number; engine: ToolEngineId;
  hasSvg: boolean; hasSiteMode: boolean; seo: { title: string; description: string };
  promotionId?: string; popular?: boolean;
};

const freeCapabilities = ["basic-calculation", "basic-tracing", "site-instructions"] as const;

export const tools: readonly ToolDefinition[] = [
  { id: "diagonale-rectangle", slug: "diagonale-rectangle", name: "Diagonale d’un rectangle", shortName: "Diagonale", categoryId: "squaring", description: "Contrôlez rapidement l’équerrage d’un ouvrage.", keywords: ["équerrage", "rectangle", "diagonale", "angle droit"], icon: "diagonal", access: "free", capabilities: freeCapabilities, status: "active", order: 10, engine: "rectangle-diagonal", hasSvg: true, hasSiteMode: true, seo: { title: "Calcul diagonale rectangle gratuit", description: "Calculez la diagonale d’un rectangle et contrôlez son équerrage sur chantier." }, popular: true },
  { id: "angle-droit-345", slug: "angle-droit-3-4-5", name: "Angle droit 3-4-5", shortName: "Angle droit 3-4-5", categoryId: "squaring", description: "Tracez ou contrôlez un angle droit avec le ratio chantier 3:4:5.", keywords: ["angle droit", "équerrage", "équerre", "diagonale", "345", "3 4 5"], icon: "triangle-345", access: "free", capabilities: freeCapabilities, status: "active", order: 15, engine: "right-triangle", hasSvg: true, hasSiteMode: true, seo: { title: "Règle 3 4 5 pour tracer un angle droit", description: "Calculez les trois longueurs de la méthode 3-4-5 et contrôlez un angle droit sur chantier." }, popular: true },
  { id: "pythagore", slug: "pythagore", name: "Pythagore — côté manquant", shortName: "Pythagore", categoryId: "squaring", description: "Calculez n’importe quel côté d’un triangle rectangle.", keywords: ["3 4 5", "hypoténuse", "triangle", "angle droit"], icon: "triangle", access: "free", capabilities: freeCapabilities, status: "active", order: 20, engine: "right-triangle", hasSvg: true, hasSiteMode: true, seo: { title: "Calcul Pythagore chantier gratuit", description: "Calculez l’hypoténuse ou un côté d’un triangle rectangle pour vos implantations." }, popular: true },
  { id: "pente", slug: "pente", name: "Pente et dénivelé", shortName: "Pente", categoryId: "slopes", description: "Passez d’une pente en % au dénivelé et aux degrés.", keywords: ["niveau", "évacuation", "toiture", "rampe", "pourcentage"], icon: "slope", access: "free", capabilities: freeCapabilities, status: "active", order: 30, engine: "slope", hasSvg: true, hasSiteMode: true, seo: { title: "Calcul pente et dénivelé gratuit", description: "Convertissez une pente en pourcentage en dénivelé, degrés et millimètres par mètre." }, popular: true },
  { id: "surface-rectangle", slug: "surface-rectangle", name: "Surface rectangulaire", shortName: "Surface", categoryId: "areas", description: "Calculez une surface de mur, plafond ou sol.", keywords: ["mètres carrés", "mur", "sol", "plafond", "peinture"], icon: "area", access: "free", capabilities: freeCapabilities, status: "active", order: 40, engine: "rectangle-area", hasSvg: true, hasSiteMode: true, seo: { title: "Calcul surface rectangle gratuit", description: "Calculez rapidement une surface de mur, plafond ou sol en mètres carrés." } },
  { id: "cercle", slug: "cercle", name: "Cercle complet", shortName: "Cercle", categoryId: "geometry", description: "Rayon, diamètre, circonférence et aire.", keywords: ["rond", "rayon", "diamètre", "circonférence"], icon: "circle", access: "free", capabilities: freeCapabilities, status: "active", order: 50, engine: "circle", hasSvg: true, hasSiteMode: true, seo: { title: "Calcul cercle rayon diamètre gratuit", description: "Calculez rayon, diamètre, circonférence et aire d’un cercle." } },
  { id: "arc-corde-fleche", slug: "arc-corde-fleche-rayon", name: "Arc, corde & flèche", shortName: "Corde & flèche", categoryId: "geometry", description: "Retrouvez le rayon et la longueur d’un arc depuis sa corde et sa flèche.", keywords: ["cintre", "rayon", "arc", "courbe", "ouverture", "corde", "flèche"], icon: "arc", access: "free", capabilities: freeCapabilities, status: "active", order: 55, engine: "segmental-arch", hasSvg: true, hasSiteMode: true, seo: { title: "Calcul rayon avec corde et flèche", description: "Calculez le rayon, l’angle et la longueur d’un arc à partir de la corde et de la flèche." }, popular: true },
  { id: "repartition", slug: "repartition", name: "Répartition régulière", shortName: "Répartir", categoryId: "distribution", description: "Positionnez modules, spots, vitrages ou montants.", keywords: ["entraxe", "spots", "montants", "vitrages", "modules"], icon: "distribution", access: "free", capabilities: freeCapabilities, status: "active", order: 60, engine: "distribution", hasSvg: true, hasSiteMode: true, seo: { title: "Calcul répartition régulière gratuit", description: "Répartissez régulièrement modules, spots, vitrages ou montants sur une longueur." }, promotionId: "gestion-pro-quantitatifs", popular: true },
  { id: "entraxes", slug: "calcul-entraxes", name: "Répartir des entraxes", shortName: "Entraxes", categoryId: "distribution", description: "Calculez un entraxe régulier qui ne dépasse jamais votre maximum.", keywords: ["montant", "ossature", "espacement", "répartition", "suspente", "tasseau", "spot"], icon: "spacing", access: "free", capabilities: freeCapabilities, status: "active", order: 62, engine: "maximum-spacing", hasSvg: true, hasSiteMode: true, seo: { title: "Calcul entraxe montants et fixations", description: "Calculez le nombre d’intervalles, l’entraxe réel et toutes les positions depuis l’origine." }, popular: true },
  { id: "repartition-vitrages", slug: "repartition-vitrages", name: "Répartition de vitrages", shortName: "Vitrages", categoryId: "glazing", description: "Déterminez la largeur identique de vos vitrages, jeux et montants compris.", keywords: ["verre", "vitrage", "vitre", "répartition", "montant", "jeu"], icon: "glazing", access: "free", capabilities: freeCapabilities, status: "active", order: 65, engine: "distribution", hasSvg: true, hasSiteMode: true, seo: { title: "Calcul répartition et largeur de vitrages", description: "Répartissez des vitrages identiques sur une longueur avec montants et jeux périphériques." }, promotionId: "gestion-pro-quantitatifs" },
  { id: "poids-vitrage", slug: "poids-vitrage", name: "Poids vitrage", shortName: "Poids vitrage", categoryId: "glazing", description: "Estimez le poids d’un vitrage depuis sa surface et ses épaisseurs de verre.", keywords: ["verre", "vitrage", "vitre", "poids verre", "kg", "feuilleté", "double vitrage"], icon: "glass-weight", access: "free", capabilities: freeCapabilities, status: "active", order: 68, engine: "glass-weight", hasSvg: false, hasSiteMode: false, seo: { title: "Calcul poids vitrage et verre", description: "Estimez le poids théorique d’un vitrage simple, feuilleté ou composé à partir des épaisseurs saisies." } },
  { id: "calcul-plaques", slug: "calcul-plaques-panneaux", name: "Calcul plaques", shortName: "Plaques", categoryId: "partitions", description: "Estimez le nombre de plaques ou panneaux nécessaires avec une marge de chute.", keywords: ["placo", "plaque", "BA13", "panneau", "quantité", "chute"], icon: "panels", access: "free", capabilities: freeCapabilities, status: "active", order: 72, engine: "area-quantitative", hasSvg: false, hasSiteMode: false, seo: { title: "Calcul nombre de plaques placo et panneaux", description: "Estimez le nombre minimum de plaques de plâtre ou panneaux pour couvrir une surface." }, promotionId: "gestion-pro-quantitatifs" },
  { id: "quantite-peinture", slug: "quantite-peinture", name: "Quantité de peinture", shortName: "Peinture", categoryId: "painting", description: "Calculez les litres nécessaires selon surface, rendement, couches et marge.", keywords: ["peinture", "litre", "rendement", "couche", "mur", "plafond", "pot"], icon: "paint", access: "free", capabilities: freeCapabilities, status: "active", order: 75, engine: "paint", hasSvg: false, hasSiteMode: false, seo: { title: "Calcul quantité de peinture en litres", description: "Calculez la surface nette et les litres de peinture nécessaires selon le rendement et le nombre de couches." }, promotionId: "colors-peinture", popular: true },
  { id: "isolation", slug: "calcul-isolation-resistance-thermique", name: "Isolation", shortName: "Isolation", categoryId: "insulation", description: "Estimez un quantitatif d’isolant ou calculez la résistance thermique R.", keywords: ["isolation", "isolant", "panneau", "rouleau", "lambda", "résistance thermique", "R"], icon: "insulation", access: "free", capabilities: freeCapabilities, status: "active", order: 78, engine: "insulation", hasSvg: false, hasSiteMode: false, seo: { title: "Calcul isolation et résistance thermique R", description: "Calculez un nombre de panneaux isolants ou la résistance thermique R à partir de l’épaisseur et du lambda." } },
  { id: "fixations", slug: "calcul-fixations", name: "Fixations", shortName: "Fixations", categoryId: "fixings", description: "Calculez le nombre et les positions exactes de vos fixations.", keywords: ["fixation", "vis", "cheville", "entraxe", "espacement", "suspente"], icon: "fixings", access: "free", capabilities: freeCapabilities, status: "active", order: 80, engine: "maximum-spacing", hasSvg: true, hasSiteMode: true, seo: { title: "Calcul nombre et entraxe de fixations", description: "Calculez les positions de fixations selon une longueur, un entraxe maximum et des retraits." } },
  { id: "arche", slug: "arche", name: "Arche segmentaire", shortName: "Tracer une arche", categoryId: "tracing", description: "Obtenez rayon, centre, longueur d’arc et étapes de traçage.", keywords: ["arc", "cintré", "niche", "passage", "rayon"], icon: "arch", access: "free", capabilities: freeCapabilities, status: "active", order: 70, engine: "segmental-arch", hasSvg: true, hasSiteMode: true, seo: { title: "Tracer une arche segmentaire", description: "Calculez le rayon et le centre puis tracez une arche segmentaire sur chantier." }, popular: true },
];

export const activeTools = tools.filter((tool) => tool.status === "active").sort((a, b) => a.order - b.order);
export function getTool(id: string) { return tools.find((tool) => tool.id === id); }
export function getToolBySlug(slug: string) { return tools.find((tool) => tool.slug === slug && tool.status === "active"); }
