import { getContexteEntreprise } from "@/lib/entreprise";
import { createClient } from "@/lib/supabase/server";
import { creerContratEntretienAction, creerInterventionAction, changerStatutInterventionAction } from "@/app/actions/suite-metier";
import { euros } from "@/lib/devis";

const champ="mt-1 w-full rounded-md border border-neutral-300 bg-white px-3 py-2 text-sm dark:border-neutral-700 dark:bg-neutral-900";
const un=<T,>(v:T|T[]|null):T|null=>Array.isArray(v)?v[0]??null:v;
const nomClient=(c:{nom?:string|null;prenom?:string|null;societe?:string|null}|null)=>c?.societe||[c?.prenom,c?.nom].filter(Boolean).join(" ")||"Client";

export default async function InterventionsPage({searchParams}:{searchParams:Promise<{error?:string;success?:string}>}){
 const message=await searchParams;const ctx=await getContexteEntreprise();const sb=await createClient();
 const [{data:clients},{data:chantiers},{data:employes},{data:contrats},{data:interventions}]=await Promise.all([
  sb.from("clients").select("id,nom,prenom,societe").eq("entreprise_id",ctx.entrepriseId).eq("statut","actif").order("societe"),
  sb.from("chantiers").select("id,nom,client_id").eq("entreprise_id",ctx.entrepriseId).not("statut","in","(archive,annule)").order("nom"),
  sb.from("employes").select("id,nom,prenom,poste").eq("entreprise_id",ctx.entrepriseId).eq("statut","actif").order("nom"),
  sb.from("contrats_entretien").select("id,numero,libelle,statut,date_debut,date_fin,periodicite,prochaine_intervention,montant_ht,client:clients(nom,prenom,societe),chantier:chantiers(nom)").eq("entreprise_id",ctx.entrepriseId).order("created_at",{ascending:false}),
  sb.from("interventions").select("id,numero,type,statut,priorite,objet,date_prevue,heure_prevue,duree_prevue,client:clients(nom,prenom,societe),chantier:chantiers(nom),employe:employes(nom,prenom)").eq("entreprise_id",ctx.entrepriseId).order("date_prevue",{ascending:true}),
 ]);
 return <main className="p-4 sm:p-8"><div className="mx-auto max-w-7xl space-y-6"><header><h1 className="text-xl font-semibold">Contrats et interventions</h1><p className="text-sm text-neutral-500">Entretien récurrent, dépannage, SAV et bons de travail assignés aux équipes.</p></header>
 {message.error&&<p className="rounded bg-red-50 p-3 text-sm text-red-700">{message.error}</p>}{message.success&&<p className="rounded bg-green-50 p-3 text-sm text-green-700">{message.success}</p>}
 <div className="grid gap-4 xl:grid-cols-2"><form action={creerInterventionAction} className="grid gap-3 rounded-xl border p-4 sm:grid-cols-2"><h2 className="font-semibold sm:col-span-2">Nouveau bon d’intervention</h2><label className="text-xs">Client<select required name="client_id" className={champ}><option value="">Choisir…</option>{(clients??[]).map(c=><option key={c.id} value={c.id}>{nomClient(c)}</option>)}</select></label><label className="text-xs">Chantier<select name="chantier_id" className={champ}><option value="">Sans chantier</option>{(chantiers??[]).map(c=><option key={c.id} value={c.id}>{c.nom}</option>)}</select></label><label className="text-xs">Contrat<select name="contrat_id" className={champ}><option value="">Hors contrat</option>{(contrats??[]).filter(c=>c.statut==="actif").map(c=><option key={c.id} value={c.id}>{c.numero} · {c.libelle}</option>)}</select></label><label className="text-xs">Intervenant<select name="employe_id" className={champ}><option value="">À affecter</option>{(employes??[]).map(e=><option key={e.id} value={e.id}>{e.prenom} {e.nom} · {e.poste}</option>)}</select></label><label className="text-xs sm:col-span-2">Objet<input required name="objet" className={champ}/></label><label className="text-xs">Type<select name="type" className={champ}><option value="depannage">Dépannage</option><option value="entretien">Entretien</option><option value="sav">SAV</option><option value="visite">Visite</option><option value="livraison">Livraison</option><option value="autre">Autre</option></select></label><label className="text-xs">Priorité<select name="priorite" className={champ}><option value="normale">Normale</option><option value="haute">Haute</option><option value="urgente">Urgente</option><option value="basse">Basse</option></select></label><label className="text-xs">Date<input type="date" name="date_prevue" className={champ}/></label><label className="text-xs">Heure<input type="time" name="heure_prevue" className={champ}/></label><label className="text-xs">Durée prévue (h)<input type="number" name="duree_prevue" min="0" step="0.25" className={champ}/></label><label className="text-xs sm:col-span-2">Description<textarea name="description" rows={2} className={champ}/></label><button className="rounded bg-blue-700 px-4 py-2 text-sm font-semibold text-white sm:col-span-2">Créer et planifier</button></form>
 <form action={creerContratEntretienAction} className="grid gap-3 rounded-xl border p-4 sm:grid-cols-2"><h2 className="font-semibold sm:col-span-2">Nouveau contrat d’entretien</h2><label className="text-xs">Client<select required name="client_id" className={champ}><option value="">Choisir…</option>{(clients??[]).map(c=><option key={c.id} value={c.id}>{nomClient(c)}</option>)}</select></label><label className="text-xs">Chantier<select name="chantier_id" className={champ}><option value="">Tous sites</option>{(chantiers??[]).map(c=><option key={c.id} value={c.id}>{c.nom}</option>)}</select></label><label className="text-xs sm:col-span-2">Libellé<input required name="libelle" className={champ}/></label><label className="text-xs">Début<input required type="date" name="date_debut" className={champ}/></label><label className="text-xs">Fin facultative<input type="date" name="date_fin" className={champ}/></label><label className="text-xs">Périodicité<select name="periodicite" className={champ}><option value="mensuelle">Mensuelle</option><option value="trimestrielle">Trimestrielle</option><option value="semestrielle">Semestrielle</option><option value="annuelle">Annuelle</option><option value="personnalisee">Personnalisée</option></select></label><label className="text-xs">Prochaine intervention<input type="date" name="prochaine_intervention" className={champ}/></label><label className="text-xs">Montant HT<input type="number" name="montant_ht" min="0" step="0.01" className={champ}/></label><label className="text-xs">TVA (%)<input type="number" name="taux_tva" defaultValue="20" step="0.01" className={champ}/></label><label className="flex items-center gap-2 text-sm sm:col-span-2"><input type="checkbox" name="reconduction_tacite"/> Reconduction tacite</label><label className="text-xs sm:col-span-2">Description<textarea name="description" rows={2} className={champ}/></label><button className="rounded bg-neutral-900 px-4 py-2 text-sm font-semibold text-white dark:bg-white dark:text-neutral-900 sm:col-span-2">Créer le contrat</button></form></div>
 <section><h2 className="mb-3 font-semibold">Bons de travail</h2><div className="grid gap-3 lg:grid-cols-2">{(interventions??[]).map(i=>{const c=un(i.client),ch=un(i.chantier),e=un(i.employe);return <article key={i.id} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><div><strong>{i.numero} · {i.objet}</strong><p className="text-sm text-neutral-500">{nomClient(c)}{ch?` · ${ch.nom}`:""}</p></div><span className={`h-fit rounded-full px-2 py-1 text-xs ${i.priorite==="urgente"?"bg-red-100 text-red-700":"bg-neutral-100"}`}>{i.priorite}</span></div><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><p><span className="text-neutral-500">Date : </span>{i.date_prevue||"À planifier"} {i.heure_prevue?.slice(0,5)}</p><p><span className="text-neutral-500">Équipe : </span>{e?`${e.prenom} ${e.nom}`:"À affecter"}</p></div><div className="mt-3 flex flex-wrap items-center gap-2"><span className="mr-auto rounded bg-blue-50 px-2 py-1 text-xs text-blue-700">{i.statut}</span>{i.statut==="a_planifier"&&<form action={changerStatutInterventionAction.bind(null,i.id,"planifiee")}><button className="rounded border px-3 py-1.5 text-xs">Planifier</button></form>}{["a_planifier","planifiee"].includes(i.statut)&&<form action={changerStatutInterventionAction.bind(null,i.id,"en_cours")}><button className="rounded bg-amber-600 px-3 py-1.5 text-xs text-white">Démarrer</button></form>}{i.statut==="en_cours"&&<form action={changerStatutInterventionAction.bind(null,i.id,"terminee")}><button className="rounded bg-green-700 px-3 py-1.5 text-xs text-white">Terminer</button></form>}</div></article>})}{!interventions?.length&&<p className="rounded-xl border border-dashed p-8 text-center text-sm text-neutral-500 lg:col-span-2">Aucune intervention.</p>}</div></section>
 <section><h2 className="mb-3 font-semibold">Contrats d’entretien</h2><div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[760px] text-sm"><thead className="bg-neutral-50 text-left text-xs uppercase text-neutral-500 dark:bg-neutral-900"><tr><th className="p-3">Contrat</th><th>Client</th><th>Périodicité</th><th>Prochaine visite</th><th>Statut</th><th className="pr-3 text-right">HT</th></tr></thead><tbody>{(contrats??[]).map(c=><tr key={c.id} className="border-t"><td className="p-3"><strong>{c.numero}</strong><div className="text-xs text-neutral-500">{c.libelle}</div></td><td>{nomClient(un(c.client))}</td><td>{c.periodicite}</td><td>{c.prochaine_intervention||"—"}</td><td>{c.statut}</td><td className="pr-3 text-right font-mono">{euros(c.montant_ht)}</td></tr>)}</tbody></table></div></section>
 </div></main>;
}
