"use client";

import Link from "next/link";
import { useEffect, useState, type FormEvent } from "react";
import { Brand } from "./HomeDashboard";
import { useAccount } from "./AccountProvider";
import { MonetizationPanel } from "./MonetizationPanel";
import { EXTERNAL_URLS } from "@/lib/site";

export function AccountWorkspace() {
  const account = useAccount(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [recovery, setRecovery] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  useEffect(() => { const timer = window.setTimeout(() => setRecovery(new URLSearchParams(window.location.search).get("recovery") === "1"), 0); return () => window.clearTimeout(timer); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); try { await account.signIn(email, password); setPassword(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "Connexion impossible."); } }
  return <main className="account-page"><header className="calculator-header shell"><Brand /><Link className="all-tools" href="/">Accueil <span>×</span></Link></header><section className="tool-hero"><div className="shell"><p className="eyebrow">COMPTE COMMUN ELSATIA</p><h1 className="projects-title">Compte ELSATIA</h1><p>Le compte est facultatif. Les calculs Free restent disponibles sans connexion.</p></div></section><section className="shell account-card">
    {recovery && account.user && <form onSubmit={(event) => { event.preventDefault(); setError(""); void account.updatePassword(newPassword).then(() => { setNotice("Mot de passe mis à jour."); setRecovery(false); setNewPassword(""); }).catch((caught) => setError(caught instanceof Error ? caught.message : "Mise à jour impossible.")); }}><h2>Nouveau mot de passe</h2><label><span>Nouveau mot de passe</span><input type="password" autoComplete="new-password" minLength={10} required value={newPassword} onChange={(event) => setNewPassword(event.target.value)} /></label><button>Enregistrer le nouveau mot de passe</button></form>}
    {account.user ? <><div className="account-identity"><span>{(account.user.email?.[0] ?? "E").toUpperCase()}</span><div><small>CONNECTÉ</small><strong>{account.user.user_metadata?.full_name ?? account.user.email}</strong><p>{account.access.tier === "pro" ? "Tools Pro" : "Tools Free"} · {account.message}</p><p>Synchronisation : {account.syncStatus === "syncing" ? "en cours" : account.syncStatus === "synced" ? "à jour" : account.syncStatus === "error" ? "erreur, les projets locaux sont conservés" : "locale uniquement"}</p></div></div>{account.companies.length > 0 && <label><span>Entreprise active</span><select aria-label="Entreprise active" value={account.activeCompany?.id ?? ""} disabled={account.switchingCompany} onChange={(event) => void account.switchCompany(event.target.value).catch((caught) => setError(caught instanceof Error ? caught.message : "Changement impossible."))}>{account.companies.map((company) => <option key={company.id} value={company.id}>{company.name}</option>)}</select><small>Les projets locaux, conflits et droits sont cloisonnés dans cette entreprise.</small></label>}<div className="account-actions"><button onClick={() => void account.syncNow()}>Synchroniser</button><button onClick={() => void account.refresh()}>Vérifier les droits</button><button className="secondary" onClick={() => void account.signOut()}>Se déconnecter</button></div><p><Link href="/suppression-compte">Supprimer mon compte ELSATIA</Link></p></> : <form onSubmit={submit}><h2>Se connecter</h2><p>Utilisez le même compte que dans les autres applications ELSATIA.</p><label><span>Adresse e-mail</span><input type="email" autoComplete="email" required value={email} onChange={(event) => setEmail(event.target.value)} /></label><label><span>Mot de passe</span><input type="password" autoComplete="current-password" required value={password} onChange={(event) => setPassword(event.target.value)} /></label><button disabled={!account.configured || account.status === "loading"}>{account.status === "loading" ? "Connexion…" : "Se connecter"}</button><button type="button" className="secondary" disabled={!email.trim()} onClick={() => void account.requestPasswordReset(email).then(() => setNotice("E-mail de récupération envoyé.")).catch((caught) => setError(caught instanceof Error ? caught.message : "Demande impossible."))}>Mot de passe oublié</button><p><a href={EXTERNAL_URLS.accountCreation} target="_blank" rel="noreferrer">Créer un compte ELSATIA</a></p>{!account.configured && <p className="account-warning">Compte cloud non configuré dans cet environnement local. Tools Free reste opérationnel.</p>}{notice && <p role="status">{notice}</p>}{error && <p className="account-error" role="alert">{error}</p>}</form>}
    <nav aria-label="Informations légales"><a href={EXTERNAL_URLS.privacy} target="_blank" rel="noreferrer">Confidentialité</a> · <a href={EXTERNAL_URLS.terms} target="_blank" rel="noreferrer">CGU</a> · <a href={EXTERNAL_URLS.support} target="_blank" rel="noreferrer">Assistance</a></nav>
  </section><MonetizationPanel /></main>;
}
