"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import type { AccessContext } from "@/lib/access";
import { hasCapability } from "@/lib/access";
import type { ToolDefinition } from "@/lib/catalog";
import { getCategory } from "@/lib/categories";
import { buildProjectDocument, projectFileName } from "@/lib/exports/document";
import { exportProjectPdf } from "@/lib/exports/pdf";
import { printProjectDocument } from "@/lib/exports/print";
import { downloadBlob, shareBlob } from "@/lib/exports/share";
import { exportProjectSvg } from "@/lib/exports/svg";
import type { ShapeGeometry } from "@/lib/geometry/shape-model";
import { createToolProject, type ToolProject } from "@/lib/projects/model";
import { createProjectRepository, projectStorageScope } from "@/lib/projects/repository";
import { ProjectService } from "@/lib/projects/service";
import { executeProTool, proToolDefaults, proToolFields, type ProToolId } from "@/lib/pro-engine";
import { AdvancedPlan } from "./AdvancedPlan";
import { Brand } from "./HomeDashboard";
import { ProFeaturePreview } from "./ProFeaturePreview";
import { ToolIcon } from "./ToolIcon";
import { useAccount } from "./AccountProvider";

type Tab = "result" | "plan" | "points" | "steps";
type SaveDraft = { name: string; siteName: string; notes: string };

export function ProCalculatorWorkspace({ tool }: { tool: ToolDefinition }) {
  const { access, projectMutations, activeCompany } = useAccount();
  if (!hasCapability(access, "advanced-tracing")) return <LockedProWorkspace tool={tool} />;
  return <UnlockedProWorkspace tool={tool} access={access} projectMutations={projectMutations} companyId={activeCompany?.id ?? null} />;
}

function LockedProWorkspace({ tool }: { tool: ToolDefinition }) {
  return <main className="calculator-page"><header className="calculator-header shell"><Brand /><Link className="all-tools" href="/">Tous les outils <span>×</span></Link></header><div className="tool-hero"><div className="shell"><Link href="/" className="breadcrumb">← Accueil</Link><div className="tool-heading"><span className="tool-icon large"><ToolIcon id={tool.id} size={36} /></span><div><p className="eyebrow">{getCategory(tool.categoryId).name} · PRO</p><h1>{tool.name}</h1><p>{tool.description}</p></div></div></div></div><section className="shell locked-pro"><div className="locked-pro-copy"><span className="pro-badge">TOOLS PRO</span><h2>Concevez et reproduisez cette forme sur chantier</h2><p>L’outil complet fournit la géométrie exacte, les centres, rayons, axes, points de construction, plan coté et étapes de traçage. Cet aperçu ne lance aucun calcul et n’affiche aucune fausse cote.</p><ul><li>Calcul local et hors ligne</li><li>Plan fondé sur les mesures saisies</li><li>Droits Pro vérifiés par le compte ELSATIA</li></ul><Link href="/compte">Se connecter ou vérifier les droits</Link></div><div className="locked-pro-preview" aria-label="Aperçu non calculé"><ToolIcon id={tool.id} size={100} /><strong>{tool.name}</strong><small>Exemple visuel non coté - aucune géométrie calculée</small></div></section><section className="shell pro-preview-section locked-export-previews"><ProFeaturePreview name="Enregistrer ce projet" description="Conservez localement les paramètres pour recalculer le plan plus tard." capability="saved-projects" preview="TOOLS PRO · compte facultatif pour Free" /><ProFeaturePreview name="Exporter PDF ou SVG" description="Créez une fiche chantier et un plan vectoriel sans service distant." capability="export-pdf" preview="PRO · génération hors ligne" /></section></main>;
}

function UnlockedProWorkspace({ tool, access, projectMutations, companyId }: { tool: ToolDefinition; access: AccessContext; projectMutations: import("@/lib/projects/service").ProjectMutationSink; companyId: string | null }) {
  const id = tool.id as ProToolId;
  const [values, setValues] = useState(proToolDefaults[id]); const [tab, setTab] = useState<Tab>("result"); const [stepIndex, setStepIndex] = useState(0);
  const service = useMemo(() => typeof indexedDB === "undefined" ? null : new ProjectService(createProjectRepository(projectStorageScope(companyId)), undefined, undefined, projectMutations), [companyId, projectMutations]); const [project, setProject] = useState<ToolProject | null>(null); const [feedback, setFeedback] = useState(""); const [showSave, setShowSave] = useState(false);
  const [draft, setDraft] = useState<SaveDraft>({ name: tool.name, siteName: "", notes: "" }); const [baseline, setBaseline] = useState(JSON.stringify(proToolDefaults[id]));
  useEffect(() => {
    if (!service) return; const projectId = new URLSearchParams(window.location.search).get("project"); if (!projectId) return;
    void service.get(projectId).then((loaded) => { if (!loaded) { setFeedback("Projet introuvable sur cet appareil."); return; } if (loaded.toolId !== id) { setFeedback("Ce projet appartient à un autre outil."); return; } setProject(loaded); setValues(loaded.inputParameters); setBaseline(JSON.stringify(loaded.inputParameters)); setDraft({ name: loaded.name, siteName: loaded.siteName ?? "", notes: loaded.notes ?? "" }); setFeedback("Projet chargé et géométrie recalculée."); }).catch((error: unknown) => setFeedback(error instanceof Error ? error.message : "Projet impossible à charger."));
  }, [id, service]);
  const evaluation = useMemo(() => { try { return { value: executeProTool(tool, values), error: "" }; } catch (error) { return { value: null, error: error instanceof Error ? error.message : "Valeurs invalides." }; } }, [tool, values]);
  const fields = proToolFields[id].filter((field) => !field.showWhen || field.showWhen.values.includes(values[field.showWhen.key])); const currentStep = evaluation.value?.geometry.steps[stepIndex]; const dirty = Boolean(project) && (JSON.stringify(values) !== baseline || draft.name !== project?.name || draft.siteName !== (project?.siteName ?? "") || draft.notes !== (project?.notes ?? ""));
  function changeValue(key: string, value: string) { setValues((current) => ({ ...current, [key]: value })); setStepIndex(0); }
  async function createProject(saveAs = false) { if (!service || !evaluation.value) return; try { const created = await service.create({ name: draft.name || tool.name, siteName: draft.siteName || undefined, notes: draft.notes || undefined, toolId: id, inputParameters: values }); setProject(created); setBaseline(JSON.stringify(values)); setShowSave(false); setFeedback(saveAs ? "Nouvelle copie enregistrée localement." : "Projet enregistré localement."); window.history.replaceState(null, "", `${window.location.pathname}?project=${encodeURIComponent(created.id)}`); } catch (error) { setFeedback(error instanceof Error ? error.message : "Enregistrement impossible."); } }
  async function saveProject() { if (!service || !project || !evaluation.value) return; try { const saved = await service.save(project, { name: draft.name, siteName: draft.siteName || undefined, notes: draft.notes || undefined, inputParameters: values }); setProject(saved); setBaseline(JSON.stringify(values)); setFeedback("Modifications enregistrées."); } catch (error) { setFeedback(error instanceof Error ? error.message : "Enregistrement impossible."); } }
  function reloadProject() { if (!project) return; setValues(project.inputParameters); setDraft({ name: project.name, siteName: project.siteName ?? "", notes: project.notes ?? "" }); setBaseline(JSON.stringify(project.inputParameters)); setFeedback("Modifications annulées."); }
  function currentDocument() { const source = project ? { ...project, name: draft.name || project.name, siteName: draft.siteName || undefined, notes: draft.notes || undefined, inputParameters: values, updatedAt: new Date().toISOString() } : createToolProject({ name: draft.name || tool.name, siteName: draft.siteName || undefined, notes: draft.notes || undefined, toolId: id, inputParameters: values }); return buildProjectDocument(source); }
  async function exportSvg() { try { const document = currentDocument(); const outcome = await downloadBlob(new Blob([exportProjectSvg(document)], { type: "image/svg+xml;charset=utf-8" }), projectFileName(document, "svg")); setFeedback(outcome.kind === "native" ? "Plan SVG enregistré dans Documents/ELSATIA Tools." : "Plan SVG vectoriel généré."); } catch (error) { setFeedback(error instanceof Error ? error.message : "Export impossible."); } }
  async function exportPdf() { try { const document = currentDocument(); const outcome = await downloadBlob(new Blob([exportProjectPdf(document)], { type: "application/pdf" }), projectFileName(document, "pdf")); setFeedback(outcome.kind === "native" ? "Fiche PDF enregistrée dans Documents/ELSATIA Tools." : "Fiche chantier PDF générée."); } catch (error) { setFeedback(error instanceof Error ? error.message : "Export impossible."); } }
  async function sharePdf() { try { const document = currentDocument(); const outcome = await shareBlob(new Blob([exportProjectPdf(document)], { type: "application/pdf" }), projectFileName(document, "pdf"), `Plan ELSATIA Tools - ${document.project.name}`, `${tool.name}${document.project.siteName ? ` - ${document.project.siteName}` : ""}`); setFeedback(outcome === "download" ? "Partage indisponible : PDF téléchargé." : "Feuille de partage ouverte."); } catch (error) { setFeedback(error instanceof Error ? error.message : "Partage impossible."); } }
  function printPlan() { try { printProjectDocument(currentDocument()); } catch (error) { setFeedback(error instanceof Error ? error.message : "Impression impossible."); } }
  return <main className="calculator-page pro-calculator"><header className="calculator-header shell"><Brand /><nav className="calculator-nav"><Link href="/projets">Mes projets</Link><Link className="all-tools" href="/">Tous les outils <span>×</span></Link></nav></header><div className="tool-hero"><div className="shell"><Link href="/" className="breadcrumb">← Accueil</Link><div className="tool-heading"><span className="tool-icon large"><ToolIcon id={tool.id} size={36} /></span><div><p className="eyebrow">{getCategory(tool.categoryId).name} · TOOLS PRO</p><h1>{tool.name}</h1><p>{tool.description}</p></div></div></div></div>
    <section className="shell project-toolbar"><div><p className="eyebrow">{project ? "PROJET OUVERT" : "TRACÉ NON ENREGISTRÉ"}</p><strong>{project ? draft.name : "Nouveau projet"}</strong>{dirty && <span className="dirty-state">Modifications non enregistrées</span>}</div><div>{project ? <><button onClick={() => void saveProject()} disabled={!dirty || !evaluation.value}>Enregistrer</button><button onClick={reloadProject} disabled={!dirty}>Annuler</button><button onClick={() => setShowSave(true)}>Enregistrer sous</button></> : <button onClick={() => setShowSave(true)}>Enregistrer le projet</button>}</div></section>
    {showSave && <section className="shell save-project-panel"><label><span>Nom du projet</span><input autoFocus value={draft.name} maxLength={100} onChange={(event) => setDraft((current) => ({ ...current, name: event.target.value }))} /></label><label><span>Chantier facultatif</span><input value={draft.siteName} maxLength={100} onChange={(event) => setDraft((current) => ({ ...current, siteName: event.target.value }))} /></label><label><span>Note locale</span><textarea value={draft.notes} maxLength={1000} onChange={(event) => setDraft((current) => ({ ...current, notes: event.target.value }))} /></label><div><button onClick={() => setShowSave(false)}>Fermer</button><button onClick={() => void createProject(Boolean(project))} disabled={!draft.name.trim() || !evaluation.value}>{project ? "Créer la copie" : "Enregistrer"}</button></div></section>}
    <p className="shell project-feedback" role="status" aria-live="polite">{feedback}</p>
    <div className="shell calculator-grid pro-grid"><section className="input-panel"><div className="panel-heading"><span>1</span><div><p className="eyebrow">GÉOMÉTRIE EN MM</p><h2>Définissez l’ouvrage</h2></div></div><div className="fields">{fields.map((field, index) => <label className="field" key={field.key}><span>{field.label}</span><div>{field.inputType === "select" ? <select value={values[field.key]} onChange={(event) => changeValue(field.key, event.target.value)}>{field.options?.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select> : <input inputMode="decimal" enterKeyHint={index === fields.length - 1 ? "done" : "next"} type="number" step={field.step ?? "any"} value={values[field.key]} onChange={(event) => changeValue(field.key, event.target.value)} />}{field.unit && <b>{field.unit === "mm" ? values.unit ?? "mm" : field.unit}</b>}</div>{field.hint && <small>{field.hint}</small>}</label>)}</div><button className="reset-button" onClick={() => { setValues(proToolDefaults[id]); setStepIndex(0); }}>↺ Réinitialiser l’exemple</button></section>
      <section className="output-panel pro-output"><div className="result-tabs pro-tabs">{(["result", "plan", "points", "steps"] as Tab[]).map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item === "result" ? "Résultats" : item === "plan" ? "Plan coté" : item === "points" ? "Coordonnées" : "Mode chantier"}</button>)}</div>
        {evaluation.error && <div className="calculation-error"><strong>Géométrie impossible</strong><p>{evaluation.error}</p></div>}
        {evaluation.value && tab === "result" && <div className="result-content"><p className="eyebrow">GÉOMÉTRIE CALCULÉE</p><div className="result-lines">{evaluation.value.results.map((line) => <div key={line.label} className={line.primary ? "primary" : ""}><span>{line.label}</span><strong>{line.value}</strong></div>)}</div><p className="result-note">ⓘ {evaluation.value.note}</p><button className="next-tab" onClick={() => setTab("plan")}>Voir le plan coté <span>→</span></button></div>}
        {evaluation.value && tab === "plan" && <div className="diagram-content"><AdvancedPlan model={evaluation.value.geometry} /><div className="diagram-legend"><span><i className="solid" /> Géométrie calculée</span><span><i /> Construction</span></div></div>}
        {evaluation.value && tab === "points" && <Coordinates model={evaluation.value.geometry} />}
        {evaluation.value && tab === "steps" && currentStep && <div className="site-step-mode"><div className="step-progress"><span>Étape {stepIndex + 1}/{evaluation.value.geometry.steps.length}</span><progress value={stepIndex + 1} max={evaluation.value.geometry.steps.length} /></div><p className="eyebrow">MODE CHANTIER</p><h2>{currentStep.title}</h2><p className="step-instruction">{currentStep.instruction}</p>{currentStep.measurements.length > 0 && <div className="step-measures"><strong>Mesure{currentStep.measurements.length > 1 ? "s" : ""}</strong>{currentStep.measurements.map((value) => <span key={value}>{value}</span>)}</div>}{currentStep.controlId && <p className="step-control">✓ {evaluation.value.geometry.controls.find((item) => item.id === currentStep.controlId)?.label}</p>}<div className="step-actions"><button disabled={stepIndex === 0} onClick={() => setStepIndex((value) => Math.max(0, value - 1))}>← Précédent</button><button onClick={() => stepIndex === evaluation.value!.geometry.steps.length - 1 ? setTab("plan") : setStepIndex((value) => value + 1)}>{stepIndex === evaluation.value.geometry.steps.length - 1 ? "Plan complet" : "Suivant →"}</button></div></div>}
      </section></div>
    {evaluation.value && <section className="shell export-toolbar"><div><p className="eyebrow">DOCUMENTS CHANTIER</p><h2>Exporter, imprimer ou partager</h2><p>Génération locale. Aucune donnée n’est transmise à ELSATIA.</p></div><div>{hasCapability(access, "export-pdf") && <button onClick={() => void exportPdf()}>Télécharger PDF</button>}{hasCapability(access, "export-svg") && <button onClick={() => void exportSvg()}>Télécharger SVG</button>}{hasCapability(access, "print-plan") && <button onClick={printPlan}>Imprimer</button>}{hasCapability(access, "native-share") && <button onClick={() => void sharePdf()}>Partager</button>}</div></section>}
  </main>;
}

function Coordinates({ model }: { model: ShapeGeometry }) {
  const origin = model.referenceFrame.origin;
  return <div className="coordinates-content"><p className="eyebrow">POINTS D’IMPLANTATION</p><h2>Coordonnées chantier</h2><p>Repère pièce : origine P0 lorsqu’elle existe. Repère forme : origine au centre O.</p><div className="coordinate-table" role="table"><div role="row" className="coordinate-head"><span>Point</span><span>X pièce</span><span>Y pièce</span><span>X depuis O</span><span>Y depuis O</span></div>{model.points.filter((item, index) => index < 18).map((item) => <div role="row" key={item.id}><strong>{item.id}</strong><span>{Math.round(item.x)} mm</span><span>{Math.round(item.y)} mm</span><span>{Math.round(item.x - origin.x)} mm</span><span>{Math.round(item.y - origin.y)} mm</span></div>)}</div><div className="site-controls coordinate-controls"><strong>Contrôles indépendants</strong>{model.controls.map((control) => <p key={control.id}>✓ {control.label} : {new Intl.NumberFormat("fr-FR", { maximumFractionDigits: 1 }).format(control.value)} {control.unit}</p>)}</div></div>;
}
