import { notFound } from "next/navigation";
import Link from "next/link";
import { creerVersionTarifaireAction } from "@/app/actions/tarification";
import { createClient } from "@/lib/supabase/server";
import { estPlateformeAdmin } from "@/lib/plateforme";

const champ = "rounded-lg border border-neutral-300 px-3 py-2 dark:border-neutral-700 dark:bg-neutral-900";

export default async function TarificationPlateformePage({ searchParams }: { searchParams: Promise<{ error?: string; succes?: string }> }) {
  if (!(await estPlateformeAdmin())) notFound();
  const messages = await searchParams;
  const supabase = await createClient();
  const [{ data: plans }, { data: historique }] = await Promise.all([
    supabase.from("plans_abonnement").select("id,code,version,nom,prix_mensuel_ht,prix_annuel_ht,utilisateurs_inclus,administrateurs_inclus,operations_ia_incluses,stockage_go_inclus,actif,valide_du,valide_au").order("code").order("version", { ascending: false }),
    supabase.from("historique_tarification").select("id,action,motif,created_at,nouveau").order("created_at", { ascending: false }).limit(30),
  ]);
  return <main className="p-4 sm:p-8"><div className="mx-auto max-w-7xl space-y-6">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-neutral-500">Plateforme</p><h1 className="text-2xl font-bold">Tarification versionnée</h1><p className="mt-1 text-sm text-neutral-500">Une nouvelle version ne modifie jamais le prix contractuel des clients existants.</p></div><Link href="/plateforme" className="rounded-lg border px-4 py-2">Retour plateforme</Link></header>
    {messages.error ? <p className="rounded-lg bg-red-50 p-3 text-red-700">{messages.error}</p> : null}
    {messages.succes ? <p className="rounded-lg bg-green-50 p-3 text-green-700">Nouvelle version enregistrée et journalisée.</p> : null}
    <section className="overflow-x-auto rounded-2xl border"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-neutral-100 dark:bg-neutral-900"><tr>{["Offre","Version","Mensuel HT","Annuel HT","Comptes","Admins","IA/mois","Stockage","Validité"].map((titre)=><th key={titre} className="px-4 py-3">{titre}</th>)}</tr></thead><tbody>{(plans??[]).map((plan)=><tr key={plan.id} className="border-t"><td className="px-4 py-3 font-semibold">{plan.nom}{plan.actif?<span className="ml-2 rounded-full bg-green-100 px-2 py-0.5 text-xs text-green-800">Actif</span>:null}</td><td className="px-4 py-3">v{plan.version}</td><td className="px-4 py-3">{Number(plan.prix_mensuel_ht).toLocaleString("fr-FR")} €</td><td className="px-4 py-3">{Number(plan.prix_annuel_ht).toLocaleString("fr-FR")} €</td><td className="px-4 py-3">{plan.utilisateurs_inclus}</td><td className="px-4 py-3">{plan.administrateurs_inclus??"Illimité"}</td><td className="px-4 py-3">{Number(plan.operations_ia_incluses).toLocaleString("fr-FR")}</td><td className="px-4 py-3">{plan.stockage_go_inclus} Go</td><td className="px-4 py-3">{new Date(plan.valide_du).toLocaleDateString("fr-FR")}{plan.valide_au?` → ${new Date(plan.valide_au).toLocaleDateString("fr-FR")}`:""}</td></tr>)}</tbody></table></section>
    <section className="rounded-2xl border p-5"><h2 className="text-lg font-bold">Créer une nouvelle version</h2><p className="mt-1 text-sm text-amber-700">Cette action change le catalogue futur, jamais les contrats déjà verrouillés.</p><form action={creerVersionTarifaireAction} className="mt-4 grid gap-3 md:grid-cols-3"><select name="code" className={champ} required>{["mini","pro","business","entreprise","sur_mesure"].map(code=><option key={code} value={code}>{code}</option>)}</select><input name="nom" placeholder="Nom public" className={champ} required/><input name="valide_du" type="date" className={champ} required/><input name="prix_mensuel_ht" type="number" min="0" step="0.01" placeholder="Prix mensuel HT" className={champ} required/><input name="prix_annuel_ht" type="number" min="0" step="0.01" placeholder="Prix annuel HT" className={champ} required/><input name="utilisateurs_inclus" type="number" min="0" placeholder="Comptes inclus" className={champ} required/><input name="administrateurs_inclus" type="number" min="0" placeholder="Administrateurs inclus" className={champ} required/><input name="operations_ia_incluses" type="number" min="0" placeholder="Opérations IA / mois" className={champ} required/><input name="stockage_go_inclus" type="number" min="0" step="0.01" placeholder="Stockage Go" className={champ} required/><textarea name="motif" placeholder="Motif obligatoire de la nouvelle version" minLength={5} className={`${champ} md:col-span-2`} required/><button className="rounded-lg bg-[#0d1b2a] px-4 py-2 font-semibold text-white">Publier la version</button></form></section>
    <section className="rounded-2xl border p-5"><h2 className="text-lg font-bold">Historique immuable</h2><div className="mt-3 space-y-2">{(historique??[]).map((event)=><div key={event.id} className="rounded-lg bg-neutral-50 p-3 text-sm dark:bg-neutral-900"><strong>{event.action}</strong> · {new Date(event.created_at).toLocaleString("fr-FR")}<p className="text-neutral-500">{event.motif??"Sans motif"}</p></div>)}</div></section>
  </div></main>;
}
