import { createClient } from "@/lib/supabase/server";
import { getContexteEntreprise } from "@/lib/entreprise";
import { permissionsUtilisateur } from "@/lib/permissions";
import { euros } from "@/lib/devis";
import { SearchableSelect } from "@/components/SearchableSelect";
import { creerAppelOffresAction,changerStatutAppelOffresAction } from "@/app/actions/appels-offres";

const statuts:Record<string,string>={a_etudier:"À étudier",en_preparation:"En préparation",depose:"Déposé",gagne:"Gagné",perdu:"Perdu",abandonne:"Abandonné"};
const relation=<T,>(v:T|T[]|null):T|null=>Array.isArray(v)?v[0]??null:v;

export default async function AppelsOffresPage({searchParams}:{searchParams:Promise<{error?:string;success?:string}>}){
  const messages=await searchParams;const ctx=await getContexteEntreprise();const supabase=await createClient();const permissions=await permissionsUtilisateur(ctx);
  const peutGerer=permissions===null||permissions.includes("gerer_appels_offres");
  const [{data:appels},{data:clients},{data:chantiers}]=await Promise.all([
    supabase.from("appels_offres").select("*,client:clients(nom,prenom,societe),chantier:chantiers(nom)").eq("entreprise_id",ctx.entrepriseId).order("date_limite",{ascending:true,nullsFirst:false}),
    supabase.from("clients").select("id,nom,prenom,societe").eq("entreprise_id",ctx.entrepriseId).eq("statut","actif").order("nom"),
    supabase.from("chantiers").select("id,nom,reference_interne").eq("entreprise_id",ctx.entrepriseId).not("statut","in","(archive,annule)").order("nom")]);
  return <main className="p-3 sm:p-8"><div className="mx-auto max-w-6xl space-y-6"><div><h1 className="text-xl font-semibold">Appels d’offres</h1><p className="text-sm text-neutral-500">Détection, préparation, dépôt et suivi commercial jusqu’à la décision.</p></div>
    {messages.error&&<p className="rounded bg-red-50 p-3 text-sm text-red-700">{messages.error}</p>}{messages.success&&<p className="rounded bg-green-50 p-3 text-sm text-green-700">{messages.success}</p>}
    {peutGerer&&<form action={creerAppelOffresAction} className="grid gap-3 rounded-lg border p-4 md:grid-cols-2 lg:grid-cols-4"><h2 className="font-semibold md:col-span-2 lg:col-span-4">Nouvel appel d’offres</h2><input name="reference" placeholder="Référence (automatique si vide)" className="rounded border px-3 py-2 text-sm"/><input name="titre" required placeholder="Intitulé du marché *" className="rounded border px-3 py-2 text-sm"/><SearchableSelect name="client_id" options={(clients??[]).map(c=>({value:c.id,label:c.societe||`${c.prenom??""} ${c.nom}`.trim()}))} placeholder="Rechercher un client…" emptyLabel="Sans client"/><SearchableSelect name="chantier_id" options={(chantiers??[]).map(c=>({value:c.id,label:`${c.nom} · ${c.reference_interne}`}))} placeholder="Rechercher un chantier…" emptyLabel="Sans chantier"/><label className="text-xs text-neutral-500">Date et heure limite<input name="date_limite" type="datetime-local" className="mt-1 w-full rounded border px-3 py-2 text-sm"/></label><label className="text-xs text-neutral-500">Montant estimé HT<input name="montant_estime_ht" type="number" min="0" step="0.01" className="mt-1 w-full rounded border px-3 py-2 text-sm"/></label><input name="source_url" type="url" placeholder="Lien vers la plateforme acheteur" className="rounded border px-3 py-2 text-sm lg:col-span-2"/><textarea name="notes" rows={2} placeholder="Pièces attendues, critères, responsable…" className="rounded border px-3 py-2 text-sm md:col-span-2 lg:col-span-4"/><button className="rounded bg-[#0d1b2a] px-4 py-2 text-sm font-semibold text-white md:col-span-2 lg:col-span-4">Ajouter au suivi</button></form>}
    <div className="grid gap-3">{(appels??[]).map(ao=>{const client=relation(ao.client as {nom:string;prenom:string|null;societe:string|null}|{nom:string;prenom:string|null;societe:string|null}[]|null);const chantier=relation(ao.chantier as {nom:string}|{nom:string}[]|null);return <article key={ao.id} className="grid gap-3 rounded-lg border p-4 lg:grid-cols-[1fr_auto]"><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-xs text-neutral-500">{ao.reference}</span><span className="rounded-full bg-neutral-100 px-2 py-1 text-xs">{statuts[ao.statut]}</span></div><h2 className="mt-2 font-semibold">{ao.titre}</h2><p className="mt-1 text-sm text-neutral-500">{client?(client.societe||`${client.prenom??""} ${client.nom}`.trim()):"Sans client"}{chantier?` · ${chantier.nom}`:""}</p><div className="mt-3 flex flex-wrap gap-4 text-sm"><span>Limite : <strong>{ao.date_limite?new Date(ao.date_limite).toLocaleString("fr-FR"):"Non définie"}</strong></span><span>Estimation : <strong>{ao.montant_estime_ht===null?"—":euros(ao.montant_estime_ht)}</strong></span>{ao.source_url&&<a href={ao.source_url} target="_blank" rel="noreferrer" className="text-blue-700 hover:underline">Ouvrir la consultation ↗</a>}</div>{ao.notes&&<p className="mt-3 whitespace-pre-wrap rounded bg-neutral-50 p-3 text-sm dark:bg-neutral-900">{ao.notes}</p>}</div>{peutGerer&&<form action={changerStatutAppelOffresAction.bind(null,ao.id)} className="flex items-end gap-2"><select name="statut" defaultValue={ao.statut} className="rounded border px-3 py-2 text-sm">{Object.entries(statuts).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button className="rounded border px-3 py-2 text-sm font-medium">Enregistrer</button></form>}</article>})}{!(appels??[]).length&&<p className="rounded border border-dashed p-10 text-center text-sm text-neutral-500">Aucun appel d’offres enregistré.</p>}</div>
  </div></main>;
}
