import Link from "next/link";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { estPlateformeAdmin } from "@/lib/plateforme";
import { isEmailLoginDisabled } from "@/lib/auth-mode";
import { genererSnapshotFacturationAction } from "@/app/actions/plateforme";

type Ligne = { employe_id: string; employe: string; poste: string | null; offre: string | null; statut: string; montant_compte_ht: number; nb_appareils: number; depassement_appareils: boolean; montant_depassement_ht: number; montant_ht: number; motif: string };
type Releve = { entreprise_id: string; entreprise_nom: string; mois: string; nombre_comptes: number; montant_ht: number; detail: Ligne[] };
const euros = (montant: number) => Number(montant).toLocaleString("fr-FR", { style: "currency", currency: "EUR" });

export default async function FacturationPlateformePage({ searchParams }: { searchParams: Promise<{ mois?: string; employe?: string; error?: string; succes?: string }> }) {
  if (!(await estPlateformeAdmin())) notFound();
  const params = await searchParams;
  const mois = /^\d{4}-\d{2}$/.test(params.mois ?? "") ? params.mois as string : new Date().toISOString().slice(0, 7);
  if (isEmailLoginDisabled()) return <main className="p-3 sm:p-8"><div className="mx-auto max-w-6xl space-y-4"><Link href="/plateforme" className="text-sm text-neutral-500">← Plateforme</Link><h1 className="text-xl font-semibold">Relevés mensuels des comptes</h1><p className="rounded bg-amber-50 p-4 text-sm text-amber-900">Les relevés nominatifs sont fermés en mode prototype. Ils seront disponibles avec le compte propriétaire authentifié.</p></div></main>;
  const supabase = await createClient();
  const { data, error } = await supabase.rpc("plateforme_releve_facturation", { p_mois: `${mois}-01` });
  const releves = (data ?? []) as Releve[];
  const employeSelectionne = params.employe
    ? releves.flatMap((releve) => releve.detail ?? []).find((ligne) => ligne.employe_id === params.employe) ?? null
    : null;
  const total = releves.reduce((somme, releve) => somme + Number(releve.montant_ht), 0);
  const comptes = releves.reduce((somme, releve) => somme + Number(releve.nombre_comptes), 0);
  return <main className="p-3 sm:p-8"><div className="mx-auto max-w-6xl space-y-6">
    <div><Link href="/plateforme" className="text-sm text-neutral-500">← Plateforme</Link><h1 className="mt-2 text-xl font-semibold">Relevés mensuels des comptes</h1><p className="text-sm text-neutral-500">Photo figée des comptes ouverts ou en pause. Deux appareils sont inclus ; tout compte dépassant cette limite est facturé une seconde fois au tarif de son poste.</p></div>
    {(params.error || error) && <p className="rounded bg-red-50 p-3 text-sm text-red-700">{params.error ?? error?.message}</p>}{params.succes && <p className="rounded bg-green-50 p-3 text-sm text-green-700">{params.succes}</p>}
    <div className="grid gap-3 sm:grid-cols-3"><div className="rounded border p-4"><p className="text-xs text-neutral-500">Mois</p><strong>{mois}</strong></div><div className="rounded border p-4"><p className="text-xs text-neutral-500">Comptes facturés</p><strong className="text-xl">{comptes}</strong></div><div className="rounded border p-4"><p className="text-xs text-neutral-500">Total HT</p><strong className="text-xl">{euros(total)}</strong></div></div>
    <div className="flex flex-wrap items-end gap-3 rounded border p-4"><form method="get" className="flex items-end gap-2"><label className="text-xs text-neutral-500">Consulter le mois<input name="mois" type="month" defaultValue={mois} className="mt-1 block rounded border px-3 py-2 text-sm"/></label><button className="rounded border px-3 py-2 text-sm">Afficher</button></form><form action={genererSnapshotFacturationAction}><input type="hidden" name="mois" value={mois}/><input type="hidden" name="retour" value={`/plateforme/facturation?mois=${mois}`}/><button className="rounded bg-[#0d1b2a] px-3 py-2 text-sm text-white">Figer les comptes de ce mois</button></form></div>
    <div className="space-y-3">{releves.map((releve) => <details key={releve.entreprise_id} open={Boolean(employeSelectionne && releve.detail?.some((ligne) => ligne.employe_id === employeSelectionne.employe_id)) || undefined} className="rounded-lg border p-4"><summary className="cursor-pointer"><span className="flex items-center justify-between gap-3"><strong>{releve.entreprise_nom}</strong><span>{releve.nombre_comptes} compte(s) facturé(s) · <strong>{euros(releve.montant_ht)}</strong></span></span></summary><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="text-left text-xs uppercase text-neutral-500"><tr><th className="py-2">Employé</th><th>Poste</th><th>Appareils</th><th>Statut</th><th className="text-right">Compte</th><th className="text-right">Supplément</th><th className="text-right">Total HT</th></tr></thead><tbody>{(releve.detail ?? []).map((ligne) => { const selectionnee = employeSelectionne?.employe_id === ligne.employe_id; return <tr key={ligne.employe_id} className={`border-t ${selectionnee ? "bg-blue-50" : "hover:bg-neutral-50"}`}><td className="py-2"><Link href={`/plateforme/facturation?mois=${mois}&employe=${ligne.employe_id}#detail-employe`} className="font-semibold text-blue-700 underline-offset-2 hover:underline" aria-current={selectionnee ? "true" : undefined}>{ligne.employe}</Link></td><td>{ligne.poste ?? "Sans poste"}</td><td><span className={ligne.depassement_appareils?"font-semibold text-red-700":""}>{ligne.nb_appareils} / 2</span></td><td>{ligne.statut}</td><td className="text-right font-mono">{euros(ligne.montant_compte_ht)}</td><td className="text-right font-mono">{ligne.depassement_appareils?euros(ligne.montant_depassement_ht):"—"}</td><td className="text-right font-mono font-semibold">{euros(ligne.montant_ht)}</td></tr>; })}</tbody></table><p className="mt-2 text-xs text-neutral-500">Sélectionnez le nom d’un employé pour afficher le détail de son compte.</p></div></details>)}</div>
    {employeSelectionne && <section id="detail-employe" className="scroll-mt-4 rounded-xl border-2 border-blue-200 bg-blue-50/40 p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-blue-700">Détail du compte sélectionné</p><h2 className="mt-1 text-lg font-semibold">{employeSelectionne.employe}</h2><p className="text-sm text-neutral-600">{employeSelectionne.poste ?? "Sans poste"}{employeSelectionne.offre ? ` · offre ${employeSelectionne.offre}` : ""}</p></div><Link href={`/plateforme/facturation?mois=${mois}`} className="rounded border bg-white px-3 py-1.5 text-xs font-medium">Fermer le détail</Link></div><dl className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-lg border bg-white p-3"><dt className="text-xs text-neutral-500">État du compte</dt><dd className="mt-1 font-semibold capitalize">{employeSelectionne.statut}</dd></div><div className="rounded-lg border bg-white p-3"><dt className="text-xs text-neutral-500">Appareils sur le mois</dt><dd className={`mt-1 font-semibold ${employeSelectionne.depassement_appareils ? "text-red-700" : "text-green-700"}`}>{employeSelectionne.nb_appareils} appareil(s) · 2 inclus</dd></div><div className="rounded-lg border bg-white p-3"><dt className="text-xs text-neutral-500">Tarif du compte</dt><dd className="mt-1 font-semibold">{euros(employeSelectionne.montant_compte_ht)} HT</dd></div><div className="rounded-lg border bg-white p-3"><dt className="text-xs text-neutral-500">Total facturé</dt><dd className="mt-1 text-lg font-bold">{euros(employeSelectionne.montant_ht)} HT</dd></div></dl><div className={`mt-3 rounded-lg border p-3 text-sm ${employeSelectionne.depassement_appareils ? "border-red-200 bg-red-50 text-red-900" : "border-green-200 bg-green-50 text-green-900"}`}>{employeSelectionne.depassement_appareils ? <><strong>Dépassement facturé : {euros(employeSelectionne.montant_depassement_ht)} HT.</strong><p className="mt-1">Ce compte a dépassé les deux appareils inclus pendant le mois et compte donc comme un employé supplémentaire au tarif de son poste.</p></> : <><strong>Aucun supplément appareil.</strong><p className="mt-1">Le compte reste dans la limite des deux appareils inclus.</p></>}</div><p className="mt-3 text-xs text-neutral-500">Motif du relevé : {employeSelectionne.motif.replaceAll("_", " ")}.</p></section>}
  </div></main>;
}
