import { createClient } from "@/lib/supabase/server";
import { getContexteEntreprise } from "@/lib/entreprise";
import { creerArticleStockAction, creerMouvementStockAction } from "@/app/actions/stock";
import { euros } from "@/lib/devis";
const input = "rounded-md border border-neutral-300 px-2 py-1.5 text-sm dark:border-neutral-700 dark:bg-neutral-900";
const typeLabel: Record<string,string> = { entree: "Entrée", sortie: "Sortie chantier", ajustement_plus: "Ajustement +", ajustement_moins: "Ajustement -" };
const un = <T,>(v:T|T[]|null):T|null => Array.isArray(v) ? v[0] ?? null : v;
type Mouvement = { id:string; date:string; type:string; quantite:number; motif:string|null; article:{reference:string;designation:string;unite:string}|{reference:string;designation:string;unite:string}[]|null; chantier:{nom:string}|{nom:string}[]|null };

export default async function StockPage({ searchParams }:{ searchParams:Promise<{error?:string;succes?:string}> }) {
  const params=await searchParams; const ctx=await getContexteEntreprise(); const supabase=await createClient();
  const [{data:articles},{data:chantiers},{data:mouvementsData}] = await Promise.all([
    supabase.from("articles_stock").select("*").eq("entreprise_id",ctx.entrepriseId).eq("actif",true).order("designation"),
    supabase.from("chantiers").select("id,nom").eq("entreprise_id",ctx.entrepriseId).order("nom"),
    supabase.from("mouvements_stock").select("id,date,type,quantite,motif,article:articles_stock(reference,designation,unite),chantier:chantiers(nom)").eq("entreprise_id",ctx.entrepriseId).order("created_at",{ascending:false}).limit(30),
  ]);
  const mouvements=(mouvementsData??[]) as Mouvement[]; const alertes=(articles??[]).filter(a=>Number(a.quantite_stock)<=Number(a.seuil_alerte)); const valeur=(articles??[]).reduce((s,a)=>s+Number(a.quantite_stock)*Number(a.prix_achat_ht),0);
  return <main className="p-8"><div className="mx-auto max-w-6xl space-y-6"><div><h1 className="text-xl font-semibold">Stock</h1><p className="text-sm text-neutral-500">Fournitures disponibles, seuils d’alerte et consommations chantier.</p></div>
  {params.error&&<p className="rounded-md bg-red-50 px-3 py-2 text-sm text-red-700">{params.error}</p>}{params.succes&&<p className="rounded-md bg-green-50 px-3 py-2 text-sm text-green-700">Opération enregistrée.</p>}
  <div className="grid grid-cols-3 gap-3"><div className="rounded-md border p-4"><div className="text-xs text-neutral-500">Articles actifs</div><div className="font-mono text-xl font-semibold">{articles?.length??0}</div></div><div className="rounded-md border p-4"><div className="text-xs text-neutral-500">Alertes réapprovisionnement</div><div className="font-mono text-xl font-semibold text-amber-700">{alertes.length}</div></div><div className="rounded-md border p-4"><div className="text-xs text-neutral-500">Valeur d’achat estimée</div><div className="font-mono text-xl font-semibold">{euros(valeur)}</div></div></div>
  <div className="grid grid-cols-2 gap-4"><form action={creerArticleStockAction} className="space-y-3 rounded-md border p-4"><h2 className="font-semibold">Nouvel article</h2><div className="grid grid-cols-2 gap-2"><input name="reference" required placeholder="Référence" className={input}/><input name="designation" required placeholder="Désignation" className={input}/><input name="unite" defaultValue="u" placeholder="Unité" className={input}/><input name="emplacement" placeholder="Emplacement" className={input}/><input name="seuil_alerte" type="number" min="0" step="0.01" defaultValue="0" placeholder="Seuil" className={input}/><input name="prix_achat_ht" type="number" min="0" step="0.01" defaultValue="0" placeholder="Prix achat HT" className={input}/></div><button className="rounded-md bg-neutral-900 px-3 py-2 text-sm text-white">Créer l’article</button></form>
  <form action={creerMouvementStockAction} className="space-y-3 rounded-md border p-4"><h2 className="font-semibold">Nouveau mouvement</h2>{articles?.length?<><div className="grid grid-cols-2 gap-2"><select name="article_id" required className={input}>{articles.map(a=><option key={a.id} value={a.id}>{a.reference} · {a.designation} ({a.quantite_stock} {a.unite})</option>)}</select><select name="type" className={input}>{Object.entries(typeLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input name="quantite" type="number" min="0.01" step="0.01" required placeholder="Quantité" className={input}/><input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} className={input}/><select name="chantier_id" className={input}><option value="">Sans chantier</option>{chantiers?.map(c=><option key={c.id} value={c.id}>{c.nom}</option>)}</select><input name="motif" placeholder="Motif / bon de livraison" className={input}/></div><button className="rounded-md bg-neutral-900 px-3 py-2 text-sm text-white">Enregistrer le mouvement</button></>:<p className="text-sm text-neutral-500">Créez d’abord un article.</p>}</form></div>
  <div className="overflow-hidden rounded-md border"><table className="w-full text-sm"><thead className="bg-neutral-50 text-left text-xs uppercase text-neutral-500"><tr><th className="px-3 py-2">Référence</th><th className="px-3 py-2">Article</th><th className="px-3 py-2">Emplacement</th><th className="px-3 py-2 text-right">Stock</th><th className="px-3 py-2 text-right">Seuil</th><th className="px-3 py-2 text-right">Prix achat</th></tr></thead><tbody>{articles?.map(a=><tr key={a.id} className={`border-t ${Number(a.quantite_stock)<=Number(a.seuil_alerte)?"bg-amber-50":""}`}><td className="px-3 py-2 font-mono">{a.reference}</td><td className="px-3 py-2 font-medium">{a.designation}</td><td className="px-3 py-2 text-neutral-500">{a.emplacement??"—"}</td><td className="px-3 py-2 text-right font-mono">{a.quantite_stock} {a.unite}</td><td className="px-3 py-2 text-right font-mono">{a.seuil_alerte} {a.unite}</td><td className="px-3 py-2 text-right font-mono">{euros(a.prix_achat_ht)}</td></tr>)}</tbody></table></div>
  <section><h2 className="mb-2 font-semibold">Derniers mouvements</h2><div className="overflow-hidden rounded-md border"><table className="w-full text-sm"><tbody>{mouvements.map(m=>{const a=un(m.article),c=un(m.chantier);return <tr key={m.id} className="border-t first:border-0"><td className="px-3 py-2">{m.date}</td><td className="px-3 py-2 font-medium">{a?.reference} · {a?.designation}</td><td className="px-3 py-2">{typeLabel[m.type]}</td><td className="px-3 py-2 text-right font-mono">{m.quantite} {a?.unite}</td><td className="px-3 py-2 text-neutral-500">{c?.nom??m.motif??""}</td></tr>})}{!mouvements.length&&<tr><td className="px-3 py-6 text-center text-neutral-500">Aucun mouvement.</td></tr>}</tbody></table></div></section>
  </div></main>;
}
