import Link from "next/link";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getContexteEntreprise } from "@/lib/entreprise";
import { mettreOutilRebutAction, mouvementOutilAction } from "@/app/actions/outillage";
import { MOUVEMENT_OUTIL_LABELS, OUTIL_ETATS, OUTIL_STATUTS } from "@/lib/outillage";
import { euros } from "@/lib/devis";
import { ConfirmSubmitButton } from "@/components/ConfirmSubmitButton";
import { IdentificationCodeCard } from "@/components/IdentificationCodeCard";

const un=<T,>(v:T|T[]|null):T|null=>Array.isArray(v)?v[0]??null:v;
export default async function OutilPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string;success?:string}>}){
  const {id}=await params;const msg=await searchParams;const ctx=await getContexteEntreprise();const sb=await createClient();
  const [{data:o},{data:m},{data:employes},{data:chantiers},{data:depenses},{data:code}]=await Promise.all([
    sb.from("outils").select("*,employe:employes(prenom,nom),chantier:chantiers(nom)").eq("id",id).eq("entreprise_id",ctx.entrepriseId).maybeSingle(),
    sb.from("mouvements_outillage").select("*,employe:employes(prenom,nom),chantier:chantiers(nom)").eq("outil_id",id).eq("entreprise_id",ctx.entrepriseId).order("created_at",{ascending:false}),
    sb.from("employes").select("id,prenom,nom").eq("entreprise_id",ctx.entrepriseId).eq("statut","actif").order("nom"),
    sb.from("chantiers").select("id,nom").eq("entreprise_id",ctx.entrepriseId).not("statut","in",'(archive,annule)').order("nom"),
    sb.from("depenses_fournisseurs").select("id,numero_piece,date_piece,montant_ttc,statut,justificatif_storage_path,fournisseur:fournisseurs(nom)").eq("outil_id",id).eq("entreprise_id",ctx.entrepriseId).order("date_piece",{ascending:false}),
    sb.from("codes_identification").select("id,code").eq("entreprise_id",ctx.entrepriseId).eq("type_ressource","outil").eq("ressource_id",id).eq("actif",true).maybeSingle(),
  ]);
  if(!o)notFound();const action=mouvementOutilAction.bind(null,id);const st=OUTIL_STATUTS[o.statut]??OUTIL_STATUTS.disponible;const total=(depenses??[]).filter(d=>d.statut!=="annulee").reduce((s,d)=>s+Number(d.montant_ttc),0);
  return <main className="p-8"><div className="mx-auto max-w-4xl space-y-6">
    <div><Link href="/outillage" className="text-sm text-neutral-500 hover:underline">← Outillage</Link><h1 className="mt-1 text-xl font-semibold">{o.designation}</h1><p className="font-mono text-sm text-neutral-500">{o.reference}{o.numero_serie?` · série ${o.numero_serie}`:""}</p></div>
    {msg.error&&<p className="rounded bg-red-50 p-3 text-sm text-red-700">{msg.error}</p>}{msg.success&&<p className="rounded bg-green-50 p-3 text-sm text-green-700">{msg.success}</p>}
    {o.statut==="hors_service"&&<div className="rounded-lg border border-red-400 bg-red-50 p-4 text-sm text-red-900"><strong>Action requise :</strong> cet outil est indisponible. Envoyez-le en maintenance ou déclarez-le irréparable.</div>}
    {o.statut==="rebut"&&<div className="rounded bg-neutral-900 p-4 text-sm text-white">Outil retiré définitivement des disponibilités{o.motif_rebut?` · ${o.motif_rebut}`:""}.</div>}
    <section className="grid gap-3 sm:grid-cols-4"><div className="rounded border p-4"><p className="text-xs text-neutral-500">Statut</p><p style={{color:st.couleur}} className="font-semibold">{st.label}</p></div><div className="rounded border p-4"><p className="text-xs text-neutral-500">État</p><p>{OUTIL_ETATS[o.etat]}</p></div><div className="rounded border p-4"><p className="text-xs text-neutral-500">Prochaine vérification</p><p>{o.prochaine_verification??"—"}</p></div><div className="rounded border p-4"><p className="text-xs text-neutral-500">Coûts facturés</p><p className="text-xl font-semibold">{euros(total)}</p></div></section>
    {code&&<IdentificationCodeCard id={code.id} code={code.code} label="Étiquette QR de l’outil"/>}
    {o.statut!=="rebut"&&<form action={action} className="grid gap-3 rounded border p-4 sm:grid-cols-2"><h2 className="font-semibold sm:col-span-2">Enregistrer un mouvement</h2><select name="type" className="rounded border px-3 py-2 text-sm">{o.statut==="disponible"&&<option value="affectation">Affecter</option>}{o.statut==="affecte"&&<option value="retour">Retour</option>}{!["maintenance","perdu"].includes(o.statut)&&<option value="maintenance">Envoyer en réparation / maintenance</option>}{["maintenance","hors_service"].includes(o.statut)&&<option value="remise_service">Remettre en service</option>}{o.statut!=="perdu"&&<option value="hors_service">Mettre hors service</option>}{o.statut!=="perdu"&&<option value="perte">Déclarer perdu</option>}</select><select name="etat" defaultValue={o.etat} className="rounded border px-3 py-2 text-sm">{Object.entries(OUTIL_ETATS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select name="employe_id" className="rounded border px-3 py-2 text-sm"><option value="">Sans employé</option>{employes?.map(e=><option key={e.id} value={e.id}>{e.prenom} {e.nom}</option>)}</select><select name="chantier_id" className="rounded border px-3 py-2 text-sm"><option value="">Sans chantier</option>{chantiers?.map(c=><option key={c.id} value={c.id}>{c.nom}</option>)}</select><input name="note" placeholder="Note / état constaté" className="rounded border px-3 py-2 text-sm sm:col-span-2"/><div className="sm:col-span-2"><button className="rounded bg-neutral-900 px-4 py-2 text-sm text-white">Enregistrer</button></div></form>}
    {["hors_service","maintenance"].includes(o.statut)&&<form action={mettreOutilRebutAction.bind(null,id)} className="rounded-lg border border-red-300 p-4"><h2 className="font-semibold text-red-800">Outil irréparable</h2><p className="mt-1 text-xs text-neutral-500">La mise au rebut est historisée et retire définitivement l’outil des listes disponibles.</p><div className="mt-3 flex gap-2"><input name="motif" required placeholder="Diagnostic et motif obligatoire" className="flex-1 rounded border px-3 py-2 text-sm"/><ConfirmSubmitButton message="Confirmer la mise au rebut définitive de cet outil ?" className="rounded bg-red-700 px-3 py-2 text-sm text-white">Mettre au rebut</ConfirmSubmitButton></div></form>}
    <section><h2 className="mb-2 font-semibold">Factures liées à l’outil</h2><div className="rounded border">{depenses?.map(d=>{const f=un(d.fournisseur as {nom:string}|{nom:string}[]|null);return <Link key={d.id} href={`/depenses/${d.id}`} className="grid gap-2 border-t px-3 py-2 text-sm first:border-0 hover:bg-neutral-50 sm:grid-cols-[110px_1fr_120px_90px]"><span>{d.date_piece}</span><span>{d.numero_piece} · {f?.nom}</span><strong className="text-right">{euros(d.montant_ttc)}</strong><span className="text-right text-xs">{d.justificatif_storage_path?"PDF/scan ✓":"Sans pièce"}</span></Link>})}{!depenses?.length&&<p className="p-6 text-center text-sm text-neutral-500">Aucune facture liée.</p>}</div></section>
    <section><h2 className="mb-2 font-semibold">Historique</h2>{(m??[]).map(x=>{const e=un(x.employe as {prenom:string;nom:string}|{prenom:string;nom:string}[]|null);const c=un(x.chantier as {nom:string}|{nom:string}[]|null);return <div key={x.id} className="grid gap-2 border-t py-2 text-sm sm:grid-cols-[100px_1fr_1fr]"><span>{x.date_mouvement}</span><strong>{MOUVEMENT_OUTIL_LABELS[x.type]??x.type.replaceAll("_"," ")}</strong><span className="text-neutral-500">{e?`${e.prenom} ${e.nom}`:c?.nom??x.note??""}</span></div>})}{(!m||!m.length)&&<p className="text-sm text-neutral-500">Aucun mouvement.</p>}</section>
  </div></main>;
}
