import { createClient } from "@/lib/supabase/server";
import { getContexteEntreprise } from "@/lib/entreprise";
import { supprimerPointageAction,validerPointageAction } from "@/app/actions/pointages";
import { ConfirmSubmitButton } from "@/components/ConfirmSubmitButton";
import { PointageTerrainForm } from "@/components/PointageTerrainForm";
import { PointageArriveeDepart } from "@/components/PointageArriveeDepart";
import Image from "next/image";

const input = "rounded-md border border-neutral-300 px-2 py-1.5 text-sm dark:border-neutral-700 dark:bg-neutral-900";
const un = <T,>(valeur: T | T[] | null): T | null => Array.isArray(valeur) ? valeur[0] ?? null : valeur;
type Pointage = { id: string; date: string; heures_normales: number; heures_supplementaires: number; pause_minutes: number; tache: string | null; commentaire: string | null;latitude:number|null;longitude:number|null;precision_metres:number|null;photo_storage_path:string|null;verification_statut:string;commentaire_verification:string|null;photoUrl?:string|null; employe: { id: string; prenom: string; nom: string } | { id: string; prenom: string; nom: string }[] | null; chantier: { id: string; nom: string } | { id:string; nom:string } | { id: string; nom: string }[] | null };

export default async function PointagePage({ searchParams }: { searchParams: Promise<{ mois?: string; error?: string; succes?: string }> }) {
  const params = await searchParams;
  const mois = /^\d{4}-\d{2}$/.test(params.mois ?? "") ? params.mois! : new Date().toISOString().slice(0, 7);
  const debut = `${mois}-01`;
  const finDate = new Date(Number(mois.slice(0, 4)), Number(mois.slice(5, 7)), 0);
  const fin = `${mois}-${String(finDate.getDate()).padStart(2, "0")}`;
  const ctx = await getContexteEntreprise();
  const supabase = await createClient();
  const [{ data: employes }, { data: chantiers }, { data: donnees }, { data: sessionsData }] = await Promise.all([
    supabase.from("employes").select("id, prenom, nom").eq("entreprise_id", ctx.entrepriseId).eq("statut", "actif").order("nom"),
    supabase.from("chantiers").select("id, nom").eq("entreprise_id", ctx.entrepriseId).order("nom"),
    supabase.from("pointages").select("id, date, heures_normales, heures_supplementaires, pause_minutes, tache, commentaire,latitude,longitude,precision_metres,photo_storage_path,verification_statut,commentaire_verification, employe:employes(id, prenom, nom), chantier:chantiers(id, nom)").eq("entreprise_id", ctx.entrepriseId).gte("date", debut).lte("date", fin).order("date", { ascending: false }),
    supabase.from("sessions_pointage").select("id,arrivee_at,tache,employe:employes(id,prenom,nom),chantier:chantiers(id,nom)").eq("entreprise_id",ctx.entrepriseId).is("depart_at",null).order("arrivee_at"),
  ]);
  const pointages = await Promise.all(((donnees ?? []) as Pointage[]).map(async p=>{if(!p.photo_storage_path)return p;const{data}=await supabase.storage.from("pointage-preuves").createSignedUrl(p.photo_storage_path,900);return{...p,photoUrl:data?.signedUrl??null}}));
  const totalNormal = pointages.reduce((s, p) => s + Number(p.heures_normales), 0);
  const totalSup = pointages.reduce((s, p) => s + Number(p.heures_supplementaires), 0);
  const parEmploye = new Map<string, { nom: string; heures: number }>();
  for (const p of pointages) { const e = un(p.employe); if (e) { const ligne = parEmploye.get(e.id) ?? { nom: `${e.prenom} ${e.nom}`, heures: 0 }; ligne.heures += Number(p.heures_normales) + Number(p.heures_supplementaires); parEmploye.set(e.id, ligne); } }
  const aujourdHui = new Date().toISOString().slice(0, 10);

  return <main className="p-8"><div className="mx-auto max-w-6xl space-y-6">
    <div className="flex items-end justify-between"><div><h1 className="text-xl font-semibold">Pointage des heures</h1><p className="text-sm text-neutral-500">Heures réellement travaillées, distinctes du planning prévisionnel.</p></div><form method="get"><label className="text-xs text-neutral-500">Mois <input name="mois" type="month" defaultValue={mois} className={input} /></label><button className="ml-2 rounded-md border border-neutral-300 px-3 py-1.5 text-sm">Afficher</button></form></div>
    {params.error && <p className="rounded-md bg-red-50 px-3 py-2 text-sm text-red-700">{params.error}</p>}{params.succes && <p className="rounded-md bg-green-50 px-3 py-2 text-sm text-green-700">{params.succes === "arrivee" ? "Arrivée enregistrée avec GPS et photo." : params.succes === "depart" ? "Départ enregistré et heures calculées automatiquement." : "Pointage enregistré."}</p>}
    <div className="grid grid-cols-3 gap-3"><div className="rounded-md border p-4"><div className="text-xs text-neutral-500">Heures normales</div><div className="font-mono text-xl font-semibold">{totalNormal} h</div></div><div className="rounded-md border p-4"><div className="text-xs text-neutral-500">Heures supplémentaires</div><div className="font-mono text-xl font-semibold text-amber-700">{totalSup} h</div></div><div className="rounded-md border p-4"><div className="text-xs text-neutral-500">Total travaillé</div><div className="font-mono text-xl font-semibold">{totalNormal + totalSup} h</div></div></div>
    {employes?.length && chantiers?.length ? <><PointageArriveeDepart employes={employes.map(e=>({id:e.id,nom:`${e.prenom} ${e.nom}`}))} chantiers={chantiers.map(c=>({id:c.id,nom:c.nom}))} sessions={(sessionsData??[]).map(s=>{const employe=un(s.employe),chantier=un(s.chantier);return{id:s.id,arrivee_at:s.arrivee_at,tache:s.tache,employe:employe?{id:employe.id,nom:`${employe.prenom} ${employe.nom}`}:null,chantier:chantier?{id:chantier.id,nom:chantier.nom}:null}})}/><details className="rounded-md border"><summary className="cursor-pointer p-4 text-sm font-medium">Saisie manuelle d’une journée complète</summary><div className="p-4 pt-0"><PointageTerrainForm mois={mois} aujourdhui={aujourdHui} employes={employes.map(e=>({id:e.id,nom:`${e.prenom} ${e.nom}`}))} chantiers={chantiers.map(c=>({id:c.id,nom:c.nom}))}/></div></details></> : <p className="rounded-md border border-dashed p-5 text-sm text-neutral-500">Ajoutez au moins un employé actif et un chantier pour saisir un pointage.</p>}
    {parEmploye.size > 0 && <div className="rounded-md border p-4"><h2 className="mb-2 text-xs font-semibold uppercase text-neutral-500">Total par employé</h2><div className="grid grid-cols-3 gap-2">{[...parEmploye.values()].map((e) => <div key={e.nom} className="flex justify-between text-sm"><span>{e.nom}</span><span className="font-mono">{e.heures} h</span></div>)}</div></div>}
    <div className="space-y-3">{pointages.map(p=>{const e=un(p.employe),c=un(p.chantier),supprimer=supprimerPointageAction.bind(null,p.id,mois),valider=validerPointageAction.bind(null,p.id,"valide",mois),rejeter=validerPointageAction.bind(null,p.id,"rejete",mois),couleur=p.verification_statut==="valide"?"bg-green-100 text-green-800":p.verification_statut==="rejete"?"bg-red-100 text-red-800":"bg-amber-100 text-amber-800";return <article key={p.id} className="grid grid-cols-[150px_1fr_220px] overflow-hidden rounded-md border"><div className="bg-neutral-50 p-4 dark:bg-neutral-900">{p.photoUrl?<Image src={p.photoUrl} alt="Preuve du pointage" width={118} height={112} unoptimized className="h-28 w-full rounded object-cover"/>:<div className="flex h-28 items-center justify-center rounded border border-dashed text-xs text-neutral-400">Sans photo</div>}</div><div className="p-4"><div className="flex items-center gap-2"><strong>{e?`${e.prenom} ${e.nom}`:"—"}</strong><span className={`rounded-full px-2 py-0.5 text-xs ${couleur}`}>{p.verification_statut.replace("_"," ")}</span></div><p className="text-sm text-neutral-500">{p.date} · {c?.nom??"—"} · {Number(p.heures_normales)+Number(p.heures_supplementaires)} h</p><p className="mt-2 text-sm">{p.tache??p.commentaire??""}</p>{p.latitude!==null&&p.longitude!==null&&<a href={`https://www.openstreetmap.org/?mlat=${p.latitude}&mlon=${p.longitude}#map=18/${p.latitude}/${p.longitude}`} target="_blank" rel="noreferrer" className="mt-2 inline-block text-xs font-medium text-blue-700 hover:underline">Voir la position GPS{p.precision_metres?` · ± ${Math.round(Number(p.precision_metres))} m`:""}</a>}{p.commentaire_verification&&<p className="mt-2 text-xs text-neutral-500">Contrôle : {p.commentaire_verification}</p>}</div><div className="space-y-2 border-l p-4"><form action={valider} className="flex gap-2"><input name="commentaire_verification" placeholder="Commentaire contrôle" className="min-w-0 flex-1 rounded border px-2 py-1 text-xs"/><button className="rounded bg-green-700 px-2 py-1 text-xs text-white">Valider</button></form><form action={rejeter} className="flex gap-2"><input name="commentaire_verification" required placeholder="Motif du rejet" className="min-w-0 flex-1 rounded border px-2 py-1 text-xs"/><button className="rounded bg-red-700 px-2 py-1 text-xs text-white">Rejeter</button></form><form action={supprimer} className="pt-2 text-right"><ConfirmSubmitButton message="Supprimer ce pointage et sa photo ?" className="text-xs text-neutral-400 hover:text-red-600">Supprimer</ConfirmSubmitButton></form></div></article>})}{!pointages.length&&<p className="rounded border border-dashed p-8 text-center text-sm text-neutral-500">Aucun pointage pour ce mois.</p>}</div>
  </div></main>;
}
