import { createClient } from "@/lib/supabase/server";
import { getContexteEntreprise } from "@/lib/entreprise";
import { supprimerPointageAction,validerPointageAction } from "@/app/actions/pointages";
import { ConfirmSubmitButton } from "@/components/ConfirmSubmitButton";
import { PointageArriveeDepart } from "@/components/PointageArriveeDepart";
import { permissionsUtilisateur } from "@/lib/permissions";

const input="rounded-md border border-neutral-300 px-2 py-1.5 text-sm dark:border-neutral-700 dark:bg-neutral-900";
const un=<T,>(valeur:T|T[]|null):T|null=>Array.isArray(valeur)?valeur[0]??null:valeur;
type Relation={id:string;prenom?:string;nom:string};
type Pointage={id:string;date:string;heures_normales:number;heures_supplementaires:number;tache:string|null;commentaire:string|null;latitude:number|null;longitude:number|null;precision_metres:number|null;verification_statut:string;commentaire_verification:string|null;employe:Relation|Relation[]|null;chantier:Relation|Relation[]|null};
type Session={id:string;arrivee_at:string;depart_at:string|null;pause_minutes:number;latitude_arrivee:number;longitude_arrivee:number;precision_arrivee_metres:number|null;latitude_depart:number|null;longitude_depart:number|null;precision_depart_metres:number|null;tache:string|null;pointage_id:string|null;employe:Relation|Relation[]|null;chantier:Relation|Relation[]|null};
const heure=(date:string)=>new Intl.DateTimeFormat("fr-FR",{timeZone:"Europe/Paris",hour:"2-digit",minute:"2-digit"}).format(new Date(date));
const dateHeure=(date:string)=>new Intl.DateTimeFormat("fr-FR",{timeZone:"Europe/Paris",day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(date));

export default async function PointagePage({searchParams}:{searchParams:Promise<{mois?:string;error?:string;succes?:string}>}){
  const params=await searchParams,mois=/^\d{4}-\d{2}$/.test(params.mois??"")?params.mois!:new Date().toISOString().slice(0,7),debut=`${mois}-01`,finDate=new Date(Number(mois.slice(0,4)),Number(mois.slice(5,7)),0),fin=`${mois}-${String(finDate.getDate()).padStart(2,"0")}`,ctx=await getContexteEntreprise(),supabase=await createClient();
  const permissions=await permissionsUtilisateur(ctx),peutGerer=permissions===null||permissions.includes("gerer_pointage"),peutPointer=peutGerer||permissions?.includes("saisir_son_pointage")===true;
  let requeteEmployes=supabase.from("employes").select("id,prenom,nom").eq("entreprise_id",ctx.entrepriseId).eq("statut","actif").order("nom");
  // En authentification réelle, même un responsable pointe uniquement avec sa propre fiche.
  if(permissions!==null)requeteEmployes=requeteEmployes.eq("utilisateur_id",ctx.userId);
  const[{data:employes},{data:chantiers},{data:pointagesData},{data:sessionsData}]=await Promise.all([
    requeteEmployes,
    supabase.from("chantiers").select("id,nom").eq("entreprise_id",ctx.entrepriseId).not("statut","in",'(archive,annule)').order("nom"),
    supabase.from("pointages").select("id,date,heures_normales,heures_supplementaires,tache,commentaire,latitude,longitude,precision_metres,verification_statut,commentaire_verification,employe:employes(id,prenom,nom),chantier:chantiers(id,nom)").eq("entreprise_id",ctx.entrepriseId).gte("date",debut).lte("date",fin).order("date",{ascending:false}),
    supabase.from("sessions_pointage").select("id,arrivee_at,depart_at,pause_minutes,latitude_arrivee,longitude_arrivee,precision_arrivee_metres,latitude_depart,longitude_depart,precision_depart_metres,tache,pointage_id,employe:employes(id,prenom,nom),chantier:chantiers(id,nom)").eq("entreprise_id",ctx.entrepriseId).gte("arrivee_at",`${debut}T00:00:00+02:00`).lte("arrivee_at",`${fin}T23:59:59+02:00`).order("arrivee_at",{ascending:false}),
  ]);
  const peutValider=permissions===null||permissions.includes("valider_pointages");
  const pointages=(pointagesData??[])as Pointage[],sessions=(sessionsData??[])as Session[],ouvertes=sessions.filter(s=>!s.depart_at),lies=new Set(sessions.map(s=>s.pointage_id).filter(Boolean)),anciens=pointages.filter(p=>!lies.has(p.id)),totalNormal=pointages.reduce((s,p)=>s+Number(p.heures_normales),0),totalSup=pointages.reduce((s,p)=>s+Number(p.heures_supplementaires),0);
  const parEmploye=new Map<string,{nom:string;heures:number}>();for(const p of pointages){const e=un(p.employe);if(e){const ligne=parEmploye.get(e.id)??{nom:`${e.prenom??""} ${e.nom}`.trim(),heures:0};ligne.heures+=Number(p.heures_normales)+Number(p.heures_supplementaires);parEmploye.set(e.id,ligne);}}
  return <main className="p-8"><div className="mx-auto max-w-6xl space-y-6">
    <div className="flex items-end justify-between gap-3"><div><h1 className="text-xl font-semibold">Pointage GPS</h1><p className="text-sm text-neutral-500">Chantier, date, heure d’arrivée, heure de départ et positions GPS.</p></div><form method="get"><label className="text-xs text-neutral-500">Mois <input name="mois" type="month" defaultValue={mois} className={input}/></label><button className="ml-2 rounded-md border px-3 py-1.5 text-sm">Afficher</button></form></div>
    {params.error&&<p className="rounded-md bg-red-50 px-3 py-2 text-sm text-red-700">{params.error}</p>}{params.succes&&<p className="rounded-md bg-green-50 px-3 py-2 text-sm text-green-700">{params.succes==="arrivee"?"Arrivée enregistrée avec la date, l’heure et le GPS.":params.succes==="depart"?"Départ enregistré avec le GPS et heures calculées.":"Pointage enregistré."}</p>}
    <div className="grid grid-cols-3 gap-3"><div className="rounded-md border p-4"><p className="text-xs text-neutral-500">Heures normales</p><strong className="font-mono text-xl">{totalNormal} h</strong></div><div className="rounded-md border p-4"><p className="text-xs text-neutral-500">Heures supplémentaires</p><strong className="font-mono text-xl text-amber-700">{totalSup} h</strong></div><div className="rounded-md border p-4"><p className="text-xs text-neutral-500">Total travaillé</p><strong className="font-mono text-xl">{totalNormal+totalSup} h</strong></div></div>
    {peutPointer&&employes?.length&&chantiers?.length?<PointageArriveeDepart employes={employes.map(e=>({id:e.id,nom:`${e.prenom} ${e.nom}`}))} chantiers={chantiers.map(c=>({id:c.id,nom:c.nom}))} sessions={ouvertes.map(s=>{const e=un(s.employe),c=un(s.chantier);return{id:s.id,arrivee_at:s.arrivee_at,tache:s.tache,employe:e?{id:e.id,nom:`${e.prenom??""} ${e.nom}`.trim()}:null,chantier:c?{id:c.id,nom:c.nom}:null};})}/>:peutPointer?<p className="rounded border border-dashed p-5 text-sm text-neutral-500">Votre compte doit être lié à une fiche employé active et à un chantier.</p>:<p className="rounded border border-dashed p-5 text-sm text-neutral-500">Vous pouvez consulter les pointages, mais votre poste ne permet pas d’en saisir.</p>}
    {parEmploye.size>0&&<div className="rounded-md border p-4"><h2 className="mb-2 text-xs font-semibold uppercase text-neutral-500">Total par employé</h2><div className="grid grid-cols-3 gap-2">{[...parEmploye.values()].map(e=><div key={e.nom} className="flex justify-between text-sm"><span>{e.nom}</span><span className="font-mono">{e.heures} h</span></div>)}</div></div>}
    <section><h2 className="mb-3 font-semibold">Historique des pointages GPS</h2><div className="space-y-3">{sessions.map(s=>{const e=un(s.employe),c=un(s.chantier),duree=s.depart_at?Math.max(0,(new Date(s.depart_at).getTime()-new Date(s.arrivee_at).getTime())/3600000-Number(s.pause_minutes)/60):null;return <article key={s.id} className="rounded-md border p-4"><div className="flex items-start justify-between gap-3"><div><strong>{e?`${e.prenom??""} ${e.nom}`.trim():"Employé"}</strong><h3 className="mt-1 text-base font-semibold text-[#9a7625]">{c?.nom??"Chantier non renseigné"}</h3><p className="mt-1 text-sm text-neutral-500">{dateHeure(s.arrivee_at)} · arrivée {heure(s.arrivee_at)}{s.depart_at?` · départ ${heure(s.depart_at)}`:" · départ non pointé"}</p>{s.tache&&<p className="mt-1 text-sm">{s.tache}</p>}</div>{duree!==null&&<strong className="rounded bg-neutral-100 px-3 py-1 font-mono dark:bg-neutral-800">{duree.toFixed(2).replace(".",",")} h</strong>}</div><div className="mt-3 flex gap-4 text-xs"><a href={`https://www.openstreetmap.org/?mlat=${s.latitude_arrivee}&mlon=${s.longitude_arrivee}#map=18/${s.latitude_arrivee}/${s.longitude_arrivee}`} target="_blank" rel="noreferrer" className="font-medium text-blue-700 hover:underline">GPS arrivée{s.precision_arrivee_metres?` · ± ${Math.round(Number(s.precision_arrivee_metres))} m`:""}</a>{s.latitude_depart!==null&&s.longitude_depart!==null&&<a href={`https://www.openstreetmap.org/?mlat=${s.latitude_depart}&mlon=${s.longitude_depart}#map=18/${s.latitude_depart}/${s.longitude_depart}`} target="_blank" rel="noreferrer" className="font-medium text-blue-700 hover:underline">GPS départ{s.precision_depart_metres?` · ± ${Math.round(Number(s.precision_depart_metres))} m`:""}</a>}</div></article>;})}{!sessions.length&&<p className="rounded border border-dashed p-6 text-center text-sm text-neutral-500">Aucun pointage GPS pour ce mois.</p>}</div></section>
    {anciens.length>0&&<details className="rounded-md border"><summary className="cursor-pointer p-4 text-sm font-medium">Anciennes saisies d’heures ({anciens.length})</summary><div className="space-y-3 p-4 pt-0">{anciens.map(p=>{const e=un(p.employe),c=un(p.chantier),supprimer=supprimerPointageAction.bind(null,p.id,mois),valider=validerPointageAction.bind(null,p.id,"valide",mois),rejeter=validerPointageAction.bind(null,p.id,"rejete",mois);return <article key={p.id} className="rounded border p-3"><strong>{e?`${e.prenom??""} ${e.nom}`.trim():"—"}</strong><p className="font-medium text-[#9a7625]">{c?.nom??"—"}</p><p className="text-sm text-neutral-500">{p.date} · {Number(p.heures_normales)+Number(p.heures_supplementaires)} h</p>{p.latitude!==null&&p.longitude!==null&&<a href={`https://www.openstreetmap.org/?mlat=${p.latitude}&mlon=${p.longitude}#map=18/${p.latitude}/${p.longitude}`} target="_blank" rel="noreferrer" className="text-xs text-blue-700">Voir le GPS</a>}<div className={`mt-2 grid gap-2 ${peutValider?"sm:grid-cols-3":"sm:grid-cols-1"}`}>{peutValider&&<><form action={valider}><button className="text-xs text-green-700">Valider</button></form><form action={rejeter}><input name="commentaire_verification" required placeholder="Motif" className="w-full rounded border px-2 py-1 text-xs"/><button className="text-xs text-red-700">Rejeter</button></form></>}{peutGerer&&<form action={supprimer}><ConfirmSubmitButton message="Supprimer ce pointage ?" className="text-xs text-neutral-400">Supprimer</ConfirmSubmitButton></form>}</div></article>;})}</div></details>}
  </div></main>;
}
