import Link from "next/link";
import { notFound } from "next/navigation";
import { justifierAnomaliePaieAction, synchroniserPeriodePaieAction, transitionPeriodePaieAction } from "@/app/actions/paie";
import { euros } from "@/lib/devis";
import { getContexteEntreprise } from "@/lib/entreprise";
import { formaterMois, statutPeriodePaie, STATUTS_DOSSIER_PAIE } from "@/lib/paie";
import { permissionsUtilisateur } from "@/lib/permissions";
import { createClient } from "@/lib/supabase/server";
import { lirePageDossiersPaie, lireSynthesePaie, type SynthesePaie } from "@/lib/pilotage-agregats";

type DossierPage={id:string;employe_id:string;statut:string;heures_normales:number;heures_sup_25:number;heures_sup_50:number;heures_absence:number;jours_conges:number;total_paniers:number;total_trajets:number;total_transports:number;total_grands_deplacements:number;total_kilometres:number;total_primes:number;total_acomptes:number;total_notes_frais:number;employe:{prenom:string;nom:string;reference_interne:string|null;poste:string|null;statut:string}|null};

const PAGE=25;
const LIMITE_ANOMALIES=500;
export default async function PeriodePaiePage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{q?:string;statut?:string;page?:string;error?:string;success?:string}>}){
 const [{id},sp,ctx]=await Promise.all([params,searchParams,getContexteEntreprise()]);const supabase=await createClient();const permissions=await permissionsUtilisateur(ctx);
 const peutGerer=permissions===null||permissions.includes("gerer_paie")||permissions.includes("saisir_variables_paie")||permissions.includes("controler_variables_paie");
 const peutControler=permissions===null||permissions.includes("controler_variables_paie")||permissions.includes("gerer_paie");
 const peutExporter=permissions===null||permissions.includes("exporter_paie");
 // Un simple droit d'auto-consultation (consulter_sa_paie) passe la porte large du prefixe
 // /paie : sans ce filtre, il donnerait acces a la paie de TOUTE l'entreprise via cette page.
 const peutVoirTousDossiers=permissions===null||["gerer_paie","saisir_variables_paie","controler_variables_paie","exporter_paie","parametrer_paie","voir_paie_confidentielle"].some(cle=>permissions.includes(cle));
 const [{data:periode},{data:anomalies},{data:validations}]=await Promise.all([
  supabase.from("periodes_paie").select("*").eq("id",id).eq("entreprise_id",ctx.entrepriseId).maybeSingle(),
  supabase.from("anomalies_paie").select("id,dossier_id,niveau,code,description,justification,created_at").eq("periode_id",id).is("corrigee_at",null).order("niveau").order("created_at").order("id").limit(LIMITE_ANOMALIES),
  supabase.from("validations_paie").select("id,etape,action,commentaire,ancien_statut,nouveau_statut,created_at").eq("periode_id",id).order("created_at",{ascending:false}).limit(20),
 ]);if(!periode)notFound();
 let monDossierId:string|null=null;
 if(!peutVoirTousDossiers){
  const{data:monEmploye}=await supabase.from("employes").select("id").eq("entreprise_id",ctx.entrepriseId).eq("utilisateur_id",ctx.userId).maybeSingle();
  const{data:monDossier}=await supabase.from("dossiers_paie_salaries").select("id").eq("periode_id",id).eq("employe_id",monEmploye?.id??"").maybeSingle();
  monDossierId=monDossier?.id??null;
 }
 const anomaliesVisibles=peutVoirTousDossiers?(anomalies??[]):(anomalies??[]).filter(a=>a.dossier_id===monDossierId);
 // Page de dossiers servie en base (paie_periode_dossiers_page) : le count
 // exact et le tri par nom sous RLS évaluaient les policies de chaque dossier.
 const page=Math.max(1,Number(sp.page)||1);const filtresDossiers={statut:sp.statut,recherche:sp.q,dossierId:peutVoirTousDossiers?null:(monDossierId??"00000000-0000-0000-0000-000000000000")};
 const listeDossiers=await lirePageDossiersPaie<DossierPage>(supabase,ctx.entrepriseId,id,filtresDossiers,PAGE,(page-1)*PAGE).then((r)=>({...r,erreur:null as Error|null}),(erreur:Error)=>({total:0,lignes:[] as DossierPage[],erreur}));
 const dossiers=listeDossiers.lignes,count=listeDossiers.total,listeErreur=listeDossiers.erreur;
 const totalPages=Math.max(1,Math.ceil((count??0)/PAGE));const estModifiable=["brouillon","saisie_en_cours","a_controler"].includes(periode.statut);
 // Indicateurs de la période sur TOUS les dossiers visibles et filtrés
 // (paie_periode_synthese) : ils additionnaient auparavant les 25 dossiers de
 // la page affichée, et « Contrôles (N) » comptait une liste plafonnée.
 const synthese=await lireSynthesePaie(supabase,ctx.entrepriseId,id,filtresDossiers).catch((err):SynthesePaie|null=>{console.error("[paie] synthèse indisponible",err instanceof Error?err.message:err);return null;});
 const montant=(v:number|undefined)=>v===undefined?"indisponible":euros(v);
 return <main className="p-4 sm:p-8"><div className="mx-auto max-w-[1500px] space-y-6"><header className="flex flex-wrap items-start justify-between gap-3"><div><Link href="/paie" className="text-sm text-neutral-500 hover:underline">← Périodes</Link><h1 className="mt-2 text-2xl font-semibold capitalize">Paie · {formaterMois(periode.mois)}</h1><p className="text-sm text-neutral-500">{periode.date_debut} → {periode.date_fin} · {statutPeriodePaie(periode.statut)}</p></div><div className="flex flex-wrap gap-2">{peutExporter&&<><a href={`/api/paie/periodes/${id}/export?format=xlsx`} className="rounded border px-3 py-2 text-sm">Excel</a><a href={`/api/paie/periodes/${id}/export?format=csv`} className="rounded border px-3 py-2 text-sm">CSV</a><a href={`/api/paie/periodes/${id}/export?format=zip`} className="rounded border px-3 py-2 text-sm">ZIP cabinet</a><Link href={`/imprimer/paie/${id}`} className="rounded border px-3 py-2 text-sm">PDF / Imprimer</Link></>}</div></header>
 {sp.error&&<p className="rounded bg-red-50 p-3 text-sm text-red-700">{sp.error}</p>}{sp.success&&<p className="rounded bg-green-50 p-3 text-sm text-green-700">{sp.success}</p>}{listeErreur&&<p className="rounded bg-red-50 p-3 text-sm text-red-700">{listeErreur.message}</p>}
 <nav className="flex flex-wrap gap-2 rounded-lg border p-2 text-sm"><a href="#salaries" className="rounded px-3 py-2 hover:bg-neutral-100">Salariés</a><a href="#anomalies" className="rounded px-3 py-2 hover:bg-neutral-100">Contrôles ({synthese?synthese.nbAnomalies:anomaliesVisibles.length})</a><a href="#historique" className="rounded px-3 py-2 hover:bg-neutral-100">Historique</a><Link href="/paie/parametres" className="rounded px-3 py-2 hover:bg-neutral-100">Paramètres</Link></nav>
 {peutGerer&&<section className="flex flex-wrap items-center gap-3 rounded-lg border p-4"><form action={synchroniserPeriodePaieAction.bind(null,id)}><button disabled={!estModifiable} className="rounded bg-[#0d1b2a] px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Synchroniser les sources</button></form>{estModifiable&&<form action={transitionPeriodePaieAction.bind(null,id,"a_controler")} className="flex gap-2"><input name="commentaire" placeholder="Commentaire de contrôle" className="rounded border px-3 py-2 text-sm"/><button className="rounded border px-3 py-2 text-sm">Passer à contrôler</button></form>}{peutControler&&periode.statut==="a_controler"&&<form action={transitionPeriodePaieAction.bind(null,id,"validee")} className="flex gap-2"><input name="commentaire" required placeholder="Validation et observations" className="rounded border px-3 py-2 text-sm"/><button className="rounded bg-green-700 px-3 py-2 text-sm font-semibold text-white">Valider la période</button></form>}{peutExporter&&periode.statut==="validee"&&<form action={transitionPeriodePaieAction.bind(null,id,"transmise_comptable")}><input type="hidden" name="commentaire" value="Export remis au cabinet comptable"/><button className="rounded border px-3 py-2 text-sm">Marquer transmise</button></form>}{peutControler&&periode.statut==="transmise_comptable"&&<form action={transitionPeriodePaieAction.bind(null,id,"verrouillee")}><input type="hidden" name="commentaire" value="Période verrouillée après transmission"/><button className="rounded border border-amber-500 px-3 py-2 text-sm">Verrouiller</button></form>}</section>}
 <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-lg border p-4"><p className="text-xs text-neutral-500">Dossiers visibles</p><strong className="text-2xl">{count??0}</strong></div><div className="rounded-lg border p-4"><p className="text-xs text-neutral-500">Indemnités déplacements</p><strong className="text-xl">{montant(synthese?.indemnitesDeplacement)}</strong></div><div className="rounded-lg border p-4"><p className="text-xs text-neutral-500">Primes</p><strong className="text-xl">{montant(synthese?.primes)}</strong></div><div className="rounded-lg border p-4"><p className="text-xs text-neutral-500">Notes de frais / acomptes</p><strong className="text-xl">{montant(synthese?.notesFrais)} / {montant(synthese?.acomptes)}</strong></div></section>
 <section id="salaries" className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">Une ligne par salarié</h2><form className="flex flex-wrap gap-2"><input name="q" defaultValue={sp.q??""} placeholder="Nom ou prénom" className="rounded border px-3 py-2 text-sm"/><select name="statut" defaultValue={sp.statut??""} className="rounded border px-3 py-2 text-sm"><option value="">Tous les statuts</option>{Object.entries(STATUTS_DOSSIER_PAIE).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button className="rounded border px-3 py-2 text-sm">Filtrer</button></form></div><div className="overflow-x-auto rounded-lg border"><table className="w-full min-w-[1150px] text-sm"><thead className="bg-neutral-50 text-left text-xs uppercase text-neutral-500 dark:bg-neutral-900"><tr><th className="p-3">Salarié</th><th className="p-3">Normales</th><th className="p-3">Sup. 25/50</th><th className="p-3">Absence</th><th className="p-3">Congés</th><th className="p-3">Paniers</th><th className="p-3">Déplacements</th><th className="p-3">Primes</th><th className="p-3">Frais</th><th className="p-3">Statut</th><th className="p-3"></th></tr></thead><tbody>{(dossiers??[]).map(d=>{const e=Array.isArray(d.employe)?d.employe[0]:d.employe;return <tr key={d.id} className="border-t"><td className="p-3"><strong>{e?.prenom} {e?.nom}</strong><p className="text-xs text-neutral-500">{e?.poste??e?.reference_interne}</p></td><td className="p-3 font-mono">{Number(d.heures_normales).toFixed(2)} h</td><td className="p-3 font-mono">{Number(d.heures_sup_25).toFixed(2)} / {Number(d.heures_sup_50).toFixed(2)} h</td><td className="p-3 font-mono">{Number(d.heures_absence).toFixed(2)} h</td><td className="p-3 font-mono">{Number(d.jours_conges).toFixed(2)} j</td><td className="p-3">{euros(d.total_paniers)}</td><td className="p-3">{euros(Number(d.total_trajets)+Number(d.total_transports)+Number(d.total_grands_deplacements))}</td><td className="p-3">{euros(d.total_primes)}</td><td className="p-3">{euros(d.total_notes_frais)}</td><td className="p-3">{STATUTS_DOSSIER_PAIE[d.statut as keyof typeof STATUTS_DOSSIER_PAIE]??d.statut}</td><td className="p-3 text-right"><Link href={`/paie/${id}/${d.id}`} className="font-medium text-blue-700 hover:underline">Détail →</Link></td></tr>})}{!(dossiers??[]).length&&<tr><td colSpan={11} className="p-8 text-center text-neutral-500">Aucun dossier visible.</td></tr>}</tbody></table></div>{totalPages>1&&<div className="flex justify-center gap-2">{Array.from({length:totalPages},(_,i)=>i+1).map(n=><Link key={n} href={`/paie/${id}?page=${n}&q=${encodeURIComponent(sp.q??"")}&statut=${sp.statut??""}`} className={`rounded border px-3 py-1 text-sm ${n===page?"bg-neutral-900 text-white":""}`}>{n}</Link>)}</div>}</section>
 <section id="anomalies" className="space-y-3"><h2 className="font-semibold">Anomalies et contrôles</h2>{synthese&&synthese.nbAnomalies>anomaliesVisibles.length&&<p className="text-xs text-neutral-500">{anomaliesVisibles.length} premières anomalies affichées sur {synthese.nbAnomalies} (par niveau).</p>}<div className="grid gap-2">{anomaliesVisibles.map(a=><article key={a.id} className={`rounded-lg border p-3 ${a.niveau==="bloquant"?"border-red-300 bg-red-50":a.niveau==="attention"?"border-amber-300 bg-amber-50":""}`}><div className="flex flex-wrap justify-between gap-2"><div><strong>{a.description}</strong><p className="text-xs text-neutral-500">{a.code} · {a.niveau}</p></div>{a.dossier_id&&<Link href={`/paie/${id}/${a.dossier_id}`} className="text-sm text-blue-700">Ouvrir le salarié</Link>}</div>{a.justification?<p className="mt-2 text-sm"><strong>Justification :</strong> {a.justification}</p>:peutControler&&<form action={justifierAnomaliePaieAction.bind(null,id,a.id)} className="mt-2 flex gap-2"><input name="justification" required placeholder="Justification obligatoire pour ignorer" className="min-w-0 flex-1 rounded border bg-white px-3 py-2 text-sm"/><button className="rounded border px-3 py-2 text-sm">Justifier</button></form>}</article>)}{!anomaliesVisibles.length&&<p className="rounded border border-dashed p-4 text-sm text-neutral-500">Aucune anomalie non corrigée.</p>}</div></section>
 <section id="historique" className="space-y-3"><h2 className="font-semibold">Historique des validations</h2><div className="rounded-lg border">{(validations??[]).map(v=><div key={v.id} className="border-t p-3 text-sm first:border-0"><strong>{v.action}</strong> · {v.ancien_statut??"—"} → {v.nouveau_statut??"—"}<p className="text-xs text-neutral-500">{new Date(v.created_at).toLocaleString("fr-FR")} · {v.commentaire??"Sans commentaire"}</p></div>)}{!(validations??[]).length&&<p className="p-4 text-sm text-neutral-500">Aucune validation enregistrée.</p>}</div></section>
 </div></main>;
}
