import Link from "next/link";
import { notFound } from "next/navigation";
import { justifierAnomaliePaieAction, synchroniserPeriodePaieAction, transitionPeriodePaieAction } from "@/app/actions/paie";
import { euros } from "@/lib/devis";
import { getContexteEntreprise } from "@/lib/entreprise";
import { formaterMois, statutPeriodePaie, STATUTS_DOSSIER_PAIE } from "@/lib/paie";
import { permissionsUtilisateur } from "@/lib/permissions";
import { createClient } from "@/lib/supabase/server";

const PAGE=25;
export default async function PeriodePaiePage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{q?:string;statut?:string;page?:string;error?:string;success?:string}>}){
 const [{id},sp,ctx]=await Promise.all([params,searchParams,getContexteEntreprise()]);const supabase=await createClient();const permissions=await permissionsUtilisateur(ctx);
 const peutGerer=permissions===null||permissions.includes("gerer_paie")||permissions.includes("saisir_variables_paie")||permissions.includes("controler_variables_paie");
 const peutControler=permissions===null||permissions.includes("controler_variables_paie")||permissions.includes("gerer_paie");
 const peutExporter=permissions===null||permissions.includes("exporter_paie");
 const [{data:periode},{data:anomalies},{data:validations}]=await Promise.all([
  supabase.from("periodes_paie").select("*").eq("id",id).eq("entreprise_id",ctx.entrepriseId).maybeSingle(),
  supabase.from("anomalies_paie").select("id,dossier_id,niveau,code,description,justification,created_at").eq("periode_id",id).is("corrigee_at",null).order("niveau"),
  supabase.from("validations_paie").select("id,etape,action,commentaire,ancien_statut,nouveau_statut,created_at").eq("periode_id",id).order("created_at",{ascending:false}).limit(20),
 ]);if(!periode)notFound();
 const page=Math.max(1,Number(sp.page)||1);let requete=supabase.from("dossiers_paie_salaries").select("id,employe_id,statut,heures_normales,heures_sup_25,heures_sup_50,heures_absence,jours_conges,total_paniers,total_trajets,total_transports,total_grands_deplacements,total_kilometres,total_primes,total_acomptes,total_notes_frais,employe:employes!inner(prenom,nom,reference_interne,poste,statut)",{count:"exact"}).eq("periode_id",id).eq("entreprise_id",ctx.entrepriseId);
 if(sp.statut)requete=requete.eq("statut",sp.statut);if(sp.q)requete=requete.or(`nom.ilike.%${sp.q.replace(/[,()]/g,"")}%,prenom.ilike.%${sp.q.replace(/[,()]/g,"")}%`,{referencedTable:"employes"});
 const {data:dossiers,count,error:listeErreur}=await requete.order("nom",{referencedTable:"employes"}).range((page-1)*PAGE,page*PAGE-1);
 const totalPages=Math.max(1,Math.ceil((count??0)/PAGE));const estModifiable=["brouillon","saisie_en_cours","a_controler"].includes(periode.statut);
 const total=(cle:"total_paniers"|"total_trajets"|"total_transports"|"total_grands_deplacements"|"total_primes"|"total_acomptes"|"total_notes_frais")=>(dossiers??[]).reduce((s,d)=>s+Number(d[cle]),0);
 return <main className="p-4 sm:p-8"><div className="mx-auto max-w-[1500px] space-y-6"><header className="flex flex-wrap items-start justify-between gap-3"><div><Link href="/paie" className="text-sm text-neutral-500 hover:underline">← Périodes</Link><h1 className="mt-2 text-2xl font-semibold capitalize">Paie · {formaterMois(periode.mois)}</h1><p className="text-sm text-neutral-500">{periode.date_debut} → {periode.date_fin} · {statutPeriodePaie(periode.statut)}</p></div><div className="flex flex-wrap gap-2">{peutExporter&&<><a href={`/api/paie/periodes/${id}/export?format=xlsx`} className="rounded border px-3 py-2 text-sm">Excel</a><a href={`/api/paie/periodes/${id}/export?format=csv`} className="rounded border px-3 py-2 text-sm">CSV</a><a href={`/api/paie/periodes/${id}/export?format=zip`} className="rounded border px-3 py-2 text-sm">ZIP cabinet</a><Link href={`/imprimer/paie/${id}`} className="rounded border px-3 py-2 text-sm">PDF / Imprimer</Link></>}</div></header>
 {sp.error&&<p className="rounded bg-red-50 p-3 text-sm text-red-700">{sp.error}</p>}{sp.success&&<p className="rounded bg-green-50 p-3 text-sm text-green-700">{sp.success}</p>}{listeErreur&&<p className="rounded bg-red-50 p-3 text-sm text-red-700">{listeErreur.message}</p>}
 <nav className="flex flex-wrap gap-2 rounded-lg border p-2 text-sm"><a href="#salaries" className="rounded px-3 py-2 hover:bg-neutral-100">Salariés</a><a href="#anomalies" className="rounded px-3 py-2 hover:bg-neutral-100">Contrôles ({anomalies?.length??0})</a><a href="#historique" className="rounded px-3 py-2 hover:bg-neutral-100">Historique</a><Link href="/paie/parametres" className="rounded px-3 py-2 hover:bg-neutral-100">Paramètres</Link></nav>
 {peutGerer&&<section className="flex flex-wrap items-center gap-3 rounded-lg border p-4"><form action={synchroniserPeriodePaieAction.bind(null,id)}><button disabled={!estModifiable} className="rounded bg-[#0d1b2a] px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Synchroniser les sources</button></form>{estModifiable&&<form action={transitionPeriodePaieAction.bind(null,id,"a_controler")} className="flex gap-2"><input name="commentaire" placeholder="Commentaire de contrôle" className="rounded border px-3 py-2 text-sm"/><button className="rounded border px-3 py-2 text-sm">Passer à contrôler</button></form>}{peutControler&&periode.statut==="a_controler"&&<form action={transitionPeriodePaieAction.bind(null,id,"validee")} className="flex gap-2"><input name="commentaire" required placeholder="Validation et observations" className="rounded border px-3 py-2 text-sm"/><button className="rounded bg-green-700 px-3 py-2 text-sm font-semibold text-white">Valider la période</button></form>}{peutExporter&&periode.statut==="validee"&&<form action={transitionPeriodePaieAction.bind(null,id,"transmise_comptable")}><input type="hidden" name="commentaire" value="Export remis au cabinet comptable"/><button className="rounded border px-3 py-2 text-sm">Marquer transmise</button></form>}{peutControler&&periode.statut==="transmise_comptable"&&<form action={transitionPeriodePaieAction.bind(null,id,"verrouillee")}><input type="hidden" name="commentaire" value="Période verrouillée après transmission"/><button className="rounded border border-amber-500 px-3 py-2 text-sm">Verrouiller</button></form>}</section>}
 <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-lg border p-4"><p className="text-xs text-neutral-500">Dossiers visibles</p><strong className="text-2xl">{count??0}</strong></div><div className="rounded-lg border p-4"><p className="text-xs text-neutral-500">Indemnités déplacements</p><strong className="text-xl">{euros(total("total_paniers")+total("total_trajets")+total("total_transports")+total("total_grands_deplacements"))}</strong></div><div className="rounded-lg border p-4"><p className="text-xs text-neutral-500">Primes</p><strong className="text-xl">{euros(total("total_primes"))}</strong></div><div className="rounded-lg border p-4"><p className="text-xs text-neutral-500">Notes de frais / acomptes</p><strong className="text-xl">{euros(total("total_notes_frais"))} / {euros(total("total_acomptes"))}</strong></div></section>
 <section id="salaries" className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">Une ligne par salarié</h2><form className="flex flex-wrap gap-2"><input name="q" defaultValue={sp.q??""} placeholder="Nom ou prénom" className="rounded border px-3 py-2 text-sm"/><select name="statut" defaultValue={sp.statut??""} className="rounded border px-3 py-2 text-sm"><option value="">Tous les statuts</option>{Object.entries(STATUTS_DOSSIER_PAIE).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button className="rounded border px-3 py-2 text-sm">Filtrer</button></form></div><div className="overflow-x-auto rounded-lg border"><table className="w-full min-w-[1150px] text-sm"><thead className="bg-neutral-50 text-left text-xs uppercase text-neutral-500 dark:bg-neutral-900"><tr><th className="p-3">Salarié</th><th className="p-3">Normales</th><th className="p-3">Sup. 25/50</th><th className="p-3">Absence</th><th className="p-3">Congés</th><th className="p-3">Paniers</th><th className="p-3">Déplacements</th><th className="p-3">Primes</th><th className="p-3">Frais</th><th className="p-3">Statut</th><th className="p-3"></th></tr></thead><tbody>{(dossiers??[]).map(d=>{const e=Array.isArray(d.employe)?d.employe[0]:d.employe;return <tr key={d.id} className="border-t"><td className="p-3"><strong>{e?.prenom} {e?.nom}</strong><p className="text-xs text-neutral-500">{e?.poste??e?.reference_interne}</p></td><td className="p-3 font-mono">{Number(d.heures_normales).toFixed(2)} h</td><td className="p-3 font-mono">{Number(d.heures_sup_25).toFixed(2)} / {Number(d.heures_sup_50).toFixed(2)} h</td><td className="p-3 font-mono">{Number(d.heures_absence).toFixed(2)} h</td><td className="p-3 font-mono">{Number(d.jours_conges).toFixed(2)} j</td><td className="p-3">{euros(d.total_paniers)}</td><td className="p-3">{euros(Number(d.total_trajets)+Number(d.total_transports)+Number(d.total_grands_deplacements))}</td><td className="p-3">{euros(d.total_primes)}</td><td className="p-3">{euros(d.total_notes_frais)}</td><td className="p-3">{STATUTS_DOSSIER_PAIE[d.statut as keyof typeof STATUTS_DOSSIER_PAIE]??d.statut}</td><td className="p-3 text-right"><Link href={`/paie/${id}/${d.id}`} className="font-medium text-blue-700 hover:underline">Détail →</Link></td></tr>})}{!(dossiers??[]).length&&<tr><td colSpan={11} className="p-8 text-center text-neutral-500">Aucun dossier visible.</td></tr>}</tbody></table></div>{totalPages>1&&<div className="flex justify-center gap-2">{Array.from({length:totalPages},(_,i)=>i+1).map(n=><Link key={n} href={`/paie/${id}?page=${n}&q=${encodeURIComponent(sp.q??"")}&statut=${sp.statut??""}`} className={`rounded border px-3 py-1 text-sm ${n===page?"bg-neutral-900 text-white":""}`}>{n}</Link>)}</div>}</section>
 <section id="anomalies" className="space-y-3"><h2 className="font-semibold">Anomalies et contrôles</h2><div className="grid gap-2">{(anomalies??[]).map(a=><article key={a.id} className={`rounded-lg border p-3 ${a.niveau==="bloquant"?"border-red-300 bg-red-50":a.niveau==="attention"?"border-amber-300 bg-amber-50":""}`}><div className="flex flex-wrap justify-between gap-2"><div><strong>{a.description}</strong><p className="text-xs text-neutral-500">{a.code} · {a.niveau}</p></div>{a.dossier_id&&<Link href={`/paie/${id}/${a.dossier_id}`} className="text-sm text-blue-700">Ouvrir le salarié</Link>}</div>{a.justification?<p className="mt-2 text-sm"><strong>Justification :</strong> {a.justification}</p>:peutControler&&<form action={justifierAnomaliePaieAction.bind(null,id,a.id)} className="mt-2 flex gap-2"><input name="justification" required placeholder="Justification obligatoire pour ignorer" className="min-w-0 flex-1 rounded border bg-white px-3 py-2 text-sm"/><button className="rounded border px-3 py-2 text-sm">Justifier</button></form>}</article>)}{!(anomalies??[]).length&&<p className="rounded border border-dashed p-4 text-sm text-neutral-500">Aucune anomalie non corrigée.</p>}</div></section>
 <section id="historique" className="space-y-3"><h2 className="font-semibold">Historique des validations</h2><div className="rounded-lg border">{(validations??[]).map(v=><div key={v.id} className="border-t p-3 text-sm first:border-0"><strong>{v.action}</strong> · {v.ancien_statut??"—"} → {v.nouveau_statut??"—"}<p className="text-xs text-neutral-500">{new Date(v.created_at).toLocaleString("fr-FR")} · {v.commentaire??"Sans commentaire"}</p></div>)}{!(validations??[]).length&&<p className="p-4 text-sm text-neutral-500">Aucune validation enregistrée.</p>}</div></section>
 </div></main>;
}
