import { createClient } from "@/lib/supabase/server";
import Link from "next/link";
import { getContexteEntreprise } from "@/lib/entreprise";
import { permissionsUtilisateur } from "@/lib/permissions";
import { euros } from "@/lib/devis";
import { powensEstConfigure } from "@/lib/banking";
import {
  activerPowensAction,
  annulerLotVirementsAction,
  enregistrerRibDepuisFormAction,
  importerBulletinPaieAction,
  preparerLotVirementsAction,
  synchroniserLotPowensAction,
  transmettreLotPowensAction,
  validerBulletinPaieAction,
  validerLotVirementsAction,
  validerRibAction,
} from "@/app/actions/paiements-bancaires";

const champ = "w-full rounded-md border border-neutral-300 bg-white px-3 py-2 text-sm dark:border-neutral-700 dark:bg-neutral-900";
const un = <T,>(valeur: T | T[] | null): T | null => Array.isArray(valeur) ? valeur[0] ?? null : valeur;
const statutLot: Record<string, string> = { brouillon: "Brouillon", a_valider: "À valider", valide: "Validé", consentement_requis: "Validation bancaire requise", transmis: "Transmis", en_cours: "En cours", execute: "Exécuté", partiel: "Partiel", echec: "Échec", annule: "Annulé" };

export default async function PaiementsBancairesPage({ searchParams }: { searchParams: Promise<{ error?: string; success?: string }> }) {
  const messages = await searchParams;
  const contexte = await getContexteEntreprise();
  if (contexte.accesSupportPlateforme) return <main className="p-4 sm:p-8"><div className="mx-auto max-w-3xl space-y-5">
    <header><h1 className="text-2xl font-semibold">Banque, virements et paie</h1><p className="text-sm text-neutral-500">Protection renforcée des données bancaires et salariales.</p></header>
    <section className="rounded-xl border border-amber-300 bg-amber-50 p-5 text-amber-950 dark:border-amber-800 dark:bg-amber-950/30 dark:text-amber-100">
      <h2 className="font-semibold">Accès bancaire indisponible en mode administrateur plateforme</h2>
      <p className="mt-2 text-sm">Ce n’est pas une erreur 404 : les RIB, bulletins de paie et virements d’une entreprise cliente sont volontairement masqués au support de la plateforme. Connectez-vous avec un compte administrateur membre de cette entreprise pour les gérer.</p>
      <Link href="/plateforme" className="mt-4 inline-flex rounded-md bg-amber-900 px-4 py-2 text-sm font-semibold text-white">Retour à la plateforme</Link>
    </section>
  </div></main>;
  const supabase = await createClient();
  const permissions = await permissionsUtilisateur(contexte);
  const autorise = (droit: string) => permissions === null || permissions.includes(droit);
  const [{ data: connexion }, { data: ribs }, { data: employes }, { data: fournisseurs }, { data: bulletins }, { data: notes }, { data: depenses }, { data: lots }, { data: journal }] = await Promise.all([
    supabase.from("connexions_bancaires").select("provider,environnement,statut,dernier_message,dernier_lot_at").eq("entreprise_id", contexte.entrepriseId).maybeSingle(),
    supabase.from("coordonnees_bancaires").select("id,type_beneficiaire,employe_id,fournisseur_id,titulaire,iban_quatre_derniers,verification_statut,verification_message,created_at,employe:employes(prenom,nom),fournisseur:fournisseurs(nom)").eq("entreprise_id", contexte.entrepriseId).eq("actif", true).order("created_at", { ascending: false }),
    supabase.from("employes").select("id,prenom,nom,statut").eq("entreprise_id", contexte.entrepriseId).not("statut", "in", "(sorti,suspendu)").order("nom"),
    supabase.from("fournisseurs").select("id,nom,siret,actif").eq("entreprise_id", contexte.entrepriseId).eq("actif", true).order("nom"),
    supabase.from("bulletins_paie").select("id,employe_id,periode,version,montant_net_a_payer,date_paiement_prevue,statut,nom_fichier_original,storage_path,reference_expert_comptable,importe_at,employe:employes(prenom,nom)").eq("entreprise_id", contexte.entrepriseId).order("periode", { ascending: false }).limit(100),
    supabase.from("notes_frais").select("id,employe_id,reference,date_frais,montant_ttc,statut,employe:employes(prenom,nom)").eq("entreprise_id", contexte.entrepriseId).in("statut", ["valide", "validee", "exporte_comptabilite"]).order("date_frais", { ascending: false }).limit(100),
    supabase.from("depenses_fournisseurs").select("id,fournisseur_id,numero_piece,date_piece,date_echeance,montant_ttc,montant_regle,statut,fournisseur:fournisseurs(nom)").eq("entreprise_id", contexte.entrepriseId).in("statut", ["a_payer", "payee_partiel"]).order("date_echeance", { ascending: true }).limit(100),
    supabase.from("lots_virements").select("id,numero,type_lot,statut,date_execution,nombre_ordres,montant_total,provider,provider_statut,provider_message,consent_url,created_at,ordres:ordres_virements(id,titulaire,iban_quatre_derniers,montant,libelle,statut)").eq("entreprise_id", contexte.entrepriseId).order("created_at", { ascending: false }).limit(50),
    supabase.from("journal_paiements_bancaires").select("id,action,ressource_type,nouveau_statut,created_at").eq("entreprise_id", contexte.entrepriseId).order("created_at", { ascending: false }).limit(30),
  ]);
  const ribEmploye = new Map((ribs ?? []).filter((rib) => rib.employe_id).map((rib) => [rib.employe_id, rib]));
  const ribFournisseur = new Map((ribs ?? []).filter((rib) => rib.fournisseur_id).map((rib) => [rib.fournisseur_id, rib]));
  const bulletinUrls = new Map<string, string>();
  if (autorise("gerer_paie")) {
    await Promise.all((bulletins ?? []).map(async (bulletin) => {
      const { data } = await supabase.storage.from("bulletins-paie").createSignedUrl(bulletin.storage_path, 600);
      if (data?.signedUrl) bulletinUrls.set(bulletin.id, data.signedUrl);
    }));
  }

  return <main className="p-4 sm:p-8"><div className="mx-auto max-w-7xl space-y-6">
    <header><h1 className="text-2xl font-semibold">Banque, virements et paie</h1><p className="text-sm text-neutral-500">Fournisseurs, salaires et remboursements de notes de frais avec contrôle avant transmission.</p></header>
    {messages.error && <p className="rounded-md bg-red-50 p-3 text-sm text-red-700">{messages.error}</p>}
    {messages.success && <p className="rounded-md bg-green-50 p-3 text-sm text-green-700">{messages.success}</p>}

    <section className="rounded-xl border border-blue-200 bg-blue-50 p-4 dark:border-blue-900 dark:bg-blue-950/30">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-semibold">Prestataire bancaire · Powens Pay</h2><p className="mt-1 max-w-3xl text-sm text-neutral-600 dark:text-neutral-300">Liria prépare les ordres. La banque exige ensuite une authentification forte avant de les exécuter. Aucun salaire ni fournisseur n’est payé à la simple réception d’un document.</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${connexion?.statut === "actif" || connexion?.statut === "pret" ? "bg-green-100 text-green-800" : "bg-amber-100 text-amber-900"}`}>{connexion?.statut === "actif" || connexion?.statut === "pret" ? `Prêt · ${connexion.environnement}` : powensEstConfigure() ? "À activer" : "Contrat et clés requis"}</span></div>
      {connexion?.dernier_message && <p className="mt-3 text-xs text-blue-900 dark:text-blue-200">{connexion.dernier_message}</p>}
      {autorise("executer_virements") && powensEstConfigure() && !["pret", "actif"].includes(connexion?.statut ?? "") && <form action={activerPowensAction} className="mt-3"><button className="rounded-md bg-blue-700 px-4 py-2 text-sm font-semibold text-white">Activer Powens pour cette entreprise</button></form>}
    </section>

    <section className="rounded-xl border p-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-semibold">Coffre RIB</h2><p className="text-xs text-neutral-500">Les IBAN sont chiffrés avant stockage. Seuls les quatre derniers caractères restent affichables.</p></div><span className="text-xs text-neutral-500">{ribs?.length ?? 0} RIB actif(s)</span></div>
      {autorise("gerer_coordonnees_bancaires") && <form action={enregistrerRibDepuisFormAction} className="mt-4 grid gap-2 md:grid-cols-4"><select name="beneficiaire" required className={champ}><option value="">Salarié ou fournisseur…</option><optgroup label="Salariés">{(employes ?? []).map((employe) => <option key={employe.id} value={`employe:${employe.id}`}>{employe.prenom} {employe.nom}</option>)}</optgroup><optgroup label="Fournisseurs">{(fournisseurs ?? []).map((fournisseur) => <option key={fournisseur.id} value={`fournisseur:${fournisseur.id}`}>{fournisseur.nom}</option>)}</optgroup></select><input name="titulaire" required placeholder="Titulaire exact du compte" autoComplete="off" className={champ}/><input name="iban" required placeholder="IBAN" autoComplete="off" className={champ}/><input name="bic" placeholder="BIC facultatif" autoComplete="off" className={champ}/><button className="rounded-md bg-[#0d1b2a] px-4 py-2 text-sm font-semibold text-white md:col-span-4">Chiffrer et enregistrer le RIB</button></form>}
      <div className="mt-4 grid gap-2 md:grid-cols-2">{(ribs ?? []).map((rib) => {const employe=un(rib.employe as {prenom:string;nom:string}|{prenom:string;nom:string}[]|null);const fournisseur=un(rib.fournisseur as {nom:string}|{nom:string}[]|null);return <article key={rib.id} className="flex flex-wrap items-center justify-between gap-3 rounded-md border p-3 text-sm"><div><strong>{employe ? `${employe.prenom} ${employe.nom}` : fournisseur?.nom}</strong><p className="text-xs text-neutral-500">{rib.titulaire} · IBAN •••• {rib.iban_quatre_derniers}</p></div><div className="flex items-center gap-2"><span className={`rounded-full px-2 py-1 text-xs ${rib.verification_statut === "verifie" ? "bg-green-100 text-green-800" : rib.verification_statut === "rejete" ? "bg-red-100 text-red-800" : "bg-amber-100 text-amber-900"}`}>{rib.verification_statut.replaceAll("_", " ")}</span>{autorise("valider_virements") && rib.verification_statut === "a_verifier" && <><form action={validerRibAction.bind(null, rib.id, true)}><button className="text-xs font-medium text-green-700">Valider</button></form><form action={validerRibAction.bind(null, rib.id, false)}><button className="text-xs font-medium text-red-700">Rejeter</button></form></>}</div></article>})}{!ribs?.length && <p className="text-sm text-neutral-500">Aucun RIB enregistré.</p>}</div>
    </section>

    {autorise("gerer_paie") && <section className="rounded-xl border p-4"><div><h2 className="font-semibold">Bulletins de paie reçus de l’expert-comptable</h2><p className="text-xs text-neutral-500">Le PDF original est conservé dans un stockage privé. Le montant net doit être contrôlé avant préparation du salaire.</p></div><form action={importerBulletinPaieAction} encType="multipart/form-data" className="mt-4 grid gap-2 md:grid-cols-3"><select name="employe_id" required className={champ}><option value="">Salarié…</option>{(employes ?? []).map((employe) => <option key={employe.id} value={employe.id}>{employe.prenom} {employe.nom}</option>)}</select><input name="periode" type="month" required className={champ}/><input name="montant_net_a_payer" type="number" min="0.01" step="0.01" required placeholder="Net à payer (€)" className={champ}/><input name="date_paiement_prevue" type="date" className={champ}/><input name="reference_expert_comptable" placeholder="Référence expert-comptable" className={champ}/><input name="bulletin" type="file" accept="application/pdf" required className={champ}/><button className="rounded-md bg-[#0d1b2a] px-4 py-2 text-sm font-semibold text-white md:col-span-3">Importer et préparer le contrôle</button></form>
      <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-neutral-50 text-left text-xs uppercase text-neutral-500"><tr><th className="px-3 py-2">Période</th><th>Salarié</th><th>Net</th><th>RIB</th><th>Statut</th><th className="px-3 text-right">Actions</th></tr></thead><tbody>{(bulletins ?? []).map((bulletin) => {const employe=un(bulletin.employe as {prenom:string;nom:string}|{prenom:string;nom:string}[]|null);const rib=ribEmploye.get(bulletin.employe_id);return <tr key={bulletin.id} className="border-t"><td className="px-3 py-2">{String(bulletin.periode).slice(0,7)} · v{bulletin.version}</td><td>{employe?.prenom} {employe?.nom}</td><td>{euros(bulletin.montant_net_a_payer)}</td><td>{rib ? `•••• ${rib.iban_quatre_derniers} · ${rib.verification_statut}` : "Absent"}</td><td>{bulletin.statut.replaceAll("_", " ")}</td><td className="px-3"><div className="flex justify-end gap-2">{bulletinUrls.get(bulletin.id) && <a href={bulletinUrls.get(bulletin.id)} target="_blank" rel="noreferrer" className="text-xs text-blue-700">Ouvrir PDF</a>}{bulletin.statut === "a_verifier" && <><form action={validerBulletinPaieAction.bind(null, bulletin.id, true)}><button className="text-xs text-green-700">Valider</button></form><form action={validerBulletinPaieAction.bind(null, bulletin.id, false)}><button className="text-xs text-red-700">Annuler</button></form></>}</div></td></tr>})}{!bulletins?.length && <tr><td colSpan={6} className="p-6 text-center text-neutral-500">Aucun bulletin importé.</td></tr>}</tbody></table></div>
    </section>}

    {autorise("preparer_virements") && <section className="rounded-xl border p-4"><div><h2 className="font-semibold">Paiements à préparer</h2><p className="text-xs text-neutral-500">Sélectionnez les sources. Un lot reste sans effet bancaire jusqu’à sa validation puis son authentification auprès de la banque.</p></div><form action={preparerLotVirementsAction} className="mt-4 space-y-4"><label className="block max-w-xs text-sm font-medium">Date d’exécution<input name="date_execution" type="date" required className={`mt-1 ${champ}`}/></label>
      <div className="grid gap-4 lg:grid-cols-3"><div className="rounded-md border p-3"><h3 className="font-medium">Salaires</h3><div className="mt-2 space-y-2">{(bulletins ?? []).filter((b) => b.statut === "valide").map((bulletin) => {const employe=un(bulletin.employe as {prenom:string;nom:string}|{prenom:string;nom:string}[]|null);const rib=ribEmploye.get(bulletin.employe_id);const pret=rib?.verification_statut === "verifie";return <label key={bulletin.id} className={`flex gap-2 text-sm ${pret ? "" : "opacity-50"}`}><input name="sources" type="checkbox" value={`bulletin:${bulletin.id}`} disabled={!pret}/><span>{employe?.prenom} {employe?.nom}<small className="block text-neutral-500">{String(bulletin.periode).slice(0,7)} · {euros(bulletin.montant_net_a_payer)} · {pret ? `RIB •••• ${rib?.iban_quatre_derniers}` : "RIB vérifié requis"}</small></span></label>})}</div></div>
      <div className="rounded-md border p-3"><h3 className="font-medium">Notes de frais</h3><div className="mt-2 space-y-2">{(notes ?? []).map((note) => {const employe=un(note.employe as {prenom:string;nom:string}|{prenom:string;nom:string}[]|null);const rib=ribEmploye.get(note.employe_id);const pret=rib?.verification_statut === "verifie";return <label key={note.id} className={`flex gap-2 text-sm ${pret ? "" : "opacity-50"}`}><input name="sources" type="checkbox" value={`note:${note.id}`} disabled={!pret}/><span>{note.reference} · {employe?.prenom} {employe?.nom}<small className="block text-neutral-500">{euros(note.montant_ttc)} · {pret ? `RIB •••• ${rib?.iban_quatre_derniers}` : "RIB vérifié requis"}</small></span></label>})}</div></div>
      <div className="rounded-md border p-3"><h3 className="font-medium">Factures fournisseurs</h3><div className="mt-2 space-y-2">{(depenses ?? []).map((depense) => {const fournisseur=un(depense.fournisseur as {nom:string}|{nom:string}[]|null);const rib=ribFournisseur.get(depense.fournisseur_id);const pret=rib?.verification_statut === "verifie";return <label key={depense.id} className={`flex gap-2 text-sm ${pret ? "" : "opacity-50"}`}><input name="sources" type="checkbox" value={`depense:${depense.id}`} disabled={!pret}/><span>{depense.numero_piece} · {fournisseur?.nom}<small className="block text-neutral-500">{euros(Number(depense.montant_ttc)-Number(depense.montant_regle))} · {pret ? `RIB •••• ${rib?.iban_quatre_derniers}` : "RIB vérifié requis"}</small></span></label>})}</div></div></div>
      <button className="rounded-md bg-[#0d1b2a] px-4 py-2 text-sm font-semibold text-white">Créer le lot à valider</button></form>
    </section>}

    <section className="rounded-xl border p-4"><h2 className="font-semibold">Lots de virements</h2><div className="mt-3 space-y-3">{(lots ?? []).map((lot) => <article key={lot.id} className="rounded-md border p-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong>{lot.numero}</strong><p className="text-xs text-neutral-500">{lot.type_lot.replaceAll("_", " ")} · exécution {lot.date_execution} · {lot.nombre_ordres} ordre(s)</p></div><div className="text-right"><strong>{euros(lot.montant_total)}</strong><p className="text-xs">{statutLot[lot.statut] ?? lot.statut}</p></div></div><details className="mt-3"><summary className="cursor-pointer text-xs text-neutral-500">Voir le détail du lot</summary><div className="mt-2 divide-y rounded border">{(lot.ordres ?? []).map((ordre: {id:string;titulaire:string;iban_quatre_derniers:string;montant:number;libelle:string;statut:string}) => <div key={ordre.id} className="flex flex-wrap justify-between gap-2 p-2 text-xs"><span>{ordre.titulaire} · •••• {ordre.iban_quatre_derniers}<small className="block text-neutral-500">{ordre.libelle}</small></span><span>{euros(ordre.montant)} · {ordre.statut}</span></div>)}</div></details>{lot.provider_message && <p className="mt-2 rounded bg-amber-50 p-2 text-xs text-amber-900">{lot.provider_message}</p>}<div className="mt-3 flex flex-wrap gap-2">{autorise("valider_virements") && lot.statut === "a_valider" && <form action={validerLotVirementsAction.bind(null, lot.id)}><button className="rounded border border-green-700 px-3 py-1.5 text-xs font-semibold text-green-800">Valider le lot</button></form>}{autorise("executer_virements") && lot.statut === "valide" && <form action={transmettreLotPowensAction.bind(null, lot.id)}><button className="rounded bg-blue-700 px-3 py-1.5 text-xs font-semibold text-white">Transmettre et ouvrir la banque</button></form>}{autorise("executer_virements") && ["consentement_requis","transmis","en_cours"].includes(lot.statut) && <form action={synchroniserLotPowensAction.bind(null, lot.id)}><button className="rounded border px-3 py-1.5 text-xs font-semibold">Actualiser le statut bancaire</button></form>}{lot.consent_url && lot.statut === "consentement_requis" && <a href={lot.consent_url} className="rounded border px-3 py-1.5 text-xs font-semibold">Reprendre la validation bancaire</a>}{autorise("preparer_virements") && ["a_valider","valide"].includes(lot.statut) && <form action={annulerLotVirementsAction.bind(null, lot.id)}><button className="rounded border border-red-300 px-3 py-1.5 text-xs font-semibold text-red-700">Annuler le lot</button></form>}</div></article>)}{!lots?.length && <p className="text-sm text-neutral-500">Aucun lot préparé.</p>}</div></section>

    <section className="rounded-xl border p-4"><h2 className="font-semibold">Journal bancaire</h2><p className="mb-3 text-xs text-neutral-500">Historique append-only des préparations, validations, transmissions et rapprochements.</p><div className="divide-y">{(journal ?? []).map((entree) => <div key={entree.id} className="flex flex-wrap justify-between gap-2 py-2 text-xs"><span>{entree.action.replaceAll("_", " ")} · {entree.ressource_type.replaceAll("_", " ")}</span><span className="text-neutral-500">{entree.nouveau_statut ?? "—"} · {new Date(entree.created_at).toLocaleString("fr-FR")}</span></div>)}{!journal?.length && <p className="text-sm text-neutral-500">Aucun événement bancaire.</p>}</div></section>
  </div></main>;
}
