import Link from "next/link";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getContexteEntreprise } from "@/lib/entreprise";
import { affecterVehiculeAction, ajouterReleveKilometrageAction } from "@/app/actions/flotte";
import { euros } from "@/lib/devis";
import { IdentificationCodeCard } from "@/components/IdentificationCodeCard";

const un = <T,>(value: T | T[] | null): T | null => Array.isArray(value) ? value[0] ?? null : value;
export default async function VehiculePage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; success?: string }> }) {
  const { id } = await params; const messages = await searchParams; const ctx = await getContexteEntreprise(); const supabase = await createClient();
  const { data: vehicule } = await supabase.from("vehicules").select("*,employe:employes(id,prenom,nom)").eq("id", id).eq("entreprise_id", ctx.entrepriseId).maybeSingle();
  if (!vehicule) notFound();
  const [{ data: releves }, { data: employes }, { data: depenses }, { data: affectations }, { data: travaux }, { data: code }] = await Promise.all([
    supabase.from("releves_kilometrage").select("*").eq("vehicule_id", id).eq("entreprise_id", ctx.entrepriseId).order("date_releve", { ascending: false }),
    supabase.from("employes").select("id,prenom,nom").eq("entreprise_id", ctx.entrepriseId).eq("statut", "actif").order("nom"),
    supabase.from("depenses_fournisseurs").select("id,numero_piece,date_piece,montant_ttc,statut,categorie,travaux_effectues,justificatif_storage_path,fournisseur:fournisseurs(nom),chantier:chantiers(id,nom)").eq("vehicule_id", id).eq("entreprise_id", ctx.entrepriseId).order("date_piece", { ascending: false }),
    supabase.from("affectations_vehicules").select("id,date_debut,date_fin,note,employe:employes(prenom,nom)").eq("vehicule_id", id).eq("entreprise_id", ctx.entrepriseId).order("date_debut", { ascending: false }),
    vehicule.employe_id ? supabase.from("pointages").select("id,date,tache,heures_normales,heures_supplementaires,chantier:chantiers(id,nom)").eq("entreprise_id", ctx.entrepriseId).eq("employe_id", vehicule.employe_id).order("date", { ascending: false }).limit(12) : Promise.resolve({ data: [] }),
    supabase.from("codes_identification").select("id,code").eq("entreprise_id",ctx.entrepriseId).eq("type_ressource","vehicule").eq("ressource_id",id).eq("actif",true).maybeSingle(),
  ]);
  const employe = un(vehicule.employe as { id: string; prenom: string; nom: string } | { id: string; prenom: string; nom: string }[] | null);
  const total = (depenses ?? []).filter((item) => item.statut !== "annulee").reduce((sum, item) => sum + Number(item.montant_ttc), 0);
  const heures = (travaux ?? []).reduce((sum, item) => sum + Number(item.heures_normales) + Number(item.heures_supplementaires), 0);
  const relever = ajouterReleveKilometrageAction.bind(null, id); const affecter = affecterVehiculeAction.bind(null, id);
  return <main className="p-8"><div className="mx-auto max-w-5xl space-y-6">
    <div><Link href="/flotte" className="text-sm text-neutral-500 hover:underline">← Flotte</Link><h1 className="mt-1 text-xl font-semibold">{vehicule.marque} {vehicule.modele}</h1><p className="font-mono text-sm text-neutral-500">{vehicule.immatriculation}</p></div>
    {messages.error && <p className="rounded bg-red-50 p-3 text-sm text-red-700">{messages.error}</p>}{messages.success && <p className="rounded bg-green-50 p-3 text-sm text-green-700">{messages.success}</p>}
    <section className="grid gap-3 sm:grid-cols-5"><div className="rounded-md border p-4"><p className="text-xs text-neutral-500">Kilométrage</p><p className="text-xl font-semibold">{Number(vehicule.kilometrage).toLocaleString("fr-FR")} km</p></div><div className="rounded-md border p-4"><p className="text-xs text-neutral-500">Statut</p><p className="font-semibold">{vehicule.statut}</p></div><div className="rounded-md border p-4"><p className="text-xs text-neutral-500">Ouvrier assigné</p><p>{employe ? `${employe.prenom} ${employe.nom}` : "Non assigné"}</p></div><div className="rounded-md border p-4"><p className="text-xs text-neutral-500">Coûts facturés</p><p className="text-xl font-semibold">{euros(total)}</p></div><div className="rounded-md border p-4"><p className="text-xs text-neutral-500">Travaux récents</p><p className="text-xl font-semibold">{heures} h</p></div></section>
    {code&&<IdentificationCodeCard id={code.id} code={code.code} label="Étiquette QR du véhicule"/>}
    <form action={affecter} className="grid items-end gap-3 rounded-md border p-4 sm:grid-cols-[1fr_1fr_auto]"><label className="text-sm">Affecter le véhicule<select name="employe_id" defaultValue={employe?.id ?? ""} className="mt-1 w-full rounded border px-3 py-2"><option value="">Aucun ouvrier</option>{employes?.map((item) => <option key={item.id} value={item.id}>{item.prenom} {item.nom}</option>)}</select></label><label className="text-sm">Note d’affectation<input name="note" placeholder="Usage principal, état de remise…" className="mt-1 w-full rounded border px-3 py-2" /></label><button className="rounded bg-[#0d1b2a] px-4 py-2 text-sm text-white">Enregistrer</button></form>
    <form action={relever} className="flex items-end gap-3 rounded-md border p-4"><label className="flex-1 text-sm">Nouveau kilométrage<input name="kilometrage" type="number" min={vehicule.kilometrage} required className="mt-1 w-full rounded-md border px-3 py-2" /></label><label className="text-sm">Date<input name="date_releve" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required className="mt-1 block rounded-md border px-3 py-2" /></label><button className="rounded-md bg-neutral-900 px-4 py-2 text-sm text-white">Enregistrer</button></form>
    <section><h2 className="mb-2 font-semibold">Factures et travaux associés au véhicule</h2><div className="rounded border">{depenses?.map((depense) => { const fournisseur = un(depense.fournisseur as { nom: string } | { nom: string }[] | null); const chantier = un(depense.chantier as { id: string; nom: string } | { id: string; nom: string }[] | null); return <Link key={depense.id} href={`/depenses/${depense.id}`} className="block border-t px-3 py-3 text-sm first:border-0 hover:bg-neutral-50"><div className="grid gap-2 sm:grid-cols-[110px_1fr_1fr_120px_90px]"><span>{depense.date_piece}</span><span>{depense.numero_piece} · {fournisseur?.nom}</span><span className="text-neutral-500">{chantier?.nom ?? depense.categorie}</span><strong className="text-right">{euros(depense.montant_ttc)}</strong><span className="text-right text-xs">{depense.justificatif_storage_path ? "PDF/scan ✓" : "Sans pièce"}</span></div>{depense.travaux_effectues&&<p className="mt-2 rounded bg-neutral-50 p-2 text-xs"><strong>Travaux :</strong> {depense.travaux_effectues}</p>}</Link>; })}{!depenses?.length && <p className="p-6 text-center text-sm text-neutral-500">Aucune facture liée.</p>}</div></section>
    <section><h2 className="mb-2 font-semibold">Résumé des travaux de l’ouvrier assigné</h2><p className="mb-3 text-xs text-neutral-500">Activité récente de {employe ? `${employe.prenom} ${employe.nom}` : "l’ouvrier affecté"}. Le lien direct véhicule/chantier reste confirmé par la facture ou la note d’affectation.</p><div className="rounded border">{(travaux ?? []).map((travail) => { const chantier = un(travail.chantier as { id: string; nom: string } | { id: string; nom: string }[] | null); return <div key={travail.id} className="grid gap-2 border-t px-3 py-2 text-sm first:border-0 sm:grid-cols-[110px_1fr_100px]"><span>{travail.date}</span><span>{chantier?.nom ?? "Chantier"} · {travail.tache ?? "Travaux chantier"}</span><strong className="text-right">{Number(travail.heures_normales) + Number(travail.heures_supplementaires)} h</strong></div>; })}{!travaux?.length && <p className="p-6 text-center text-sm text-neutral-500">Aucun travail récent pour l’ouvrier assigné.</p>}</div></section>
    <section className="grid gap-6 md:grid-cols-2"><div><h2 className="mb-2 font-semibold">Historique des affectations</h2>{(affectations ?? []).map((item) => { const personne = un(item.employe as { prenom: string; nom: string } | { prenom: string; nom: string }[] | null); return <div key={item.id} className="border-t py-2 text-sm"><strong>{personne ? `${personne.prenom} ${personne.nom}` : "Non assigné"}</strong><div className="text-xs text-neutral-500">Depuis le {new Date(item.date_debut).toLocaleDateString("fr-FR")}{item.date_fin ? ` jusqu’au ${new Date(item.date_fin).toLocaleDateString("fr-FR")}` : " · en cours"}</div>{item.note && <p className="text-xs">{item.note}</p>}</div>; })}</div><div><h2 className="mb-2 font-semibold">Historique kilométrique</h2>{(releves ?? []).map((item) => <div key={item.id} className="flex justify-between border-t py-2 text-sm"><span>{item.date_releve}</span><strong>{Number(item.kilometrage).toLocaleString("fr-FR")} km</strong><span className="text-neutral-500">{item.note ?? ""}</span></div>)}</div></section>
  </div></main>;
}
