import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { getContexteEntreprise } from "@/lib/entreprise";
import { OUTIL_CATEGORIES, OUTIL_STATUTS } from "@/lib/outillage";
import { importerOutilsAction } from "@/app/actions/outillage";

const un=<T,>(value:T|T[]|null):T|null=>Array.isArray(value)?value[0]??null:value;
export default async function OutillagePage({searchParams}:{searchParams:Promise<{error?:string;success?:string}>}) {
  const messages=await searchParams,ctx=await getContexteEntreprise(),supabase=await createClient();
  const {data:outils}=await supabase.from("outils").select("id,reference,designation,categorie,marque,modele,statut,etat,prochaine_verification,employe:employes(prenom,nom),chantier:chantiers(nom)").eq("entreprise_id",ctx.entrepriseId).order("reference");
  const alertes=(outils??[]).filter(outil=>outil.prochaine_verification&&outil.prochaine_verification<=new Date().toISOString().slice(0,10)).length;
  return <main className="p-8"><div className="mx-auto max-w-6xl space-y-6">
    <div className="flex items-center justify-between"><div><h1 className="text-xl font-semibold">Outillage</h1><p className="text-sm text-neutral-500">{outils?.length??0} outil(s) · {alertes} vérification(s) échue(s)</p></div><Link href="/outillage/nouveau" className="rounded-md bg-neutral-900 px-4 py-2 text-sm font-medium text-white">+ Nouvel outil</Link></div>
    {messages.error&&<p className="rounded bg-red-50 p-3 text-sm text-red-700">{messages.error}</p>}{messages.success&&<p className="rounded bg-green-50 p-3 text-sm text-green-700">{messages.success}</p>}
    <form action={importerOutilsAction} encType="multipart/form-data" className="flex flex-wrap items-end gap-3 rounded-md border border-[#c9a24a]/40 bg-[#c9a24a]/5 p-4"><div className="min-w-64 flex-1"><h2 className="font-semibold">Importer une liste d’outillage</h2><p className="text-xs text-neutral-500">Excel, CSV ou PDF : référence, désignation, catégorie, marque, modèle, série, état et prix.</p></div><input name="fichier" type="file" accept=".xlsx,.csv,.pdf,application/pdf" required className="rounded border px-3 py-2 text-sm"/><button className="rounded bg-[#0d1b2a] px-4 py-2 text-sm text-white">Importer</button></form>
    <div className="overflow-hidden rounded-md border dark:border-neutral-800"><table className="w-full text-sm"><thead className="bg-neutral-50 text-left text-xs uppercase text-neutral-500 dark:bg-neutral-900"><tr><th className="px-3 py-2">Réf.</th><th>Outil</th><th>Catégorie</th><th>Affectation</th><th>État</th><th>Statut</th><th>Vérification</th></tr></thead><tbody>{(outils??[]).map(outil=>{const employe=un(outil.employe as {prenom:string;nom:string}|{prenom:string;nom:string}[]|null),chantier=un(outil.chantier as {nom:string}|{nom:string}[]|null),statut=OUTIL_STATUTS[outil.statut]??OUTIL_STATUTS.disponible,horsService=outil.statut==="hors_service";return <tr key={outil.id} className={`border-t dark:border-neutral-800 ${horsService?"bg-red-50/60 opacity-70 dark:bg-red-950/20":""}`}><td className="px-3 py-3 font-mono"><Link href={`/outillage/${outil.id}`} className="hover:underline">{outil.reference}</Link></td><td className="font-medium">{outil.designation}<span className="block text-xs font-normal text-neutral-500">{[outil.marque,outil.modele].filter(Boolean).join(" ")}</span></td><td>{OUTIL_CATEGORIES[outil.categorie]}</td><td>{horsService?<strong className="text-red-700">Indisponible</strong>:employe?`${employe.prenom} ${employe.nom}`:chantier?.nom??"—"}</td><td className="capitalize">{outil.etat.replace("_"," ")}</td><td><span className="inline-flex items-center gap-1.5"><span className="h-2 w-2 rounded-full" style={{background:statut.couleur}}/>{statut.label}</span></td><td className={outil.prochaine_verification&&outil.prochaine_verification<=new Date().toISOString().slice(0,10)?"text-red-600":""}>{outil.prochaine_verification??"—"}</td></tr>})}{!outils?.length&&<tr><td colSpan={7} className="p-8 text-center text-neutral-500">Aucun outil enregistré.</td></tr>}</tbody></table></div>
  </div></main>;
}
