import { getContexteEntreprise } from "@/lib/entreprise";
import { createClient } from "@/lib/supabase/server";
import { creerMetreAction, creerModeleDevisAction } from "@/app/actions/suite-metier";
import { euros } from "@/lib/devis";

const champ="mt-1 w-full rounded-md border border-neutral-300 bg-white px-3 py-2 text-sm dark:border-neutral-700 dark:bg-neutral-900";
const un=<T,>(v:T|T[]|null):T|null=>Array.isArray(v)?v[0]??null:v;
export default async function OuvragesPage({searchParams}:{searchParams:Promise<{error?:string;success?:string}>}){
 const message=await searchParams,ctx=await getContexteEntreprise(),sb=await createClient();
 const [{data:modeles},{data:metres},{data:chantiers},{data:devis}]=await Promise.all([
  sb.from("modeles_devis").select("id,nom,description,categorie,actif,lignes:lignes_modeles_devis(id,designation,type,quantite,unite,prix_unitaire_ht,taux_tva,ordre)").eq("entreprise_id",ctx.entrepriseId).order("nom"),
  sb.from("metres").select("id,numero,nom,date_releve,notes,chantier:chantiers(nom),devis:devis(numero),lignes:lignes_metres(id,designation,resultat,unite,formule)").eq("entreprise_id",ctx.entrepriseId).order("created_at",{ascending:false}),
  sb.from("chantiers").select("id,nom").eq("entreprise_id",ctx.entrepriseId).not("statut","in","(archive,annule)").order("nom"),
  sb.from("devis").select("id,numero").eq("entreprise_id",ctx.entrepriseId).order("created_at",{ascending:false}).limit(100),
 ]);
 return <main className="p-4 sm:p-8"><div className="mx-auto max-w-7xl space-y-6"><header><h1 className="text-xl font-semibold">Ouvrages, modèles et métrés</h1><p className="text-sm text-neutral-500">Bibliothèque de devis chiffrés et calculs de surfaces, longueurs et quantités.</p></header>{message.error&&<p className="rounded bg-red-50 p-3 text-sm text-red-700">{message.error}</p>}{message.success&&<p className="rounded bg-green-50 p-3 text-sm text-green-700">{message.success}</p>}
 <div className="grid gap-4 xl:grid-cols-2"><form action={creerModeleDevisAction} className="grid gap-3 rounded-xl border p-4 sm:grid-cols-2"><h2 className="font-semibold sm:col-span-2">Nouveau modèle chiffré</h2><label className="text-xs">Nom du modèle<input required name="nom" placeholder="Rénovation complète d’une pièce" className={champ}/></label><label className="text-xs">Catégorie<input name="categorie" placeholder="Aménagement intérieur" className={champ}/></label><label className="text-xs sm:col-span-2">Description<textarea name="description" rows={2} className={champ}/></label><div className="rounded-lg bg-neutral-50 p-3 dark:bg-neutral-900 sm:col-span-2"><h3 className="mb-2 text-sm font-semibold">Première ligne</h3><div className="grid gap-3 sm:grid-cols-3"><label className="text-xs sm:col-span-2">Désignation<input name="designation" placeholder="Fourniture et pose" className={champ}/></label><label className="text-xs">Type<select name="ligne_type" className={champ}><option value="forfait">Forfait</option><option value="main_oeuvre">Main-d’œuvre</option><option value="fourniture">Fourniture</option><option value="sous_traitance">Sous-traitance</option><option value="deplacement">Déplacement</option></select></label><label className="text-xs">Quantité<input name="quantite" type="number" step="0.001" defaultValue="1" className={champ}/></label><label className="text-xs">Unité<input name="unite" defaultValue="u" className={champ}/></label><label className="text-xs">Prix unitaire HT<input name="prix_unitaire_ht" type="number" step="0.01" defaultValue="0" className={champ}/></label><label className="text-xs">TVA (%)<input name="taux_tva" type="number" step="0.01" defaultValue="20" className={champ}/></label></div></div><button className="rounded bg-blue-700 px-4 py-2 text-sm font-semibold text-white sm:col-span-2">Créer le modèle</button></form>
 <form action={creerMetreAction} className="grid gap-3 rounded-xl border p-4 sm:grid-cols-2"><h2 className="font-semibold sm:col-span-2">Nouveau métré assisté</h2><label className="text-xs">Nom<input required name="nom" placeholder="Métré cloisons étage 1" className={champ}/></label><label className="text-xs">Chantier<select name="chantier_id" className={champ}><option value="">Sans chantier</option>{(chantiers??[]).map(c=><option key={c.id} value={c.id}>{c.nom}</option>)}</select></label><label className="text-xs">Devis associé<select name="devis_id" className={champ}><option value="">Aucun</option>{(devis??[]).map(d=><option key={d.id} value={d.id}>{d.numero||"Brouillon"}</option>)}</select></label><label className="text-xs">Désignation<input required name="designation" placeholder="Cloisons vitrées" className={champ}/></label><label className="text-xs">Longueur<input required name="longueur" type="number" min="0" step="0.001" className={champ}/></label><label className="text-xs">Largeur<input name="largeur" type="number" min="0" step="0.001" className={champ}/></label><label className="text-xs">Hauteur<input name="hauteur" type="number" min="0" step="0.001" className={champ}/></label><label className="text-xs">Nombre<input name="nombre" type="number" min="0" step="0.001" defaultValue="1" className={champ}/></label><label className="text-xs">Déduction<input name="deduction" type="number" min="0" step="0.001" defaultValue="0" className={champ}/></label><label className="text-xs">Unité<select name="unite" className={champ}><option value="m²">m²</option><option value="ml">ml</option><option value="m³">m³</option><option value="u">unité</option></select></label><label className="text-xs sm:col-span-2">Notes<textarea name="notes" rows={2} className={champ}/></label><button className="rounded bg-neutral-900 px-4 py-2 text-sm font-semibold text-white dark:bg-white dark:text-neutral-900 sm:col-span-2">Calculer et enregistrer</button></form></div>
 <section><h2 className="mb-3 font-semibold">Bibliothèque personnalisée</h2><div className="grid gap-3 lg:grid-cols-2">{(modeles??[]).map(m=><article key={m.id} className="rounded-xl border p-4"><div className="flex justify-between"><div><strong>{m.nom}</strong><p className="text-xs text-neutral-500">{m.categorie||"Sans catégorie"}</p></div><span className="text-xs text-neutral-500">{m.lignes?.length??0} ligne(s)</span></div>{m.description&&<p className="mt-2 text-sm">{m.description}</p>}<div className="mt-3 space-y-1">{(m.lignes??[]).slice(0,5).map(l=><div key={l.id} className="flex justify-between rounded bg-neutral-50 px-2 py-1.5 text-xs dark:bg-neutral-900"><span>{l.designation} · {l.quantite} {l.unite}</span><span className="font-mono">{euros(Number(l.quantite)*Number(l.prix_unitaire_ht))}</span></div>)}</div></article>)}{!modeles?.length&&<p className="rounded-xl border border-dashed p-8 text-center text-sm text-neutral-500 lg:col-span-2">Aucun modèle.</p>}</div></section>
 <section><h2 className="mb-3 font-semibold">Métrés enregistrés</h2><div className="grid gap-3 lg:grid-cols-2">{(metres??[]).map(m=>{const ch=un(m.chantier),d=un(m.devis);return <article key={m.id} className="rounded-xl border p-4"><div className="flex justify-between"><div><strong>{m.numero} · {m.nom}</strong><p className="text-xs text-neutral-500">{ch?.nom||"Sans chantier"}{d?` · ${d.numero}`:""}</p></div><span className="text-xs">{m.date_releve}</span></div><div className="mt-3 space-y-2">{(m.lignes??[]).map(l=><div key={l.id} className="rounded bg-blue-50 p-2 text-sm dark:bg-blue-950/30"><div className="flex justify-between"><span>{l.designation}</span><strong>{Number(l.resultat).toLocaleString("fr-FR")} {l.unite}</strong></div><p className="text-xs text-neutral-500">{l.formule}</p></div>)}</div></article>})}{!metres?.length&&<p className="rounded-xl border border-dashed p-8 text-center text-sm text-neutral-500 lg:col-span-2">Aucun métré.</p>}</div></section>
 </div></main>;
}
