import Link from "next/link";
import { getContexteColors } from "@/lib/contexte";
import { resoudreRoleColors } from "@/lib/acces-colors";
import { peutEffectuerColors } from "@/lib/permissions-colors";
import { listerEmplacementsColors, listerSeauxColors, obtenirParametresColors } from "@/lib/metier-colors";
import { creerSeauAction } from "@/app/actions-metier";
import { FlashMessage } from "@/components/FlashMessage";
import { formaterQuantite } from "@/lib/quantites";

type Recherche={q?:string;etat?:string;emplacement?:string;faible?:string;sansPhoto?:string;archives?:string;ok?:string;erreur?:string};
export default async function InventairePage({searchParams}:{searchParams:Promise<Recherche>}){
  const [contexte,f]=await Promise.all([getContexteColors(),searchParams]);if(!contexte.entrepriseId)return null;
  const role=await resoudreRoleColors(contexte);const peutAjouter=peutEffectuerColors(role,"ajouter_seau");
  const [seaux,emplacements,parametres]=await Promise.all([listerSeauxColors(contexte.entrepriseId,{q:f.q,etat:f.etat,emplacement:f.emplacement,faible:f.faible==="1",sansPhoto:f.sansPhoto==="1",archives:f.archives==="1"}),listerEmplacementsColors(contexte.entrepriseId),obtenirParametresColors(contexte.entrepriseId)]);
  return <><header className="page-heading"><div><span className="eyebrow">Stock dédié</span><h1>Inventaire Colors</h1><p>Chaque seau est individualisé, localisé et historisé, sans utiliser le stock générique de Gestion Pro.</p></div>{peutEffectuerColors(role,"exporter")&&<a className="outline-button" href="/api/export/inventaire">Exporter en CSV</a>}</header><FlashMessage ok={f.ok} erreur={f.erreur}/>
  <form className="filter-bar"><label className="grow">Rechercher<input name="q" defaultValue={f.q} placeholder="Marque, produit, teinte, HEX, RAL…"/></label><label>État<select name="etat" defaultValue={f.etat??"tous"}><option value="tous">Tous</option><option value="ferme">Fermé</option><option value="ouvert">Ouvert</option><option value="vide">Vide</option><option value="archive">Archivé</option></select></label><label>Emplacement<select name="emplacement" defaultValue={f.emplacement??""}><option value="">Tous</option>{emplacements.map(e=><option key={e.id} value={e.id}>{e.nom}</option>)}</select></label><label className="check"><input type="checkbox" name="faible" value="1" defaultChecked={f.faible==="1"}/> Stock faible</label><label className="check"><input type="checkbox" name="sansPhoto" value="1" defaultChecked={f.sansPhoto==="1"}/> Sans photo</label><button className="primary-action">Filtrer</button></form>
  {peutAjouter&&<details className="panel create-panel"><summary>Ajouter un seau manuellement</summary><form action={creerSeauAction} className="form-grid"><label>Marque<input name="marque" required maxLength={120}/></label><label>Produit<input name="produit" required maxLength={180}/></label><label>Référence<input name="reference_produit"/></label><label>Teinte<input name="teinte_nom"/></label><label>Référence teinte<input name="teinte_reference"/></label><label>Couleur HEX<input name="couleur_hex" pattern="#[0-9A-Fa-f]{6}" placeholder="#F2EFEA"/></label><label>Mode<select name="mode_quantite" defaultValue="volume"><option value="volume">Volume</option><option value="poids">Poids</option><option value="pourcentage">Pourcentage estimé</option></select></label><label>Unité<select name="unite" defaultValue="l"><option value="l">litres</option><option value="ml">ml</option><option value="kg">kg</option><option value="g">g</option><option value="pourcent">%</option></select></label><label>Quantité nominale<input name="quantite_nominale" type="number" min="0" step="0.01" defaultValue="10"/></label><label>Quantité restante<input name="quantite_restante" type="number" min="0" step="0.01" defaultValue="10"/></label><label>Pourcentage estimé<input name="pourcentage_saisi" type="number" min="0" max="100" step="1" defaultValue="100"/></label><label>État<select name="etat" defaultValue="ferme"><option value="ferme">Fermé</option><option value="ouvert">Ouvert</option><option value="vide">Vide</option></select></label><label>Emplacement<select name="emplacement_id" defaultValue=""><option value="">Non rangé</option>{emplacements.map(e=><option key={e.id} value={e.id}>{e.nom}</option>)}</select></label><label className="wide">Notes<textarea name="notes" rows={3}/></label><button className="primary-action wide">Créer le seau</button></form></details>}
  <section className="inventory-grid" aria-label={`${seaux.length} seaux`}>{seaux.map(s=><Link href={`/inventaire/${s.id}`} className="bucket-card" key={s.id}><span className="swatch" style={{background:s.couleur_hex??"#e9e2e7"}}/><div className="bucket-head"><span className={`badge state-${s.etat}`}>{s.etat}</span>{s.etat!=="archive"&&s.etat!=="vide"&&s.pourcentage_restant<=parametres.seuil_stock_faible_pourcent&&<span className="badge">Stock faible ≤ {parametres.seuil_stock_faible_pourcent}%</span>}<strong>{s.marque} — {s.produit}</strong><small>{s.teinte_nom??s.teinte_reference??"Teinte non renseignée"}</small></div><div className="level"><i style={{width:`${Math.max(0,Math.min(100,s.pourcentage_restant))}%`}}/></div><div className="bucket-meta"><span>{formaterQuantite({mode:s.mode_quantite,unite:s.unite,nominale:s.quantite_nominale,restante:s.quantite_restante,pourcentage:s.pourcentage_saisi})}</span><span>{s.colors_emplacements?.nom??"Non rangé"}</span></div></Link>)}</section>{seaux.length===0&&<div className="empty-state"><strong>Aucun seau ne correspond.</strong><span>Modifiez les filtres ou ajoutez le premier seau Colors.</span></div>}</>;
}
