"use client";
import{useEffect,useState}from"react";
import{declarerPointageOublieAction}from"@/app/actions/pointages";
import{SearchableSelect}from"@/components/SearchableSelect";
type Chantier={id:string;nom:string};const input="w-full rounded-md border px-3 py-2 text-sm dark:bg-neutral-900";
export function ForgottenPointageForm({chantiers}:{chantiers:Chantier[]}){
 const[position,setPosition]=useState<{lat:number;lng:number;precision:number}|null>(null),[erreur,setErreur]=useState("");
 const[explication,setExplication]=useState("");
 useEffect(()=>{if(!navigator.geolocation)return;const id=navigator.geolocation.watchPosition(p=>{setPosition({lat:p.coords.latitude,lng:p.coords.longitude,precision:p.coords.accuracy});setErreur("");},e=>setErreur(e.message),{enableHighAccuracy:true,maximumAge:10000});return()=>navigator.geolocation.clearWatch(id);},[]);
 return <details className="rounded-lg border"><summary className="cursor-pointer p-4 text-sm font-semibold">J’ai oublié de pointer mon arrivée ou mon départ</summary><form action={declarerPointageOublieAction} className="grid gap-3 border-t p-4 sm:grid-cols-2 lg:grid-cols-4"><p className="text-xs text-neutral-500 sm:col-span-2 lg:col-span-4">Déclarez les horaires réellement effectués. La position GPS actuelle (si disponible), l’heure de déclaration et une alerte responsable sont enregistrées. Le pointage devra être validé.</p><input type="hidden" name="latitude" value={position?.lat??""}/><input type="hidden" name="longitude" value={position?.lng??""}/><input type="hidden" name="precision_metres" value={position?.precision??""}/><input type="hidden" name="motif_sans_gps" value={position?"":explication}/><label className="text-xs">Date<input name="date" type="date" required max={new Date().toISOString().slice(0,10)} className={`${input} mt-1`}/></label><label className="text-xs">Chantier<SearchableSelect name="chantier_id" required options={chantiers.map(c=>({value:c.id,label:c.nom}))} placeholder="Écrire le nom du chantier…" className="mt-1"/></label><label className="text-xs">Arrivée<input name="heure_arrivee" type="time" required className={`${input} mt-1`}/></label><label className="text-xs">Départ<input name="heure_depart" type="time" required className={`${input} mt-1`}/></label><label className="text-xs">Pause (minutes)<input name="pause_minutes" type="number" min="0" max="1440" step="5" defaultValue="45" className={`${input} mt-1`}/></label><label className="text-xs sm:col-span-2 lg:col-span-3">Explication obligatoire<input name="commentaire" required value={explication} onChange={e=>setExplication(e.target.value)} placeholder="Ex. oubli du pointage de départ" className={`${input} mt-1`}/></label><div className="sm:col-span-2 lg:col-span-4">{position?<p className="mb-2 text-xs text-green-700">GPS de déclaration prêt · ± {Math.round(position.precision)} m</p>:<p className="mb-2 text-xs text-amber-700">Pas de position GPS ({erreur||"indisponible sur cet appareil"}) : l’explication ci-dessous sera transmise à la place.</p>}<button disabled={!position&&!explication.trim()} className="w-full rounded bg-amber-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Transmettre pour vérification</button></div></form></details>;
}
