"use client";
import { useState } from "react";
import { creerPointageAction } from "@/app/actions/pointages";
type Option={id:string;nom:string};
const input="rounded-md border border-neutral-300 px-2 py-1.5 text-sm dark:border-neutral-700 dark:bg-neutral-900";
export function PointageTerrainForm({employes,chantiers,mois,aujourdhui}:{employes:Option[];chantiers:Option[];mois:string;aujourdhui:string}) {
  const [position,setPosition]=useState<{lat:number;lng:number;precision:number}|null>(null),[geoError,setGeoError]=useState(""),[recherche,setRecherche]=useState(false);
  const localiser=()=>{setRecherche(true);setGeoError("");if(!navigator.geolocation){setGeoError("La géolocalisation n’est pas disponible sur cet appareil.");setRecherche(false);return;}navigator.geolocation.getCurrentPosition(p=>{setPosition({lat:p.coords.latitude,lng:p.coords.longitude,precision:p.coords.accuracy});setRecherche(false);},e=>{setGeoError(e.message||"Position impossible à obtenir.");setRecherche(false);},{enableHighAccuracy:true,timeout:15000,maximumAge:0});};
  return <form action={creerPointageAction} className="grid grid-cols-6 items-end gap-3 rounded-md border p-4">
    <input type="hidden" name="mois" value={mois}/><input type="hidden" name="latitude" value={position?.lat??""}/><input type="hidden" name="longitude" value={position?.lng??""}/><input type="hidden" name="precision_metres" value={position?.precision??""}/>
    <label className="space-y-1 text-xs text-neutral-500">Employé<select name="employe_id" required className={`${input} w-full`}>{employes.map(e=><option key={e.id} value={e.id}>{e.nom}</option>)}</select></label><label className="space-y-1 text-xs text-neutral-500">Chantier<select name="chantier_id" required className={`${input} w-full`}>{chantiers.map(c=><option key={c.id} value={c.id}>{c.nom}</option>)}</select></label><label className="space-y-1 text-xs text-neutral-500">Date<input name="date" type="date" required defaultValue={aujourdhui} className={`${input} w-full`}/></label><label className="space-y-1 text-xs text-neutral-500">Heures<input name="heures_normales" type="number" min="0" max="24" step="0.25" required defaultValue="7" className={`${input} w-full`}/></label><label className="space-y-1 text-xs text-neutral-500">Heures sup.<input name="heures_supplementaires" type="number" min="0" max="24" step="0.25" defaultValue="0" className={`${input} w-full`}/></label><label className="space-y-1 text-xs text-neutral-500">Pause (min)<input name="pause_minutes" type="number" min="0" max="1440" step="5" defaultValue="0" className={`${input} w-full`}/></label>
    <label className="col-span-2 space-y-1 text-xs text-neutral-500">Tâche<input name="tache" required placeholder="Pose cloisons…" className={`${input} w-full`}/></label><label className="col-span-4 space-y-1 text-xs text-neutral-500">Commentaire<input name="commentaire" className={`${input} w-full`}/></label>
    <div className="col-span-3 rounded-md border border-dashed p-3"><p className="text-xs font-semibold uppercase text-neutral-500">Preuve GPS</p><button type="button" onClick={localiser} disabled={recherche} className="mt-2 rounded-md border px-3 py-2 text-sm font-medium">{recherche?"Localisation…":position?"Actualiser ma position":"Utiliser ma position"}</button>{position&&<p className="mt-2 text-xs text-green-700">Position enregistrée · précision ± {Math.round(position.precision)} m</p>}{geoError&&<p className="mt-2 text-xs text-red-600">{geoError}</p>}</div>
    <label className="col-span-3 rounded-md border border-dashed p-3 text-xs text-neutral-500">Photo de vérification *<input name="photo" type="file" accept="image/png,image/jpeg,image/webp" capture="environment" required className="mt-2 block w-full text-sm"/><span className="mt-1 block">Prenez une photo du chantier au moment du pointage (10 Mo max.).</span></label>
    <button disabled={!position} className="col-span-6 rounded-md bg-neutral-900 px-3 py-2 text-sm font-medium text-white disabled:cursor-not-allowed disabled:opacity-40">Enregistrer le pointage terrain</button>
  </form>;
}
