import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { getContexteEntreprise } from "@/lib/entreprise";
import { euros } from "@/lib/devis";
import { projectionHebdomadaire, type FluxTresorerie } from "@/lib/tresorerie";

const JOUR = 86_400_000;
const iso = (date: Date) => date.toISOString().slice(0, 10);
const dateFr = (date: Date) => new Intl.DateTimeFormat("fr-FR", { day: "2-digit", month: "short" }).format(date);
const ajouterMois = (date: Date, mois: number) => { const jour = date.getDate(); const cible = new Date(date.getFullYear(), date.getMonth() + mois, 1, 12); const dernierJour = new Date(cible.getFullYear(), cible.getMonth() + 1, 0, 12).getDate(); cible.setDate(Math.min(jour, dernierJour)); return cible; };

export default async function TresoreriePage() {
  const ctx = await getContexteEntreprise(); const supabase = await createClient();
  const maintenant = new Date(); const aujourdHui = new Date(`${iso(maintenant)}T12:00:00`);
  const depuis30Jours = iso(new Date(aujourdHui.getTime() - 29 * JOUR));
  const [{ data: factures }, { data: depenses }, { data: encaissements }, { data: decaissements }, { data: charges }] = await Promise.all([
    supabase.from("factures").select("id,numero,date_emission,date_echeance,montant_ttc,montant_paye,statut,client:clients(nom,prenom,societe)").eq("entreprise_id",ctx.entrepriseId),
    supabase.from("depenses_fournisseurs").select("id,numero_piece,date_piece,date_echeance,montant_ttc,montant_regle,statut,fournisseur:fournisseurs(nom)").eq("entreprise_id",ctx.entrepriseId),
    supabase.from("paiements").select("montant,date,facture:factures!inner(entreprise_id)").eq("facture.entreprise_id",ctx.entrepriseId).gte("date",depuis30Jours),
    supabase.from("reglements_fournisseurs").select("montant,date,depense:depenses_fournisseurs!inner(entreprise_id)").eq("depense.entreprise_id",ctx.entrepriseId).gte("date",depuis30Jours),
    supabase.from("charges_recurrentes").select("periodicite,montant_ht,montant_tva,prochaine_echeance,date_fin").eq("entreprise_id",ctx.entrepriseId).eq("actif",true),
  ]);
  const entrees30=(encaissements??[]).reduce((s,x)=>s+Number(x.montant),0),sorties30=(decaissements??[]).reduce((s,x)=>s+Number(x.montant),0);
  const aEncaisser=(factures??[]).filter(f=>!["payee","annulee","avoir_emis","brouillon"].includes(f.statut)).reduce((s,f)=>s+Math.max(0,Number(f.montant_ttc)-Number(f.montant_paye)),0);
  const aPayer=(depenses??[]).filter(d=>!["payee","annulee"].includes(d.statut)).reduce((s,d)=>s+Math.max(0,Number(d.montant_ttc)-Number(d.montant_regle)),0);
  const flux: FluxTresorerie[]=[];
  for(const f of factures??[]){if(["payee","annulee","avoir_emis","brouillon"].includes(f.statut))continue;const reste=Math.max(0,Number(f.montant_ttc)-Number(f.montant_paye));if(reste)flux.push({date:f.date_echeance??f.date_emission,montant:reste,type:"entree"});}
  for(const d of depenses??[]){if(["payee","annulee"].includes(d.statut))continue;const reste=Math.max(0,Number(d.montant_ttc)-Number(d.montant_regle));if(reste)flux.push({date:d.date_echeance??d.date_piece,montant:reste,type:"sortie"});}
  for(const charge of charges??[]){let date=new Date(`${charge.prochaine_echeance}T12:00:00`);const fin=charge.date_fin?Date.parse(`${charge.date_fin}T12:00:00`):Infinity;for(let i=0;i<4&&date.getTime()<=fin;i++){flux.push({date:iso(date),montant:Number(charge.montant_ht)+Number(charge.montant_tva),type:"sortie"});const mois=charge.periodicite==="mensuelle"?1:charge.periodicite==="trimestrielle"?3:12;date=ajouterMois(date,mois);}}
  const projection=projectionHebdomadaire(flux,iso(aujourdHui));const maxFlux=Math.max(1,...projection.flatMap(s=>[s.entrees,s.sorties]));
  const attendu90=projection.reduce((s,x)=>s+x.entrees,0),aPayer90=projection.reduce((s,x)=>s+x.sorties,0);
  return <main className="p-8"><div className="mx-auto max-w-6xl space-y-6"><div><h1 className="text-xl font-semibold">Trésorerie prévisionnelle</h1><p className="text-sm text-neutral-500">Flux réalisés sur 30 jours et échéances attendues sur 90 jours.</p></div>
    <div className="grid grid-cols-5 gap-3"><div className="rounded border p-4"><p className="text-xs text-neutral-500">Encaissé · 30 j</p><strong className="text-lg text-green-700">{euros(entrees30)}</strong></div><div className="rounded border p-4"><p className="text-xs text-neutral-500">Décaissé · 30 j</p><strong className="text-lg text-red-700">{euros(sorties30)}</strong></div><div className="rounded border p-4"><p className="text-xs text-neutral-500">Net réalisé · 30 j</p><strong className={`text-lg ${entrees30-sorties30>=0?"text-green-700":"text-red-700"}`}>{euros(entrees30-sorties30)}</strong></div><Link href="/factures" className="rounded border p-4 hover:bg-neutral-50"><p className="text-xs text-neutral-500">Total à encaisser</p><strong className="text-lg">{euros(aEncaisser)}</strong></Link><Link href="/depenses" className="rounded border p-4 hover:bg-neutral-50"><p className="text-xs text-neutral-500">Total à payer</p><strong className="text-lg">{euros(aPayer)}</strong></Link></div>
    <section className="rounded-md border p-4 dark:border-neutral-800"><div className="flex justify-between"><div><h2 className="font-semibold">Projection à 90 jours</h2><p className="text-xs text-neutral-500">Les échéances dépassées sont regroupées dans la première semaine.</p></div><div className="text-right text-sm"><span className="text-green-700">+ {euros(attendu90)}</span><span className="mx-2 text-neutral-300">/</span><span className="text-red-700">− {euros(aPayer90)}</span></div></div><div className="mt-4 grid grid-cols-13 items-end gap-2" style={{gridTemplateColumns:"repeat(13,minmax(0,1fr))"}}>{projection.map(s=><div key={s.index} className="space-y-1 text-center"><div className="flex h-32 items-end justify-center gap-1"><div title={`Encaissements ${euros(s.entrees)}`} className="w-3 rounded-t bg-green-500" style={{height:`${Math.max(s.entrees?4:0,s.entrees/maxFlux*100)}%`}}/><div title={`Décaissements ${euros(s.sorties)}`} className="w-3 rounded-t bg-red-400" style={{height:`${Math.max(s.sorties?4:0,s.sorties/maxFlux*100)}%`}}/></div><p className="text-[10px] text-neutral-500">{dateFr(s.debut)}</p></div>)}</div><div className="mt-3 flex gap-4 text-xs text-neutral-500"><span><i className="mr-1 inline-block h-2 w-2 bg-green-500"/>Encaissements</span><span><i className="mr-1 inline-block h-2 w-2 bg-red-400"/>Décaissements</span></div></section>
    <div className="overflow-hidden rounded-md border dark:border-neutral-800"><table className="w-full text-sm"><thead className="bg-neutral-50 text-left text-xs uppercase text-neutral-500 dark:bg-neutral-900"><tr><th className="px-3 py-2">Période</th><th className="text-right">Entrées</th><th className="text-right">Sorties</th><th className="text-right">Net semaine</th><th className="px-3 text-right">Variation cumulée</th></tr></thead><tbody>{projection.map(s=><tr key={s.index} className="border-t dark:border-neutral-800"><td className="px-3 py-2">{dateFr(s.debut)} → {dateFr(s.fin)} <span className="text-xs text-neutral-400">({s.detailsEntrees+s.detailsSorties} échéance(s))</span></td><td className="text-right text-green-700">{euros(s.entrees)}</td><td className="text-right text-red-700">{euros(s.sorties)}</td><td className={`text-right ${s.net>=0?"text-green-700":"text-red-700"}`}>{euros(s.net)}</td><td className={`px-3 text-right font-medium ${s.cumul>=0?"text-green-700":"text-red-700"}`}>{euros(s.cumul)}</td></tr>)}</tbody></table></div>
    <p className="text-xs text-neutral-500">Cette projection présente une variation de trésorerie, pas un solde bancaire. Elle repose sur les dates d’échéance renseignées dans les factures clients et fournisseurs.</p>
  </div></main>;
}
