/**
 * ELSATIA — Commercialization Readiness Gate V1 : registre des preuves.
 *
 * Chaque point cite ses preuves : un fichier du dépôt (et un marqueur qu'il doit contenir), un
 * fichier d'une branche `origin/*` déjà récupérée localement, un constat ou une décision du
 * manifeste d'environnement, un script npm, ou une exécution locale (`--run-code` / `--run-db`).
 *
 * Règles du registre (validées par gate.mjs) :
 *   - statut ∈ GO | NO-GO | DECISION_REQUIRED | REMOTE_PROOF_REQUIRED | MANUAL_REQUIRED | NOT_APPLICABLE ;
 *   - hors GO : priorité objective (P0/P1/P2), porteur et dépendance technique obligatoires ;
 *   - un GO dont une preuve manque est rétrogradé en NO-GO par le moteur ;
 *   - `derive` permet à un point de basculer seul quand le dépôt change (ex. lot porté dans le train).
 *
 * Priorités (mission) :
 *   P0 = empêche objectivement la mise en vente ou expose un risque sécurité/data majeur ;
 *   P1 = nécessaire avant ouverture clients ;
 *   P2 = amélioration post-lancement possible.
 * Quand un rapport source fixe déjà une gravité, elle est reprise telle quelle (champ `rationale`).
 */

export const BASE = Object.freeze({
  ref: "integration/elsatia-canonical-train-v6",
  commit: "9102ec80",
  verdict: "CANONICAL TRAIN V6 LOCALLY QUALIFIED",
  migrations: 358,
  last_migration: "20260928000601",
});

export const REFERENCE_DATES = Object.freeze({
  activity_start_declared: "2026-10-01",
  note:
    "date d'activité déclarée, utilisée uniquement comme repère de configuration existant ; elle n'implique aucune obligation de vendre à cette date",
});

const V6 = BASE.commit;
const V6_RAPPORT = "docs/qualification/ELSATIA_CANONICAL_TRAIN_V6_CONVERGENCE_V1.md";
// package.json exclu : le gate n'y ajoute que ses deux scripts npm (aucune dépendance, aucun script de build).
const CODE_V6 = ["src", "apps", "packages", "supabase", "workers", "package-lock.json"];

// Rapports qualifiés post-V6 (branches origin/* ; aucun n'est intégré au train V6).
const R = Object.freeze({
  EMAIL: { ref: "origin/claude/practical-ritchie-yvsg3f", path: "docs/qualification/ELSATIA_TRANSACTIONAL_EMAIL_ARCHITECTURE_V1.md" },
  LEGAL: { ref: "origin/claude/awesome-franklin-se2s33", path: "docs/qualification/ELSATIA_LEGAL_IDENTITY_COMMERCIALIZATION_AUDIT_V1.md" },
  DR: { ref: "origin/claude/determined-rubin-zdzpmy", path: "docs/qualification/ELSATIA_DISASTER_RECOVERY_RESTORE_V2.md" },
  HANDOFF: { ref: "origin/claude/wizardly-keller-3gz8nv", path: "docs/qualification/ELSATIA_REMOTE_PREVIEW_OPERATOR_HANDOFF_V1.md" },
  V4EXEC: { ref: "origin/claude/zen-davinci-xn6m3m", path: "docs/qualification/ELSATIA_V4_REMOTE_PREVIEW_EXECUTION_V1.md" },
  STUDIO_POSTH: { ref: "origin/claude/modest-pasteur-izfaqm", path: "docs/qualification/ELSATIA_STUDIO_POST_H_PORT_V1.md" },
  STUDIO_E2E: { ref: "origin/claude/jolly-volta-doejq2", path: "docs/qualification/ELSATIA_STUDIO_DEDICATED_PLAYWRIGHT_CI_V1.md" },
  RELEVE7: { ref: "origin/claude/nifty-edison-mevolm", path: "docs/product/ELSATIA_TOOLS_RELEVE_METRE_LOT7_EQUIPEMENTS_CALQUES_V1.md" },
  OBS: { ref: "origin/ops/observability-incident-readiness-v1", path: "docs/qualification/ELSATIA_OBSERVABILITY_INCIDENT_READINESS_V1.md" },
});

const f = (path, contains) => ({ kind: "file", path, contains });
const ref = (r, contains) => ({ kind: "ref", ref: r.ref, path: r.path, contains });
const v6 = (contains) => f(V6_RAPPORT, contains);
const inchange = { kind: "unchanged-since", commit: V6, paths: CODE_V6 };
const exec = (name) => ({ kind: "exec", name });
const finding = (id) => ({ kind: "manifest-finding", id });
const decision = (id) => ({ kind: "manifest-decision", id });
const note = (text) => ({ kind: "note", text });
const optionnel = (p) => ({ ...p, optional: true });

/** Bascule en GO quand toutes les sondes `optional` passent (lot porté dans le train). */
const goSiPorte = (preuves) => (preuves.filter((p) => p.optional).every((p) => p.ok) ? { status: "GO", rationale: "lot porté dans le train (sondes du dépôt vertes)" } : null);

/** Constat du manifeste : fermé (fixed/accepted) → GO. */
const goSiConstatFerme = (preuves) => {
  const c = preuves.find((p) => p.kind === "manifest-finding");
  return c?.ok && /\b(fixed|accepted)$/.test(c.detail) ? { status: "GO", rationale: `constat ${c.id} fermé au manifeste` } : null;
};

/** Décision du manifeste : tranchée → GO. */
const goSiDecisionTranchee = (preuves) => {
  const d = preuves.find((p) => p.kind === "manifest-decision");
  return d?.ok && /tranchée$/.test(d.detail) ? { status: "GO", rationale: `décision ${d.id} tranchée au manifeste` } : null;
};

// ── Portes locales exécutables (--run-code) ─────────────────────────────────
export const EXECUTIONS = Object.freeze({
  typecheck: { cmd: "npm", args: ["run", "-s", "typecheck"] },
  lint: { cmd: "npm", args: ["run", "-s", "lint"] },
  test: { cmd: "npm", args: ["run", "-s", "test"] },
  "studio-test": { cmd: "npm", args: ["--prefix", "apps/studio", "run", "-s", "test"] },
  "verify:migrations": { cmd: "npm", args: ["run", "-s", "verify:migrations"] },
  "test:migration-targets": { cmd: "npm", args: ["run", "-s", "test:migration-targets"] },
  "verify:train-expectations": { cmd: "npm", args: ["run", "-s", "verify:train-expectations"] },
  "verify:secrets": { cmd: "npm", args: ["run", "-s", "verify:secrets"] },
  "verify:env-manifest": { cmd: "npm", args: ["run", "-s", "verify:env-manifest"] },
  "test:env-manifest": { cmd: "npm", args: ["run", "-s", "test:env-manifest"] },
  "test:seeds": { cmd: "npm", args: ["run", "-s", "test:seeds"] },
  "test:preview-pack": { cmd: "npm", args: ["run", "-s", "test:preview-pack"] },
  "test:stripe-scripts": {
    cmd: "sh",
    args: ["-c", "npm run -s test:stripe-ordering-script && npm run -s test:stripe-trial-script && npm run -s test:stripe-resubscription-script"],
  },
  build: {
    cmd: "sh",
    args: ["-c", "npm run -s build && npm run -s build:reserves && npm run -s build:colors && npm --prefix apps/studio run -s build"],
    env: { NEXT_PUBLIC_TOOLS_ENV: "local", ELSATIA_APPLICATION_ENV: "local" },
  },
});

// ── Portes base de données locales (--run-db, base jetable elsatia_gate_* uniquement) ───
export const EXECUTIONS_DB = Object.freeze({
  "db:fresh": { cmd: "bash", args: (db) => ["scripts/local-postgres-bootstrap/rebuild_db.sh", db] },
  "db:verify-local": {
    cmd: "node",
    args: () => ["scripts/preview/db-verify.mjs", "--local-harness", "--before-owner"],
    env: (url) => ({ ELSATIA_PREVIEW_DB_URL: url }),
  },
});

// ═════════════════════════════════════════════════════════════════════════════
export const REGISTRE = [
  // ── CODE ───────────────────────────────────────────────────────────────────
  {
    id: "CODE-BUILD",
    category: "CODE",
    title: "Build des 5 applications (GP, Tools, Colors, Réserves, Studio)",
    status: "GO",
    evidence: [v6("CANONICAL TRAIN V6 LOCALLY QUALIFIED"), v6("✅ `next build`"), inchange, exec("build")],
  },
  {
    id: "CODE-TYPECHECK",
    category: "CODE",
    title: "Typecheck (racine + apps)",
    status: "GO",
    evidence: [v6("Les 5 applications passent typecheck"), inchange, exec("typecheck")],
  },
  {
    id: "CODE-LINT",
    category: "CODE",
    title: "Lint (0 erreur ; 15 avertissements préexistants)",
    status: "GO",
    evidence: [v6("✅ 0 erreur (15 avertissements"), inchange, exec("lint")],
  },
  {
    id: "CODE-TESTS",
    category: "CODE",
    title: "Tests unitaires Vitest (GP 2 300, Tools 2 118, Colors 431, Réserves 186, Studio 291)",
    status: "GO",
    evidence: [v6("**2 300** passés"), inchange, exec("test"), exec("studio-test")],
  },
  {
    id: "CODE-MIGRATIONS",
    category: "CODE",
    title: "Migrations : 358 valides, cibles partagé / Studio dédié, attendus du train synchronisés",
    status: "GO",
    evidence: [
      v6("`npm run verify:migrations` : **358 valides**"),
      inchange,
      exec("verify:migrations"),
      exec("test:migration-targets"),
      exec("verify:train-expectations"),
    ],
  },
  {
    id: "CODE-SEEDS",
    category: "CODE",
    title: "Seeds : registre complet et 16/16 seeds actifs qualifiés sur 358 migrations",
    status: "GO",
    evidence: [v6("ALL ACTIVE SEEDS QUALIFIED — 16/16"), inchange, exec("test:seeds")],
  },
  {
    id: "CODE-TOOLING-TESTS",
    category: "CODE",
    title: "Outillage hors réseau (pack Preview, manifeste, scripts Stripe test-mode)",
    status: "GO",
    evidence: [v6("`test:preview-pack` ✅ **29/29**"), exec("test:preview-pack"), exec("test:env-manifest"), exec("test:stripe-scripts")],
  },
  {
    id: "CODE-POST-V6-CONVERGENCE",
    category: "CODE",
    title: "Lots qualifiés post-V6 hors train (e-mail, identité légale, DR V2, pack Preview, Studio post-H/E2E, Relevé Lot 7, observabilité)",
    status: "NO-GO",
    priority: "P1",
    owner: "Dév (train canonique)",
    dependency:
      "Train V7 : intégrer et requalifier les branches post-V6 (bases hétérogènes : V5 f6399f15, Lot 6 d734f255, Studio fb7082c6, et main 4d92ddbe pour identité légale et observabilité)",
    rationale: "Le code qui ferme plusieurs points EMAIL, LEGAL, BACKUP_DR, PREVIEW et OBSERVABILITY n'existe que sur ces branches.",
    evidence: [
      ref(R.EMAIL, "ELSATIA EMAIL ACTIONS REQUIRED"),
      ref(R.LEGAL, "ELSATIA LEGAL IDENTITY ACTIONS REQUIRED"),
      ref(R.DR, "ELSATIA DR LOCALLY QUALIFIED"),
      ref(R.HANDOFF, "REMOTE PREVIEW OPERATOR HANDOFF PACK V1 READY"),
      ref(R.STUDIO_E2E, "STUDIO DEDICATED E2E LOCALLY QUALIFIED"),
      ref(R.RELEVE7, "RELEVE METRE LOT 7 LOCALLY QUALIFIED"),
      optionnel(f("packages/email/src/identite.ts")),
      optionnel(f("src/lib/identite-legale.ts")),
      optionnel(f("scripts/dr/v2/dr-verify.mjs")),
      optionnel(f("scripts/preview/qualification/train.json")),
      optionnel(f("src/app/api/healthz/route.ts")),
    ],
    derive: goSiPorte,
  },

  // ── DATABASE ───────────────────────────────────────────────────────────────
  {
    id: "DB-FRESH",
    category: "DATABASE",
    title: "Base neuve : 358/358 migrations, 0 erreur (PostgreSQL 16)",
    status: "GO",
    evidence: [v6("**358/358 migrations, 0 erreur**"), inchange, exec("db:fresh")],
  },
  {
    id: "DB-UPGRADE",
    category: "DATABASE",
    title: "Upgrade V5 → V6 avec données réalistes : 0 écart de lignes, 91/91 empreintes, 28/28 contrôles métier",
    status: "GO",
    evidence: [v6("**91/91 empreintes métier identiques**"), v6("**28/28 contrôles métier**"), f("scripts/qualification/upgrade-v5-v6.sh")],
  },
  {
    id: "DB-RLS",
    category: "DATABASE",
    title: "RLS : sonde réelle 51 utilisateurs × 29 tables, 0 écart ; aucune table publique sans RLS",
    status: "GO",
    evidence: [v6("**0 écart / 1 479 cellules**"), exec("db:verify-local")],
  },
  {
    id: "DB-POLICIES",
    category: "DATABASE",
    title: "Policies : 639 → 639, aucune supprimée, modifiée ou ajoutée par V6",
    status: "GO",
    evidence: [v6("639 → 639 : **0 supprimée, 0 modifiée, 0 ajoutée**")],
  },
  {
    id: "DB-GRANTS",
    category: "DATABASE",
    title: "Grants et EXECUTE : inchangés ; 37 RPC techniques réservées au service_role",
    status: "GO",
    evidence: [v6("Grants | ✅ 0 retiré/modifié, 0 ajouté"), v6("**37** (+ `purger_contrats_conserves_echus`"), exec("db:verify-local")],
  },
  {
    id: "DB-VERIFY-LOCAL",
    category: "DATABASE",
    title: "DB verify Preview rejoué sur base V6 neuve : GO (29 contrôles, préflight 21 / 0 bloquant, 19 buckets, 37/37)",
    status: "GO",
    evidence: [v6("**`GO : base Preview conforme.`**"), f("scripts/preview/db-verify.mjs"), exec("db:verify-local")],
  },
  {
    id: "DB-PGTAP-COMPLETE",
    category: "DATABASE",
    title: "pgTAP complet : 143/152 fichiers propres, 0 régression ; 9 fichiers limités par le banc local",
    status: "REMOTE_PROOF_REQUIRED",
    priority: "P1",
    owner: "Opérateur",
    dependency:
      "pgsodium réel (platform_stripe_state_attestation_r72) et amorce Supabase complète (cloud sync entitlement) : `supabase test db` sur un vrai projet Supabase ; les 7 suites Studio du projet partagé relèvent du projet dédié (543/543)",
    evidence: [v6("pgTAP **143/152 propres, 0 régression**"), v6("pgsodium réel absent de l'amorce")],
  },
  {
    id: "DB-HOSTED-LEDGER",
    category: "DATABASE",
    title: "Migrations V6 appliquées sur Preview puis Production (ledger hébergé)",
    status: "REMOTE_PROOF_REQUIRED",
    priority: "P0",
    owner: "Opérateur",
    dependency: "Exécution de la qualification Preview (sauvegarde validée puis `db push`), puis bascule Production ; V6 n'est déployé nulle part",
    evidence: [v6("V6 **non déployé**"), ref(R.V4EXEC, "V4 PREVIEW BLOCKED")],
  },
  {
    id: "DB-DR-LOCAL",
    category: "DATABASE",
    title: "Restauration base : backup strict restauré à l'identique (0 écart), 4 sinistres, compatibilité schéma V6",
    status: "GO",
    rationale: "Détail et limites hébergées : catégorie BACKUP_DR.",
    evidence: [ref(R.DR, "ELSATIA DR LOCALLY QUALIFIED"), ref(R.DR, "Contrôle de compatibilité V6")],
  },

  // ── SECURITY ───────────────────────────────────────────────────────────────
  {
    id: "SEC-MULTI-TENANT",
    category: "SECURITY",
    title: "Isolation multi-tenant : red team V3 (3 failles corrigées), remédiation des bloqueurs, sonde RLS V6",
    status: "GO",
    evidence: [
      f("docs/qualification/ELSATIA_SECURITY_TENANT_RED_TEAM_V3.md", "REDTEAM-V3-01"),
      f("supabase/migrations/20260922000323_redteam_v3_authenticated_rpc_bypass_revocation.sql"),
      f("docs/qualification/ELSATIA_SECURITY_BLOCKERS_REMEDIATION_V1.md", "SECURITY BLOCKERS REMEDIATED"),
      v6("**0 écart / 1 479 cellules**"),
    ],
  },
  {
    id: "SEC-REDTEAM-RESIDUALS",
    category: "SECURITY",
    title: "Résidus red team V3 non corrigés : oracle inter-tenant (RT-V3-P2-01), jeton de document anon (P3-02), pas de limitation de débit sur les partages publics (P3-03)",
    status: "NO-GO",
    priority: "P2",
    owner: "Dév",
    dependency: "Lot sécurité : resserrer `acces_module_pour_permission`, revoir le grant anon de `document_commercial_par_token`, limiter le débit des routes de partage public",
    rationale: "Gravités P2/P3 reprises du rapport red team V3 ; couverture de la matrice des 15 acteurs déclarée partielle par ce rapport.",
    evidence: [f("docs/qualification/ELSATIA_SECURITY_TENANT_RED_TEAM_V3.md", "RT-V3-P2-01"), f("docs/qualification/ELSATIA_SECURITY_TENANT_RED_TEAM_V3.md", "RT-V3-P3-03")],
  },
  {
    id: "SEC-READ-ONLY-RESERVES-D01",
    category: "SECURITY",
    title: "Lecture seule Réserves D-01 (hôte suspendu) : pgTAP 97, Playwright 7/7 sur V6",
    status: "GO",
    evidence: [
      f("docs/qualification/ELSATIA_RESERVES_HOST_SUSPENSION_POLICY_V1.md", "RESERVES SUSPENSION POLICY LOCALLY QUALIFIED"),
      f("supabase/migrations/20260928000301_reserves_hote_suspendu_lecture_seule_v1.sql"),
      v6("| **Réserves D-01** | idem, base neuve distincte | 7 | ✅ **7/7** |"),
    ],
  },
  {
    id: "SEC-READ-ONLY-STUDIO",
    category: "SECURITY",
    title: "Lecture seule Studio appliquée en base (garde d'écriture centrale, 22 RPC refusées, 42501)",
    status: "GO",
    evidence: [f("docs/qualification/ELSATIA_STUDIO_DB_GUARDS_RGPD_FOUNDATION_V1.md", "STUDIO DB GUARDS LOCALLY QUALIFIED"), v6("**22 RPC\nauthentifiées** protégées")],
  },
  {
    id: "SEC-SUSPENSION-CROSS-APP",
    category: "SECURITY",
    title: "Abonnement GP suspendu : accès coupé (pas de lecture seule) et accès Colors/Tools/Réserves couplé au statut GP (RT-V3-P2-02)",
    status: "DECISION_REQUIRED",
    priority: "P1",
    owner: "Julien",
    dependency: "Décision produit explicite demandée par le red team V3 ; puis `a_acces_application()` et `est_membre_actif` alignés et testés",
    evidence: [
      f("docs/qualification/ELSATIA_SECURITY_TENANT_RED_TEAM_V3.md", "RT-V3-P2-02"),
      f("docs/qualification/ELSATIA_STRIPE_RESUBSCRIPTION_FLOW_V1.md", "deviennent invisibles à ses membres"),
    ],
  },
  {
    id: "SEC-AUTH-LOCAL",
    category: "SECURITY",
    title: "Auth sur GoTrue réel local : jetons valides/expirés/bannis/révoqués, identité Studio B + I1 73/73 ×3",
    status: "GO",
    evidence: [
      f("docs/qualification/ELSATIA_PILOT_AUTH_POSTGREST_ACCEPTANCE_AUTOMATION_V1.md", "Auth qualifiée"),
      v6("**73/73, trois exécutions consécutives**"),
      f("docs/qualification/ELSATIA_STUDIO_AUTH_CLOSED_SIGNUP_HARDENING_V1.md", "STUDIO CLOSED SIGNUP LOCALLY ENFORCED"),
    ],
  },
  {
    id: "SEC-AUTH-HOSTED",
    category: "SECURITY",
    title: "Auth hébergée : AAL2/MFA réel, URLs de redirection par application, signup fermé sur GoTrue hébergé",
    status: "REMOTE_PROOF_REQUIRED",
    priority: "P1",
    owner: "Opérateur",
    dependency: "Qualification Preview (étapes Auth du pack) ; réglages Supabase Dashboard par projet",
    evidence: [f("docs/qualification/ELSATIA_PREVIEW_GO_LIVE_CHECKLIST_V2.md", "AAL2/MFA réel"), f("docs/qualification/ELSATIA_PREVIEW_GO_LIVE_CHECKLIST_V2.md", "Redirect URLs Auth par app")],
  },
  {
    id: "SEC-STORAGE-HOSTED",
    category: "SECURITY",
    title: "Policies Storage (19 buckets) jamais vérifiées sur un vrai service Storage",
    status: "REMOTE_PROOF_REQUIRED",
    priority: "P0",
    owner: "Opérateur",
    dependency: "`preview:storage-smoke` (cross-tenant) pendant la qualification Preview",
    rationale: "Photos, plans et documents clients : une policy fausse expose des données d'un tenant à un autre.",
    evidence: [f("docs/qualification/ELSATIA_PREVIEW_GO_LIVE_CHECKLIST_V2.md", "Auth / Storage / multi-tenant | **REMOTE PROOF REQUIRED**"), f("scripts/preview/storage-smoke.mjs")],
  },
  {
    id: "SEC-SECRETS",
    category: "SECURITY",
    title: "Aucun secret reconnu dans les fichiers suivis (verify:secrets, CI)",
    status: "GO",
    evidence: [v6("`verify:secrets` ✅"), f(".github/workflows/ci.yml", "verify:secrets"), exec("verify:secrets")],
  },
  {
    id: "SEC-DEPENDENCIES",
    category: "SECURITY",
    title: "Audit des dépendances (npm audit --audit-level=high) en CI hebdomadaire",
    status: "GO",
    rationale: "Non rejoué par le gate (appel au registre npm) ; preuve = remédiation documentée et job CI.",
    evidence: [f("docs/qualification/ELSATIA_SECURITY_BLOCKERS_REMEDIATION_V1.md", "js-yaml"), f(".github/workflows/ci.yml", "audit:security")],
  },
  {
    id: "SEC-LEGACY-DEMO-CREDENTIALS",
    category: "SECURITY",
    title: "Rotation des identifiants de démo historiques signalée « rotation requise » par l'audit de sécurité",
    status: "MANUAL_REQUIRED",
    priority: "P1",
    owner: "Exploitant",
    dependency: "Confirmer par écrit la suppression du compte de démo et la rotation ; mettre à jour docs/AUDIT_SECURITE.md (daté du 18/07/2026, antérieur à la fermeture de l'accès anonyme)",
    evidence: [f("docs/AUDIT_SECURITE.md", "rotation requise")],
  },
  {
    id: "SEC-BANK-KEY-VERSIONING",
    category: "SECURITY",
    title: "Clé BANK_DATA_ENCRYPTION_KEY sans identifiant de version : pas de rotation, perte = IBAN/BIC illisibles (F-DR-BANK-KEY-VERSIONING)",
    status: "NO-GO",
    priority: "P0",
    owner: "Dév",
    dependency: "Lot cryptographie : versionnement de clé (format chiffré avec identifiant) et procédure de rotation",
    rationale: "Gravité P0 reprise du manifeste d'environnement. Bascule seule en GO quand le constat est fermé au manifeste.",
    evidence: [finding("F-DR-BANK-KEY-VERSIONING")],
    derive: goSiConstatFerme,
  },
  {
    id: "SEC-ENV-P1-FINDINGS",
    category: "SECURITY",
    title: "Constats P1 ouverts du manifeste : double usage de secrets HMAC, repli silencieux d'environnement, replis localhost, nom de clé service Studio",
    status: "NO-GO",
    priority: "P1",
    owner: "Dév",
    dependency: "Lots code du manifeste : STRIPE_CONNECT_STATE_HMAC_KEY, clé d'état bancaire dédiée, refus d'environnement absent au déploiement, indicateur d'environnement dans Réserves/Studio",
    evidence: [
      finding("F-HMAC-STRIPE-OAUTH-STATE"),
      finding("F-HMAC-BANK-STATE-FALLBACK"),
      finding("F-ENV-FALLBACK-LOCAL"),
      finding("F-ENV-INDICATOR-ADOPTION"),
      finding("F-URL-LOCALHOST-FALLBACK"),
      finding("F-STUDIO-SERVICE-KEY-NAME"),
      finding("F-SUPABASE-PUBLIC-KEY-NAME"),
    ],
    derive: (preuves) =>
      preuves.every((p) => p.kind !== "manifest-finding" || /\b(fixed|accepted)$/.test(p.detail)) ? { status: "GO", rationale: "tous les constats fermés au manifeste" } : null,
  },
  {
    id: "SEC-CI-COVERAGE",
    category: "SECURITY",
    title: "pgTAP du projet partagé (red team, D-01, Stripe) et recettes Playwright GP/Réserves/Relevé/Colors absents de la CI",
    status: "NO-GO",
    priority: "P2",
    owner: "Dév",
    dependency: "Job CI PostgreSQL 16 + pgTAP sur supabase/tests (comme `studio-dedicated`) et job Playwright sur piles locales",
    evidence: [f(".github/workflows/ci.yml", "studio-dedicated"), note("Aucun job CI n'exécute supabase/tests du projet partagé ni les recettes Playwright GP/Réserves/Relevé/Colors (lecture de .github/workflows/*.yml).")],
  },

  // ── BILLING ────────────────────────────────────────────────────────────────
  {
    id: "BILL-LOCAL-SECURITY",
    category: "BILLING",
    title: "Sécurité facturation self-service : contournement RLS fermé, 3DS ne suspend jamais, colonnes commerciales verrouillées",
    status: "GO",
    evidence: [
      f("docs/qualification/ELSATIA_SELF_SERVICE_BILLING_SECURITY_CLOSURE_V3.md", "BILLING SECURITY CLOSED"),
      f("supabase/migrations/20260923000332_verrouillage_colonnes_commerciales_entreprises.sql"),
    ],
  },
  {
    id: "BILL-LOCAL-ORDERING",
    category: "BILLING",
    title: "Ordre des événements Stripe : désordre, rejeu, doublons et 100 courses convergent",
    status: "GO",
    evidence: [f("docs/qualification/ELSATIA_STRIPE_EVENT_ORDERING_HARDENING_V1.md", "STRIPE ORDERING LOCALLY QUALIFIED")],
  },
  {
    id: "BILL-LOCAL-TRIAL",
    category: "BILLING",
    title: "Essai : trial_end borné à l'essai local, double Checkout concurrent bloqué",
    status: "GO",
    evidence: [f("docs/qualification/ELSATIA_STRIPE_TRIAL_SYNCHRONIZATION_V1.md", "STRIPE TRIAL LOCALLY QUALIFIED")],
  },
  {
    id: "BILL-LOCAL-RESUBSCRIPTION",
    category: "BILLING",
    title: "Réabonnement après annulation : 120/120 ordres convergent, Playwright 6/6 ×2 sur V6",
    status: "GO",
    evidence: [f("docs/qualification/ELSATIA_STRIPE_RESUBSCRIPTION_FLOW_V1.md", "STRIPE RESUBSCRIPTION LOCALLY QUALIFIED"), v6("Stripe réabonnement **6/6 ×2**")],
  },
  {
    id: "BILL-LOCAL-CONNECT-BOUTIQUE",
    category: "BILLING",
    title: "Webhooks Connect/Boutique et idempotence de la Boutique (Boutique et Connect OFF au lancement)",
    status: "GO",
    evidence: [
      f("docs/qualification/ELSATIA_STRIPE_CONNECT_BOUTIQUE_WEBHOOK_CLOSURE_V1.md", "STRIPE WEBHOOK BLOCKER CLOSED LOCALLY"),
      f("docs/qualification/ELSATIA_BOUTIQUE_PAYMENT_IDEMPOTENCY_CLOSURE_V1.md", "BOUTIQUE IDEMPOTENCY BLOCKER CLOSED LOCALLY"),
    ],
  },
  {
    id: "BILL-STRIPE-TEST-PRICES",
    category: "BILLING",
    title: "Existence et montants des Price IDs Stripe (verify:stripe-prices strict jamais vert)",
    status: "REMOTE_PROOF_REQUIRED",
    priority: "P0",
    owner: "Opérateur",
    dependency: "Clé Stripe Test en lecture (`STRIPE_TEST_SECRET_KEY` CI ou poste opérateur) puis `npm run verify:stripe-prices` en mode strict ; dépend de BILL-PRICING-DECISIONS",
    evidence: [f("scripts/verify-stripe-prices.mjs"), f("config/stripe-prices.test.json")],
  },
  {
    id: "BILL-STRIPE-TEST-WEBHOOKS",
    category: "BILLING",
    title: "Webhooks signés par Stripe Test réel, endpoints et événements abonnés, STRIPE_WEBHOOK_EXPECTED_MODE par déploiement",
    status: "REMOTE_PROOF_REQUIRED",
    priority: "P0",
    owner: "Opérateur",
    dependency: "`preview:stripe-verify` + événements Stripe Test réels pendant la qualification Preview",
    evidence: [f("scripts/preview/stripe-test-verify.mjs"), f("docs/qualification/ELSATIA_STRIPE_CONNECT_BOUTIQUE_WEBHOOK_CLOSURE_V1.md", "REMOTE_ACTION_REQUIRED")],
  },
  {
    id: "BILL-STRIPE-TEST-FLOWS",
    category: "BILLING",
    title: "Checkout, essai, ordre et réabonnement contre Stripe Test réel (scripts préparés, jamais exécutés)",
    status: "REMOTE_PROOF_REQUIRED",
    priority: "P0",
    owner: "Opérateur",
    dependency: "`scripts/qualification/stripe-{ordering,trial,resubscription}-test-mode.mjs` avec clé Stripe Test, sur Preview",
    evidence: [
      f("scripts/qualification/stripe-ordering-test-mode.mjs"),
      f("scripts/qualification/stripe-trial-test-mode.mjs"),
      f("scripts/qualification/stripe-resubscription-test-mode.mjs"),
      v6("Stripe Test réel, Storage/GoTrue/e-mail réels, Portail Stripe réel"),
    ],
  },
  {
    id: "BILL-CUSTOMER-PORTAL",
    category: "BILLING",
    title: "Portail client Stripe (configuration et bouton de reprise) non observé",
    status: "REMOTE_PROOF_REQUIRED",
    priority: "P1",
    owner: "Opérateur",
    dependency: "`scripts/configurer-portail-stripe.mjs` sur Stripe Test puis observation du Portail pendant la Preview",
    evidence: [f("scripts/configurer-portail-stripe.mjs"), f("docs/qualification/ELSATIA_SELF_SERVICE_BILLING_SECURITY_CLOSURE_V3.md", "REMOTE STRIPE REQUIRED")],
  },
  {
    id: "BILL-PRICING-DECISIONS",
    category: "BILLING",
    title: "Grille tarifaire Stripe : contrats de Price divergents (modules, comptes supplémentaires, options IA, générations historiques, bloc stockage)",
    status: "DECISION_REQUIRED",
    priority: "P1",
    owner: "Julien",
    dependency: "5 décisions STRIPE-* du manifeste, puis création des Price IDs et `verify:stripe-prices`",
    rationale:
      "Constat F-STRIPE-CONTRACTS-DIVERGENT classé P1 au manifeste ; les décisions propriétaire finales le rangent en P2-9. Retenu P1 : aucune vente sans grille de prix arrêtée.",
    evidence: [
      f("docs/qualification/ELSATIA_OWNER_DECISIONS_FINAL_V1.md", "P2-9"),
      finding("F-STRIPE-CONTRACTS-DIVERGENT"),
      decision("DECISION_REQUIRED:STRIPE-MODULE-PRICE-MODEL"),
      decision("DECISION_REQUIRED:STRIPE-SUPPLEMENTARY-ACCOUNTS"),
      decision("DECISION_REQUIRED:STRIPE-IA-OPTIONS"),
      decision("DECISION_REQUIRED:STRIPE-LEGACY-GENERATIONS"),
      decision("DECISION_REQUIRED:STRIPE-STORAGE-BLOCK"),
    ],
    derive: goSiConstatFerme,
  },
  {
    id: "BILL-STRIPE-TAX",
    category: "BILLING",
    title: "Stripe Tax / STRIPE_AUTOMATIC_TAX_ENABLED : bloqué tant que le régime de TVA n'est pas confirmé",
    status: "DECISION_REQUIRED",
    priority: "P0",
    owner: "Julien + comptable",
    dependency: "LEGAL-VAT (régime de TVA), puis paramétrage Stripe Tax et affichage HT/TTC aligné",
    evidence: [f("docs/organisation/P15_STRIPE_LIVE_PREPARATION.md", "BLOQUÉ — régime TVA officiel à confirmer"), f("src/lib/stripe-abonnement.ts", "STRIPE_AUTOMATIC_TAX_ENABLED")],
  },
  {
    id: "BILL-WEBHOOK-RETRY-RESIDUAL",
    category: "BILLING",
    title: "Événement webhook réservé puis en échec : perdu au réessai suivant de Stripe (résidu D3)",
    status: "NO-GO",
    priority: "P1",
    owner: "Dév",
    dependency: "Réessai après échec idempotent sur `stripe_webhook_events` (réarmement de la réservation en échec)",
    rationale: "Résidu fonctionnel classé P1 et non corrigé par décision dans le rapport de clôture des webhooks.",
    evidence: [f("docs/qualification/ELSATIA_STRIPE_CONNECT_BOUTIQUE_WEBHOOK_CLOSURE_V1.md", "D3")],
  },
  {
    id: "BILL-GRACE-PERIOD",
    category: "BILLING",
    title: "Délai de grâce après impayé (STRIPE_DELAI_GRACE_PAIEMENT_JOURS, défaut 0 = suspension immédiate)",
    status: "DECISION_REQUIRED",
    priority: "P1",
    owner: "Julien",
    dependency: "Valeur écrite puis variable posée par environnement",
    evidence: [f("supabase/migrations/20260923000333_horodatage_events_abonnement_et_delai_grace.sql"), f("docs/qualification/ELSATIA_PREVIEW_GO_LIVE_CHECKLIST_V2.md", "STRIPE_DELAI_GRACE_PAIEMENT_JOURS")],
  },
  {
    id: "BILL-COMMERCIAL-LOCK",
    category: "BILLING",
    title: "Ouverture des souscriptions publiques (verrou ABONNEMENTS_PUBLICS_OUVERTS ; aucune garde de date dans V6)",
    status: "DECISION_REQUIRED",
    priority: "P0",
    owner: "Julien",
    dependency: "Décision d'ouverture après levée des P0 ; variable posée en Production. La garde de date du 01/10/2026 n'existe que sur la branche identité légale (non portée)",
    rationale: "Le verrou est un drapeau d'environnement : sans décision explicite, aucune souscription publique n'est possible.",
    evidence: [f("src/lib/commercialisation-abonnements.ts", "ABONNEMENTS_PUBLICS_OUVERTS"), ref(R.LEGAL, "DEBUT_COMMERCIALISATION")],
  },
  {
    id: "BILL-STRIPE-LIVE",
    category: "BILLING",
    title: "Compte Stripe Live : activation, Price IDs Live, endpoints webhook Live",
    status: "MANUAL_REQUIRED",
    priority: "P0",
    owner: "Exploitant",
    dependency: "LEGAL-STRIPE-SELLER, BILL-PRICING-DECISIONS, BILL-STRIPE-TAX ; `docs/organisation/P15_STRIPE_LIVE_PREPARATION.md`",
    evidence: [f("docs/operations/DIAGNOSTIC_STRIPE_WEBHOOKS_V1.md", "Stripe Live n'est pas activé")],
  },

  // ── EMAIL ──────────────────────────────────────────────────────────────────
  {
    id: "EMAIL-CODE-READY",
    category: "EMAIL",
    title: "Architecture e-mail commune (garde Preview, origines par application, gabarit, journal sans fuite, lettre morte) : code prêt",
    status: "NO-GO",
    priority: "P1",
    owner: "Dév (train canonique)",
    dependency: "Porter `claude/practical-ritchie-yvsg3f` (base V5 f6399f15) dans le train V7 et requalifier",
    rationale: "Code prêt et qualifié localement, mais hors train : V6 n'a ni `packages/email/src/identite.ts` ni la garde Preview du transport.",
    evidence: [ref(R.EMAIL, "ELSATIA EMAIL ACTIONS REQUIRED"), optionnel(f("packages/email/src/identite.ts")), optionnel(f("packages/email/src/livraison.ts"))],
    derive: goSiPorte,
  },
  {
    id: "EMAIL-SECURITY-FIXES",
    category: "EMAIL",
    title: "Correctifs de sécurité du lot e-mail absents de V6 : open redirect du callback Réserves, jetons de partage envoyés à Sentry, échappement HTML",
    status: "NO-GO",
    priority: "P1",
    owner: "Dév (train canonique)",
    dependency: "Même portage que EMAIL-CODE-READY (fichiers `apps/reserves/src/app/auth/callback/route.ts`, `src/lib/sentry-nettoyage.ts`)",
    evidence: [ref(R.EMAIL, "Défaut réel corrigé dans Réserves"), optionnel(f("src/lib/sentry-nettoyage.ts"))],
    derive: goSiPorte,
  },
  {
    id: "EMAIL-AUTH-SMTP-PROD",
    category: "EMAIL",
    title: "SMTP Brevo du projet Supabase Production, domaine elsatia.fr authentifié (DKIM), reset testé de bout en bout (lignée pré-V6)",
    status: "GO",
    rationale: "Preuve du registre central (P5, 09-08-2026). Ne couvre pas les gabarits neutres du lot e-mail (EMAIL-HOSTED-TEMPLATES).",
    evidence: [f("docs/organisation/REGISTRE_CENTRAL.md", "SMTP Brevo configuré directement par l'utilisateur"), f("docs/organisation/REGISTRE_CENTRAL.md", "Test de bout en bout réussi après correctifs")],
  },
  {
    id: "EMAIL-BREVO-API-REAL",
    category: "EMAIL",
    title: "Flux applicatifs Brevo (devis/factures, relances, abonnement, support, invitations Réserves) : aucun envoi réel",
    status: "REMOTE_PROOF_REQUIRED",
    priority: "P1",
    owner: "Opérateur",
    dependency: "`smoke:email:preview --brevo-send` vers une adresse de l'allowlist Preview, après EMAIL-CODE-READY",
    evidence: [ref(R.EMAIL, "**Aucun e-mail réel n'a été envoyé.**"), f("scripts/smoke-email-preview.mjs")],
  },
  {
    id: "EMAIL-HOSTED-TEMPLATES",
    category: "EMAIL",
    title: "Gabarits Supabase neutres à reporter dans le Dashboard (Preview et Production) — action A-2",
    status: "MANUAL_REQUIRED",
    priority: "P1",
    owner: "Opérateur",
    dependency: "EMAIL-CODE-READY (gabarits versionnés), puis report manuel dans les deux projets Supabase",
    evidence: [ref(R.EMAIL, "| A-2 |")],
  },
  {
    id: "EMAIL-PRODUCTION-ENV",
    category: "EMAIL",
    title: "ELSATIA_APPLICATION_ENV=production sur GP et Réserves, EMAIL_PREVIEW_ALLOWLIST en Preview — action A-4",
    status: "REMOTE_PROOF_REQUIRED",
    priority: "P1",
    owner: "Opérateur",
    dependency: "Après portage du lot e-mail : sans la variable, la garde fail-closed bloque tous les e-mails Brevo",
    evidence: [ref(R.EMAIL, "| A-4 |")],
  },
  {
    id: "EMAIL-CONTACT-ADDRESS",
    category: "EMAIL",
    title: "Adresse de contact affichée : support@elsatia.fr (registre P14B) ou contact@elsatia.fr (runbook SMTP, audit identité) — action A-3",
    status: "DECISION_REQUIRED",
    priority: "P1",
    owner: "Julien",
    dependency: "Choix écrit, puis SUPPORT_EMAIL, EMAIL_FROM_ADDRESS et pack juridique alignés",
    evidence: [ref(R.EMAIL, "| A-3 |"), f("docs/juridique/README.md", "support@elsatia.fr"), ref(R.LEGAL, "contact@elsatia.fr")],
  },
  {
    id: "EMAIL-AUTH-ROUTING",
    category: "EMAIL",
    title: "Routage Auth par application (reset Tools atterrit sur GP) — action A-1",
    status: "DECISION_REQUIRED",
    priority: "P1",
    owner: "Julien",
    dependency: "Option 1/2/3 du rapport e-mail, puis implémentation",
    evidence: [ref(R.EMAIL, "| A-1 |")],
  },
  {
    id: "EMAIL-PROVIDERS",
    category: "EMAIL",
    title: "Fournisseurs e-mail : SMTP du projet Studio, Brevo API + SMTP (DPA), secours éventuel — action A-8",
    status: "DECISION_REQUIRED",
    priority: "P2",
    owner: "Julien / conseil",
    dependency: "Décision fournisseurs ; Studio OFF au lancement",
    evidence: [ref(R.EMAIL, "| A-8 |")],
  },
  {
    id: "EMAIL-FLOW-DEFECTS",
    category: "EMAIL",
    title: "Défauts de flux ouverts : Studio consomme le jeton au GET (A-5), idempotence B1/B5 (A-6), relais Colors (A-7), repli localhost Réserves (A-9)",
    status: "NO-GO",
    priority: "P2",
    owner: "Dév",
    dependency: "Correctifs P2 du rapport e-mail (A-5, A-6) et décisions A-7, A-9",
    evidence: [ref(R.EMAIL, "| A-5 |"), ref(R.EMAIL, "| A-6 |"), decision("DECISION_REQUIRED:RESERVES-URL-FAIL-CLOSED")],
  },

  // ── LEGAL ──────────────────────────────────────────────────────────────────
  {
    id: "LEGAL-IDENTITY-IN-TRAIN",
    category: "LEGAL",
    title: "Identité officielle (EI, 850 559 873 R.C.S. Strasbourg, elsatia.fr) absente des pages légales de V6",
    status: "NO-GO",
    priority: "P0",
    owner: "Dév (train canonique)",
    blocker: "BLOCKER_LEGAL",
    dependency:
      "Porter l'alignement d'identité de `claude/awesome-franklin-se2s33` — branche partie de main 4d92ddbe, pas de V6 : portage manuel des seules corrections d'identité, puis requalification",
    rationale: "Mentions légales V6 : SIRET « en cours de finalisation », TVA « à confirmer », aucun RCS. Mentions obligatoires d'un éditeur (LCEN).",
    evidence: [
      f("docs/juridique/mentions-legales.md", "[EDITEUR_SIRET]"),
      f("src/components/DocumentLegal.tsx", "en cours de finalisation"),
      ref(R.LEGAL, "850 559 873 R.C.S. Strasbourg"),
      optionnel(f("docs/juridique/mentions-legales.md", "850 559 873")),
    ],
    derive: goSiPorte,
  },
  {
    id: "LEGAL-ADDRESS",
    category: "LEGAL",
    title: "Adresse de publication (mentions légales et factures Stripe) : adresse retenue à l'immatriculation ou domiciliation",
    status: "DECISION_REQUIRED",
    priority: "P0",
    owner: "Exploitant",
    blocker: "BLOCKER_LEGAL",
    dependency: "Décision écrite de l'exploitant (aucune adresse n'est choisie par le gate), puis mentions légales et Stripe alignés",
    evidence: [f("docs/juridique/mentions-legales.md", "à revérifier contre l'avis SIRENE"), ref(R.LEGAL, "Adresse de l'établissement")],
  },
  {
    id: "LEGAL-VAT",
    category: "LEGAL",
    title: "Régime de TVA (franchise « 293 B » ou assujettissement) : prix affichés HT, mention TVA « à confirmer »",
    status: "DECISION_REQUIRED",
    priority: "P0",
    owner: "Exploitant + comptable",
    blocker: "BLOCKER_LEGAL",
    dependency: "Régime confirmé, puis NEXT_PUBLIC_LEGAL_TVA, CGV, /tarifs, Stripe Tax et pied de facture alignés",
    evidence: [f("docs/juridique/cgv.md", "[EDITEUR_MENTION_TVA]"), f("src/components/DocumentLegal.tsx", "à confirmer"), ref(R.LEGAL, "Régime de TVA")],
  },
  {
    id: "LEGAL-SIRET",
    category: "LEGAL",
    title: "SIRET (SIREN + NIC) non connu du dépôt : NEXT_PUBLIC_LEGAL_SIRET vide",
    status: "MANUAL_REQUIRED",
    priority: "P1",
    owner: "Exploitant",
    dependency: "Avis de situation SIRENE, puis NEXT_PUBLIC_LEGAL_SIRET par environnement (aucune valeur inventée)",
    evidence: [f(".env.example", "NEXT_PUBLIC_LEGAL_SIRET="), ref(R.LEGAL, "Le **SIRET** (SIREN + NIC) n'est pas connu")],
  },
  {
    id: "LEGAL-CONTACT",
    category: "LEGAL",
    title: "Boîte de contact publiée dans le pack juridique (support@ ou contact@elsatia.fr)",
    status: "DECISION_REQUIRED",
    priority: "P1",
    owner: "Exploitant",
    blocker: "BLOCKER_LEGAL",
    dependency: "Même décision que EMAIL-CONTACT-ADDRESS",
    evidence: [ref(R.LEGAL, "Boîte `contact@elsatia.fr`"), f("docs/juridique/README.md", "support@elsatia.fr")],
  },
  {
    id: "LEGAL-STRIPE-SELLER",
    category: "LEGAL",
    title: "Identité vendeur Stripe (entreprise, public details, libellé bancaire, pied de facture, CGV/confidentialité)",
    status: "MANUAL_REQUIRED",
    priority: "P0",
    owner: "Exploitant",
    blocker: "BLOCKER_LEGAL",
    dependency: "Checklist opérateur §6 de l'audit d'identité ; dépend de LEGAL-ADDRESS et LEGAL-VAT",
    evidence: [ref(R.LEGAL, "Stripe — champs d'identité vendeur attendus")],
  },
  {
    id: "LEGAL-SHOP",
    category: "LEGAL",
    title: "Boutique matériel : vente de biens hors activité déclarée, Checkout sans `invoice_creation` (aucune facture émise)",
    status: "DECISION_REQUIRED",
    priority: "P1",
    owner: "Juriste + exploitant",
    blocker: "BLOCKER_LEGAL",
    dependency: "Décision juridique avant toute activation (Boutique OFF au lancement)",
    rationale: "La fiche fournisseur « Liria (boutique) » citée par l'audit est déjà renommée dans V6 (migration 20260801000194).",
    evidence: [ref(R.LEGAL, "Boutique matériel"), f("supabase/migrations/20260801000194_renommer_identite_elsatia_boutique.sql")],
  },
  {
    id: "LEGAL-VISUALS",
    category: "LEGAL",
    title: "Guides PDF et vidéos (output/) encore à la marque « Liria » ; icônes PWA de V6 déjà ELSATIA",
    status: "NO-GO",
    priority: "P2",
    owner: "Exploitant / design",
    dependency: "Régénération des guides et vidéos ELSATIA avant toute diffusion (fichiers non servis par l'application)",
    rationale: "L'audit d'identité (base main 4d92ddbe) visait aussi le logo et les icônes : dans V6, public/icons affiche ELSATIA et src/ ne référence aucun fichier output/.",
    evidence: [f("output/pdf/Guide_utilisation_Liria_Gestion_Pro.pdf"), ref(R.LEGAL, "Logos, icônes, guide PDF, vidéos")],
  },
  {
    id: "LEGAL-PROVIDERS-PUBLIC",
    category: "LEGAL",
    title: "Sous-traitants (OpenAI, Sentry, Powens) : garanties et localisation à vérifier avant publication",
    status: "MANUAL_REQUIRED",
    priority: "P1",
    owner: "Juriste",
    blocker: "BLOCKER_LEGAL",
    dependency: "Vérification juridique ; voir RGPD-PROVIDERS",
    evidence: [ref(R.LEGAL, "**Sous-traitants** OpenAI, Sentry, Powens")],
  },
  {
    id: "LEGAL-LAWYER-REVIEW",
    category: "LEGAL",
    title: "Relecture avocat du pack juridique (brouillons, pas un conseil juridique)",
    status: "MANUAL_REQUIRED",
    priority: "P1",
    owner: "Juriste",
    blocker: "BLOCKER_LEGAL",
    dependency: "Pack aligné (LEGAL-IDENTITY-IN-TRAIN, LEGAL-ADDRESS, LEGAL-VAT) puis relecture",
    evidence: [f("docs/juridique/README.md", "à faire relire par un avocat"), f("docs/commercial/GO_LIVE_COMMERCIAL_CHECKLIST.md", "[ ] Relecture avocat effectuée")],
  },
  {
    id: "LEGAL-OTHER-APPS",
    category: "LEGAL",
    title: "Identité légale de Tools, Colors, Réserves, Studio et du site vitrine non auditée ; pack juridique limité à « ELSATIA Gestion Pro »",
    status: "MANUAL_REQUIRED",
    priority: "P1",
    owner: "Dév + juriste",
    dependency: "Audit d'identité par application (référence : audit V1) et extension des CGU/confidentialité aux applications vendues",
    evidence: [ref(R.LEGAL, "Apps Tools, Colors, Réserves, Studio, et site vitrine"), f("docs/juridique/mentions-legales.md", "ELSATIA Gestion Pro")],
  },
  {
    id: "LEGAL-TRADEMARK",
    category: "LEGAL",
    title: "Dépôt de la marque ELSATIA non vérifié",
    status: "DECISION_REQUIRED",
    priority: "P2",
    owner: "Exploitant",
    dependency: "Vérification ; ne pas parler de marque déposée d'ici là",
    evidence: [ref(R.LEGAL, "Dépôt de la marque ELSATIA")],
  },
  {
    id: "LEGAL-ACTIVITY-DATE",
    category: "LEGAL",
    title: "Date d'activité déclarée 01/10/2026",
    status: "NOT_APPLICABLE",
    rationale:
      "Repère de configuration existant (garde DEBUT_COMMERCIALISATION de la branche identité légale). Le gate n'en déduit aucune obligation de vendre ; l'ouverture reste la décision BILL-COMMERCIAL-LOCK.",
    evidence: [ref(R.LEGAL, "DEBUT_COMMERCIALISATION")],
  },

  // ── RGPD ───────────────────────────────────────────────────────────────────
  {
    id: "RGPD-CONTRACT-RETENTION",
    category: "RGPD",
    title: "Conservation des contrats acceptés : A durée, B point de départ (B1/B2), C photos — rien d'activé (fail-closed)",
    status: "DECISION_REQUIRED",
    priority: "P1",
    owner: "Julien + conseil",
    dependency: "Décision écrite dans docs/legal/ELSATIA_RGPD_CONTRACT_RETENTION_OWNER_DECISION_V2.md (aucune durée choisie par le gate), puis activation propriétaire et mise à jour confidentialité/registre/DPA",
    evidence: [
      f("docs/legal/ELSATIA_RGPD_CONTRACT_RETENTION_OWNER_DECISION_V2.md", "fail-closed"),
      v6("**aucune durée, aucun point de départ, aucun sort des\nphotos activés — fail-closed**"),
    ],
  },
  {
    id: "RGPD-LIFECYCLE-DECISIONS",
    category: "RGPD",
    title: "Décisions de cycle de vie ouvertes : tables RETAIN et durée comptable, photos GPS/pointage, pseudonymisation du journal, purge self-service, anonymisation clients",
    status: "DECISION_REQUIRED",
    priority: "P1",
    owner: "Julien + conseil",
    dependency: "LEGAL_DECISION_REQUIRED 1-5 (P1-6, P1-7 des décisions propriétaire)",
    evidence: [f("docs/qualification/ELSATIA_RGPD_DATA_LIFECYCLE_CLOSURE_V3.md", "LEGAL_DECISION_REQUIRED"), f("docs/qualification/ELSATIA_OWNER_DECISIONS_FINAL_V1.md", "P1-6")],
  },
  {
    id: "RGPD-CGV-DELETION-PROMISE",
    category: "RGPD",
    title: "CGV : suppression des données 30 jours après la fin du contrat, sans tâche de production qui l'exécute",
    status: "NO-GO",
    priority: "P1",
    owner: "Dév + Julien",
    dependency: "Planification de la purge (architecture V2 existante) ou modification de la clause CGV",
    evidence: [f("docs/juridique/cgv.md", "délai de **30 jours** pour récupérer ses données"), f("docs/qualification/ELSATIA_RGPD_DATA_LIFECYCLE_CLOSURE_V3.md", "30 jours")],
  },
  {
    id: "RGPD-EMPLOYES-OVEREXPOSURE",
    category: "RGPD",
    title: "Table employes : e-mail, téléphone, notes (et colonnes de carte BTP / code de borne) lisibles par tout membre actif du tenant",
    status: "NO-GO",
    priority: "P1",
    owner: "Dév",
    dependency: "Resserrer la policy SELECT de `employes` (vue `employes_annuaire` = fondation), migrer les 82 lectures `from(\"employes\")` de src/",
    rationale:
      "« ACTUAL BLOCKER (réduit) » de la checklist Preview V2 ; vérifié sur la base V6 neuve : policy PERMISSIVE ALL `est_membre_actif(entreprise_id)`. Intra-tenant uniquement (l'isolation inter-tenant est prouvée).",
    evidence: [
      f("docs/qualification/ELSATIA_PREVIEW_GO_LIVE_CHECKLIST_V2.md", "Sur-exposition RGPD table `employes`"),
      f("supabase/migrations/20260922000312_gp_pilot_employes_annuaire_vue_restreinte.sql", "OUVERT"),
    ],
  },
  {
    id: "RGPD-PURGE-HOSTED",
    category: "RGPD",
    title: "Purge d'entreprise (architecture V2) qualifiée localement ; jamais exécutée sur un projet hébergé",
    status: "REMOTE_PROOF_REQUIRED",
    priority: "P1",
    owner: "Opérateur",
    dependency: "Rejeu de `purger-entreprise.mjs` sur Preview (tenant de recette), runbook RGPD V2",
    evidence: [f("docs/qualification/ELSATIA_RGPD_PURGE_ARCHITECTURE_CLOSURE_V2.md", "RGPD PURGE ARCHITECTURE LOCALLY QUALIFIED"), f("docs/runbooks/ELSATIA_RGPD_PURGE_OPERATION_V2.md")],
  },
  {
    id: "RGPD-RESERVES-PURGE",
    category: "RGPD",
    title: "Aucune couverture RGPD des tables reserves_* (purge, fichiers de plans, mutations appliquées)",
    status: "NO-GO",
    priority: "P1",
    owner: "Dév",
    dependency: "Étendre l'architecture de purge V2 à Réserves (G-05 fichiers `reserves-plans`, R-09 `reserves_mutations_appliquees`)",
    evidence: [
      f("docs/qualification/ELSATIA_RGPD_PURGE_ARCHITECTURE_CLOSURE_V2.md", "ne correspond à des « réserves » de chantier"),
      f("docs/qualification/ELSATIA_RESERVES_FULL_LOCAL_QUALIFICATION_V1.md", "R-09"),
    ],
  },
  {
    id: "RGPD-PROVIDERS",
    category: "RGPD",
    title: "Registre des sous-traitants : région Sentry à confirmer ; hébergeur worker Studio et Redis absents ; réévaluation avant Boutique/Powens",
    status: "MANUAL_REQUIRED",
    priority: "P1",
    owner: "Exploitant",
    dependency: "Confirmer la région Sentry ; compléter le registre au choix de DECISION_REQUIRED:HOSTING-PROVIDER-STUDIO-WORKER",
    evidence: [f("docs/juridique/rgpd-sous-traitants.md", "Confirmer la région du projet Sentry"), decision("DECISION_REQUIRED:HOSTING-PROVIDER-STUDIO-WORKER")],
  },
  {
    id: "RGPD-LOG-RETENTION",
    category: "RGPD",
    title: "Rétention des journaux techniques (Vercel, Supabase, Sentry) et des journaux opérateur non définie ni vérifiée",
    status: "DECISION_REQUIRED",
    priority: "P1",
    owner: "Julien",
    dependency: "Durées décidées puis vérifiées chez chaque fournisseur",
    evidence: [
      f("docs/qualification/ELSATIA_DATA_RETENTION_BACKUP_CONSISTENCY_V1.md", "jamais vérifiée dans ce dépôt"),
      f("docs/operations/AUDIT_LOG_OPERATEUR_V1.md", "Aucune politique de rétention définie"),
    ],
  },
  {
    id: "RGPD-STUDIO-INVITATIONS",
    category: "RGPD",
    title: "Invitations Studio : aucune analyse RGPD dans le train (lot post-H hors V6)",
    status: "DECISION_REQUIRED",
    priority: "P2",
    owner: "Julien",
    dependency: "Lot Studio post-H porté (STUDIO-POST-V6-LOTS) puis classement des données d'invitation ; Studio OFF au lancement",
    evidence: [f("docs/qualification/ELSATIA_STUDIO_V3_PORT_HOSTED_READINESS_V1.md", "invitations"), ref(R.STUDIO_POSTH, "invitations")],
  },
  {
    id: "RGPD-STUDIO-SHARED-WORKSPACES",
    category: "RGPD",
    title: "Effacement Studio : espaces partagés d'un compte supprimé (D3), contenus dans l'espace d'autrui (D4), délai (D1), conservation du journal (D2)",
    status: "DECISION_REQUIRED",
    priority: "P2",
    owner: "Julien + conseil",
    dependency: "Décisions D1-D5, D7 du lot Studio B ; exécution d'effacement `off` d'ici là ; Studio OFF au lancement",
    evidence: [f("docs/qualification/ELSATIA_STUDIO_DB_GUARDS_RGPD_FOUNDATION_V1.md", "**Espaces partagés**")],
  },

  // ── BACKUP_DR ──────────────────────────────────────────────────────────────
  {
    id: "DR-LOCAL",
    category: "BACKUP_DR",
    title: "DR local : backup vérifié par restauration stricte, 4 sinistres, Storage et Auth réels (GoTrue, storage-api) — ELSATIA DR LOCALLY QUALIFIED",
    status: "GO",
    evidence: [ref(R.DR, "ELSATIA DR LOCALLY QUALIFIED"), ref(R.DR, "**0 écart**")],
  },
  {
    id: "DR-TOOLING-IN-TRAIN",
    category: "BACKUP_DR",
    title: "Outillage DR V2 (`npm run dr:verify`, garde-fous) absent du train V6",
    status: "NO-GO",
    priority: "P1",
    owner: "Dév (train canonique)",
    dependency: "Porter `claude/determined-rubin-zdzpmy` (base V5) ; réconcilier ci.yml et le registre des seeds (§16 du rapport DR V2)",
    evidence: [ref(R.DR, "npm run dr:verify"), optionnel(f("scripts/dr/v2/dr-verify.mjs"))],
    derive: goSiPorte,
  },
  {
    id: "DR-REMOTE-BACKUP",
    category: "BACKUP_DR",
    title: "Sauvegarde hébergée (PITR / sauvegardes Supabase) jamais restaurée ni vérifiée",
    status: "REMOTE_PROOF_REQUIRED",
    priority: "P0",
    owner: "Opérateur",
    dependency: "Drill Preview autorisé : restauration de projet / PITR, puis `dr:verify --backup` sur la sauvegarde",
    rationale: "Données clients sans restauration prouvée : risque data majeur.",
    evidence: [ref(R.DR, "Les RTO/RPO hébergés restent **NOT PROVEN**"), f("PRODUCTION_CHECKLIST.md", "Sauvegardes Supabase testées et restaurables")],
  },
  {
    id: "DR-HOSTED-STORAGE",
    category: "BACKUP_DR",
    title: "Fichiers Storage hors des sauvegardes de base : copie S3 → S3 appariée au backup_id à mettre en place",
    status: "REMOTE_PROOF_REQUIRED",
    priority: "P0",
    owner: "Opérateur",
    dependency: "Copie S3 → S3 vérifiée par SHA-256 (manifeste), mesurée sur Preview (R3 du rapport DR V2)",
    evidence: [ref(R.DR, "La sauvegarde des objets d'un projet Supabase hébergé")],
  },
  {
    id: "DR-HOSTED-AUTH-CONFIG",
    category: "BACKUP_DR",
    title: "Configuration Auth hébergée hors base (clés JWT, SMTP, gabarits, hooks, MFA, URLs de redirection) non sauvegardée",
    status: "REMOTE_PROOF_REQUIRED",
    priority: "P1",
    owner: "Opérateur",
    dependency: "Export documenté de la configuration par projet et procédure de révocation globale validée sur Preview",
    evidence: [ref(R.DR, "Nécessite Supabase hébergé (non prouvé)")],
  },
  {
    id: "DR-RTO-RPO",
    category: "BACKUP_DR",
    title: "RTO/RPO hébergés non mesurés ; aucun objectif fixé (mesures locales ≠ SLA)",
    status: "REMOTE_PROOF_REQUIRED",
    priority: "P1",
    owner: "Julien + opérateur",
    dependency: "Objectifs RTO/RPO décidés puis drill Preview mesuré (R8 du rapport DR V2)",
    evidence: [ref(R.DR, "Ces valeurs ne sont pas un SLA")],
  },
  {
    id: "DR-POST-RESTORE-PROCEDURE",
    category: "BACKUP_DR",
    title: "Procédure post-restauration obligatoire : rejeu Stripe (droits rouverts), révocation des sessions et rotation JWT (mots de passe/bans ressuscités)",
    status: "MANUAL_REQUIRED",
    priority: "P0",
    owner: "Opérateur",
    dependency: "Intégrer R1/R2/R6 du rapport DR V2 au runbook DR et les valider sur Preview",
    rationale: "Priorité « P0 procédure » reprise du rapport DR V2.",
    evidence: [ref(R.DR, "| R1 |"), ref(R.DR, "| R2 |"), f("docs/runbooks/ELSATIA_DISASTER_RECOVERY_RUNBOOK_V2.md")],
  },
  {
    id: "DR-VOLUME-PASSPHRASE",
    category: "BACKUP_DR",
    title: "Passphrase du volume DR (seul dépôt de secrets) sans garde documentée (F-DR-VOLUME-PASSPHRASE)",
    status: "MANUAL_REQUIRED",
    priority: "P0",
    owner: "Exploitant",
    dependency: "Deux dépositaires documentés et un test de restauration du volume",
    rationale: "Gravité P0 reprise du manifeste d'environnement.",
    evidence: [finding("F-DR-VOLUME-PASSPHRASE")],
    derive: goSiConstatFerme,
  },

  // ── PREVIEW ────────────────────────────────────────────────────────────────
  {
    id: "PREVIEW-PACK-READY",
    category: "PREVIEW",
    title: "Pack opérateur Preview distante : commande unique, 35 étapes, protection Production, 27 tests hors réseau",
    status: "GO",
    rationale: "Pack prêt ≠ Preview exécutée (voir PREVIEW-EXECUTED).",
    evidence: [ref(R.HANDOFF, "REMOTE PREVIEW OPERATOR HANDOFF PACK V1 READY")],
  },
  {
    id: "PREVIEW-PACK-TARGETS-V6",
    category: "PREVIEW",
    title: "Le pack cible V5 (f6399f15) : son préflight refuse un train plus récent qualifié (V6)",
    status: "NO-GO",
    priority: "P0",
    owner: "Dév (train canonique)",
    dependency: "Porter le pack sur le train retenu et mettre à jour `scripts/preview/qualification/train.json` par revue",
    evidence: [ref(R.HANDOFF, "rend `NO-GO` et demande de mettre à jour `train.json` par revue"), optionnel(f("scripts/preview/qualification/train.json", BASE.commit))],
    derive: goSiPorte,
  },
  {
    id: "PREVIEW-EXECUTED",
    category: "PREVIEW",
    title: "Qualification Preview distante réellement exécutée (V4 : BLOCKED ; pack V1 : NOT EXECUTED)",
    status: "REMOTE_PROOF_REQUIRED",
    priority: "P0",
    owner: "Opérateur",
    dependency: "`npm run preview:qualification -- --mode full --apply-migrations` depuis un poste avec réseau et identifiants ; rendre artifacts/preview-qualification.json",
    evidence: [ref(R.V4EXEC, "V4 PREVIEW BLOCKED"), ref(R.HANDOFF, "`NOT EXECUTED`"), optionnel(f("artifacts/preview-qualification.json", "PREVIEW QUALIFIED\""))],
    derive: (p) => (p.find((x) => x.optional)?.ok ? { status: "GO", rationale: "résultat de qualification Preview présent" } : null),
  },
  {
    id: "PREVIEW-PROJECT-INVENTORY",
    category: "PREVIEW",
    title: "Projets Preview : réutiliser elsatia-preview (limite de 2 projets) ; aucun projet Vercel pour Colors, Tools, Réserves, Studio",
    status: "DECISION_REQUIRED",
    priority: "P0",
    owner: "Julien",
    dependency: "Décision propriétaire (P0-1 des décisions finales) avant toute exécution Preview",
    evidence: [decision("DECISION_REQUIRED:PREVIEW-PROJECT-INVENTORY"), f("docs/qualification/ELSATIA_OWNER_DECISIONS_FINAL_V1.md", "P0-1")],
    derive: goSiDecisionTranchee,
  },
  {
    id: "PREVIEW-MANUAL-CONFIRMATIONS",
    category: "PREVIEW",
    title: "Confirmations manuelles de la Preview (réception des e-mails, parcours humains)",
    status: "MANUAL_REQUIRED",
    priority: "P1",
    owner: "Julien",
    dependency: "Après PREVIEW-EXECUTED : cocher les confirmations de summary.md",
    evidence: [ref(R.HANDOFF, "confirmations manuelles")],
  },

  // ── OBSERVABILITY ──────────────────────────────────────────────────────────
  {
    id: "OBS-SENTRY-CODE",
    category: "OBSERVABILITY",
    title: "Sentry câblé (serveur, edge, navigateur), sendDefaultPii=false, désactivé sans DSN",
    status: "GO",
    evidence: [f("sentry.server.config.ts", "sendDefaultPii: false"), f("sentry.edge.config.ts"), f("docs/SENTRY.md")],
  },
  {
    id: "OBS-SENTRY-PRODUCTION",
    category: "OBSERVABILITY",
    title: "Sentry branché et reçu sur l'environnement Production",
    status: "REMOTE_PROOF_REQUIRED",
    priority: "P1",
    owner: "Opérateur",
    dependency: "DSN posé et événement de test observé en Production",
    evidence: [f("PRODUCTION_CHECKLIST.md", "Sentry branché sur l'environnement Production")],
  },
  {
    id: "OBS-HEALTH-LOGS",
    category: "OBSERVABILITY",
    title: "Journaux structurés, /api/healthz, suivi des tâches planifiées : branche observabilité (PILOT INCIDENT READY) hors train",
    status: "NO-GO",
    priority: "P1",
    owner: "Dév (train canonique)",
    dependency: "Porter `ops/observability-incident-readiness-v1` (base main 4d92ddbe, migration job_runs à renuméroter) puis requalifier",
    evidence: [ref(R.OBS, "PILOT INCIDENT READY"), optionnel(f("src/app/api/healthz/route.ts"))],
    derive: goSiPorte,
  },
  {
    id: "OBS-ALERTING-UPTIME",
    category: "OBSERVABILITY",
    title: "Alerting et surveillance de disponibilité : aucun fournisseur connecté, aucune astreinte définie",
    status: "MANUAL_REQUIRED",
    priority: "P1",
    owner: "Exploitant",
    dependency: "Moniteur externe + canal d'alerte + personne d'astreinte, après OBS-HEALTH-LOGS",
    evidence: [f("PRODUCTION_CHECKLIST.md", "Monitoring/alerting Production"), ref(R.OBS, "Aucun fournisseur d'alertes connecté")],
  },

  // ── PERFORMANCE ────────────────────────────────────────────────────────────
  {
    id: "PERF-V6-CAPACITY",
    category: "PERFORMANCE",
    title: "Capacité GP sur V6 : REMOTE/LOCAL PROOF PENDING (dernier rapport mesuré sur release/gp-v1-rc@8caef21, verdict PILOT CAPACITY READY, pas « 40 utilisateurs »)",
    status: "REMOTE_PROOF_REQUIRED",
    priority: "P1",
    owner: "Dév + opérateur",
    dependency: "Aucun rapport Performance en cours disponible sur origin : rejouer `scripts/perf` sur V6 localement, puis mesurer sur Preview (pooler, latence réelle)",
    evidence: [
      f("docs/qualification/ELSATIA_GP_PERFORMANCE_CAPACITY_V1.md", "PILOT CAPACITY READY"),
      f("docs/qualification/ELSATIA_PREVIEW_GO_LIVE_CHECKLIST_V2.md", "Dashboard 1,7–1,8 s non corrigé"),
    ],
  },
  {
    id: "PERF-RESERVES-LOCAL",
    category: "PERFORMANCE",
    title: "Réserves : recette performance V6 5/5 (2 000 réserves) sur pile locale",
    status: "GO",
    evidence: [v6("V6 performance"), f("docs/qualification/ELSATIA_RESERVES_FULL_LOCAL_QUALIFICATION_V1.md", "2 000 réserves")],
  },
  {
    id: "PERF-RELEVE-LOCAL",
    category: "PERFORMANCE",
    title: "Relevé : 500 murs + 300 ouvertures (next dev), recette V6 16/16",
    status: "GO",
    evidence: [v6("perf 100-500 murs + 50-300 ouvertures"), f("docs/product/ELSATIA_TOOLS_RELEVE_METRE_LOT6_GEOMETRIE_BATIMENT_V1.md", "500 murs + 300 ouvertures")],
  },

  // ── MOBILE ─────────────────────────────────────────────────────────────────
  {
    id: "MOB-EMULATED",
    category: "MOBILE",
    title: "Profils émulés : WebKit iPhone 13 / iPad (gen 7), Pixel 7, colors-mobile 73/73, Réserves V4 mobile 6/6",
    status: "GO",
    rationale: "Émulation seulement ; aucune preuve sur appareil physique.",
    evidence: [f("playwright.config.ts", "iPhone 13"), f("playwright.config.ts", "iPad (gen 7)"), v6("Colors (`colors` + `colors-mobile`)")],
  },
  {
    id: "MOB-IPHONE-PHYSICAL",
    category: "MOBILE",
    title: "iPhone physique : aucun test",
    status: "MANUAL_REQUIRED",
    priority: "P1",
    owner: "Julien",
    dependency: "Recette sur un vrai iPhone contre la Preview HTTPS (après PREVIEW-EXECUTED)",
    evidence: [f("docs/product/ELSATIA_TOOLS_RELEVE_METRE_LOT4_CAPTURE_MEDIA_V1.md", "MOBILE EMULATED ONLY"), f("apps/tools/docs/native-validation-r7.md", "pas sur iPhone physique")],
  },
  {
    id: "MOB-IPAD-PHYSICAL",
    category: "MOBILE",
    title: "iPad physique : aucun test (Relevé tablette : MOBILE EMULATED ONLY)",
    status: "MANUAL_REQUIRED",
    priority: "P1",
    owner: "Julien",
    dependency: "Recette Relevé et Réserves sur un vrai iPad contre la Preview",
    evidence: [f("docs/product/ELSATIA_TOOLS_RELEVE_METRE_LOT6_GEOMETRIE_BATIMENT_V1.md", "MOBILE EMULATED ONLY")],
  },
  {
    id: "MOB-SAFARI-IOS",
    category: "MOBILE",
    title: "Safari / WebKit iOS réel : non testé (seul WebKit desktop piloté par Playwright)",
    status: "MANUAL_REQUIRED",
    priority: "P1",
    owner: "Julien",
    dependency: "Parcours clés (connexion, capture photo, hors ligne, PWA) dans Safari iOS réel",
    evidence: [f("docs/product/ELSATIA_TOOLS_RELEVE_METRE_LOT4_CAPTURE_MEDIA_V1.md", "Safari / WebKit iOS")],
  },
  {
    id: "MOB-FIELD",
    category: "MOBILE",
    title: "Terrain réel : rechargement hors ligne Réserves non exécutable localement, installation PWA réelle non testée",
    status: "MANUAL_REQUIRED",
    priority: "P1",
    owner: "Julien",
    dependency: "Recette terrain (réseau dégradé, hors ligne, PWA installée) sur appareils réels",
    evidence: [v6("--grep-invert \"rechargement hors ligne\""), f("PRODUCTION_CHECKLIST.md", "installation réelle sur appareil non testée")],
  },
  {
    id: "MOB-NATIVE-STORES",
    category: "MOBILE",
    title: "Tools natif : installation sur appareil réel non cochée (TestFlight / Google Play)",
    status: "MANUAL_REQUIRED",
    priority: "P2",
    owner: "Julien",
    dependency: "Distribution magasins d'applications (hors vente web)",
    evidence: [f("docs/mobile-stores/tools/TOOLS_TESTFLIGHT_CHECKLIST_V1.md", "Installation vérifiée sur un appareil réel")],
  },

  // ── STUDIO ─────────────────────────────────────────────────────────────────
  {
    id: "STUDIO-OFF-AT-LAUNCH",
    category: "STUDIO",
    title: "Studio OFF pour la première Preview (aucune migration Studio dans le projet partagé, STUDIO_ACCESS_MODE=closed)",
    status: "GO",
    evidence: [v6("**Studio reste OFF pour la première Preview**")],
  },
  {
    id: "STUDIO-LOCAL",
    category: "STUDIO",
    title: "Chaîne Studio dédiée : 14 migrations, 543 pgTAP, 0 table GP, identité B + I1 73/73 ×3",
    status: "GO",
    evidence: [v6("pgTAP **543 ok, 0 échec**"), f("apps/studio/scripts/dedicated-db-check.sh")],
  },
  {
    id: "STUDIO-POST-V6-LOTS",
    category: "STUDIO",
    title: "Studio post-H et banc E2E dédié (21/21 ×4, correctif F1) qualifiés hors train",
    status: "NO-GO",
    priority: "P2",
    owner: "Dév (train canonique)",
    dependency: "Porter `claude/jolly-volta-doejq2` (inclut `claude/modest-pasteur-izfaqm`, base fb7082c6) ; Studio OFF au lancement",
    evidence: [ref(R.STUDIO_E2E, "STUDIO DEDICATED E2E LOCALLY QUALIFIED"), ref(R.STUDIO_POSTH, "STUDIO POST-H LOCALLY QUALIFIED"), optionnel(f("apps/studio/e2e-dedicated"))],
    derive: goSiPorte,
  },
  {
    id: "STUDIO-HOSTED",
    category: "STUDIO",
    title: "Projet Supabase Studio dédié hébergé et contrôles H1-H6 non exécutés",
    status: "REMOTE_PROOF_REQUIRED",
    priority: "P2",
    owner: "Opérateur",
    dependency: "Projet dédié provisionné (décision B + I1 tranchée), checklist H1-H6 ; Studio OFF au lancement",
    evidence: [f("docs/qualification/ELSATIA_STUDIO_DB_GUARDS_RGPD_FOUNDATION_V1.md", "H1"), decision("DECISION_REQUIRED:STUDIO-DEDICATED-SUPABASE-AND-CONTINUATION")],
  },
  {
    id: "STUDIO-DECISIONS",
    category: "STUDIO",
    title: "Décisions Studio ouvertes : mode d'inscription en Production, hébergeur du worker vidéo",
    status: "DECISION_REQUIRED",
    priority: "P2",
    owner: "Julien",
    dependency: "Avant toute ouverture de Studio (OFF au lancement)",
    evidence: [decision("DECISION_REQUIRED:STUDIO-SIGNUP-DEFAULT"), decision("DECISION_REQUIRED:HOSTING-PROVIDER-STUDIO-WORKER")],
  },

  // ── TOOLS_RELEVE ───────────────────────────────────────────────────────────
  {
    id: "TOOLS-RELEVE-LOCAL",
    category: "TOOLS_RELEVE",
    title: "Relevé & Métré Lots 2-6 + Atelier : Playwright 68/68, pgTAP Relevé propres, surface pièce serveur 32/32",
    status: "GO",
    evidence: [v6("**Relevé + Atelier total**"), v6("`elsatia_tools_releve_surface_piece_sync_v1` **32/32**")],
  },
  {
    id: "TOOLS-ENTITLEMENT",
    category: "TOOLS_RELEVE",
    title: "Contournement d'entitlement cloud-sync fermé localement (16/16), jamais rejoué sur Supabase réel",
    status: "REMOTE_PROOF_REQUIRED",
    priority: "P1",
    owner: "Opérateur",
    dependency: "pgTAP `elsatia_tools_cloud_sync_entitlement_closure_v1` sur un vrai projet Supabase (erreurs d'amorce localement)",
    evidence: [f("docs/qualification/ELSATIA_TOOLS_ENTITLEMENT_CLOUD_SYNC_CLOSURE_V1.md", "TOOLS ENTITLEMENT BLOCKER CLOSED LOCALLY")],
  },
  {
    id: "TOOLS-DOWNGRADE-READ",
    category: "TOOLS_RELEVE",
    title: "Utilisateur rétrogradé : perte de lecture des projets synchronisés (choix conservateur à confirmer, DECISION_REQUIRED-04)",
    status: "DECISION_REQUIRED",
    priority: "P1",
    owner: "Julien",
    dependency: "Confirmation explicite du comportement avant vente de l'offre Tools Pro",
    evidence: [f("docs/qualification/ELSATIA_TOOLS_ENTITLEMENT_CLOUD_SYNC_CLOSURE_V1.md", "DECISION_REQUIRED-04")],
  },
  {
    id: "TOOLS-RELEVE-LOT7",
    category: "TOOLS_RELEVE",
    title: "Relevé Lot 7 (mobilier, équipements, calques) qualifié hors train",
    status: "NO-GO",
    priority: "P2",
    owner: "Dév (train canonique)",
    dependency: "Porter `claude/nifty-edison-mevolm` (base Lot 6 d734f255) dans le train suivant",
    evidence: [ref(R.RELEVE7, "RELEVE METRE LOT 7 LOCALLY QUALIFIED")],
  },
  {
    id: "TOOLS-VOLUME-PIECE",
    category: "TOOLS_RELEVE",
    title: "Volume de la pièce non calculé (colonne réservée)",
    status: "DECISION_REQUIRED",
    priority: "P2",
    owner: "Julien",
    dependency: "DECISION_REQUIRED:V6-VOLUME-PIECE",
    evidence: [v6("`DECISION_REQUIRED:V6-VOLUME-PIECE`")],
  },

  // ── RESERVES ───────────────────────────────────────────────────────────────
  {
    id: "RES-LOCAL",
    category: "RESERVES",
    title: "Réserves : 59/59 Playwright, D-01 7/7, GP ↔ Réserves 5/5 ×3 sur V6",
    status: "GO",
    evidence: [f("docs/qualification/ELSATIA_RESERVES_FULL_LOCAL_QUALIFICATION_V1.md", "RESERVES LOCALLY QUALIFIED"), v6("**59/59**"), v6("**5/5 ×3**")],
  },
  {
    id: "RES-HOSTED",
    category: "RESERVES",
    title: "Storage réel (S3), GoTrue réel et e-mails d'invitation non couverts par la pile locale (H-01)",
    status: "REMOTE_PROOF_REQUIRED",
    priority: "P1",
    owner: "Opérateur",
    dependency: "Qualification Preview Réserves (projet Vercel à créer, voir PREVIEW-PROJECT-INVENTORY)",
    evidence: [f("docs/qualification/ELSATIA_RESERVES_FULL_LOCAL_QUALIFICATION_V1.md", "H-01")],
  },
  {
    id: "RES-MINOR-DEFECTS",
    category: "RESERVES",
    title: "Défauts mineurs ouverts : R-06 auteur nul, R-07 nb_pages réécrivable, R-08 échappement de recherche",
    status: "NO-GO",
    priority: "P2",
    owner: "Dév",
    dependency: "Correctifs P3 du rapport Réserves",
    evidence: [f("docs/qualification/ELSATIA_RESERVES_FULL_LOCAL_QUALIFICATION_V1.md", "R-07")],
  },
  {
    id: "RES-SENTRY",
    category: "RESERVES",
    title: "Télémétrie Sentry absente de Réserves",
    status: "NOT_APPLICABLE",
    rationale: "Choix produit assumé documenté (NON-BLOCKER) ; l'alerting global relève d'OBS-ALERTING-UPTIME.",
    evidence: [f("docs/qualification/ELSATIA_PREVIEW_GO_LIVE_CHECKLIST_V2.md", "Absente par choix produit assumé")],
  },

  // ── COLORS ─────────────────────────────────────────────────────────────────
  {
    id: "COLORS-LOCAL",
    category: "COLORS",
    title: "Colors : 442 pgTAP, 431 Vitest, Playwright 73/73 (V6) — COLORS LOCALLY QUALIFIED",
    status: "GO",
    evidence: [f("docs/qualification/ELSATIA_COLORS_FULL_QUALIFICATION_V2.md", "COLORS LOCALLY QUALIFIED"), v6("**73/73**")],
  },
  {
    id: "COLORS-PREVIEW",
    category: "COLORS",
    title: "Colors Preview : domaine 13 « Preview config » non prouvé, 73 e2e à rejouer sur Preview, supabase test db réel",
    status: "REMOTE_PROOF_REQUIRED",
    priority: "P1",
    owner: "Opérateur",
    dependency: "Projet Vercel Colors (PREVIEW-PROJECT-INVENTORY), option « fichiers hors racine », rejeu e2e",
    evidence: [f("docs/qualification/ELSATIA_COLORS_FULL_QUALIFICATION_V2.md", "Preview config")],
  },
  {
    id: "COLORS-OPEN-ITEMS",
    category: "COLORS",
    title: "Colors : redirection des actions suspendues (R1, UX), écran /utilisateurs « ComingSoon »",
    status: "NO-GO",
    priority: "P2",
    owner: "Dév",
    dependency: "§7 du rapport Colors V2",
    evidence: [f("docs/qualification/ELSATIA_COLORS_FULL_QUALIFICATION_V2.md", "ComingSoon")],
  },
  {
    id: "COLORS-LICENSED-CHART",
    category: "COLORS",
    title: "Nuancier sous licence / OCR (DPA requis)",
    status: "DECISION_REQUIRED",
    priority: "P2",
    owner: "Julien",
    dependency: "P2-10 des décisions propriétaire",
    evidence: [f("docs/qualification/ELSATIA_OWNER_DECISIONS_FINAL_V1.md", "P2-10")],
  },

  // ── OPERATIONS ─────────────────────────────────────────────────────────────
  {
    id: "OPS-SUPPORT",
    category: "OPERATIONS",
    title: "Processus support premiers clients (support@elsatia.fr, priorités P0-P3, fil in-app, aucun SLA promis)",
    status: "GO",
    evidence: [f("docs/commercial/SUPPORT_PREMIERS_CLIENTS.md", "support@elsatia.fr")],
  },
  {
    id: "OPS-ROLLBACK",
    category: "OPERATIONS",
    title: "Go-live et rollback Production documentés, jamais répétés sur la lignée V6",
    status: "REMOTE_PROOF_REQUIRED",
    priority: "P1",
    owner: "Opérateur",
    dependency: "Répétition du rollback applicatif (Vercel) et du correctif base forward-only sur Preview",
    evidence: [f("docs/runbooks/ELSATIA_PRODUCTION_ROLLBACK_V1.md"), f("docs/DEPLOIEMENT_ET_RETOUR_ARRIERE.md", "restaure pas la base Supabase")],
  },
  {
    id: "OPS-V6-PRODUCTION",
    category: "OPERATIONS",
    title: "Production (app.elsatia.fr) sur une lignée antérieure : V6 jamais déployé",
    status: "REMOTE_PROOF_REQUIRED",
    priority: "P0",
    owner: "Opérateur",
    dependency: "PREVIEW-EXECUTED vert, puis bascule Production selon le runbook de cutover",
    evidence: [v6("V6 **non déployé**"), f("docs/runbooks/ELSATIA_GP_CUTOVER_DAY_OF_RUNBOOK_V1.md")],
  },
  {
    id: "OPS-PREFLIGHT-ENFORCEMENT",
    category: "OPERATIONS",
    title: "Préflight d'environnement : « enforce » en Preview, pas encore en Production (F-PREFLIGHT-ENFORCEMENT)",
    status: "NO-GO",
    priority: "P1",
    owner: "Dév",
    dependency: "Passer `preflight_enforcement_by_target.production` à enforce après vérification des variables Production",
    evidence: [finding("F-PREFLIGHT-ENFORCEMENT")],
    derive: goSiConstatFerme,
  },
  {
    id: "OPS-CRONS-FAIL-OPEN",
    category: "OPERATIONS",
    title: "FEATURE_CRONS_ENABLED fail-open (absent = tâches planifiées actives)",
    status: "DECISION_REQUIRED",
    priority: "P1",
    owner: "Julien",
    dependency: "DECISION_REQUIRED:FLAG-CRONS-FAIL-OPEN (poser la variable avant tout déploiement si fail-closed)",
    evidence: [decision("DECISION_REQUIRED:FLAG-CRONS-FAIL-OPEN"), finding("F-FLAG-CRONS-FAIL-OPEN")],
    derive: goSiDecisionTranchee,
  },
];
