import Link from "next/link";
import { ajouterZonePaieAction, enregistrerParametresPaieAction } from "@/app/actions/paie";
import { getContexteEntreprise } from "@/lib/entreprise";
import { createClient } from "@/lib/supabase/server";

const champ="mt-1 w-full rounded border px-3 py-2 text-sm dark:bg-neutral-900";
export default async function ParametresPaiePage({searchParams}:{searchParams:Promise<{error?:string;success?:string}>}){
 const [{error,success},ctx]=await Promise.all([searchParams,getContexteEntreprise()]);const supabase=await createClient();
 const [{data:p},{data:zones}]=await Promise.all([
  supabase.from("parametres_paie_entreprise").select("*").eq("entreprise_id",ctx.entrepriseId).maybeSingle(),
  supabase.from("zones_deplacement_paie").select("*").eq("entreprise_id",ctx.entrepriseId).order("valide_du",{ascending:false}),
 ]);
 return <main className="p-4 sm:p-8"><div className="mx-auto max-w-5xl space-y-6"><header><Link href="/paie" className="text-sm text-neutral-500 hover:underline">← Préparation de la paie</Link><h1 className="mt-2 text-2xl font-semibold">Paramètres permanents de paie</h1><p className="text-sm text-neutral-500">Ces valeurs sont reprises chaque mois et restent modifiables uniquement par les personnes habilitées.</p></header>{error&&<p className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}{success&&<p className="rounded bg-green-50 p-3 text-sm text-green-700">{success}</p>}
 <form action={enregistrerParametresPaieAction} className="grid gap-4 rounded-lg border p-4 sm:grid-cols-2"><h2 className="font-semibold sm:col-span-2">Entreprise et cabinet comptable</h2>
  <label className="text-xs text-neutral-500 sm:col-span-2">Convention collective<input name="convention_collective" defaultValue={p?.convention_collective??"Convention collective nationale des ouvriers du bâtiment"} className={champ}/></label>
  <label className="text-xs text-neutral-500">Mutuelle<input name="organisme_mutuelle" defaultValue={p?.organisme_mutuelle??""} className={champ}/></label><label className="text-xs text-neutral-500">Prévoyance<input name="organisme_prevoyance" defaultValue={p?.organisme_prevoyance??""} className={champ}/></label>
  <label className="text-xs text-neutral-500">Caisse retraite<input name="caisse_retraite" defaultValue={p?.caisse_retraite??""} className={champ}/></label><label className="text-xs text-neutral-500">Caisse CIBTP<input name="caisse_cibtp" defaultValue={p?.caisse_cibtp??""} className={champ}/></label>
  <label className="text-xs text-neutral-500">Taux accident du travail (%)<input name="taux_accident_travail" type="number" min="0" max="100" step="0.0001" defaultValue={p?.taux_accident_travail??""} className={champ}/></label><label className="text-xs text-neutral-500">Jour de clôture<input name="jour_cloture" type="number" min="1" max="31" defaultValue={p?.jour_cloture??25} className={champ}/></label>
  <label className="text-xs text-neutral-500">Jour habituel de paiement<input name="jour_paiement" type="number" min="1" max="31" defaultValue={p?.jour_paiement??30} className={champ}/></label><label className="text-xs text-neutral-500">Cabinet comptable<input name="cabinet_comptable" defaultValue={p?.cabinet_comptable??""} className={champ}/></label>
  <label className="text-xs text-neutral-500">Contact comptable<input name="contact_comptable" defaultValue={p?.contact_comptable??""} className={champ}/></label><label className="text-xs text-neutral-500">E-mail comptable<input name="email_comptable" type="email" defaultValue={p?.email_comptable??""} className={champ}/></label>
  <label className="text-xs text-neutral-500 sm:col-span-2">Consignes permanentes<textarea name="consignes_permanentes" rows={3} defaultValue={p?.consignes_permanentes??""} className={champ}/></label><button className="rounded bg-[#0d1b2a] px-4 py-2 text-sm font-semibold text-white sm:col-span-2">Enregistrer les paramètres</button>
 </form>
 <section className="space-y-4 rounded-lg border p-4"><div><h2 className="font-semibold">Zones BTP et barèmes historiques</h2><p className="text-sm text-neutral-500">Chaque changement crée une nouvelle ligne datée : l’ancien barème reste exploitable pour les périodes antérieures.</p></div><form action={ajouterZonePaieAction} className="grid gap-3 sm:grid-cols-3"><input name="nom" required placeholder="Zone 1" className={champ}/><input name="distance_min_km" required type="number" min="0" step="0.1" placeholder="Distance min." className={champ}/><input name="distance_max_km" type="number" min="0" step="0.1" placeholder="Distance max." className={champ}/><input name="indemnite_trajet" type="number" min="0" step="0.01" placeholder="Trajet €" className={champ}/><input name="indemnite_transport" type="number" min="0" step="0.01" placeholder="Transport €" className={champ}/><input name="panier" type="number" min="0" step="0.01" placeholder="Panier €" className={champ}/><label className="text-xs text-neutral-500">Valide du<input name="valide_du" required type="date" className={champ}/></label><label className="text-xs text-neutral-500">Valide au<input name="valide_au" type="date" className={champ}/></label><button className="self-end rounded border px-4 py-2 text-sm font-medium">Ajouter le barème</button></form><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead><tr className="text-left text-xs uppercase text-neutral-500"><th className="p-2">Zone</th><th className="p-2">Distances</th><th className="p-2">Trajet</th><th className="p-2">Transport</th><th className="p-2">Panier</th><th className="p-2">Validité</th></tr></thead><tbody>{(zones??[]).map(z=><tr key={z.id} className="border-t"><td className="p-2 font-medium">{z.nom}</td><td className="p-2">{z.distance_min_km}–{z.distance_max_km??"∞"} km</td><td className="p-2">{z.indemnite_trajet} €</td><td className="p-2">{z.indemnite_transport} €</td><td className="p-2">{z.panier} €</td><td className="p-2">{z.valide_du} → {z.valide_au??"en cours"}</td></tr>)}</tbody></table></div></section>
 </div></main>;
}
