import Link from "next/link";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getContexteEntreprise } from "@/lib/entreprise";
import { permissionsUtilisateur } from "@/lib/permissions";
import { CoordonneesBancairesForm } from "@/components/CoordonneesBancairesForm";
import { DELAIS_PAIEMENT_FOURNISSEUR, libelleDelaiPaiementFournisseur } from "@/lib/echeances-fournisseurs";
import { affecterSousTraitantAction, modifierSousTraitantAction, retirerAffectationSousTraitantAction } from "@/app/actions/sous-traitants";
import { euros } from "@/lib/devis";
import { lireCurseur, lireOptionsChantiers, lirePageCurseur, lireSyntheseDepenses, lireSyntheseMissionsSousTraitant, type SyntheseDepenses, type SyntheseMissions } from "@/lib/fiches-agregats";

const TAILLE_PAGE=50;

const champ="mt-1 w-full rounded-md border border-neutral-300 bg-white px-3 py-2 text-sm dark:border-neutral-700 dark:bg-neutral-900";
const un=<T,>(valeur:T|T[]|null):T|null=>Array.isArray(valeur)?valeur[0]??null:valeur;

export default async function SousTraitantDetailPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string;success?:string;missions_apres?:string;factures_apres?:string}>}){
  const {id}=await params;const messages=await searchParams;const ctx=await getContexteEntreprise();const supabase=await createClient();const permissions=await permissionsUtilisateur(ctx);
  const peutGerer=permissions===null||permissions.includes("gerer_sous_traitants");
  const peutGererRib=!ctx.accesSupportPlateforme&&(permissions===null||permissions.includes("gerer_coordonnees_bancaires"));
  const peutVoirFactures=permissions===null||permissions.includes("acces_achats");
  const peutVoirMissions=permissions===null||permissions.includes("acces_sous_traitants");
  // Totaux en base (gp_sous_traitant_missions_synthese, gp_depenses_synthese) :
  // PostgREST tronquait missions et factures à 1 000 lignes sans erreur.
  // Listes paginées par curseur ; en cas d'erreur, « indisponible ».
  const curseurMissions=lireCurseur(messages.missions_apres),curseurFactures=lireCurseur(messages.factures_apres);
  const [{data:tiers},pageMissions,{data:chantiers},pageFactures,{data:rib},syntheseMissions,syntheseFactures]=await Promise.all([
    supabase.from("fournisseurs").select("*").eq("id",id).eq("entreprise_id",ctx.entrepriseId).eq("type_tiers","sous_traitant").maybeSingle(),
    !peutVoirMissions?Promise.resolve({lignes:[],suivant:null}):lirePageCurseur(supabase.from("sous_traitants_chantiers").select("id,mission,date_debut,date_fin,montant_previsionnel_ht,statut,notes,created_at,chantier:chantiers(id,nom,reference_interne)").eq("entreprise_id",ctx.entrepriseId).eq("fournisseur_id",id),"created_at",TAILLE_PAGE,curseurMissions),
    peutGerer?lireOptionsChantiers(supabase,ctx.entrepriseId).then((data)=>({data})):Promise.resolve({data:[]}),
    peutVoirFactures?lirePageCurseur(supabase.from("depenses_fournisseurs").select("id,numero_piece,date_piece,date_echeance,montant_ht,montant_ttc,montant_regle,statut,chantier:chantiers(id,nom)").eq("entreprise_id",ctx.entrepriseId).eq("fournisseur_id",id),"date_piece",TAILLE_PAGE,curseurFactures):Promise.resolve({lignes:[],suivant:null}),
    peutGererRib?supabase.from("coordonnees_bancaires").select("titulaire,iban_quatre_derniers,verification_statut,verification_message").eq("entreprise_id",ctx.entrepriseId).eq("fournisseur_id",id).eq("actif",true).maybeSingle():Promise.resolve({data:null}),
    !peutVoirMissions?Promise.resolve({nb:0,nbActives:0,previsionnelHt:0} as SyntheseMissions):lireSyntheseMissionsSousTraitant(supabase,ctx.entrepriseId,id).catch((err):SyntheseMissions|null=>{console.error("[sous-traitant] missions indisponibles",err instanceof Error?err.message:err);return null;}),
    peutVoirFactures?lireSyntheseDepenses(supabase,ctx.entrepriseId,{fournisseurId:id}).catch((err):SyntheseDepenses|null=>{console.error("[sous-traitant] factures indisponibles",err instanceof Error?err.message:err);return null;}):Promise.resolve(null),
  ]);
  if(!tiers)notFound();
  const affectations=pageMissions.lignes,factures=pageFactures.lignes;
  const montant=(v:number|null|undefined)=>v===null||v===undefined?"indisponible":euros(v);
  const lienPage=(cle:"missions_apres"|"factures_apres",valeur:string|null)=>{const q=new URLSearchParams();if(cle==="missions_apres"){if(valeur)q.set(cle,valeur);if(messages.factures_apres)q.set("factures_apres",messages.factures_apres);}else{if(messages.missions_apres)q.set("missions_apres",messages.missions_apres);if(valeur)q.set(cle,valeur);}const t=q.toString();return `/sous-traitants/${id}${t?`?${t}`:""}`;};
  const pagination=(cle:"missions_apres"|"factures_apres",courant:boolean,suivant:string|null)=>(courant||suivant)?<nav aria-label="Pagination" className="mt-3 flex items-center justify-between text-sm">{courant?<Link href={lienPage(cle,null)} className="rounded-md border px-3 py-2">← Plus récentes</Link>:<span/>}{suivant?<Link href={lienPage(cle,suivant)} className="rounded-md border px-3 py-2">Plus anciennes →</Link>:<span/>}</nav>:null;
  const input=(nom:string,label:string,valeur:string|null,type="text")=><label className="text-xs text-neutral-500">{label}<input name={nom} type={type} defaultValue={valeur??""} className={champ}/></label>;
  return <main className="p-4 sm:p-8"><div className="mx-auto max-w-5xl space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><Link href="/sous-traitants" className="text-sm text-neutral-500">← Sous-traitants</Link><h1 className="mt-1 text-2xl font-semibold">{tiers.nom}</h1><p className="font-mono text-xs text-neutral-500">{tiers.reference} · {tiers.specialite??"Sous-traitant"}</p></div>{peutVoirFactures&&<Link href={`/depenses?fournisseur=${id}&categorie=sous_traitance`} className="rounded-md bg-[#0d1b2a] px-3 py-2 text-sm text-white">Nouvelle facture de sous-traitance</Link>}</header>
    {messages.error&&<p className="rounded bg-red-50 p-3 text-sm text-red-700">{messages.error}</p>}{messages.success&&<p className="rounded bg-green-50 p-3 text-sm text-green-700">{messages.success}</p>}
    <section className="grid gap-3 sm:grid-cols-3"><div className="rounded-md border p-4"><p className="text-xs text-neutral-500">Missions actives</p><strong className="text-xl">{syntheseMissions?syntheseMissions.nbActives:"indisponible"}</strong></div><div className="rounded-md border p-4"><p className="text-xs text-neutral-500">Prévisionnel HT</p><strong className="text-xl">{montant(syntheseMissions?.previsionnelHt)}</strong></div>{peutVoirFactures&&<div className="rounded-md border p-4"><p className="text-xs text-neutral-500">Facturé HT / réglé TTC</p><strong className="text-xl">{montant(syntheseFactures?.totalHt)} / {montant(syntheseFactures?.totalRegle)}</strong></div>}</section>
    {peutGerer&&<form action={modifierSousTraitantAction.bind(null,id)} className="grid gap-3 rounded-md border p-4 sm:grid-cols-2"><h2 className="font-semibold sm:col-span-2">Fiche du sous-traitant</h2>{input("nom","Raison sociale",tiers.nom)}{input("specialite","Spécialité",tiers.specialite)}{input("contact_nom","Contact",tiers.contact_nom)}{input("email","E-mail",tiers.email,"email")}{input("telephone","Téléphone",tiers.telephone)}{input("siret","SIRET",tiers.siret)}{input("numero_tva","N° TVA intracommunautaire",tiers.numero_tva)}{input("adresse","Adresse",tiers.adresse)}{input("code_postal","Code postal",tiers.code_postal)}{input("ville","Ville",tiers.ville)}{input("assurance_rc_pro","Assurance RC Pro / police",tiers.assurance_rc_pro)}{input("assurance_decennale","Assurance décennale / police",tiers.assurance_decennale)}{input("date_validite_assurance","Validité des assurances",tiers.date_validite_assurance,"date")}<label className="text-xs text-neutral-500">Délai de paiement<select name="delai_paiement_jours" defaultValue={String(tiers.delai_paiement_jours??30)} className={champ}>{DELAIS_PAIEMENT_FOURNISSEUR.map(d=><option key={d} value={d}>{libelleDelaiPaiementFournisseur(d)}</option>)}</select></label><label className="text-xs text-neutral-500 sm:col-span-2">Notes<textarea name="notes" rows={3} defaultValue={tiers.notes??""} className={champ}/></label><button className="rounded-md bg-[#0d1b2a] px-4 py-2 text-white sm:col-span-2">Enregistrer</button></form>}
    {peutGererRib&&<CoordonneesBancairesForm type="fournisseur" beneficiaireId={id} retour={`/sous-traitants/${id}`} rib={rib}/>}
    <section className="space-y-4 rounded-md border p-4"><div><h2 className="font-semibold">Missions et chantiers</h2><p className="text-sm text-neutral-500">Le budget prévu et les factures réelles sont intégrés à la rentabilité du chantier.</p></div>
      {peutGerer&&<form action={affecterSousTraitantAction.bind(null,id)} className="grid gap-3 rounded-md bg-neutral-50 p-3 dark:bg-neutral-900 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs text-neutral-500 lg:col-span-2">Chantier<select name="chantier_id" required className={champ}><option value="">— Choisir —</option>{(chantiers??[]).map(c=><option key={c.id} value={c.id}>{c.nom} · {c.reference_interne}</option>)}</select></label><label className="text-xs text-neutral-500 lg:col-span-2">Mission<input name="mission" required placeholder="Lot, intervention ou travaux confiés" className={champ}/></label><label className="text-xs text-neutral-500">Début<input name="date_debut" type="date" className={champ}/></label><label className="text-xs text-neutral-500">Fin prévue<input name="date_fin" type="date" className={champ}/></label><label className="text-xs text-neutral-500">Budget HT<input name="montant_previsionnel_ht" type="number" min="0" step="0.01" defaultValue="0" className={champ}/></label><label className="text-xs text-neutral-500">Statut<select name="statut" defaultValue="prevue" className={champ}><option value="prevue">Prévue</option><option value="en_cours">En cours</option><option value="terminee">Terminée</option><option value="annulee">Annulée</option></select></label><label className="text-xs text-neutral-500 lg:col-span-3">Notes<input name="notes" className={champ}/></label><button className="self-end rounded-md bg-[#0d1b2a] px-4 py-2 text-sm text-white">Affecter</button></form>}
      <div className="space-y-2">{(affectations??[]).map(a=>{const chantier=un(a.chantier as {id:string;nom:string;reference_interne:string}|{id:string;nom:string;reference_interne:string}[]|null);return <article key={a.id} className="flex flex-wrap items-start justify-between gap-3 rounded-md border p-3"><div><Link href={`/chantiers/${chantier?.id}`} className="font-semibold hover:underline">{chantier?.nom??"Chantier"}</Link><p className="text-sm">{a.mission} · {a.statut.replaceAll("_"," ")}</p><small className="text-neutral-500">{a.date_debut??"date à définir"}{a.date_fin?` → ${a.date_fin}`:""}</small></div><div className="text-right"><strong>{euros(Number(a.montant_previsionnel_ht))} HT</strong>{peutGerer&&<form action={retirerAffectationSousTraitantAction.bind(null,id,a.id)}><button className="block text-xs text-red-700">Retirer</button></form>}</div></article>})}{!affectations?.length&&<p className="rounded border border-dashed p-4 text-sm text-neutral-500">Aucune mission affectée.</p>}</div>{pagination("missions_apres",Boolean(curseurMissions),pageMissions.suivant)}
    </section>
    {peutVoirFactures&&<section className="rounded-md border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Factures et règlements</h2><p className="text-sm text-neutral-500">Même circuit sécurisé que les fournisseurs.</p></div><Link href="/depenses" className="rounded-md bg-[#0d1b2a] px-3 py-2 text-sm text-white">Enregistrer / régler une facture</Link></div><div className="mt-3 divide-y">{(factures??[]).map(f=>{const chantier=un(f.chantier as {id:string;nom:string}|{id:string;nom:string}[]|null);return <Link key={f.id} href={`/depenses/${f.id}`} className="flex justify-between gap-3 py-3 text-sm"><span><strong>{f.numero_piece}</strong><small className="block text-neutral-500">{f.date_piece}{chantier?` · ${chantier.nom}`:" · sans chantier"}</small></span><span className="text-right">{euros(Number(f.montant_ttc))}<small className="block text-neutral-500">Réglé {euros(Number(f.montant_regle))}</small></span></Link>})}{!factures?.length&&<p className="py-4 text-sm text-neutral-500">Aucune facture enregistrée.</p>}</div>{syntheseFactures&&<p className="mt-2 text-xs text-neutral-500">{syntheseFactures.nb} facture(s) au total.</p>}{pagination("factures_apres",Boolean(curseurFactures),pageFactures.suivant)}</section>}
  </div></main>;
}
