import { getContexteEntreprise } from "@/lib/entreprise";
import { createClient } from "@/lib/supabase/server";
import { creerConnecteurAction, preparerConnecteurFournisseurAction, preparerConnecteurFournisseurLibreAction } from "@/app/actions/suite-metier";
import { euros } from "@/lib/devis";
import { completerStripeTestAction, connecterStripeAction } from "@/app/actions/paiements-en-ligne";
import { stripeEstConfigure } from "@/lib/stripe";
import { CONNECTEURS_FOURNISSEURS_CONNUS, LIBELLES_MODES_CONNECTEUR } from "@/lib/fournisseur-connecteurs";

const champ="mt-1 w-full rounded-md border border-neutral-300 bg-white px-3 py-2 text-sm dark:border-neutral-700 dark:bg-neutral-900";
function portailDepuisConfiguration(configuration:unknown){if(!configuration||typeof configuration!=="object"||Array.isArray(configuration))return null;const valeur=(configuration as Record<string,unknown>).portail_url;return typeof valeur==="string"&&valeur.startsWith("https://")?valeur:null;}
export default async function ConnecteursPage({searchParams}:{searchParams:Promise<{error?:string;success?:string}>}){
 const message=await searchParams,ctx=await getContexteEntreprise(),sb=await createClient();const [{data:connecteurs},{data:fournisseurs},{data:tarifs},{data:entreprise}]=await Promise.all([
  sb.from("connecteurs_externes").select("id,domaine,nom,type,statut,fournisseur_code,compte_client_reference,capacites,activation_demandee_at,derniere_synchro_at,prochaine_synchro_at,dernier_message,configuration,fournisseur:fournisseurs(nom)").eq("entreprise_id",ctx.entrepriseId).order("created_at",{ascending:false}),
  sb.from("fournisseurs").select("id,nom").eq("entreprise_id",ctx.entrepriseId).eq("actif",true).order("nom"),
  sb.from("tarifs_fournisseurs").select("id,reference_fournisseur,designation,unite,prix_public_ht,prix_negocie_ht,devise,disponibilite,updated_at,fournisseur:fournisseurs(nom)").eq("entreprise_id",ctx.entrepriseId).order("updated_at",{ascending:false}).limit(100),
  sb.from("entreprises").select("stripe_account_id,stripe_onboarding_complete").eq("id",ctx.entrepriseId).single(),
 ]);const un=<T,>(v:T|T[]|null):T|null=>Array.isArray(v)?v[0]??null:v;
 return <main className="p-4 sm:p-8"><div className="mx-auto max-w-7xl space-y-6"><header><h1 className="text-xl font-semibold">Connecteurs et tarifs négociés</h1><p className="text-sm text-neutral-500">Comptes fournisseurs, comptabilité, paiements et SMS.</p></header>{message.error&&<p className="rounded bg-red-50 p-3 text-sm text-red-700">{message.error}</p>}{message.success&&<p className="rounded bg-green-50 p-3 text-sm text-green-700">{message.success}</p>}
 <aside className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900 dark:border-blue-900 dark:bg-blue-950/30 dark:text-blue-200"><strong>Sécurité des connexions</strong><p className="mt-1">Liria Gestion Pro n’enregistre jamais le mot de passe d’un compte fournisseur. Une synchronisation devient active uniquement avec un accès officiel API, EDI, PunchOut ou OAuth remis par le partenaire. En attendant, utilisez son portail ou importez le catalogue officiel CSV/Excel.</p></aside>
 <section className="space-y-3"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-semibold">Comptes fournisseurs</h2><p className="text-xs text-neutral-500">Référencez votre numéro client, choisissez le mode demandé puis faites activer l’échange par le fournisseur.</p></div><a href="/parametres/import" className="rounded-md border px-3 py-2 text-sm font-medium hover:bg-neutral-50 dark:hover:bg-neutral-900">Importer un tarif négocié</a></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{CONNECTEURS_FOURNISSEURS_CONNUS.map(preset=>{const connexion=(connecteurs??[]).find(c=>c.fournisseur_code===preset.code);return <article key={preset.code} className="flex flex-col rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{preset.nom}</h3><p className="mt-1 text-xs text-neutral-500">{preset.description}</p></div><span className={`shrink-0 rounded-full px-2 py-1 text-[10px] ${connexion?.statut==="actif"?"bg-green-100 text-green-700":connexion?"bg-amber-100 text-amber-800":"bg-neutral-100 text-neutral-600"}`}>{connexion?.statut==="actif"?"Actif":connexion?"À finaliser":"Non relié"}</span></div><div className="mt-3 flex flex-wrap gap-1">{preset.capacites.map(capacite=><span key={capacite} className="rounded bg-neutral-100 px-2 py-1 text-[10px] dark:bg-neutral-800">{capacite.replaceAll("_"," ")}</span>)}</div>{connexion?.compte_client_reference&&<p className="mt-3 text-xs"><span className="text-neutral-500">Compte client :</span> {connexion.compte_client_reference}</p>}<form action={preparerConnecteurFournisseurAction.bind(null,preset.code)} className="mt-auto grid gap-2 pt-4"><input name="compte_client_reference" defaultValue={connexion?.compte_client_reference??""} placeholder="N° client (jamais le mot de passe)" className={champ}/><select name="type" defaultValue={connexion?.type??preset.modes[0]} className={champ}>{preset.modes.map(mode=><option key={mode} value={mode}>{LIBELLES_MODES_CONNECTEUR[mode]}</option>)}</select><button className="rounded bg-neutral-900 px-3 py-2 text-sm font-medium text-white dark:bg-white dark:text-neutral-900">{connexion?"Mettre à jour":"Préparer la connexion"}</button></form><a href={preset.portailUrl} target="_blank" rel="noreferrer" className="mt-2 text-center text-xs text-blue-700 hover:underline">Ouvrir le service officiel ↗</a></article>})}</div></section>
 <section className="rounded-xl border-2 border-[#c9a24a]/50 bg-[#c9a24a]/5 p-4"><div><h2 className="font-semibold">Ajouter n’importe quel fournisseur</h2><p className="mt-1 text-sm text-neutral-600">Si l’entreprise possède un compte professionnel chez ce fournisseur, elle peut le référencer ici, même s’il n’apparaît pas dans la liste ci-dessus.</p></div><form action={preparerConnecteurFournisseurLibreAction} className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-5"><label className="text-xs">Fournisseur existant<select name="fournisseur_id" className={champ}><option value="">Créer depuis le nom saisi</option>{(fournisseurs??[]).map(f=><option key={f.id} value={f.id}>{f.nom}</option>)}</select></label><label className="text-xs">Nom si nouveau<input name="nom_fournisseur" placeholder="Ex. Point.P, Gedimat…" className={champ}/></label><label className="text-xs">N° de compte client<input name="compte_client_reference" placeholder="Jamais le mot de passe" className={champ}/></label><label className="text-xs">Portail professionnel<input name="portail_url" type="url" placeholder="https://…" className={champ}/></label><label className="text-xs">Mode d’échange<select required name="type" defaultValue="portail" className={champ}><option value="portail">Portail professionnel</option><option value="csv">CSV</option><option value="xlsx">Excel</option><option value="fabdis">FAB-DIS</option><option value="api">API</option><option value="edi">EDI</option><option value="punchout_oci">PunchOut OCI</option><option value="punchout_cxml">PunchOut cXML</option><option value="oauth2">OAuth 2</option></select></label><button className="rounded bg-[#0d1b2a] px-4 py-2 text-sm font-semibold text-white md:col-span-2 xl:col-span-5">Ajouter ce compte fournisseur</button></form><p className="mt-3 text-xs text-neutral-500">Le compte client peut être enregistré. Les mots de passe ne sont jamais demandés ni conservés. Une synchronisation automatique exige toujours une interface officielle fournie par le fournisseur.</p></section>
 <section className="flex flex-wrap items-center justify-between gap-4 rounded-xl border p-4"><div><h2 className="font-semibold">Paiements Stripe Connect</h2><p className="text-sm text-neutral-500">Les règlements clients arrivent directement sur le compte Stripe de l’entreprise, jamais sur le compte de la plateforme.</p></div><div className="flex flex-wrap gap-2">{stripeEstConfigure()?<form action={connecterStripeAction}><button className="rounded bg-[#635bff] px-4 py-2 text-sm font-semibold text-white">{entreprise?.stripe_account_id?"Continuer la configuration Stripe":"Connecter mon compte Stripe"}</button></form>:<span className="rounded bg-amber-50 px-3 py-2 text-xs text-amber-800">Clés plateforme Stripe à configurer</span>}{entreprise?.stripe_account_id&&process.env.STRIPE_SECRET_KEY?.startsWith("sk_test_")&&<form action={completerStripeTestAction}><button className="rounded border border-[#635bff] px-4 py-2 text-sm font-semibold text-[#635bff]">Appliquer le justificatif Stripe de test</button></form>}</div></section>
 <div className="grid gap-4 lg:grid-cols-[minmax(0,420px)_1fr]"><form action={creerConnecteurAction} className="grid h-fit gap-3 rounded-xl border p-4 sm:grid-cols-2 lg:grid-cols-1"><h2 className="font-semibold">Autre service externe</h2><label className="text-xs">Domaine<select required name="domaine" className={champ}><option value="comptabilite">Comptabilité</option><option value="paiement">Paiement en ligne</option><option value="sms">SMS</option></select></label><label className="text-xs">Nom<input required name="nom" placeholder="Nom du service" className={champ}/></label><label className="text-xs">Mode d’échange<select required name="type" className={champ}><option value="api">API</option><option value="csv">CSV</option><option value="xlsx">Excel</option><option value="oauth2">OAuth 2</option></select></label><p className="rounded bg-neutral-50 p-3 text-xs text-neutral-600 dark:bg-neutral-900 dark:text-neutral-300">Les clés et secrets seront ajoutés uniquement dans le coffre sécurisé du serveur lors de l’activation technique.</p><button className="rounded bg-blue-700 px-4 py-2 text-sm font-semibold text-white">Préparer</button></form>
 <section><h2 className="mb-3 font-semibold">Connexions</h2><div className="grid gap-3 sm:grid-cols-2">{(connecteurs??[]).map(c=>{const portail=portailDepuisConfiguration(c.configuration);return <article key={c.id} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><div><strong>{c.nom}</strong><p className="text-xs text-neutral-500">{c.domaine} · {c.type}{un(c.fournisseur)?` · ${un(c.fournisseur)?.nom}`:""}</p></div><span className={`h-fit rounded-full px-2 py-1 text-xs ${c.statut==="actif"?"bg-green-100 text-green-700":c.statut==="erreur"?"bg-red-100 text-red-700":"bg-amber-100 text-amber-800"}`}>{c.statut}</span></div><p className="mt-3 text-xs text-neutral-500">Dernière synchro : {c.derniere_synchro_at?new Date(c.derniere_synchro_at).toLocaleString("fr-FR"):"jamais"}</p>{c.dernier_message&&<p className="mt-2 rounded bg-neutral-50 p-2 text-xs dark:bg-neutral-900">{c.dernier_message}</p>}{portail&&<a href={portail} target="_blank" rel="noreferrer" className="mt-3 inline-block text-xs font-medium text-blue-700 hover:underline">Ouvrir le portail professionnel ↗</a>}</article>})}{!connecteurs?.length&&<p className="rounded-xl border border-dashed p-8 text-center text-sm text-neutral-500 sm:col-span-2">Aucun connecteur préparé.</p>}</div></section></div>
 <section><div className="mb-3 flex items-end justify-between gap-3"><div><h2 className="font-semibold">Catalogue de tarifs négociés</h2><p className="text-xs text-neutral-500">Importé ou synchronisé depuis les comptes fournisseurs officiels.</p></div><span className="text-xs text-neutral-500">{tarifs?.length??0} référence(s) affichée(s)</span></div><div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[820px] text-sm"><thead className="bg-neutral-50 text-left text-xs uppercase text-neutral-500 dark:bg-neutral-900"><tr><th className="p-3">Fournisseur</th><th>Référence</th><th>Désignation</th><th>Disponibilité</th><th className="text-right">Public HT</th><th className="pr-3 text-right">Négocié HT</th></tr></thead><tbody>{(tarifs??[]).map(t=><tr key={t.id} className="border-t"><td className="p-3">{un(t.fournisseur)?.nom}</td><td className="font-mono text-xs">{t.reference_fournisseur}</td><td>{t.designation}<span className="ml-1 text-xs text-neutral-500">/{t.unite}</span></td><td>{t.disponibilite||"—"}</td><td className="text-right text-neutral-500">{t.prix_public_ht==null?"—":euros(t.prix_public_ht)}</td><td className="pr-3 text-right font-mono font-semibold">{euros(t.prix_negocie_ht)}</td></tr>)}</tbody></table></div></section>
 </div></main>;
}
