import { getContexteEntreprise } from "@/lib/entreprise";
import { createClient } from "@/lib/supabase/server";
import { creerConnecteurAction } from "@/app/actions/suite-metier";
import { euros } from "@/lib/devis";
import { connecterStripeAction } from "@/app/actions/paiements-en-ligne";
import { stripeEstConfigure } from "@/lib/stripe";

const champ="mt-1 w-full rounded-md border border-neutral-300 bg-white px-3 py-2 text-sm dark:border-neutral-700 dark:bg-neutral-900";
export default async function ConnecteursPage({searchParams}:{searchParams:Promise<{error?:string;success?:string}>}){
 const message=await searchParams,ctx=await getContexteEntreprise(),sb=await createClient();const [{data:connecteurs},{data:fournisseurs},{data:tarifs},{data:entreprise}]=await Promise.all([
  sb.from("connecteurs_externes").select("id,domaine,nom,type,statut,derniere_synchro_at,prochaine_synchro_at,dernier_message,fournisseur:fournisseurs(nom)").eq("entreprise_id",ctx.entrepriseId).order("created_at",{ascending:false}),
  sb.from("fournisseurs").select("id,nom").eq("entreprise_id",ctx.entrepriseId).eq("actif",true).order("nom"),
  sb.from("tarifs_fournisseurs").select("id,reference_fournisseur,designation,unite,prix_public_ht,prix_negocie_ht,devise,disponibilite,updated_at,fournisseur:fournisseurs(nom)").eq("entreprise_id",ctx.entrepriseId).order("updated_at",{ascending:false}).limit(100),
  sb.from("entreprises").select("stripe_account_id,stripe_onboarding_complete").eq("id",ctx.entrepriseId).single(),
 ]);const un=<T,>(v:T|T[]|null):T|null=>Array.isArray(v)?v[0]??null:v;
 return <main className="p-4 sm:p-8"><div className="mx-auto max-w-7xl space-y-6"><header><h1 className="text-xl font-semibold">Connecteurs et tarifs négociés</h1><p className="text-sm text-neutral-500">Préparation des échanges fournisseurs, comptabilité, paiements, SMS et Batichiffrage.</p></header>{message.error&&<p className="rounded bg-red-50 p-3 text-sm text-red-700">{message.error}</p>}{message.success&&<p className="rounded bg-green-50 p-3 text-sm text-green-700">{message.success}</p>}
 <aside className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900 dark:border-blue-900 dark:bg-blue-950/30 dark:text-blue-200"><strong>Sécurité des connexions</strong><p className="mt-1">Les mots de passe fournisseurs ne sont jamais enregistrés ici. Une connexion devient active uniquement après ajout d’un accès officiel API, EDI, PunchOut ou OAuth fourni par le partenaire. Batichiffrage nécessite une licence valide.</p></aside>
 <section className="flex flex-wrap items-center justify-between gap-4 rounded-xl border p-4"><div><h2 className="font-semibold">Paiements Stripe Connect</h2><p className="text-sm text-neutral-500">Les règlements clients arrivent directement sur le compte Stripe de l’entreprise, jamais sur le compte de la plateforme.</p></div>{stripeEstConfigure()?<form action={connecterStripeAction}><button className="rounded bg-[#635bff] px-4 py-2 text-sm font-semibold text-white">{entreprise?.stripe_account_id?"Continuer la configuration Stripe":"Connecter mon compte Stripe"}</button></form>:<span className="rounded bg-amber-50 px-3 py-2 text-xs text-amber-800">Clés plateforme Stripe à configurer</span>}</section>
 <div className="grid gap-4 lg:grid-cols-[minmax(0,420px)_1fr]"><form action={creerConnecteurAction} className="grid h-fit gap-3 rounded-xl border p-4 sm:grid-cols-2 lg:grid-cols-1"><h2 className="font-semibold">Préparer un connecteur</h2><label className="text-xs">Domaine<select required name="domaine" className={champ}><option value="fournisseur">Fournisseur</option><option value="comptabilite">Comptabilité</option><option value="paiement">Paiement en ligne</option><option value="sms">SMS</option><option value="batichiffrage">Batichiffrage</option></select></label><label className="text-xs">Nom<input required name="nom" placeholder="Legallais · API tarifs" className={champ}/></label><label className="text-xs">Fournisseur associé<select name="fournisseur_id" className={champ}><option value="">Aucun</option>{(fournisseurs??[]).map(f=><option key={f.id} value={f.id}>{f.nom}</option>)}</select></label><label className="text-xs">Mode d’échange<select required name="type" className={champ}><option value="csv">CSV</option><option value="xlsx">Excel</option><option value="fabdis">FAB-DIS</option><option value="api">API</option><option value="edi">EDI</option><option value="punchout_oci">PunchOut OCI</option><option value="punchout_cxml">PunchOut cXML</option><option value="oauth2">OAuth 2</option></select></label><label className="text-xs">Référence du secret sécurisé<input name="secret_reference" placeholder="secret://fournisseur/legallais" className={champ}/><span className="mt-1 block text-[11px] text-neutral-500">Seulement une référence, jamais la clé elle-même.</span></label><button className="rounded bg-blue-700 px-4 py-2 text-sm font-semibold text-white">Préparer</button></form>
 <section><h2 className="mb-3 font-semibold">Connexions</h2><div className="grid gap-3 sm:grid-cols-2">{(connecteurs??[]).map(c=><article key={c.id} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><div><strong>{c.nom}</strong><p className="text-xs text-neutral-500">{c.domaine} · {c.type}{un(c.fournisseur)?` · ${un(c.fournisseur)?.nom}`:""}</p></div><span className={`h-fit rounded-full px-2 py-1 text-xs ${c.statut==="actif"?"bg-green-100 text-green-700":c.statut==="erreur"?"bg-red-100 text-red-700":"bg-amber-100 text-amber-800"}`}>{c.statut}</span></div><p className="mt-3 text-xs text-neutral-500">Dernière synchro : {c.derniere_synchro_at?new Date(c.derniere_synchro_at).toLocaleString("fr-FR"):"jamais"}</p>{c.dernier_message&&<p className="mt-2 rounded bg-neutral-50 p-2 text-xs dark:bg-neutral-900">{c.dernier_message}</p>}</article>)}{!connecteurs?.length&&<p className="rounded-xl border border-dashed p-8 text-center text-sm text-neutral-500 sm:col-span-2">Aucun connecteur préparé.</p>}</div></section></div>
 <section><div className="mb-3 flex items-end justify-between gap-3"><div><h2 className="font-semibold">Catalogue de tarifs négociés</h2><p className="text-xs text-neutral-500">Importé ou synchronisé depuis les comptes fournisseurs officiels.</p></div><span className="text-xs text-neutral-500">{tarifs?.length??0} référence(s) affichée(s)</span></div><div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[820px] text-sm"><thead className="bg-neutral-50 text-left text-xs uppercase text-neutral-500 dark:bg-neutral-900"><tr><th className="p-3">Fournisseur</th><th>Référence</th><th>Désignation</th><th>Disponibilité</th><th className="text-right">Public HT</th><th className="pr-3 text-right">Négocié HT</th></tr></thead><tbody>{(tarifs??[]).map(t=><tr key={t.id} className="border-t"><td className="p-3">{un(t.fournisseur)?.nom}</td><td className="font-mono text-xs">{t.reference_fournisseur}</td><td>{t.designation}<span className="ml-1 text-xs text-neutral-500">/{t.unite}</span></td><td>{t.disponibilite||"—"}</td><td className="text-right text-neutral-500">{t.prix_public_ht==null?"—":euros(t.prix_public_ht)}</td><td className="pr-3 text-right font-mono font-semibold">{euros(t.prix_negocie_ht)}</td></tr>)}</tbody></table></div></section>
 </div></main>;
}
