import Link from "next/link";
import { getContexteEntreprise } from "@/lib/entreprise";
import { createClient } from "@/lib/supabase/server";
import { creerAppelAction, marquerRelanceEnvoyeeAction } from "@/app/actions/suite-metier";
import { euros } from "@/lib/devis";
import { RelanceForm } from "@/components/RelanceForm";

const champ="mt-1 w-full rounded-md border border-neutral-300 bg-white px-3 py-2 text-sm dark:border-neutral-700 dark:bg-neutral-900";
const un=<T,>(v:T|T[]|null):T|null=>Array.isArray(v)?v[0]??null:v;
const nomClient=(c:{nom?:string|null;prenom?:string|null;societe?:string|null}|null)=>c?.societe||[c?.prenom,c?.nom].filter(Boolean).join(" ")||"Client";

export default async function CrmPage({searchParams}:{searchParams:Promise<{error?:string;success?:string}>}){
 const message=await searchParams,ctx=await getContexteEntreprise(),sb=await createClient();const aujourdHui=new Date().toISOString().slice(0,10);
 const [{data:clients},{data:factures},{data:activites},{data:relances}]=await Promise.all([
  sb.from("clients").select("id,nom,prenom,societe,email").eq("entreprise_id",ctx.entrepriseId).neq("statut","inactif").order("societe"),
  sb.from("factures").select("id,numero,montant_ttc,montant_paye,date_echeance,client:clients(nom,prenom,societe,email),chantier:chantiers(nom,reference_interne)").eq("entreprise_id",ctx.entrepriseId).in("statut",["envoyee","payee_partiel","en_retard"]).order("date_echeance"),
  sb.from("appels_contacts").select("id,type,sens,objet,compte_rendu,a_rappeler_at,termine,created_at,client:clients(nom,prenom,societe)").eq("entreprise_id",ctx.entrepriseId).order("created_at",{ascending:false}).limit(100),
  sb.from("relances_impayes").select("id,niveau,canal,statut,date_prevue,date_envoi,sujet,facture:factures(id,numero,client:clients(nom,prenom,societe))").eq("entreprise_id",ctx.entrepriseId).order("date_prevue",{ascending:false}).limit(100),
 ]);
 const impayes=(factures??[]).filter(f=>Number(f.montant_ttc)>Number(f.montant_paye));const total=impayes.reduce((s,f)=>s+Number(f.montant_ttc)-Number(f.montant_paye),0);
 return <main className="p-4 sm:p-8"><div className="mx-auto max-w-7xl space-y-6"><header><h1 className="text-xl font-semibold">CRM et relances</h1><p className="text-sm text-neutral-500">Historique des appels, rendez-vous, rappels et relances d’impayés.</p></header>{message.error&&<p className="rounded bg-red-50 p-3 text-sm text-red-700">{message.error}</p>}{message.success&&<p className="rounded bg-green-50 p-3 text-sm text-green-700">{message.success}</p>}
 <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl border p-4"><span className="text-xs text-neutral-500">Factures à relancer</span><strong className="mt-1 block text-2xl">{impayes.length}</strong></div><div className="rounded-xl border p-4"><span className="text-xs text-neutral-500">Reste à encaisser</span><strong className="mt-1 block text-2xl">{euros(total)}</strong></div><div className="rounded-xl border p-4"><span className="text-xs text-neutral-500">Rappels ouverts</span><strong className="mt-1 block text-2xl">{(activites??[]).filter(a=>!a.termine&&a.a_rappeler_at).length}</strong></div></div>
 <div className="grid gap-4 lg:grid-cols-2"><form action={creerAppelAction} className="grid gap-3 rounded-xl border p-4 sm:grid-cols-2"><h2 className="font-semibold sm:col-span-2">Journaliser une communication</h2><label className="text-xs">Client<select name="client_id" className={champ}><option value="">Contact général</option>{(clients??[]).map(c=><option key={c.id} value={c.id}>{nomClient(c)}</option>)}</select></label><label className="text-xs">Canal<select name="type" className={champ}><option value="appel">Appel</option><option value="email">E-mail</option><option value="sms">SMS</option><option value="courrier">Courrier</option><option value="rendez_vous">Rendez-vous</option></select></label><label className="text-xs">Sens<select name="sens" className={champ}><option value="sortant">Sortant</option><option value="entrant">Entrant</option></select></label><label className="text-xs">Rappel prévu<input type="datetime-local" name="a_rappeler_at" className={champ}/></label><label className="text-xs sm:col-span-2">Objet<input required name="objet" className={champ}/></label><label className="text-xs sm:col-span-2">Compte rendu<textarea name="compte_rendu" rows={3} className={champ}/></label><button className="rounded bg-blue-700 px-4 py-2 text-sm font-semibold text-white sm:col-span-2">Enregistrer</button></form>
 <RelanceForm aujourdHui={aujourdHui} factures={impayes.map((f)=>{const client=un(f.client),chantier=un(f.chantier);return {id:f.id,numero:f.numero,client:nomClient(client),chantier:chantier?.nom??null,reste:Number(f.montant_ttc)-Number(f.montant_paye),email:client?.email??null,dateEcheance:f.date_echeance};})}/></div>
 <div className="grid gap-4 xl:grid-cols-2"><section><h2 className="mb-3 font-semibold">Dernières communications</h2><div className="space-y-2">{(activites??[]).map(a=><article key={a.id} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><strong>{a.objet}</strong><span className="text-xs text-neutral-500">{a.type} · {a.sens}</span></div><p className="text-sm text-neutral-500">{nomClient(un(a.client))} · {new Date(a.created_at).toLocaleString("fr-FR")}</p>{a.compte_rendu&&<p className="mt-2 text-sm">{a.compte_rendu}</p>}{a.a_rappeler_at&&<p className="mt-2 text-xs font-medium text-amber-700">Rappel : {new Date(a.a_rappeler_at).toLocaleString("fr-FR")}</p>}</article>)}{!activites?.length&&<p className="rounded-xl border border-dashed p-6 text-center text-sm text-neutral-500">Aucune communication.</p>}</div></section>
 <section><h2 className="mb-3 font-semibold">Historique des relances</h2><div className="space-y-2">{(relances??[]).map(r=>{const f=un(r.facture),c=f?un(f.client):null;return <article key={r.id} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><div><strong>Niveau {r.niveau} · {f?.numero}</strong><p className="text-sm text-neutral-500">{nomClient(c)} · prévue le {r.date_prevue}</p></div><span className="h-fit rounded-full bg-neutral-100 px-2 py-1 text-xs">{r.statut.replaceAll("_"," ")}</span></div><div className="mt-2 flex flex-wrap items-center justify-between gap-2 text-xs"><span>{r.canal} · {r.sujet||"Sans objet"}</span><div className="flex items-center gap-2">{["a_envoyer","preparee"].includes(r.statut)&&<form action={marquerRelanceEnvoyeeAction.bind(null,r.id)}><button className="text-green-700 hover:underline">Marquer envoyée</button></form>}{f?.id&&<Link href={`/factures/${f.id}`} className="text-blue-700 hover:underline">Ouvrir la facture</Link>}</div></div></article>})}{!relances?.length&&<p className="rounded-xl border border-dashed p-6 text-center text-sm text-neutral-500">Aucune relance.</p>}</div></section></div>
 </div></main>;
}
