import Link from "next/link";
import { notFound } from "next/navigation";
import { enregistrerProfilPaieAction } from "@/app/actions/paie";
import { getContexteEntreprise } from "@/lib/entreprise";
import { permissionsUtilisateur } from "@/lib/permissions";
import { createClient } from "@/lib/supabase/server";

const champ="mt-1 w-full rounded border px-3 py-2 text-sm dark:bg-neutral-900";
const Field=({label,name,value,type="text"}:{label:string;name:string;value:string|number|null|undefined;type?:string})=><label className="text-xs text-neutral-500">{label}<input name={name} type={type} defaultValue={value??""} className={champ}/></label>;

export default async function ProfilPaieEmployePage({params,searchParams}:{params:Promise<{employeId:string}>;searchParams:Promise<{error?:string;success?:string}>}){
 const [{employeId},sp,ctx]=await Promise.all([params,searchParams,getContexteEntreprise()]);const supabase=await createClient();const permissions=await permissionsUtilisateur(ctx);const peutModifier=permissions===null||permissions.includes("gerer_paie");
 // Fiche permanente sensible (SS, adresse, situation medicale...) : consultation reservee
 // aux managers RH/paie, jamais accessible via un simple droit d'auto-consultation
 // (consulter_sa_paie), qui ne fait que passer la porte large du prefixe /paie.
 const peutVoir=permissions===null||permissions.includes("gerer_paie")||permissions.includes("gerer_employes")||permissions.includes("voir_paie_confidentielle");if(!peutVoir)notFound();
 const [{data:e},{data:p},{data:pieces}]=await Promise.all([supabase.from("employes").select("id,prenom,nom,poste,type_contrat").eq("id",employeId).eq("entreprise_id",ctx.entrepriseId).maybeSingle(),supabase.from("profils_paie_employes").select("*").eq("employe_id",employeId).eq("entreprise_id",ctx.entrepriseId).maybeSingle(),supabase.from("pieces_jointes_paie").select("id,type_document,nom_original,created_at").eq("employe_id",employeId).is("dossier_id",null).order("created_at",{ascending:false})]);if(!e)notFound();
 return <main className="p-4 sm:p-8"><div className="mx-auto max-w-5xl space-y-6"><header><Link href={`/employes/${employeId}`} className="text-sm text-neutral-500 hover:underline">← Fiche employé</Link><h1 className="mt-2 text-2xl font-semibold">Profil de paie · {e.prenom} {e.nom}</h1><p className="text-sm text-neutral-500">Informations permanentes sensibles, séparées des variables mensuelles.</p></header>{sp.error&&<p className="rounded bg-red-50 p-3 text-sm text-red-700">{sp.error}</p>}{sp.success&&<p className="rounded bg-green-50 p-3 text-sm text-green-700">{sp.success}</p>}
 <form action={enregistrerProfilPaieAction.bind(null,employeId)} className="grid gap-4 rounded-lg border p-4 sm:grid-cols-2 lg:grid-cols-3"><h2 className="font-semibold sm:col-span-2 lg:col-span-3">Identité et contrat</h2><label className="text-xs text-neutral-500 sm:col-span-2">Adresse<input name="adresse" defaultValue={p?.adresse??""} className={champ}/></label><Field label="Date de naissance" name="date_naissance" type="date" value={p?.date_naissance}/><Field label="Lieu de naissance" name="lieu_naissance" value={p?.lieu_naissance}/><Field label="N° Sécurité sociale" name="numero_securite_sociale" value={p?.numero_securite_sociale}/><Field label="Contact d’urgence" name="contact_urgence_nom" value={p?.contact_urgence_nom}/><Field label="Téléphone urgence" name="contact_urgence_telephone" value={p?.contact_urgence_telephone}/><Field label="Type de contrat" name="type_contrat" value={p?.type_contrat??e.type_contrat}/><Field label="Fin prévue CDD / mission" name="date_fin_prevue" type="date" value={p?.date_fin_prevue}/><Field label="Fin période d’essai" name="fin_periode_essai" type="date" value={p?.fin_periode_essai}/>
 <h2 className="font-semibold sm:col-span-2 lg:col-span-3">Classification BTP et rémunération</h2><Field label="Qualification" name="qualification" value={p?.qualification}/><Field label="Classification" name="classification" value={p?.classification}/><Field label="Coefficient" name="coefficient" value={p?.coefficient}/><label className="text-xs text-neutral-500">Catégorie<select name="categorie_statut" defaultValue={p?.categorie_statut??"ouvrier"} className={champ}><option value="ouvrier">Ouvrier</option><option value="etam">ETAM</option><option value="cadre">Cadre</option><option value="apprenti">Apprenti</option></select></label><Field label="Salaire horaire brut" name="salaire_horaire_brut" type="number" value={p?.salaire_horaire_brut}/><Field label="Salaire mensuel brut" name="salaire_mensuel_brut" type="number" value={p?.salaire_mensuel_brut}/><Field label="Durée hebdomadaire" name="duree_hebdomadaire" type="number" value={p?.duree_hebdomadaire}/><Field label="Durée mensuelle" name="duree_mensuelle" type="number" value={p?.duree_mensuelle}/><label className="text-xs text-neutral-500">Organisation<select name="temps_travail" defaultValue={p?.temps_travail??"temps_plein"} className={champ}><option value="temps_plein">Temps plein</option><option value="temps_partiel">Temps partiel</option><option value="forfait_jours">Forfait jours</option></select></label><Field label="Forfait jours" name="forfait_jours" type="number" value={p?.forfait_jours}/><Field label="Convention collective" name="convention_collective" value={p?.convention_collective}/><Field label="Établissement" name="etablissement" value={p?.etablissement}/>
 <h2 className="font-semibold sm:col-span-2 lg:col-span-3">Protection sociale et situations particulières</h2><Field label="Mutuelle" name="mutuelle" value={p?.mutuelle}/><Field label="Prévoyance" name="prevoyance" value={p?.prevoyance}/><label className="flex items-end gap-2 pb-2 text-sm"><input name="dispense_mutuelle" type="checkbox" defaultChecked={p?.dispense_mutuelle}/> Dispense mutuelle</label><Field label="Bénéficiaires" name="beneficiaires" value={p?.beneficiaires}/><Field label="Avantages en nature" name="avantages_nature" value={p?.avantages_nature}/><div className="flex flex-wrap items-center gap-4 text-sm"><label><input name="vehicule_fonction" type="checkbox" defaultChecked={p?.vehicule_fonction}/> Véhicule</label><label><input name="logement" type="checkbox" defaultChecked={p?.logement}/> Logement</label><label><input name="telephone" type="checkbox" defaultChecked={p?.telephone}/> Téléphone</label></div><Field label="Saisie sur salaire" name="saisie_salaire" type="number" value={p?.saisie_salaire}/><Field label="Pension alimentaire" name="pension_alimentaire" type="number" value={p?.pension_alimentaire}/><Field label="Acompte permanent" name="acompte_permanent" type="number" value={p?.acompte_permanent}/><Field label="Titre de séjour" name="titre_sejour" value={p?.titre_sejour}/><Field label="Expiration titre" name="titre_sejour_expiration" type="date" value={p?.titre_sejour_expiration}/><Field label="Autorisation de travail" name="autorisation_travail" value={p?.autorisation_travail}/><label className="text-xs text-neutral-500 sm:col-span-2 lg:col-span-3">Remarques confidentielles<textarea name="remarques_confidentielles" rows={3} defaultValue={p?.remarques_confidentielles??""} className={champ}/></label><button disabled={!peutModifier} className="rounded bg-[#0d1b2a] px-4 py-2 text-sm font-semibold text-white disabled:opacity-40 sm:col-span-2 lg:col-span-3">Enregistrer le profil permanent</button></form>
 <section className="space-y-4 rounded-lg border p-4"><div><h2 className="font-semibold">Documents permanents</h2><p className="text-sm text-neutral-500">Contrat, avenants, RIB, titre de séjour et attestations sont conservés dans un stockage privé.</p></div>{peutModifier&&<form action="/api/paie/documents/upload" method="post" encType="multipart/form-data" className="grid gap-3 sm:grid-cols-[220px_1fr_auto]"><input type="hidden" name="employe_id" value={employeId}/><input type="hidden" name="retour" value={`/paie/profils/${employeId}`}/><select name="type_document" className={champ}><option value="contrat">Contrat de travail</option><option value="avenant">Avenant</option><option value="rib">RIB</option><option value="titre_sejour">Titre de séjour</option><option value="autorisation_travail">Autorisation de travail</option><option value="attestation">Attestation</option><option value="autre">Autre</option></select><input required type="file" name="fichier" accept="application/pdf,image/jpeg,image/png,image/webp,image/heic,image/heif" className={champ}/><button className="self-end rounded bg-[#0d1b2a] px-4 py-2 text-sm font-semibold text-white">Importer</button></form>}<div className="grid gap-2">{(pieces??[]).map(piece=><a key={piece.id} href={`/api/paie/documents/${piece.id}`} className="flex items-center justify-between rounded border p-3 text-sm hover:bg-neutral-50 dark:hover:bg-neutral-900"><span><strong>{piece.nom_original}</strong><span className="ml-2 text-xs text-neutral-500">{piece.type_document}</span></span><span>Télécharger</span></a>)}{!pieces?.length&&<p className="text-sm text-neutral-500">Aucun document permanent.</p>}</div></section>
 </div></main>;
}
