import Link from "next/link";
import { notFound } from "next/navigation";
import { ajouterAbsencePaieAction, ajouterDeductionPaieAction, ajouterIndemnitePaieAction, ajouterPrimePaieAction, ajouterRegularisationPaieAction, ajouterTempsPaieAction, enregistrerDossierPaieAction, supprimerVariablePaieAction } from "@/app/actions/paie";
import { euros } from "@/lib/devis";
import { getContexteEntreprise } from "@/lib/entreprise";
import { CATEGORIES_TEMPS_PAIE, estPeriodePaieModifiable, STATUTS_DOSSIER_PAIE, TYPES_ABSENCE_PAIE, TYPES_INDEMNITE_PAIE, TYPES_PRIME_PAIE } from "@/lib/paie";
import { permissionsUtilisateur } from "@/lib/permissions";
import { createClient } from "@/lib/supabase/server";

const champ="mt-1 w-full rounded border px-3 py-2 text-sm dark:bg-neutral-900";
const option=(items:readonly (readonly [string,string])[])=><>{items.map(([v,l])=><option key={v} value={v}>{l}</option>)}</>;
export default async function DossierPaiePage({params,searchParams}:{params:Promise<{id:string;dossierId:string}>;searchParams:Promise<{error?:string;success?:string}>}){
 const [{id,dossierId},sp,ctx]=await Promise.all([params,searchParams,getContexteEntreprise()]);const supabase=await createClient();const permissions=await permissionsUtilisateur(ctx);const peutSaisir=permissions===null||permissions.includes("saisir_variables_paie")||permissions.includes("controler_variables_paie")||permissions.includes("gerer_paie");const confidentiel=permissions===null||permissions.includes("voir_paie_confidentielle");
 const [{data:dossier},{data:temps},{data:absences},{data:primes},{data:indemnites},{data:deductions},{data:regularisations},{data:chantiers},{data:pieces}]=await Promise.all([
  supabase.from("dossiers_paie_salaries").select("*,periode:periodes_paie(id,mois,date_debut,date_fin,statut),employe:employes(id,prenom,nom,poste,type_contrat,date_entree,date_sortie)").eq("id",dossierId).eq("periode_id",id).eq("entreprise_id",ctx.entrepriseId).maybeSingle(),
  supabase.from("temps_travail_paie").select("*,chantier:chantiers(nom)").eq("dossier_id",dossierId).order("date"),supabase.from("absences_paie").select("*").eq("dossier_id",dossierId).order("date_debut"),
  supabase.from("primes_paie").select("*").eq("dossier_id",dossierId).order("created_at"),supabase.from("indemnites_deplacement_paie").select("*,chantier:chantiers(nom)").eq("dossier_id",dossierId).order("date"),
  confidentiel?supabase.from("deductions_paie").select("*").eq("dossier_id",dossierId).order("created_at"):Promise.resolve({data:[],error:null}),supabase.from("regularisations_paie").select("*").eq("dossier_id",dossierId).order("created_at"),
  supabase.from("chantiers").select("id,nom,reference_interne").eq("entreprise_id",ctx.entrepriseId).not("statut","in","(archive,annule)").order("nom"),supabase.from("pieces_jointes_paie").select("id,type_document,nom_original,created_at").eq("dossier_id",dossierId).order("created_at",{ascending:false}),
 ]);if(!dossier)notFound();const periode=Array.isArray(dossier.periode)?dossier.periode[0]:dossier.periode;const employe=Array.isArray(dossier.employe)?dossier.employe[0]:dossier.employe;if(!periode||!employe)notFound();const modifiable=peutSaisir&&estPeriodePaieModifiable(periode.statut);
 const supprimer=(table:string,element:{id:string;source_type?:string})=>(element.source_type===undefined||element.source_type==="saisie_manuelle")&&modifiable?<form action={supprimerVariablePaieAction.bind(null,table,element.id,dossierId)}><button className="text-xs text-red-700">Supprimer</button></form>:<span className="text-xs text-neutral-400">Synchronisé</span>;
 return <main className="p-4 sm:p-8"><div className="mx-auto max-w-6xl space-y-6"><header><Link href={`/paie/${id}`} className="text-sm text-neutral-500 hover:underline">← Période de paie</Link><h1 className="mt-2 text-2xl font-semibold">{employe.prenom} {employe.nom}</h1><p className="text-sm text-neutral-500">{employe.poste??employe.type_contrat??"Salarié"} · {periode.date_debut} → {periode.date_fin}</p></header>{sp.error&&<p className="rounded bg-red-50 p-3 text-sm text-red-700">{sp.error}</p>}{sp.success&&<p className="rounded bg-green-50 p-3 text-sm text-green-700">{sp.success}</p>}
 <section className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6"><div className="rounded border p-3"><span className="text-xs text-neutral-500">Heures normales</span><strong className="block text-xl">{dossier.heures_normales} h</strong></div><div className="rounded border p-3"><span className="text-xs text-neutral-500">Sup. 25 / 50</span><strong className="block">{dossier.heures_sup_25} / {dossier.heures_sup_50} h</strong></div><div className="rounded border p-3"><span className="text-xs text-neutral-500">Absences</span><strong className="block">{dossier.heures_absence} h</strong></div><div className="rounded border p-3"><span className="text-xs text-neutral-500">Primes</span><strong className="block">{euros(dossier.total_primes)}</strong></div><div className="rounded border p-3"><span className="text-xs text-neutral-500">Déplacements</span><strong className="block">{euros(Number(dossier.total_paniers)+Number(dossier.total_trajets)+Number(dossier.total_transports)+Number(dossier.total_grands_deplacements))}</strong></div><div className="rounded border p-3"><span className="text-xs text-neutral-500">Statut</span><strong className="block">{STATUTS_DOSSIER_PAIE[dossier.statut as keyof typeof STATUTS_DOSSIER_PAIE]??dossier.statut}</strong></div></section>
 {peutSaisir&&<form action={enregistrerDossierPaieAction.bind(null,dossierId)} className="grid gap-3 rounded-lg border p-4 sm:grid-cols-[220px_1fr_auto]"><select name="statut" defaultValue={dossier.statut} className={champ}>{Object.entries(STATUTS_DOSSIER_PAIE).filter(([v])=>["saisie_en_cours","a_controler","correction_demandee","valide","refuse"].includes(v)).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input name="commentaire_comptable" defaultValue={dossier.commentaire_comptable??""} placeholder="Commentaire pour le cabinet comptable" className={champ}/><button disabled={!modifiable} className="self-end rounded bg-[#0d1b2a] px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Enregistrer</button></form>}
 <section className="space-y-3"><h2 className="font-semibold">Temps de travail</h2>{modifiable&&<form action={ajouterTempsPaieAction.bind(null,dossierId)} className="grid gap-2 rounded border p-3 sm:grid-cols-3 lg:grid-cols-6"><input name="date" type="date" required min={periode.date_debut} max={periode.date_fin} className={champ}/><select name="categorie" className={champ}>{option(CATEGORIES_TEMPS_PAIE)}</select><input name="quantite_heures" type="number" min="0.01" max="24" step="0.01" required placeholder="Heures" className={champ}/><input name="majoration" type="number" min="0" step="0.01" placeholder="Majoration %" className={champ}/><select name="chantier_id" className={champ}><option value="">Sans chantier</option>{(chantiers??[]).map(c=><option key={c.id} value={c.id}>{c.reference_interne} · {c.nom}</option>)}</select><button className="self-end rounded border px-3 py-2 text-sm">Ajouter</button></form>}<div className="overflow-x-auto rounded border"><table className="w-full min-w-[750px] text-sm"><thead><tr className="text-left text-xs uppercase text-neutral-500"><th className="p-2">Date</th><th className="p-2">Catégorie</th><th className="p-2">Chantier</th><th className="p-2">Heures</th><th className="p-2">Source</th><th className="p-2"></th></tr></thead><tbody>{(temps??[]).map(t=>{const c=Array.isArray(t.chantier)?t.chantier[0]:t.chantier;return <tr key={t.id} className="border-t"><td className="p-2">{t.date??"—"}</td><td className="p-2">{CATEGORIES_TEMPS_PAIE.find(([v])=>v===t.categorie)?.[1]??t.categorie}</td><td className="p-2">{c?.nom??"—"}</td><td className="p-2 font-mono">{t.quantite_heures} h</td><td className="p-2">{t.source_type}</td><td className="p-2">{supprimer("temps_travail_paie",t)}</td></tr>})}</tbody></table></div></section>
 <section className="space-y-3"><h2 className="font-semibold">Absences et congés</h2>{modifiable&&<form action={ajouterAbsencePaieAction.bind(null,dossierId)} className="grid gap-2 rounded border p-3 sm:grid-cols-4 lg:grid-cols-7"><select name="type_absence" className={champ}>{option(TYPES_ABSENCE_PAIE)}</select><input name="date_debut" type="date" required className={champ}/><input name="date_fin" type="date" required className={champ}/><input name="duree_jours" type="number" min="0" step="0.5" placeholder="Jours" className={champ}/><input name="duree_heures" type="number" min="0" step="0.01" placeholder="Heures" className={champ}/><select name="maintien_salaire" className={champ}><option value="a_controler">Maintien à contrôler</option><option value="oui">Maintien oui</option><option value="non">Maintien non</option></select><button className="self-end rounded border px-3 py-2 text-sm">Ajouter</button></form>}<div className="grid gap-2">{(absences??[]).map(a=><article key={a.id} className="flex flex-wrap justify-between gap-2 rounded border p-3 text-sm"><div><strong>{TYPES_ABSENCE_PAIE.find(([v])=>v===a.type_absence)?.[1]??a.type_absence}</strong><p className="text-neutral-500">{a.date_debut} → {a.date_fin} · {a.duree_jours} j / {a.duree_heures} h · maintien {a.maintien_salaire}</p></div>{supprimer("absences_paie",a)}</article>)}</div></section>
 <div className="grid gap-6 lg:grid-cols-2"><section className="space-y-3"><h2 className="font-semibold">Primes</h2>{modifiable&&<form action={ajouterPrimePaieAction.bind(null,dossierId)} className="grid gap-2 rounded border p-3 sm:grid-cols-2"><select name="type_prime" className={champ}>{option(TYPES_PRIME_PAIE)}</select><input name="libelle" required placeholder="Libellé" className={champ}/><input name="montant" required type="number" min="0" step="0.01" placeholder="Montant €" className={champ}/><select name="cotisations" className={champ}><option value="a_determiner">Cotisations à déterminer</option><option value="oui">Soumise</option><option value="non">Non soumise</option></select><label className="flex items-center gap-2 text-sm"><input name="recurrent" type="checkbox"/> Reprendre le mois suivant</label><button className="rounded border px-3 py-2 text-sm">Ajouter</button></form>}<div className="grid gap-2">{(primes??[]).map(p=><article key={p.id} className="flex justify-between rounded border p-3 text-sm"><div><strong>{p.libelle}</strong><p className="text-xs text-neutral-500">{p.type_prime} · cotisations {p.cotisations}{p.recurrent?" · récurrente":""}</p></div><div className="text-right"><strong>{euros(p.montant)}</strong>{supprimer("primes_paie",p)}</div></article>)}</div></section>
 <section className="space-y-3"><h2 className="font-semibold">Indemnités et déplacements</h2>{modifiable&&<form action={ajouterIndemnitePaieAction.bind(null,dossierId)} className="grid gap-2 rounded border p-3 sm:grid-cols-2"><input name="date" type="date" required className={champ}/><select name="type_indemnite" className={champ}>{option(TYPES_INDEMNITE_PAIE)}</select><input name="quantite" type="number" min="0" step="0.01" defaultValue="1" placeholder="Quantité" className={champ}/><input name="tarif_unitaire" type="number" min="0" step="0.01" required placeholder="Tarif unitaire €" className={champ}/><select name="chantier_id" className={champ}><option value="">Sans chantier</option>{(chantiers??[]).map(c=><option key={c.id} value={c.id}>{c.nom}</option>)}</select><select name="traitement" className={champ}><option value="integre_paie">Intégré en paie</option><option value="remboursable">Remboursable</option></select><button className="rounded border px-3 py-2 text-sm sm:col-span-2">Ajouter</button></form>}<div className="grid gap-2">{(indemnites??[]).map(i=>{const c=Array.isArray(i.chantier)?i.chantier[0]:i.chantier;return <article key={i.id} className="flex justify-between rounded border p-3 text-sm"><div><strong>{TYPES_INDEMNITE_PAIE.find(([v])=>v===i.type_indemnite)?.[1]??i.type_indemnite}</strong><p className="text-xs text-neutral-500">{i.date} · {c?.nom??"Sans chantier"} · {i.quantite} × {euros(i.tarif_unitaire)} · {i.source_type}</p></div><div className="text-right"><strong>{euros(i.montant_total)}</strong>{supprimer("indemnites_deplacement_paie",i)}</div></article>})}</div></section></div>
 {confidentiel&&<section className="space-y-3 rounded-lg border border-red-200 p-4"><h2 className="font-semibold">Retenues et éléments confidentiels</h2>{modifiable&&<form action={ajouterDeductionPaieAction.bind(null,dossierId)} className="grid gap-2 sm:grid-cols-5"><select name="type_deduction" className={champ}><option value="acompte">Acompte</option><option value="avance_salaire">Avance sur salaire</option><option value="saisie_salaire">Saisie sur salaire</option><option value="pension_alimentaire">Pension alimentaire</option><option value="avantage_nature">Avantage en nature</option><option value="autre">Autre</option></select><input name="libelle" required placeholder="Libellé" className={champ}/><input name="montant" required type="number" min="0" step="0.01" placeholder="Montant €" className={champ}/><label className="flex items-center gap-2 text-sm"><input name="recurrent" type="checkbox"/> Reprendre le mois suivant</label><button className="self-end rounded border px-3 py-2 text-sm">Ajouter</button></form>}<div className="grid gap-2">{(deductions??[]).map(d=><article key={d.id} className="flex justify-between rounded border p-3 text-sm"><div><strong>{d.libelle}</strong><p className="text-xs text-neutral-500">{d.type_deduction}{d.recurrent?" · récurrente":""}</p></div><div className="text-right"><strong>{euros(d.montant)}</strong>{supprimer("deductions_paie",d)}</div></article>)}</div></section>}
 <section className="space-y-3"><h2 className="font-semibold">Régularisations</h2>{modifiable&&<form action={ajouterRegularisationPaieAction.bind(null,dossierId)} className="grid gap-2 rounded border p-3 sm:grid-cols-5"><input name="type_regularisation" required placeholder="Type" className={champ}/><input name="libelle" required placeholder="Libellé" className={champ}/><input name="montant" required type="number" step="0.01" placeholder="Montant +/- €" className={champ}/><input name="periode_origine" type="date" className={champ}/><button className="self-end rounded border px-3 py-2 text-sm">Ajouter</button></form>}<div className="grid gap-2">{(regularisations??[]).map(r=><article key={r.id} className="flex justify-between rounded border p-3 text-sm"><div><strong>{r.libelle}</strong><p className="text-xs text-neutral-500">Période d’origine {r.periode_origine??"non précisée"}</p></div><div className="text-right"><strong>{euros(r.montant)}</strong>{supprimer("regularisations_paie",r)}</div></article>)}</div></section>
 <section className="space-y-4 rounded-lg border p-4"><div><h2 className="font-semibold">Pièces jointes du mois</h2><p className="text-sm text-neutral-500">Documents privés contrôlés par empreinte SHA-256.</p></div>{modifiable&&<form action="/api/paie/documents/upload" method="post" encType="multipart/form-data" className="grid gap-3 sm:grid-cols-[220px_1fr_auto]"><input type="hidden" name="dossier_id" value={dossierId}/><input type="hidden" name="employe_id" value={employe.id}/><input type="hidden" name="retour" value={`/paie/${id}/${dossierId}`}/><select name="type_document" className={champ}><option value="justificatif_variable">Justificatif de variable</option><option value="arret_travail">Arrêt de travail</option><option value="fiche_paie_source">Document du cabinet</option><option value="autre">Autre</option></select><input required type="file" name="fichier" accept="application/pdf,image/jpeg,image/png,image/webp,image/heic,image/heif" className={champ}/><button className="self-end rounded bg-[#0d1b2a] px-4 py-2 text-sm font-semibold text-white">Importer</button></form>}<div className="grid gap-2">{(pieces??[]).map(piece=><a key={piece.id} href={`/api/paie/documents/${piece.id}`} className="flex items-center justify-between rounded border p-3 text-sm hover:bg-neutral-50 dark:hover:bg-neutral-900"><span><strong>{piece.nom_original}</strong><span className="ml-2 text-xs text-neutral-500">{piece.type_document}</span></span><span>Télécharger</span></a>)}{!pieces?.length&&<p className="text-sm text-neutral-500">Aucune pièce jointe pour ce mois.</p>}</div></section>
 </div></main>;
}
