"use server";
import{redirect}from"next/navigation";import{revalidatePath}from"next/cache";import{createClient}from"@/lib/supabase/server";import{getContexteEntreprise}from"@/lib/entreprise";
const permissions=(f:FormData)=>[...new Set(f.getAll("permissions").map(String).filter(Boolean))];
export async function creerPosteAction(f:FormData){const ctx=await getContexteEntreprise(),sb=await createClient(),nom=String(f.get("nom")??"").trim();if(!nom)redirect(`/parametres/acces?error=${encodeURIComponent("Nom du poste obligatoire")}`);const{error}=await sb.rpc("creer_poste_avec_permissions",{p_entreprise_id:ctx.entrepriseId,p_nom:nom,p_permissions:permissions(f)});if(error)redirect(`/parametres/acces?error=${encodeURIComponent(error.message)}`);revalidatePath("/parametres/acces");redirect("/parametres/acces?success=Poste créé");}
export async function enregistrerPermissionsPosteAction(posteId:string,f:FormData){const ctx=await getContexteEntreprise(),sb=await createClient();const{error}=await sb.rpc("enregistrer_permissions_poste",{p_entreprise_id:ctx.entrepriseId,p_poste_id:posteId,p_permissions:permissions(f)});if(error)redirect(`/parametres/acces?error=${encodeURIComponent(error.message)}`);revalidatePath("/", "layout");revalidatePath("/parametres/acces");redirect("/parametres/acces?success=Autorisations enregistrées");}
export async function modifierPosteMembreAction(utilisateurId:string,f:FormData){const ctx=await getContexteEntreprise(),sb=await createClient(),posteId=String(f.get("poste_id")??""),pointageActif=String(f.get("pointage_personnel_actif")??"false")==="true";const{error}=await sb.rpc("modifier_compte_poste_pointage",{p_entreprise_id:ctx.entrepriseId,p_utilisateur_id:utilisateurId,p_poste_id:posteId,p_pointage_personnel_actif:pointageActif});if(error)redirect(`/parametres/acces?error=${encodeURIComponent(error.message)}`);revalidatePath("/", "layout");revalidatePath("/parametres/acces");redirect("/parametres/acces?success=Compte et pointage mis à jour");}
export async function supprimerPosteAction(posteId:string){const ctx=await getContexteEntreprise(),sb=await createClient();const{error}=await sb.rpc("supprimer_poste_vide",{p_entreprise_id:ctx.entrepriseId,p_poste_id:posteId});if(error)redirect(`/parametres/acces?error=${encodeURIComponent(error.message)}`);revalidatePath("/parametres/acces");redirect("/parametres/acces?success=Poste supprimé");}
export async function installerRolesPredefinisAction(){const ctx=await getContexteEntreprise(),sb=await createClient();const{data,error}=await sb.rpc("installer_roles_predefinis",{p_entreprise_id:ctx.entrepriseId,p_reinitialiser_existants:false});if(error)redirect(`/parametres/acces?error=${encodeURIComponent(error.message)}`);revalidatePath("/parametres/acces");redirect(`/parametres/acces?success=${encodeURIComponent(`${data??0} rôle(s) prédéfini(s) ajouté(s)`)}`);}
export async function reinitialiserRolePredefiniAction(posteId:string,modeleCle:string){const ctx=await getContexteEntreprise(),sb=await createClient();const{error}=await sb.rpc("reinitialiser_role_predefini",{p_entreprise_id:ctx.entrepriseId,p_poste_id:posteId,p_modele_cle:modeleCle});if(error)redirect(`/parametres/acces?error=${encodeURIComponent(error.message)}`);revalidatePath("/", "layout");revalidatePath("/parametres/acces");redirect("/parametres/acces?success=Droits recommandés réappliqués");}
