import Link from "next/link";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getContexteEntreprise } from "@/lib/entreprise";
import { permissionsUtilisateur } from "@/lib/permissions";
import { isEmailLoginDisabled } from "@/lib/auth-mode";
import { euros } from "@/lib/devis";
import { noteModifiable, statutNoteFrais, TYPES_JUSTIFICATIF } from "@/lib/notes-frais";
import { ExpenseDocumentUploader } from "@/components/ExpenseDocumentUploader";
import { enregistrerReferenceComptableAction, modifierNoteFraisAction, transitionNoteFraisAction } from "@/app/actions/notes-frais";
import { leverLegalHoldNoteFraisAction, poserLegalHoldNoteFraisAction } from "@/app/actions/notes-frais-admin";

const input = "w-full rounded-md border border-neutral-300 px-3 py-2 text-sm dark:border-neutral-700 dark:bg-neutral-900";
const un = <T,>(value: T | T[] | null): T | null => Array.isArray(value) ? value[0] ?? null : value;

export default async function NoteFraisDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; succes?: string }> }) {
  const { id } = await params; const message = await searchParams;
  if (isEmailLoginDisabled()) notFound();
  const ctx = await getContexteEntreprise(); const supabase = await createClient(); const permissions = await permissionsUtilisateur(ctx);
  const [{ data: note }, { data: categories }, { data: chantiers }, { data: employeCompte }, { data: politique }] = await Promise.all([
    supabase.from("notes_frais").select("*,employe:employes(id,prenom,nom),chantier:chantiers!notes_frais_chantier_entreprise_fkey(id,nom)").eq("id", id).eq("entreprise_id", ctx.entrepriseId).maybeSingle(),
    supabase.from("categories_notes_frais").select("code,libelle").eq("entreprise_id", ctx.entrepriseId).eq("actif", true).order("ordre"),
    supabase.from("chantiers").select("id,nom").eq("entreprise_id", ctx.entrepriseId).not("statut", "in", "(archive,annule)").order("nom"),
    supabase.from("employes").select("id").eq("entreprise_id", ctx.entrepriseId).eq("utilisateur_id", ctx.userId).maybeSingle(),
    supabase.from("politiques_conservation_notes_frais").select("mode_archivage,duree_conservation_annees,analyse_antivirus_obligatoire").eq("entreprise_id", ctx.entrepriseId).maybeSingle(),
  ]);
  if (!note) notFound();
  const [{ data: documents }, { data: validations }, { data: audit }, { data: legalHold }] = await Promise.all([
    supabase.from("documents_notes_frais").select("*,versions:versions_documents_notes_frais(id,numero_page,role_fichier,nom_fichier_original,type_mime_detecte,taille_octets,empreinte_sha256,antivirus_statut,horodatage_provider,created_at)").eq("note_frais_id", id).order("importe_at"),
    supabase.from("validations_notes_frais").select("id,action,ancien_statut,nouveau_statut,message,role_utilisateur,created_at").eq("note_frais_id", id).order("created_at"),
    permissions?.includes("consulter_audit_notes_frais") ? supabase.from("journal_audit_notes_frais").select("id,action,role_utilisateur,date_serveur,metadata,empreinte_document").eq("ressource_id", id).order("date_serveur", { ascending: false }).limit(100) : Promise.resolve({ data: [] }),
    permissions?.includes("administrer_archivage_notes_frais") ? supabase.from("legal_holds_notes_frais").select("id,motif,pose_at").eq("note_frais_id",id).eq("actif",true).maybeSingle() : Promise.resolve({data:null}),
  ]);
  const employe = un(note.employe as {id:string;prenom:string;nom:string}|{id:string;prenom:string;nom:string}[]|null);
  const chantier = un(note.chantier as {id:string;nom:string}|{id:string;nom:string}[]|null);
  const personnel = employeCompte?.id === employe?.id;
  const modifiable = personnel && noteModifiable(note.statut) && !note.verrouille_at;
  const verificateur = permissions?.includes("verifier_notes_frais") || permissions?.includes("gerer_notes_frais");
  const comptable = permissions?.includes("comptabiliser_notes_frais");
  const verrouilleur = permissions?.includes("verrouiller_notes_frais");
  const adminArchivage = permissions?.includes("administrer_archivage_notes_frais");
  const st = statutNoteFrais(note.statut);
  const actionModifier = modifierNoteFraisAction.bind(null, id);
  const transition = (statut: string) => transitionNoteFraisAction.bind(null, id, statut);

  return <main className="p-8"><div className="mx-auto max-w-5xl space-y-6">
    <div><Link href="/notes-frais" className="text-sm text-neutral-500 hover:underline">← Notes de frais</Link><div className="mt-2 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-semibold">{note.reference}</h1><p className="text-sm text-neutral-500">{employe ? `${employe.prenom} ${employe.nom}` : "Salarié"} · {note.date_frais}</p></div><span className="rounded-full px-3 py-1 text-sm font-semibold" style={{color:st.couleur,background:`${st.couleur}15`}}>{st.libelle}</span></div></div>
    {message.error && <p className="rounded bg-red-50 p-3 text-sm text-red-700">{message.error}</p>}{message.succes && <p className="rounded bg-green-50 p-3 text-sm text-green-700">{message.succes}</p>}
    <div className="grid gap-3 sm:grid-cols-4"><div className="rounded border p-3"><p className="text-xs text-neutral-500">TTC</p><strong className="text-xl">{euros(note.montant_ttc)}</strong></div><div className="rounded border p-3"><p className="text-xs text-neutral-500">HT / TVA</p><strong>{note.montant_ht === null ? "—" : euros(note.montant_ht)} / {note.montant_tva === null ? "—" : euros(note.montant_tva)}</strong></div><div className="rounded border p-3"><p className="text-xs text-neutral-500">Chantier</p><strong>{chantier?.nom ?? "Frais généraux"}</strong></div><div className="rounded border p-3"><p className="text-xs text-neutral-500">Archivage</p><strong>{politique?.mode_archivage === "reinforced_archive" ? "Renforcé non qualifié" : "Stockage simple"}</strong></div></div>

    <p className="rounded-lg border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900"><strong>Justificatif transmis.</strong> Conservez l’original papier jusqu’à confirmation de sa conservation conforme par votre entreprise.</p>
    {politique?.mode_archivage === "reinforced_archive" && <p className="rounded-lg border border-blue-300 bg-blue-50 p-4 text-sm text-blue-900">Le mode renforcé conserve original, copie figée, empreintes et audit. Il ne constitue pas à lui seul un archivage juridiquement conforme ou à valeur probante.</p>}

    {modifiable && <form action={actionModifier} className="grid gap-3 rounded-lg border p-4 sm:grid-cols-2 lg:grid-cols-4"><h2 className="font-semibold sm:col-span-2 lg:col-span-4">Informations de la dépense</h2>
      <label className="text-xs text-neutral-500">Date<input name="date_frais" type="date" required defaultValue={note.date_frais} className={`${input} mt-1`} /></label><label className="text-xs text-neutral-500">Fournisseur<input name="fournisseur" defaultValue={note.fournisseur ?? ""} className={`${input} mt-1`} /></label><label className="text-xs text-neutral-500">Catégorie<select name="categorie" defaultValue={note.categorie ?? ""} className={`${input} mt-1`}>{(categories ?? []).map((c) => <option key={c.code} value={c.code}>{c.libelle}</option>)}</select></label><label className="text-xs text-neutral-500">Type<select name="type_document_principal" defaultValue={note.type_document_principal ?? "facture"} className={`${input} mt-1`}>{TYPES_JUSTIFICATIF.map((t) => <option key={t.cle} value={t.cle}>{t.libelle}</option>)}</select></label>
      <label className="text-xs text-neutral-500">HT<input name="montant_ht" type="number" min="0" step="0.01" defaultValue={note.montant_ht ?? ""} className={`${input} mt-1`} /></label><label className="text-xs text-neutral-500">TVA<input name="montant_tva" type="number" min="0" step="0.01" defaultValue={note.montant_tva ?? ""} className={`${input} mt-1`} /></label><label className="text-xs text-neutral-500">TTC<input name="montant_ttc" type="number" min="0" step="0.01" required defaultValue={note.montant_ttc} className={`${input} mt-1`} /></label><label className="text-xs text-neutral-500">Taux TVA<input name="taux_tva" type="number" min="0" max="100" step="0.01" defaultValue={note.taux_tva ?? ""} className={`${input} mt-1`} /></label>
      <label className="text-xs text-neutral-500">Chantier<select name="chantier_id" defaultValue={chantier?.id ?? ""} className={`${input} mt-1`}><option value="">Frais généraux</option>{(chantiers ?? []).map((c) => <option key={c.id} value={c.id}>{c.nom}</option>)}</select></label><label className="text-xs text-neutral-500">Paiement<select name="moyen_paiement" defaultValue={note.moyen_paiement ?? ""} className={`${input} mt-1`}><option value="">Non renseigné</option><option value="carte_entreprise">Carte entreprise</option><option value="carte_personnelle">Carte personnelle</option><option value="especes">Espèces</option><option value="virement">Virement</option><option value="autre">Autre</option></select></label><label className="text-xs text-neutral-500">Devise<input name="devise" defaultValue={note.devise ?? "EUR"} maxLength={3} className={`${input} mt-1 uppercase`} /></label><label className="text-xs text-neutral-500 sm:col-span-2 lg:col-span-4">Commentaire<textarea name="commentaire_salarie" rows={2} defaultValue={note.commentaire_salarie ?? note.description ?? ""} className={`${input} mt-1`} /></label><button className="rounded-md bg-[#0d1b2a] px-4 py-2 text-sm font-semibold text-white sm:col-span-2 lg:col-span-4">Enregistrer les informations</button>
    </form>}

    <ExpenseDocumentUploader noteId={id} disabled={!modifiable} />
    <section className="space-y-3"><h2 className="font-semibold">Documents et intégrité</h2>{(documents ?? []).map((document) => <article key={document.id} className="rounded-lg border p-4"><div className="flex flex-wrap justify-between gap-2"><div><strong>{document.nom_fichier_original ?? "Justificatif"}</strong><p className="text-xs text-neutral-500">{document.type_document.replaceAll("_", " ")} · {document.nombre_pages} page(s)</p></div><div className="flex flex-wrap gap-1 text-[10px]"><span className="rounded-full bg-blue-100 px-2 py-1 text-blue-800">Original conservé</span>{document.verrouille_at ? <span className="rounded-full bg-neutral-900 px-2 py-1 text-white">Document verrouillé</span> : <span className="rounded-full bg-amber-100 px-2 py-1 text-amber-800">Non verrouillé</span>}{document.facture_electronique_originale && <span className="rounded-full bg-violet-100 px-2 py-1 text-violet-800">Facture électronique originale</span>}</div></div><div className="mt-3 space-y-2">{(document.versions ?? []).map((version: {id:string;numero_page:number;role_fichier:string;nom_fichier_original:string;type_mime_detecte:string;taille_octets:number;empreinte_sha256:string;antivirus_statut:string;horodatage_provider:string}) => <div key={version.id} className="flex flex-wrap items-center justify-between gap-2 rounded bg-neutral-50 p-2 text-xs"><div><strong>Page {version.numero_page} · {version.role_fichier.replaceAll("_", " ")}</strong><p className="text-neutral-500">{version.type_mime_detecte} · {(version.taille_octets/1024/1024).toFixed(2)} Mo · horodatage serveur non qualifié</p><p className="break-all font-mono text-[9px] text-neutral-400">SHA-256 {version.empreinte_sha256}</p></div><div className="flex gap-2"><span className={`rounded-full px-2 py-1 ${version.antivirus_statut === "sain" ? "bg-green-100 text-green-800" : "bg-amber-100 text-amber-800"}`}>{version.antivirus_statut === "sain" ? "Analyse saine" : "Antivirus non configuré"}</span><a href={`/api/notes-frais/documents/${version.id}`} target="_blank" rel="noopener" className="rounded border px-2 py-1">Vérifier et ouvrir</a><a href={`/api/notes-frais/documents/${version.id}?download=1`} className="rounded border px-2 py-1">Télécharger</a></div></div>)}</div></article>)}{!documents?.length && <p className="rounded border border-dashed p-5 text-center text-sm text-neutral-500">Aucun justificatif ajouté.</p>}</section>

    {modifiable && <form action={transition("soumis")} className="rounded-lg border border-green-300 bg-green-50 p-4"><h2 className="font-semibold text-green-900">Transmettre au responsable</h2><p className="mt-1 text-sm text-green-800">Vérifiez les informations et le justificatif. Après soumission, seules les corrections demandées pourront être modifiées.</p><button className="mt-3 rounded-md bg-green-800 px-4 py-2 text-sm font-semibold text-white">Soumettre la dépense</button></form>}
    {verificateur && ["soumis","soumise","en_verification"].includes(note.statut) && <section className="grid gap-3 rounded-lg border p-4 sm:grid-cols-3"><h2 className="sm:col-span-3 font-semibold">Décision du responsable</h2>{note.statut !== "en_verification" && <form action={transition("en_verification")}><button className="w-full rounded-md border px-3 py-2 text-sm">Prendre en charge</button></form>}<form action={transition("valide")}><button className="w-full rounded-md bg-green-700 px-3 py-2 text-sm font-semibold text-white">Valider</button></form><form action={transition("correction_demandee")} className="space-y-2"><textarea name="message" required placeholder="Correction demandée…" className={input} /><button className="w-full rounded-md bg-amber-600 px-3 py-2 text-sm font-semibold text-white">Demander une correction</button></form><form action={transition("refuse")} className="space-y-2"><textarea name="message" required placeholder="Motif obligatoire…" className={input} /><button className="w-full rounded-md bg-red-700 px-3 py-2 text-sm font-semibold text-white">Refuser</button></form></section>}
    {comptable && ["valide","validee","remboursee","exporte_comptabilite"].includes(note.statut) && <section className="rounded-lg border p-4"><h2 className="font-semibold">Comptabilité</h2><form action={enregistrerReferenceComptableAction.bind(null,id)} className="mt-3 flex gap-2"><input name="reference_comptable" defaultValue={note.reference_comptable ?? ""} placeholder="Référence comptable" className={input} /><button className="rounded-md border px-3 py-2 text-sm">Enregistrer</button></form>{note.statut !== "exporte_comptabilite" && <form action={transition("exporte_comptabilite")} className="mt-3"><button className="rounded-md bg-blue-700 px-3 py-2 text-sm text-white">Marquer exportée en comptabilité</button></form>}</section>}
    {verrouilleur && ["valide","validee","remboursee","exporte_comptabilite"].includes(note.statut) && <form action={transition("verrouille")} className="rounded-lg border border-neutral-400 p-4"><h2 className="font-semibold">Verrouillage administratif</h2><p className="mt-1 text-sm text-neutral-600">Cette action interdit toute modification ou tout remplacement silencieux. Une nouvelle version devra être ajoutée et auditée.</p><button className="mt-3 rounded-md bg-neutral-900 px-4 py-2 text-sm font-semibold text-white">Verrouiller le document</button></form>}
    {verrouilleur && note.statut === "verrouille" && <form action={transition("archive")}><button className="rounded-md border px-4 py-2 text-sm">Archiver</button></form>}
    {adminArchivage && <section className={`rounded-lg border p-4 ${legalHold?"border-red-400 bg-red-50":""}`}><h2 className="font-semibold">Suspension de suppression (legal hold)</h2>{legalHold?<><p className="mt-1 text-sm text-red-800"><strong>Active depuis le {new Date(legalHold.pose_at).toLocaleDateString("fr-FR")} :</strong> {legalHold.motif}</p><form action={leverLegalHoldNoteFraisAction.bind(null,id,legalHold.id)}><button className="mt-3 rounded-md border border-red-400 px-3 py-2 text-sm text-red-800">Lever la suspension</button></form></>:<form action={poserLegalHoldNoteFraisAction.bind(null,id)} className="mt-3 flex flex-col gap-2 sm:flex-row"><input name="motif" required placeholder="Contrôle, litige ou obligation de conservation…" className={input}/><button className="rounded-md border px-3 py-2 text-sm">Suspendre toute suppression</button></form>}</section>}

    <section><h2 className="mb-2 font-semibold">Historique de validation</h2><div className="rounded-lg border">{(validations ?? []).map((v) => <div key={v.id} className="border-t p-3 text-sm first:border-0"><div className="flex justify-between gap-3"><strong>{v.action.replaceAll("_", " ")}</strong><span className="text-xs text-neutral-500">{new Date(v.created_at).toLocaleString("fr-FR")}</span></div><p className="text-xs text-neutral-500">{v.ancien_statut ?? "—"} → {v.nouveau_statut} · {v.role_utilisateur ?? "utilisateur"}</p>{v.message && <p className="mt-1">{v.message}</p>}</div>)}{!validations?.length && <p className="p-4 text-sm text-neutral-500">Aucune décision enregistrée.</p>}</div></section>
    {permissions?.includes("consulter_audit_notes_frais") && <section><h2 className="mb-2 font-semibold">Journal d’audit</h2><div className="max-h-80 overflow-y-auto rounded-lg border">{(audit ?? []).map((a) => <div key={a.id} className="border-t p-3 text-xs first:border-0"><div className="flex justify-between gap-2"><strong>{a.action.replaceAll("_", " ")}</strong><span>{new Date(a.date_serveur).toLocaleString("fr-FR")}</span></div>{a.empreinte_document && <p className="mt-1 break-all font-mono text-[9px] text-neutral-400">{a.empreinte_document}</p>}</div>)}{!audit?.length && <p className="p-4 text-sm text-neutral-500">Aucun événement accessible.</p>}</div></section>}
  </div></main>;
}
